// âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
// ÃMIR â shared/strings.js
//
// Single source of truth for all user-visible strings across every page.
// Loaded after shared/api.js (which provides getLang()).
//
// USAGE
// âââââ
//   s("key")              â string in current language, fallback to EN
//   s("key", {n:3})       â interpolate: "3 trips" / "3 ferÃ°ir"
//   s("key", null, "IS")  â force a specific language (for email templates etc.)
//
// KEY NAMESPACES
// ââââââââââââââ
//   nav.*        Header navigation
//   btn.*        Generic buttons (Save, Cancel, Delete â¦)
//   lbl.*        Generic labels (Loading, Name, Date â¦)
//   toast.*      Toast / feedback messages
//   flag.*       Sailing flag labels & advice
//   wx.*         Weather widget strings
//   login.*      Login page
//   member.*     Member hub
//   staff.*      Staff hub + coForm.*
//   daily.*      Daily log
//   incident.*   Incidents
//   maint.*      Maintenance
//   logrev.*     Logbook review
//   admin.*      Admin panel
//   cert.*       Certifications
// âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ

const STRINGS = {

  // ââ Navigation âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'nav.staffHub':      { EN:'â Staff Hub',      IS:'â Starfsmaenn' },
  'nav.memberHub':     { EN:'âµ Members',         IS:'âµ FÃ©lagssvÃ¦Ã°i' },
  'nav.admin':         { EN:'â Admin',            IS:'â StjÃ³rnborÃ°' },
  'nav.weather':       { EN:'â Weather',          IS:'â VeÃ°ur' },
  'nav.logbook':       { EN:'ð Logbook',         IS:'ð SiglingabÃ³k' },
  'nav.back':          { EN:'â Back',            IS:'â Tilbaka' },
  'nav.signOut':       { EN:'Sign out',            IS:'SkrÃ¡ Ãºt' },
  'nav.langToggle':    { EN:'IS',                  IS:'EN' },

  // ââ Generic buttons ââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'btn.save':          { EN:'Save',                IS:'Vista' },
  'btn.cancel':        { EN:'Cancel',              IS:'HÃ¦tta viÃ°' },
  'btn.delete':        { EN:'Delete',              IS:'EyÃ°a' },
  'btn.edit':          { EN:'Edit',                IS:'Breyta' },
  'btn.add':           { EN:'+ Add',               IS:'+ BÃ¦ta viÃ°' },
  'btn.close':         { EN:'Close',               IS:'Loka' },
  'btn.confirm':       { EN:'Confirm',             IS:'StaÃ°festa' },
  'btn.resolve':       { EN:'Resolve',             IS:'LjÃºka' },
  'btn.saveDraft':     { EN:'Save draft',          IS:'Vista drÃ¶g' },
  'btn.signOff':       { EN:'Save & Sign off',     IS:'Vista & Undirrita' },
  'btn.submit':        { EN:'Submit',              IS:'Senda inn' },
  'btn.addComment':    { EN:'Add comment',         IS:'BÃ¦ta viÃ° athugasemd' },
  'btn.viewAll':       { EN:'View all â',          IS:'SjÃ¡ allt â' },

  // ââ Generic labels âââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'lbl.loading':       { EN:'Loadingâ¦',            IS:'HleÃ°urâ¦' },
  'lbl.noData':        { EN:'No data',            IS:'Engin gÃ¶gn' },
  'lbl.name':          { EN:'Name',                IS:'Nafn' },
  'lbl.date':          { EN:'Date',                IS:'Dagsetning' },
  'lbl.time':          { EN:'Time',                IS:'TÃ­mi' },
  'lbl.notes':         { EN:'Notes',               IS:'Athugasemdir' },
  'lbl.status':        { EN:'Status',              IS:'StaÃ°a' },
  'lbl.phone':         { EN:'Phone',               IS:'SÃ­mi' },
  'lbl.email':         { EN:'Email',               IS:'Netfang' },
  'lbl.location':      { EN:'Location',            IS:'StaÃ°setning' },
  'lbl.boat':          { EN:'Boat',                IS:'BÃ¡tur' },
  'lbl.crew':          { EN:'Crew',                IS:'ÃhÃ¶fn' },
  'lbl.role':          { EN:'Role',                IS:'Hlutverk' },
  'lbl.member':        { EN:'Member',              IS:'FÃ©lagi' },
  'lbl.guardian':      { EN:'Guardian',            IS:'ForrÃ¡Ã°amaÃ°ur' },
  'lbl.minor':         { EN:'MINOR',               IS:'ÃlÃ¶grÃ¡Ã°a' },
  'lbl.verified':      { EN:'â Verified',          IS:'â StaÃ°fest' },
  'lbl.pending':       { EN:'Pending review',      IS:'BÃ­Ã°ur yfirferÃ°ar' },
  'lbl.optional':      { EN:'optional',            IS:'valfrjÃ¡lst' },
  'lbl.active':        { EN:'Active',              IS:'Virkt' },
  'lbl.inactive':      { EN:'Inactive',            IS:'Ãvirkt' },
  'lbl.season':        { EN:'Season',              IS:'TÃ­mabil' },
  'lbl.category':      { EN:'Category',            IS:'Flokkur' },
  'lbl.description':   { EN:'Description',         IS:'LÃ½sing' },
  'lbl.severity':      { EN:'Severity',            IS:'Alvarleiki' },
  'lbl.type':          { EN:'Type',                IS:'Tegund' },
  'lbl.phase':         { EN:'Phase',               IS:'Fasi' },
  'lbl.sortOrder':     { EN:'Sort order',          IS:'RÃ¶Ã°un' },
  'lbl.selectDots':    { EN:'Selectâ¦',             IS:'Velduâ¦' },
  'lbl.noneDash':      { EN:'â none â',            IS:'â ekkert â' },

  // ââ Toast / feedback âââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'toast.saved':       { EN:'Saved',              IS:'VistaÃ°' },
  'toast.saveFailed':  { EN:'Save failed',         IS:'MistÃ³kst aÃ° vista' },
  'toast.deleted':     { EN:'Deleted',            IS:'Eytt' },
  'toast.error':       { EN:'Something went wrong. Try again.', IS:'EitthvaÃ° fÃ³r ÃºrskeiÃ°is. Reyndu aftur.' },
  'toast.loadFailed':  { EN:'Load failed',         IS:'HleÃ°sla mistÃ³kst' },
  'toast.signedOff':   { EN:'Signed off â',        IS:'UndirritaÃ° â' },
  'toast.checkedIn':   { EN:'Checked in â',        IS:'SkrÃ¡Ã° inn â' },
  'toast.noPhone':     { EN:'No phone on record',  IS:'Ekkert sÃ­manÃºmer skrÃ¡Ã°' },

  // ââ Sailing flags ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'flag.green.label':  { EN:'Green',               IS:'GrÃ¦nn' },
  'flag.green.advice': { EN:'Good conditions.',    IS:'Gott veÃ°urlag.' },
  'flag.yellow.label': { EN:'Yellow',              IS:'Gulur' },
  'flag.yellow.advice':{ EN:'Marginal â experienced sailors only.', IS:'Krefjandi â aÃ°eins reyndir siglingamenn.' },
  'flag.orange.label': { EN:'Orange',              IS:'AppelsÃ­nugulur' },
  'flag.orange.advice':{ EN:'Difficult â keelboats only, staff auth for dinghies.', IS:'Erfitt â takmÃ¶rkuÃ° siglingar.' },
  'flag.red.label':    { EN:'Red',                 IS:'RauÃ°ur' },
  'flag.red.advice':   { EN:'Do not sail â all sailing suspended.', IS:'Ekki sigla â Ãll siglingar stÃ¶Ã°vaÃ°ar.' },
  'flag.currentLabel': { EN:'CURRENT FLAG',        IS:'NÃVERANDI FÃNI' },
  'flag.allLevels':    { EN:'All levels â',        IS:'Allar stigur â' },
  'flag.conditions':   { EN:'Sailing Conditions',  IS:'SiglingaraÃ°stÃ¦Ã°ur' },

  // ââ Weather widget âââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'wx.wind':           { EN:'WIND',                IS:'VINDUR' },
  'wx.gusts':          { EN:'GUSTS',               IS:'HVIÃA' },
  'wx.waves':          { EN:'WAVES',               IS:'BYLGJUR' },
  'wx.pressure':       { EN:'PRESSURE',            IS:'LOFTÃRÃSTINGUR' },
  'wx.loading':        { EN:'Loading conditionsâ¦', IS:'SÃ¦ki veÃ°urgÃ¶gnâ¦' },
  'wx.unavailable':    { EN:'â  Weather unavailable', IS:'â  VeÃ°ur ekki tiltÃ¦kt' },
  'wx.fullForecast':   { EN:'Full forecast â',     IS:'HeildarspÃ¡ â' },
  'wx.updated':        { EN:'Updated',             IS:'UppfÃ¦rt' },

  // ââ Login ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'login.title':       { EN:'Ãmir Sailing Club',   IS:'SiglingafÃ©lagiÃ° Ãmir' },
  'login.subtitle':    { EN:'Member & Staff Portal', IS:'GÃ¡tt fÃ©laga og starfsmanna' },
  'login.kennitala':   { EN:'Kennitala',            IS:'Kennitala' },
  'login.placeholder': { EN:'0000000000',           IS:'0000000000' },
  'login.btn':         { EN:'Sign in',              IS:'SkrÃ¡ inn' },
  'login.loading':     { EN:'Signing inâ¦',          IS:'SkrÃ¡i innâ¦' },
  'login.notFound':    { EN:'Member not found or account inactive.', IS:'FÃ©lagi finnst ekki eÃ°a aÃ°gangur er Ã³virkur.' },
  'login.tooShort':    { EN:'Please enter your 10-digit kennitala.', IS:'Vinsamlegast slÃ¡Ã°u inn 10 stafa kennitÃ¶lu.' },
  'login.error':       { EN:'Login failed. Try again.', IS:'InnskrÃ¡ning mistÃ³kst. Reyndu aftur.' },
  'login.welcome':     { EN:'Welcome,',              IS:'Velkomin/n,' },
  'login.chooseView':  { EN:'How would you like to sign in?', IS:'Hvernig viltu skrÃ¡ Ã¾ig inn?' },
  'login.back':        { EN:'â Sign in as someone else', IS:'â SkrÃ¡ inn sem annan notandi' },
  'login.admin.label': { EN:'Admin Panel',           IS:'StjÃ³rnborÃ°' },
  'login.admin.desc':  { EN:'Manage members, boats, locations, settings', IS:'StjÃ³rna fÃ©laga, bÃ¡tum, stÃ¶Ã°um, stillingum' },
  'login.staff.label': { EN:'Staff Dashboard',       IS:'StarfsmannaÃ¾jÃ³nusta' },
  'login.staff.desc':  { EN:'Daily log, fleet status, incidents', IS:'Daglegur rekstur, flotinn, tilvik' },
  'login.member.label':{ EN:'Member Hub',            IS:'FÃ©lagssvÃ¦Ã°i' },
  'login.member.desc': { EN:'Check in/out, logbook, my trips', IS:'Inn/ÃºtskrÃ¡ning, dagbÃ³k, mÃ­nar ferÃ°ir' },

  // ââ Member hub âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'member.launchBoat':   { EN:'ð Launch a Boat',   IS:'ð Fara Ã¡ sjÃ³' },
  'member.checkIn':      { EN:'â Check In',          IS:'â SkrÃ¡ inn' },
  'member.reportIssue':  { EN:'ð§ Report Issue',     IS:'ð§ Tilkynna vandamÃ¡l' },
  'member.myCheckout':   { EN:'MY BOATS',            IS:'MÃNIR BÃTAR' },
  'member.myCheckoutSub':{ EN:'tap a boat to check in', IS:'smelltu Ã¡ bÃ¡t til aÃ° skrÃ¡ inn' },
  'member.tabFleet':     { EN:'Fleet',               IS:'Flotinn' },
  'member.tabTrips':     { EN:'Log a Trip',          IS:'SkrÃ¡ siglingu' },
  'member.tabLogbook':   { EN:'Logbook',             IS:'DagbÃ³k' },
  'member.tabCerts':     { EN:'Certifications',               IS:'SkÃ­rteini' },
  'member.fleetAvail':   { EN:'AVAILABLE BOATS',     IS:'LAUSIR BÃTAR' },
  'member.tripTabHint':  { EN:'Tap a recent trip below to add it to your logbook as crew, or log a trip manually.', IS:'Smelltu Ã¡ nÃ½lega siglingu til aÃ° bÃ¦ta henni viÃ° dagbÃ³kina Ã¾Ã­na sem Ã¡hÃ¶fn, eÃ°a skrÃ¡Ã°u siglingu handvirkt.' },
  'member.statTrips':    { EN:'TOTAL TRIPS',         IS:'SAMTALS SIGLINGAR' },
  'member.statHours':    { EN:'HOURS SAILED',        IS:'SIGLINGATÃMAR' },
  'member.statBoat':     { EN:'MOST-SAILED BOAT',    IS:'MEST NOTAÃI BÃTUR' },
  'member.statSeason':   { EN:'TRIPS THIS SEASON',   IS:'SIGLINGAR Ã TÃMABILI' },
  'member.noTrips':      { EN:'No trips in your logbook yet.', IS:'Engar siglingard Ã­ dagbÃ³kinni Ã¾inni enn.' },
  'member.noCheckouts':  { EN:'No active checkouts.', IS:'Engir bÃ¡tar Ã¡ sjÃ³.' },
  'member.noBoats':      { EN:'No boats available.', IS:'Engir bÃ¡tar lausir.' },
  'member.noCerts':      { EN:'No certifications on file.', IS:'Engin skÃ­rteini skrÃ¡Ã°.' },
  'member.boatOut':      { EN:'Out',                 IS:'Ãti' },
  'member.boatOos':      { EN:'Out of service',      IS:'Utan Ã¾jÃ³nustu' },
  'member.boatAvail':    { EN:'Available',           IS:'Laus' },
  'member.skipper':      { EN:'skipper',             IS:'skipstjÃ³ri' },
  'member.crewRole':     { EN:'crew',                IS:'Ã¡hÃ¶fn' },
  'member.addAsCrew':        { EN:'Add as crew',                IS:'BÃ¦ta viÃ° sem Ã¡hÃ¶fn' },
  'member.tripsTapHint':     { EN:'Tap a trip for details',     IS:'Smelltu Ã¡ siglingu til aÃ° sjÃ¡ nÃ¡nar' },
  'member.departed':     { EN:'Departed',            IS:'Lagt af staÃ°' },
  'member.returned':     { EN:'Returned',            IS:'KomiÃ° tilbaka' },
  'member.duration':     { EN:'Duration',            IS:'TÃ­malengd' },
  'member.loadFailed':   { EN:'Load failed',         IS:'HleÃ°sla mistÃ³kst' },
  'member.logManual':    { EN:'+ Log manually',      IS:'+ SkrÃ¡ handvirkt' },
  'member.recentTrips':  { EN:'RECENT PUBLIC TRIPS', IS:'NÃLEGAR SIGLINGAR' },
  'member.noRecent':     { EN:'No recent trips',    IS:'Engar nÃ½legar siglingar' },
  'member.myLogbook':    { EN:'MY LOGBOOK',          IS:'MÃN DAGBÃK' },
  'member.myCerts':      { EN:'MY CERTIFICATIONS',  IS:'MÃN SKÃRTEINI' },
  'member.launchTitle':  { EN:'Launch a Boat',       IS:'Fara Ã¡ sjÃ³' },
  'member.checkInTitle': { EN:'Check In',            IS:'SkrÃ¡ inn' },
  'member.manualTrip':   { EN:'Log a Trip',          IS:'SkrÃ¡ siglingu' },

  // ââ Staff hub ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'staff.dashTitle':         { EN:'Staff Dashboard',          IS:'StjÃ³rnborÃ° starfsmanna' },
  'staff.fleet':             { EN:'FLEET STATUS',             IS:'STAÃA FLOTANS' },
  'staff.expandAll':         { EN:'expand all',               IS:'sÃ½na allt' },
  'staff.collapseAll':       { EN:'collapse all',             IS:'fela allt' },
  'staff.recentCheckins':    { EN:'RECENT CHECK-INS (24H)',   IS:'NÃLEGAR INNSKRÃNINGAR (24H)' },
  'staff.overdue':           { EN:'OVERDUE',                  IS:'UMFRAM ÃÃTLUN' },
  'staff.overdueMinor':      { EN:'OVERDUE â MINOR',          IS:'UMFRAM ÃÃTLUN â BARN' },
  'staff.maintenance':       { EN:'OPEN MAINTENANCE',         IS:'OPIN VIÃHALDSMÃL' },
  'staff.maintDetail':        { en: 'Issue Detail',           is: 'UpplÃ½singar' },
  'staff.dailyLog':          { EN:'Daily Log',                IS:'DagbÃ³k fÃ©lagsins' },
  'staff.dailyLogDesc':      { EN:'Tides, weather records, checklists, activities, sign-off', IS:'FlÃ³Ã°, veÃ°urskrÃ¡ning, gÃ¡tlistar, starfsemi, undirskrift' },
  'staff.logbook':           { EN:'Logbook Review',           IS:'DagbÃ³karskoÃ°un' },
  'staff.logbookDesc':       { EN:'Verify member trips & assign certifications', IS:'StaÃ°festa ferÃ°ir fÃ©laga og Ãºthluta skÃ­rteinum' },
  'staff.incidents':         { EN:'Incidents',                IS:'Tilvik' },
  'staff.incidentsDesc':     { EN:'File or review safety incident reports', IS:'SkrÃ¡ eÃ°a fara yfir Ã¶ryggistilvik' },
  'staff.maintenanceDesc':   { EN:'Report and track boat & equipment issues', IS:'Tilkynna og fylgjast meÃ° vandamÃ¡lum Ã¡ bÃ¡tum og bÃºnaÃ°i' },
  'staff.noOverdue':         { EN:'No overdue checkouts.',    IS:'Engar yfirtÃ­ma ÃºtskrÃ¡ningar.' },
  'staff.noMaint':           { EN:'No open requests.',        IS:'Engar opnar beiÃ°nir.' },
  'staff.silence':           { EN:'Silence',                  IS:'Ãagga' },
  'staff.snooze':            { EN:'Snooze',                   IS:'Fresta' },
  'staff.minsOverdue':       { EN:'{n} min overdue',          IS:'{n} mÃ­n yfirtÃ­ma' },
  'staff.hrsOverdue':        { EN:'{h}h {m}min overdue',     IS:'{h}klst {m}mÃ­n yfirtÃ­ma' },
  'staff.expectedReturn':    { EN:'Expected return',          IS:'ÃÃ¦tlaÃ°ur skilatÃ­mi' },
  'staff.checkIn':           { EN:'â Check In',               IS:'â SkrÃ¡ inn' },
  'staff.deleteCheckout':    { EN:'Delete',                   IS:'EyÃ°a' },
  'staff.availCount':        { EN:'{n} available',            IS:'{n} tiltÃ¦kir' },
  'staff.activeCheckouts':   { EN:'ACTIVE CHECKOUTS',         IS:'VIRKAR ÃTSKRÃNINGAR' },
  'staff.boatsOutNow':       { EN:'BOATS OUT NOW',            IS:'BÃTAR Ã SJÃNUM' },
  'staff.checkOutBtn':         { EN:'Boat Checkout',            IS:'Uthluta bati' },
  'staff.groupCheckout':      { EN:'Group Checkout',           IS:'HÃ³paÃºthlutun' },
  'staff.newCheckout':       { EN:'NEW CHECKOUT',             IS:'NÃ ÃTSKRÃNING' },
  'staff.statBoats':         { EN:'BOATS OUT',                IS:'BÃTAR Ã SJÃ' },
  'staff.statPeople':        { EN:'PEOPLE OUT',               IS:'FÃLK Ã SJÃ' },
  'staff.statOverdue':       { EN:'OVERDUE',                  IS:'YFIRTÃMA' },
  'staff.toolsLabel':        { EN:'TOOLS',                    IS:'VERKFÃRI' },
  'staff.fullForecast':      { EN:'â Full Forecast â',        IS:'â HeildarlÃ­kan â' },
  'staff.tideHeader':        { EN:'TIDES Â· FAXAFLÃI',         IS:'FLÃÃ Â· FAXAFLÃI' },
  'staff.tideComingSoon':    { EN:'Tide data coming soon',    IS:'FlÃ³Ã°gÃ¶gn koma fljÃ³tlega' },
  'staff.tideDesc':          { EN:'Real-time tidal predictions for ReykjavÃ­k harbour', IS:'RauntÃ­ma flÃ³Ã°spÃ¡r fyrir ReykjavÃ­kurhÃ¶fn' },
  // Checkout form sub-keys
  'staff.coForm.departure':         { EN:'Departure',               IS:'BrottfÃ¶r' },
  'staff.coForm.estReturn':         { EN:'Est. return',             IS:'ÃÃ¦tl. heimkoma' },
  'staff.coForm.crew':              { EN:'Crew on board',           IS:'ÃhÃ¶fn um borÃ°' },
  'staff.coForm.notes':             { EN:'Notes (optional)',        IS:'Athugasemdir (valfrjÃ¡lst)' },
  'staff.coForm.submit':            { EN:'Check Out',               IS:'ÃtskrÃ¡' },
  'staff.coForm.memberPlaceholder': { EN:'Name or kennitalaâ¦',      IS:'Nafn eÃ°a kennitalaâ¦' },
  'staff.coForm.notesPlaceholder':  { EN:'Any notesâ¦',              IS:'Einhverjar athugasemdirâ¦' },
  'staff.coForm.errMember':         { EN:'Select a member.',        IS:'Veldu fÃ©laga.' },
  'staff.coForm.errBoat':           { EN:'Select a boat.',          IS:'Veldu bÃ¡t.' },
  'staff.coForm.errLocation':       { EN:'Select a location.',      IS:'Veldu staÃ°setningu.' },
  'staff.coForm.checkedOut':        { EN:'Checked out â',           IS:'ÃtskrÃ¡Ã° â' },
  // Detail modal sub-keys
  'staff.coDetail.title':     { EN:'Checkout Details',   IS:'UpplÃ½singar um ÃºtskrÃ¡ningu' },
  'staff.coDetail.tripLabel': { EN:'TRIP',               IS:'FERÃ' },
  'staff.coDetail.out':       { EN:'OUT',                IS:'FÃRT' },
  'staff.coDetail.return':    { EN:'EST. RETURN',        IS:'ÃÃTL. HEIMKOMA' },
  'staff.noBoatsOut':         { EN:'No boats currently out.', IS:'Engir bÃ¡tar Ã¡ sjÃ³num.' },
  'staff.noRecentCheckins':   { EN:'No check-ins in the last 24 hours.', IS:'Engar innkrÃ¡ningar sÃ­Ã°ustu 24 klukkustundir.' },

  // ââ Daily log ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'daily.title':           { EN:'Daily Log',               IS:'Dagleg skrÃ¡ning' },
  'daily.today':           { EN:'Today',                   IS:'Ã dag' },
  'daily.tripsToday':      { EN:'TRIPS TODAY',             IS:'FERÃIR Ã DAG' },
  'daily.openingChecklist':{ EN:'OPENING CHECKLIST',       IS:'OPNUNARGÃTLISTI' },
  'daily.closingChecklist':{ EN:'CLOSING CHECKLIST',       IS:'LOKUNARGÃTLISTI' },
  'daily.activities':      { EN:'ACTIVITIES',              IS:'STARFSEMI' },
  'daily.addActivity':     { EN:'+ Add',                   IS:'+ BÃ¦ta viÃ°' },
  'daily.staffNotes':      { EN:'STAFF NOTES',             IS:'ATHUGASEMDIR STARFSMANNA' },
  'daily.notesPlaceholder':{ EN:'General notes, conditions summaryâ¦', IS:'Almennar athugasemdir, samantekt Ã¡ aÃ°stÃ¦Ã°umâ¦' },
  'daily.incidentReport':  { EN:'INCIDENT REPORT',         IS:'TILVIKSSKÃRSLA' },
  'daily.fileIncident':    { EN:'Submit an Incident Report', IS:'Senda tilviksskÃ½rslu' },
  'daily.incidentSub':     { EN:'Injuries, near-misses, property damage, safety concerns', IS:'MeiÃ°sli, nÃ¦stum slys, eignatjÃ³n, Ã¶ryggismÃ¡l' },
  'daily.noIncidents':     { EN:'No incidents filed this day.', IS:'Engar tilviksskÃ½rslur Ã¾ennan dag.' },
  'daily.wxLog':           { EN:'WEATHER LOG',             IS:'VEÃURSKRÃNING' },
  'daily.tides':           { EN:'TIDES',                   IS:'FLÃÃ OG EBB' },
  'daily.signedOff':       { EN:'Signed off',              IS:'UndirritaÃ°' },
  'daily.readOnly':        { EN:'Read-only',               IS:'LesaÃ°gangur' },
  'daily.noActivities':    { EN:'No activities recorded yet.', IS:'Engin starfsemi skrÃ¡Ã° enn.' },
  'daily.noTrips':         { EN:'No trips recorded today.', IS:'Engar ferÃ°ir skrÃ¡Ã°ar Ã­ dag.' },
  'daily.activityModal':   { EN:'Add Activity',            IS:'BÃ¦ta viÃ° starfsemi' },
  'daily.actType':         { EN:'Type',                    IS:'Tegund' },
  'daily.actNameLabel':    { EN:'Name / description',      IS:'Nafn / lÃ½sing' },
  'daily.actNameHint':     { EN:'e.g. Junior lesson, club raceâ¦', IS:'t.d. Unglingakennsla, fÃ©lagskeppniâ¦' },
  'daily.actParticipants': { EN:'Participants',            IS:'ÃÃ¡tttakendur' },
  'daily.actPartHint':     { EN:'e.g. 12 juniors',         IS:'t.d. 12 unglingar' },
  'daily.actNotes':        { EN:'Notes',                   IS:'Athugasemdir' },
  'daily.actNotesHint':    { EN:'optional',                IS:'valfrjÃ¡lst' },
  'daily.startTime':       { EN:'Start time',              IS:'ByrjunartÃ­mi' },
  'daily.endTime':         { EN:'End time',                IS:'LokatÃ­mi' },
  'daily.wxLogBtn':        { EN:'ð¸ Log snapshot',         IS:'ð¸ Taka veÃ°urmynd' },
  'daily.noWxData':        { EN:'No weather data yet.',    IS:'Engin veÃ°urgÃ¶gn enn.' },
  'daily.signOffConfirm':  { EN:'PM checklist not complete ({done}/{total}). Sign off anyway?', IS:'PM gÃ¡tlisti er ekki fullklÃ¡raÃ°ur ({done}/{total}). Undirrita samt?' },
  'daily.saveDraftSaving': { EN:'Savingâ¦',                 IS:'Vistaâ¦' },
  'daily.signOffSaving':   { EN:'Signing offâ¦',            IS:'Undirritunâ¦' },
  'daily.signedOffBy':     { EN:'â Signed off by ',        IS:'â UndirritaÃ° af ' },

  // ââ Incidents ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'incident.title':        { EN:'Incidents',               IS:'Tilvik' },
  'incident.viewList':     { EN:'View incidents',          IS:'SkoÃ°a tilvik' },
  'incident.fileNew':      { EN:'File new report',         IS:'SkrÃ¡ nÃ½ja skÃ½rslu' },
  'incident.typeLabel':    { EN:'Incident type(s)',         IS:'Tegund tilviks' },
  'incident.noIncidents':  { EN:'No incidents filed.',     IS:'Engin tilvik skrÃ¡Ã°.' },
  'incident.description':  { EN:'Description',             IS:'LÃ½sing' },
  'incident.involved':     { EN:'Person(s) involved',      IS:'HlutaÃ°eigandi aÃ°ilar' },
  'incident.witnesses':    { EN:'Witnesses',               IS:'Vitni' },
  'incident.immediateAction':{ EN:'Immediate action taken',IS:'BrÃ¡Ã°abirgÃ°aaÃ°gerÃ°ir' },
  'incident.followUp':     { EN:'Follow-up required',      IS:'NauÃ°synleg eftirfylgni' },
  'incident.handOff':      { EN:'Handed off to',           IS:'Framselt til' },
  'incident.staffNotes':   { EN:'Staff notes',             IS:'Athugasemdir starfsmanna' },
  'incident.addNote':      { EN:'Add note',                IS:'BÃ¦ta viÃ° athugasemd' },
  'incident.resolved':     { EN:'Resolved',                IS:'LokiÃ°' },
  'incident.open':         { EN:'Open',                    IS:'OpiÃ°' },
  'incident.markResolved': { EN:'Mark resolved',           IS:'Merkja sem lokiÃ°' },
  'incident.markOpen':     { EN:'Reopen',                  IS:'Enduropna' },
  'incident.filedBy':      { EN:'Filed by',                IS:'SkrÃ¡Ã° af' },
  'incident.boatLabel':    { EN:'Boat (if applicable)',    IS:'BÃ¡tur (ef viÃ° Ã¡)' },
  'incident.personsInvolved':{ EN:'Persons involved',      IS:'AÃ°ilar aÃ° mÃ¡li' },
  'incident.witnessHint':  { EN:'Names / contact infoâ¦',   IS:'NÃ¶fn / tengiliÃ°aupplÃ½singarâ¦' },
  'incident.actionHint':   { EN:'First aid, evacuation, coastguard calledâ¦', IS:'SkyndihjÃ¡lp, rÃ½ming, landhelgisgÃ¦slanâ¦' },
  'incident.followUpHint': { EN:'Referral, repair, investigationâ¦', IS:'TilvÃ­sun, viÃ°gerÃ°, rannsÃ³knâ¦' },
  'incident.handoffSection':{ EN:'Hand-off',               IS:'Framsending' },
  'incident.handoffTo':    { EN:'Handed off to',           IS:'Framselt til' },
  'incident.handoffName':  { EN:'Contact name / ref.',     IS:'Nafn tengiliÃ°ar / tilvÃ­sun' },
  'incident.handoffNotes': { EN:'Handoff notes',           IS:'Athugasemdir um framsendingu' },
  'incident.fileBtn':      { EN:'File Report',             IS:'SkrÃ¡ skÃ½rslu' },
  'incident.descRequired': { EN:'Description is required.', IS:'LÃ½sing er skylda.' },
  'incident.typeRequired': { EN:'Select at least one incident type.', IS:'Veldu aÃ° minnsta kosti eina tegund tilviks.' },
  'incident.sevRequired':  { EN:'Select severity.',        IS:'Veldu alvarleika.' },
  'incident.filed':        { EN:'Report filed â',          IS:'SkÃ½rsla skrÃ¡Ã° â' },
  'incident.addNoteBtn':   { EN:'Add note',                IS:'BÃ¦ta viÃ° athugasemd' },
  'incident.notePlaceholder':{ EN:'Add a noteâ¦',           IS:'BÃ¦ta viÃ° athugasemdâ¦' },
  'incident.type.injury':     { EN:'ð©¹ Injury',            IS:'ð©¹ MeiÃ°sli' },
  'incident.type.capsize':    { EN:'âµ Capsize',            IS:'âµ KÃ¦ning' },
  'incident.type.collision':  { EN:'ð¥ Collision',         IS:'ð¥ Ãrekstur' },
  'incident.type.equipment':  { EN:'ð§ Equipment failure', IS:'ð§ BÃºnaÃ°arbilun' },
  'incident.type.medical':    { EN:'ð¥ Medical',           IS:'ð¥ LÃ¦knisfrÃ¦Ã°ilegt' },
  'incident.type.nearMiss':   { EN:'â¡ Near miss',          IS:'â¡ NÃ¡kvÃ¦mt miss' },
  'incident.type.missing':    { EN:'ð Missing person',    IS:'ð SaknaÃ° manneskja' },
  'incident.type.propertyDmg':{ EN:'ð Property damage',  IS:'ð EignatjÃ³n' },
  'incident.type.other':      { EN:'ð Other',             IS:'ð AnnaÃ°' },
  'incident.sev.low':         { EN:'Low',                  IS:'LÃ¡gt' },
  'incident.sev.medium':      { EN:'Medium',               IS:'MiÃ°lungs' },
  'incident.sev.high':        { EN:'High',                 IS:'HÃ¡tt' },
  'incident.sev.critical':    { EN:'Critical',             IS:'BrÃ¡Ã°avarsamt' },

  // ââ Maintenance ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'maint.title':           { EN:'Maintenance',             IS:'ViÃ°hald' },
  'maint.newRequest':      { EN:'+ Report issue',          IS:'+ Tilkynna vandamÃ¡l' },
  'maint.category':        { EN:'Category',                IS:'Flokkur' },
  'maint.catBoat':         { EN:'Boat',                    IS:'BÃ¡tur' },
  'maint.catEquipment':    { EN:'Equipment',               IS:'BÃºnaÃ°ur' },
  'maint.catFacility':     { EN:'Facility',                IS:'AÃ°staÃ°a' },
  'maint.part':            { EN:'Part / item',             IS:'Hluti' },
  'maint.severity':        { EN:'Severity',                IS:'Alvarleiki' },
  'maint.sevLow':          { EN:'Low â no rush',           IS:'LÃ¡gt â engin haste' },
  'maint.sevMedium':       { EN:'Medium â fix soon',       IS:'MiÃ°lungs â laga fljÃ³tt' },
  'maint.sevHigh':         { EN:'High â affects safety',   IS:'HÃ¡tt â hefur Ã¡hrif Ã¡ Ã¶ryggi' },
  'maint.markOos':         { EN:'Mark boat out of service', IS:'Merkja bÃ¡t utan Ã¾jÃ³nustu' },
  'maint.reportedBy':      { EN:'Reported by',             IS:'Tilkynnt af' },
  'maint.noRequests':      { EN:'No open maintenance requests.', IS:'Engar opnar viÃ°haldsbeiÃ°nir.' },
  'maint.resolved':        { EN:'Resolved',                IS:'LokiÃ°' },
  'maint.open':            { EN:'Open',                    IS:'OpiÃ°' },
  'maint.resolveBtn':      { EN:'Mark resolved',           IS:'Merkja sem lokiÃ°' },
  'maint.comments':        { EN:'Comments',                IS:'Athugasemdir' },
  'maint.descPlaceholder': { EN:'Describe the issueâ¦',     IS:'LÃ½stu vandamÃ¡linuâ¦' },
  'maint.partPlaceholder': { EN:'e.g. rudder, jib halyardâ¦', IS:'t.d. stÃ½riÃ°, forskatbyljaâ¦' },
  'maint.newTitle':        { EN:'NEW MAINTENANCE REQUEST', IS:'NÃ VIÃHALDSBEIÃNI' },
  'maint.filterOpen':      { EN:'Open',                    IS:'OpiÃ°' },
  'maint.filterAll':       { EN:'All',                     IS:'Allt' },
  'maint.filterBoat':      { EN:'Boat',                    IS:'BÃ¡tur' },
  'maint.filterEquipment': { EN:'Equipment',               IS:'BÃºnaÃ°ur' },
  'maint.filterFacility':  { EN:'Facility',                IS:'AÃ°staÃ°a' },
  'maint.commentPlaceholder':{ EN:'Add a commentâ¦',        IS:'BÃ¦ta viÃ° athugasemdâ¦' },
  'maint.addCommentBtn':   { EN:'Add',                     IS:'BÃ¦ta viÃ°' },
  'maint.oosConfirm':      { EN:'Mark this boat out of service?', IS:'Merkja Ã¾ennan bÃ¡t utan Ã¾jÃ³nustu?' },
  'maint.resolveConfirm':  { EN:'Mark this request as resolved?', IS:'Merkja Ã¾essa beiÃ°ni sem lokna?' },
  'maint.statOpen':        { EN:'OPEN',                    IS:'OPIÃ' },
  'maint.statHigh':        { EN:'HIGH / CRITICAL',         IS:'HÃTT / BRÃÃAVARSAMT' },
  'maint.statOos':         { EN:'BOATS OOS',               IS:'BÃTAR UTAN ÃJÃNUSTU' },

  // ââ Logbook review âââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'logrev.title':          { EN:'Logbook Review',          IS:'DagbÃ³karskoÃ°un' },
  'logrev.subtitle':       { EN:'Verify member trips Â· assign certifications', IS:'StaÃ°festa ferÃ°ir fÃ©laga Â· Ãºthluta skÃ­rteinum' },
  'logrev.totalTrips':     { EN:'TOTAL TRIPS',             IS:'SAMTALS FERÃIR' },
  'logrev.pending':        { EN:'PENDING REVIEW',          IS:'BÃÃUR SKOÃUNAR' },
  'logrev.verified':       { EN:'VERIFIED',                IS:'STAÃFEST' },
  'logrev.verify':         { EN:'Verify',                  IS:'StaÃ°festa' },
  'logrev.unverify':       { EN:'Unverify',                IS:'AfstaÃ°festa' },
  'logrev.staffComment':   { EN:'Staff comment (optional)',IS:'Athugasemd starfsmanns (valfrjÃ¡lst)' },
  'logrev.noTrips':        { EN:'No trips to review.',     IS:'Engar ferÃ°ir til skoÃ°unar.' },
  'logrev.filterAll':      { EN:'All',                     IS:'Allt' },
  'logrev.filterPending':  { EN:'Pending',                 IS:'Ã biÃ°' },
  'logrev.filterVerified': { EN:'Verified',                IS:'StaÃ°fest' },
  'logrev.filterName':     { EN:'Filter by nameâ¦',         IS:'SÃ­a eftir nafniâ¦' },
  'logrev.filterFrom':     { EN:'From',                    IS:'FrÃ¡' },
  'logrev.filterTo':       { EN:'To',                      IS:'Til' },
  'logrev.assignCert':     { EN:'ASSIGN CERTIFICATION',    IS:'ÃTHLUTA SKÃRTEINI' },
  'logrev.assignedDate':   { EN:'Assigned date',           IS:'Ãthlutunardagur' },
  'logrev.expires':        { EN:'Expires',                 IS:'Rennur Ãºt' },
  'logrev.assignBtn':      { EN:'Assign',                  IS:'Ãthluta' },
  'logrev.certModal':      { EN:'Certifications',          IS:'SkÃ­rteini' },
  'logrev.noCerts':        { EN:'No certifications on file.', IS:'Engin skÃ­rteini skrÃ¡Ã°.' },
  'logrev.validationRequests':    { EN:'Validation requests',                                       IS:'BeiÃ°nir um staÃ°festingu'                                   },
  'logrev.showAll':               { EN:'Show all trips',                                             IS:'SÃ½na allar ferÃ°ir'                                         },
  'logrev.certSearch':            { EN:'Search for a member above to view their certifications.',   IS:'LeitaÃ°u aÃ° fÃ©laga hÃ©r aÃ° ofan til aÃ° skoÃ°a skÃ­rteini.'     },
  'logrev.certSearchPlaceholder': { EN:'Search member name...',                                     IS:'Leita aÃ° nafni fÃ©laga...'   },
  'logrev.certModeByMember':      { EN:'By member',                                                 IS:'Eftir fÃ©laga'                                              },
  'logrev.certModeByType':        { EN:'By certification',                                          IS:'Eftir skÃ­rteini'                                           },
  'logrev.certSelectType':        { EN:'â Select certification â',                                  IS:'â Veldu skÃ­rteini â'                                       },
  'logrev.certNoMatches':         { EN:'No members found with this certification.',                  IS:'Engir fÃ©lagar fundust meÃ° Ã¾etta skÃ­rteini.'                },
  
    // ââ Admin panel ââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'admin.tabMembers':      { EN:'Members',                 IS:'FÃ©lagar' },
  'admin.tabBoats':        { EN:'Boats',                   IS:'BÃ¡tar' },                               
  'admin.tabLocations':    { EN:'Locations',               IS:'StaÃ°ir' },
  'admin.tabChecklists':   { EN:'Checklists',              IS:'GÃ¡tlistar' },
  'admin.tabActTypes':     { EN:'Activity Types',          IS:'Tegundir starfsemi' },
  'admin.tabCerts':        { EN:'Certifications',          IS:'SkÃ­rteini' },
  'admin.tabAlerts':       { EN:'Alerts',                  IS:'ViÃ°varanir' },
  'admin.tabPayroll':      { EN:'ð° Payroll',             IS:'ð° Launakerfi' },
  'admin.tabFlags':        { EN:'ð© Flags',                IS:'ð© FÃ¡nar' },
  'admin.importCsv':       { EN:'âª Import CSV',            IS:'âª Flytja inn CSV' },
  'admin.searchMembers':   { EN:'Search name or kennitalaâ¦', IS:'Leita aÃ° nafni eÃ°a kennitÃ¶luâ¦' },
  'admin.noMembers':       { EN:'No members yet.',         IS:'Engir fÃ©lagar ennÃ¾Ã¡.' },
  'admin.addMember':       { EN:'+ Add member',            IS:'+ BÃ¦ta viÃ° fÃ©laga' },
  'admin.addBoat':         { EN:'+ Add boat',              IS:'+ BÃ¦ta viÃ° bÃ¡t' },
  'admin.addLocation':     { EN:'+ Add location',          IS:'+ BÃ¦ta viÃ° staÃ°' },
  'admin.addItem':         { EN:'+ Add item',              IS:'+ BÃ¦ta viÃ° atriÃ°i' },
  'admin.addType':         { EN:'+ Add type',              IS:'+ BÃ¦ta viÃ° tegund' },
  'admin.importUpdated':   { EN:'updated',                 IS:'uppfÃ¦rt' },
  'admin.importMissing':   { EN:'not in import',           IS:'ekki Ã­ innflutningi' },
  'admin.importUnchanged': { EN:'unchanged',               IS:'Ã³breytt' },
  'admin.saveChanges':     { EN:'Save changes',            IS:'Vista breytingar' },
  'admin.alertFirstMins':  { EN:'First alert after (min)', IS:'Fyrsta viÃ°vÃ¶run eftir (mÃ­n)' },
  'admin.alertRepeatMins': { EN:'Repeat every (min)',      IS:'Endurtaka Ã¡ (mÃ­n)' },
  'admin.alertSnoozeMins': { EN:'Snooze duration (min)',   IS:'Frestunarlengd (mÃ­n)' },
  'admin.alertEnabled':    { EN:'Alerts enabled',          IS:'ViÃ°varanir virkar' },
  'admin.flagThresholds':  { EN:'Flag thresholds',         IS:'MÃ¶rk fÃ¡na' },
  'admin.windYellow':      { EN:'Wind yellow (Bft)',        IS:'Vindur gulur (Bft)' },
  'admin.windOrange':      { EN:'Wind orange (Bft)',        IS:'Vindur appelsÃ­nugulur (Bft)' },
  'admin.windRed':         { EN:'Wind red (Bft)',           IS:'Vindur rauÃ°ur (Bft)' },
  'admin.waveYellow':      { EN:'Wave yellow (m)',          IS:'Bylgja gul (m)' },
  'admin.waveOrange':      { EN:'Wave orange (m)',          IS:'Bylgja appelsÃ­nugul (m)' },
  'admin.waveRed':         { EN:'Wave red (m)',             IS:'Bylgja rauÃ° (m)' },
  'admin.memberModal.add': { EN:'Add Member',              IS:'BÃ¦ta viÃ° fÃ©laga' },
  'admin.memberModal.edit':{ EN:'Edit Member',             IS:'Breyta fÃ©laga' },
  'admin.fullName':        { EN:'Full name',               IS:'Fullt nafn' },
  'admin.birthYear':       { EN:'Birth year',              IS:'FÃ¦Ã°ingarÃ¡r' },
  'admin.isMinor':         { EN:'Minor (under 18)',        IS:'Barn (undir 18)' },
  'admin.guardianSection': { EN:'GUARDIAN / PARENT',       IS:'FORRÃÃAMAÃUR / FORELDRI' },
  'admin.guardianName':    { EN:'Guardian name',           IS:'Nafn forrÃ¡Ã°amanns' },
  'admin.guardianPhone':   { EN:'Guardian phone',          IS:'SÃ­mi forrÃ¡Ã°amanns' },
  'admin.guardianKt':      { EN:'Guardian kennitala',      IS:'Kennitala forrÃ¡Ã°amanns' },
  'admin.boatModal.add':   { EN:'Add Boat',                IS:'BÃ¦ta viÃ° bÃ¡t' },
  'admin.boatModal.edit':  { EN:'Edit Boat',               IS:'Breyta bÃ¡t' },
  'admin.boatName':        { EN:'Boat name',               IS:'Nafn bÃ¡ts' },
  'admin.boatCategory':    { EN:'Category',                IS:'Flokkur' },
  'admin.boatOos':         { EN:'Out of service',          IS:'Utan Ã¾jÃ³nustu' },
  'admin.boatOosReason':   { EN:'OOS reason',              IS:'ÃstÃ¦Ã°a OOS' },
  'admin.locModal.add':    { EN:'Add Location',            IS:'BÃ¦ta viÃ° staÃ°' },
  'admin.locModal.edit':   { EN:'Edit Location',           IS:'Breyta staÃ°' },
  'admin.clPhase':         { EN:'Phase',                   IS:'Fasi' },
  'admin.clPhaseAm':       { EN:'AM',                      IS:'AM' },
  'admin.clPhasePm':       { EN:'PM',                      IS:'PM' },
  'admin.clTextEN':        { EN:'Text (EN)',                IS:'Texti (EN)' },
  'admin.clTextIS':        { EN:'Text (IS)',                IS:'Texti (IS)' },
  'admin.actTypeEN':       { EN:'Name (EN)',                IS:'Nafn (EN)' },
  'admin.actTypeIS':       { EN:'Name (IS)',                IS:'Nafn (IS)' },
  'admin.certName':           { EN:'Cert name (EN)',              IS:'Nafn skÃ­rteinis (EN)' },
  'admin.certRenewal':        { EN:'Renewal (days, 0 = permanent)', IS:'EndurnÃ½jun (dagar, 0 = varanlegt)' },
  'admin.certTypes':          { EN:'CERTIFICATION TYPES',         IS:'TEGUNDIR SKÃRTEINA' },
  'admin.certAssign':         { EN:'ASSIGN CERTIFICATIONS',       IS:'ÃTHLUTA SKÃRTEINUM' },
  'admin.certAddType':        { EN:'+ Add certification type',    IS:'+ BÃ¦ta viÃ° tegund skÃ­rteinis' },
  'admin.certAddModal':       { EN:'Add Certification Type',      IS:'BÃ¦ta viÃ° tegund skÃ­rteinis' },
  'admin.certEditModal':      { EN:'Edit Certification Type',     IS:'Breyta tegund skÃ­rteinis' },
  'admin.certDesc':           { EN:'Description',                 IS:'LÃ½sing' },
  'admin.certDescOptional':   { EN:'(optional)',                  IS:'(valfrjÃ¡lst)' },
  'admin.certRenewalPerm':    { EN:'Permanent',                   IS:'Varanlegt' },
  'admin.certRenewalAnnual':  { EN:'Annual (365 days)',           IS:'Ãrlegt (365 dagar)' },
  'admin.certRenewalBiennial':{ EN:'Biennial (730 days)',         IS:'AnnaÃ° hvert Ã¡r (730 dagar)' },
  'admin.certRenewalCustom':  { EN:'Customâ¦',                    IS:'SÃ©rsniÃ°iÃ°â¦' },
  'admin.certDaysUntilExpiry':{ EN:'Days until expiry',          IS:'Dagar Ã¾ar til rennur Ãºt' },
  'admin.certSearchMember':   { EN:'Search memberâ¦',             IS:'Leita aÃ° fÃ©lagaâ¦' },
  'admin.certAllTypes':       { EN:'All cert types',             IS:'Allar tegundir skÃ­rteina' },
  'admin.noBoats':         { EN:'No boats.',               IS:'Engir bÃ¡tar.' },
  'admin.noLocations':     { EN:'No locations.',           IS:'Engir staÃ°ir.' },
  'admin.backToList':      { EN:'â Back to list',          IS:'â Aftur Ã¡ lista' },
  'admin.importFromCsv':   { EN:'Import from Abler.io CSV', IS:'Flytja inn Ãºr Abler.io CSV' },

  // ââ Certifications âââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
  'cert.noCerts':              { EN:'No certifications on file.',       IS:'Engin skÃ­rteini skrÃ¡Ã°.' },
  'cert.assignedBy':           { EN:'Assigned by',                      IS:'ÃthlutaÃ° af' },
  'cert.assignedAt':           { EN:'Assigned',                         IS:'ÃthlutaÃ°' },
  'cert.expires':              { EN:'Expires',                          IS:'Rennur Ãºt' },
  'cert.expired':              { EN:'Expired',                          IS:'ÃtrunniÃ°' },
  'cert.permanent':            { EN:'Permanent',                        IS:'Varanlegt' },
  'cert.level':                { EN:'Level / Subcategory',              IS:'Stig / Undirflokkur' },
  'cert.assign':               { EN:'Assign',                           IS:'Ãthluta' },
  'cert.remove':               { EN:'Remove',                           IS:'FjarlÃ¦gja' },
  'cert.issuingAuthority':     { EN:'Issuing Authority',                IS:'Ãtgefandi' },
  'cert.renewalDays':          { EN:'Renewal (days)',                   IS:'EndurnÃ½jun (dagar)' },
  'cert.renewalOverride':      { EN:'Renewal (days, overrides parent)', IS:'EndurnÃ½jun (dagar, hnekkir yfirflokki)' },
  'cert.fixedExpiry':          { EN:'Fixed Expiry Date',                IS:'FÃ¶st lokadagsetning' },
  'cert.fixedExpiryOverride':  { EN:'Fixed Expiry Date (overrides renewal)', IS:'FÃ¶st lokadagsetning (hnekkir endurnÃ½jun)' },
  'cert.subcats':              { EN:'Subcategories',                    IS:'Undirflokkar' },
  'cert.subcatHint':           { EN:'Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce "higher replaces lower" logic. Per-subtype issuing authority, renewal days, or a fixed expiry date will override the parent values.',
                                  IS:'BÃ¦ttu viÃ° undirflokkum ef skÃ­rteiniÃ° hefur stig (t.d. Stig 1, 2, 3). Stilltu rÃ¶Ã° til aÃ° framfylgja âhÃ¦rra kemur Ã­ staÃ° lÃ¦gra" rÃ¶k. Ãtgefandi, endurnÃ½junardagar eÃ°a fÃ¶st lokadagsetning Ã¡ undirflokki hnekkir gildum yfirflokksins.' },
  'cert.noSubcats':            { EN:'No subcategories',                 IS:'Engir undirflokkar' },
  'cert.subcatLabel':          { EN:'Label (e.g. Level 1)',             IS:'Merking (t.d. Stig 1)' },
  'cert.subcatDesc':           { EN:'Description',                      IS:'LÃ½sing' },
  'cert.subcatRank':           { EN:'Rank',                             IS:'RÃ¶Ã°' },
  'cert.rankHint':             { EN:'Rank (higher replaces lower on assign)', IS:'RÃ¶Ã° (hÃ¦rra kemur Ã­ staÃ° lÃ¦gra viÃ° Ãºthlutun)' },
  'cert.staffOnly':            { EN:'Staff-only cert',                  IS:'SkÃ­rteini einungis fyrir starfsfÃ³lk' },
  'cert.cardColour':           { EN:'Card colour',                      IS:'Litur korts' },
  'cert.colourAuto':           { EN:'auto if blank',                    IS:'sjÃ¡lfvirkt ef autt' },
  'cert.deleteConfirm':        { EN:"Delete this certification type? This won't remove existing assignments.", IS:'EyÃ°a Ã¾essari tegund skÃ­rteinis? Ãetta mun ekki fjarlÃ¦gja fyrirliggjandi Ãºthlutanir.' },
  'cert.deleteSubConfirm':     { EN:'Remove this subtype?',             IS:'FjarlÃ¦gja Ã¾ennan undirflokk?' },
  'cert.saved':                { EN:'Certification type saved.',        IS:'Tegund skÃ­rteinis vistuÃ°.' },
  'cert.deleted':              { EN:'Certification type deleted.',      IS:'Tegund skÃ­rteinis eytt.' },
  'cert.assigned':             { EN:'Certification assigned.',          IS:'SkÃ­rteini ÃºthlutaÃ°.' },
  'cert.removed':              { EN:'Certification removed.',           IS:'SkÃ­rteini fjarlÃ¦gt.' },
  'cert.nameRequired':         { EN:'Name required.',                   IS:'Nafn vantar.' },
  'cert.typeRequired':         { EN:'Select a certification type.',     IS:'Veldu tegund skÃ­rteinis.' },
  'cert.levelRequired':        { EN:'Select a level / subcategory.',    IS:'Veldu stig / undirflokk.' },
  
  // ââ Payroll â tab labels (renamed) ââââââââââââââââââââââââââââââââââââââââââ
  'payroll.tabTimeReporting': { EN:'Time Reporting', IS:'TÃ­maskrÃ¡ning' },
  'payroll.tabTimesheets':    { EN:'Timesheets / Payslips', IS:'LaunaseÃ°lar' },
  'payroll.tabEmployees':     { EN:'Employees', IS:'Starfsmenn' },
  'payroll.tabLaunamidlar':   { EN:'LaunamiÃ°lar', IS:'LaunamiÃ°lar' },

  // ââ Payroll â period & approval flow ââââââââââââââââââââââââââââââââââââââââ
  'payroll.definePeriod':      { EN:'Define Pay Period', IS:'Skilgreina launatÃ­mabil' },
  'payroll.periodFrom':        { EN:'From', IS:'FrÃ¡' },
  'payroll.periodTo':          { EN:'To', IS:'Til' },
  'payroll.previewPayslips':   { EN:'Preview Payslips', IS:'ForskoÃ°a launaseÃ°la' },
  'payroll.approvePeriod':     { EN:'Approve & Close Period', IS:'SamÃ¾ykkja og loka tÃ­mabili' },
  'payroll.approveConfirm':    { EN:'Approve payslips for all employees and close this period?', IS:'SamÃ¾ykkja launaseÃ°la allra starfsmanna og loka Ã¾essu tÃ­mabili?' },
  'payroll.periodClosed':      { EN:'Period closed â', IS:'TÃ­mabili lokaÃ° â' },
  'payroll.exportPdf':         { EN:'Export PDF', IS:'SÃ¦kja PDF' },
  'payroll.exportXml':         { EN:'Export XML', IS:'SÃ¦kja XML' },
  'payroll.noPeriodDefined':   { EN:'No pay period defined yet.', IS:'Ekkert launatÃ­mabil skilgreint enn.' },
  'payroll.noClosedPeriods':   { EN:'No closed periods yet.', IS:'Engin lokuÃ° tÃ­mabil enn.' },
  'payroll.hoursFromSheets':   { EN:'Hours from timesheets', IS:'TÃ­mar Ãºr tÃ­maskrÃ¡ningu' },
  'payroll.hoursConfirm':      { EN:'Confirm hours before approving', IS:'StaÃ°festu tÃ­ma Ã¡Ã°ur en samÃ¾ykkt er' },
  'payroll.manualLines':       { EN:'Manual line items', IS:'HandvirÃ°ar lÃ­nur' },
  'payroll.addLine':           { EN:'+ Add line', IS:'+ BÃ¦ta viÃ° lÃ­nu' },
  'payroll.lineDescription':   { EN:'Description', IS:'LÃ½sing' },
  'payroll.lineDescriptionIS': { EN:'Description (IS)', IS:'LÃ½sing (IS)' },
  'payroll.lineAmount':        { EN:'Amount (kr)', IS:'UpphÃ¦Ã° (kr)' },
  'payroll.regularHours':      { EN:'Regular hours', IS:'Dagvinna (klst)' },
  'payroll.ot1Hours':          { EN:'Overtime 1.33Ã', IS:'Eftirvinna 1,33' },
  'payroll.ot2Hours':          { EN:'Overtime 1.55Ã', IS:'Eftirvinna 1,55' },
  'payroll.correctedHours':    { EN:'Corrected hours', IS:'LeiÃ°rÃ©ttir tÃ­mar' },
  'payroll.hoursNote':         { EN:'Note / reason for correction', IS:'Athugasemd / Ã¡stÃ¦Ã°a leiÃ°rÃ©ttingar' },
  'payroll.confirmHours':      { EN:'Confirm hours', IS:'StaÃ°festa tÃ­ma' },
  'payroll.periodApproved':    { EN:'Approved', IS:'SamÃ¾ykkt' },
  'payroll.periodOpen':        { EN:'Open', IS:'OpiÃ°' },
  'payroll.periodLabel':       { EN:'Pay period', IS:'LaunatÃ­mabil' },
  'payroll.employeeCount':     { EN:'{n} employees', IS:'{n} starfsmenn' },
  'payroll.grossLabel':        { EN:'Gross', IS:'Heildarlaun' },
  'payroll.netLabel':          { EN:'Net', IS:'Ãtborgun' },
  'payroll.paymentDate':       { EN:'Payment date', IS:'GreiÃ°sludagur' },
  'payroll.slipNumber':        { EN:'Slip no.', IS:'SeÃ°ilnÃºmer' },
  'payroll.personuafslattr':   { EN:'Personal tax credit (kr/month)', IS:'PersÃ³nuafslÃ¡ttur (kr/mÃ¡n.)' },
  'payroll.personuafslattrPct':{ EN:'% of standard credit used here', IS:'% af staÃ°laÃ°ri upphÃ¦Ã° hÃ©r' },
  'payroll.configTitle':       { EN:'Payroll Config', IS:'Stillingar launakerfis' },
  'payroll.ot1Rate':           { EN:'Overtime tier 1 multiplier', IS:'Eftirvinna Ã¾rep 1 margfaldari' },
  'payroll.ot2Rate':           { EN:'Overtime tier 2 multiplier', IS:'Eftirvinna Ã¾rep 2 margfaldari' },
  'payroll.orlofsRate':        { EN:'Holiday pay rate', IS:'Orlofslaun hlutfall' },
  'payroll.empPensionRate':    { EN:'Employee pension %', IS:'LÃ­feyrissjÃ³Ã°ur starfsmann %' },
  'payroll.emplPensionRate':   { EN:'Employer pension %', IS:'MÃ³tframlag lÃ­feyrissjÃ³Ã°ur %' },
  'payroll.taxBracket1':       { EN:'Tax bracket 1 rate (up to 583,854 kr)', IS:'Skattstigi 1 (upp aÃ° 583.854 kr)' },
  'payroll.taxBracket2':       { EN:'Tax bracket 2 rate (up to 1,645,733 kr)', IS:'Skattstigi 2 (upp aÃ° 1.645.733 kr)' },
  'payroll.taxBracket3':       { EN:'Tax bracket 3 rate', IS:'Skattstigi 3' },
  'payroll.unionDuesRate':     { EN:'Union dues rate', IS:'StÃ©ttarfÃ©lagsgjald hlutfall' },
  'payroll.hoursTotal':        { EN:'Total hours', IS:'HeildartÃ­mar' },
  'payroll.editEntry':         { EN:'Edit', IS:'Breyta' },
  'payroll.notEnabled':        { EN:'Not in payroll', IS:'Ekki Ã­ launakerfi' },
  'payroll.enablePayroll':     { EN:'Enable payroll', IS:'Virkja Ã­ launakerfi' },
  'payroll.calView':           { EN:'Calendar',            IS:'Dagatal' },
  'payroll.listView':          { EN:'List',                IS:'Listi' },
  'payroll.addEntry':          { EN:'+ Add entry',         IS:'+ BÃ¦ta viÃ° fÃ¦rslu' },
  'payroll.deleteEntry':       { EN:'Delete',              IS:'EyÃ°a' },
  'payroll.deleteConfirm':     { EN:'Delete this time entry?', IS:'EyÃ°a Ã¾essari tÃ­mafÃ¦rslu?' },
  'payroll.allStaff':          { EN:'All staff',           IS:'Allir starfsmenn' },
  'payroll.employee':          { EN:'Employee',            IS:'StarfsmaÃ°ur' },
  'payroll.totalHours':        { EN:'total',               IS:'samtals' },
  'payroll.clockInLabel':      { EN:'Clock in',            IS:'Stimpla inn' },
  'payroll.clockOutLabel':     { EN:'Clock out',           IS:'Stimpla Ãºt' },
  'payroll.minsLabel':         { EN:'Duration (minutes)',  IS:'TÃ­malengd (mÃ­nÃºtur)' },
  'payroll.noteOptional':      { EN:'Note (optional)',     IS:'Athugasemd (valfrjÃ¡lst)' },
  'payroll.notePlaceholder':   { EN:'e.g. forgotten punch-in', IS:'t.d. gleymt innstimpl' },
  'payroll.autoCalc':          { EN:'auto-calculated, override if needed', IS:'reiknast sjÃ¡lft, hnekktu ef Ã¾arf' },
  'payroll.entryRequired':  { EN:'Employee, clock-in and clock-out are required.', IS:'Starfsma\u00f0ur, innstimplun og \u00fatstimplun eru nauÃ°synleg.' },
  'payroll.clockOutAfterIn':{ EN:'Clock-out must be after clock-in.', IS:'\u00datstimplun ver\u00f0ur a\u00f0 vera eftir innstimplun.' },
  'payroll.moreEntries':    { EN:'more',                        IS:'\u00ed vi\u00f0b\u00f3t' },
  'payroll.pastPeriods':    { EN:'Past periods',                IS:'Fyrri t\u00edmabil' },
  'payroll.titleField':     { EN:'Title',                       IS:'Starfsheiti' },
  'payroll.bankAccount':    { EN:'Bank account',                IS:'Launareikningur' },
  'payroll.orlofsreikningur':{ EN:'Holiday account',           IS:'Orlofsreikningur' },
  'payroll.union':          { EN:'Union',                       IS:'St\u00e9ttarf\u00e9lag' },
  'payroll.sereignRate':    { EN:'Private pension %',           IS:'S\u00e9reign %' },
  'payroll.pension':        { EN:'Pension',                     IS:'L\u00edfeyrissjÃ³\u00f0ur' },
  'lbl.year':               { EN:'Year',                        IS:'\u00c1r' },
  'lbl.duration':           { EN:'Duration',                    IS:'T\u00edmal\u00e6ngd' },
  'lbl.edited':             { EN:'edited',                      IS:'breytt' },
  'lbl.admin':              { EN:'admin',                       IS:'stjÃ³rnandi' },
  'lbl.staff':              { EN:'staff',                       IS:'starfsma\u00f0ur' },
  'lbl.monShort':           { EN:'Mon',                         IS:'M\u00e1n' },
  'lbl.tueShort':           { EN:'Tue',                         IS:'\u00deri' },
  'lbl.wedShort':           { EN:'Wed',                         IS:'Mi\u00f0' },
  'lbl.thuShort':           { EN:'Thu',                         IS:'Fim' },
  'lbl.friShort':           { EN:'Fri',                         IS:'F\u00f6s' },
  'lbl.satShort':           { EN:'Sat',                         IS:'Lau' },
  'lbl.sunShort':           { EN:'Sun',                         IS:'Sun' },
  'payroll.earningsSection':   { EN:'Earnings',          IS:'Laun' },
  'payroll.deductionsSection': { EN:'Deductions',        IS:'Fr\u00e1dr\u00e1ttur' },
  'payroll.accumulatedSection':{ EN:'Accumulated',       IS:'Til uppsafnanar' },
  'payroll.employerSection':   { EN:'Employer contribution', IS:'Framlag launagrei\u00f0anda' },
  'payroll.ytdSection':        { EN:'Year to date',      IS:'\u00c1r til \u00fea gs' },
  'payroll.totalDeductions':   { EN:'Total deductions',  IS:'Heildarf r\u00e1dr\u00e1ttur' },
  'payroll.orlofslaun':        { EN:'Holiday pay (bank)',IS:'Orlof \u00ed banka' },
  'payroll.payslip':           { EN:'Payslip',           IS:'Launase\u00f0ill' },
  'payroll.baseRate':          { EN:'Base rate (kr/hr)', IS:'Grunntaxti (kr/klst)' },
  'payroll.dagvinna':            { EN:'Regular time',           IS:'Dagvinna' },
  'payroll.ot1Label':            { EN:'Overtime 1.33\u00d7',    IS:'Eftirvinna 1,33' },
  'payroll.ot2Label':            { EN:'Overtime 1.55\u00d7',    IS:'Eftirvinna 1,55' },
  'payroll.units':               { EN:'Units',                  IS:'Einingar' },
  'payroll.rate':                { EN:'Rate',                   IS:'Taxti' },
  'payroll.amount':              { EN:'Amount',                 IS:'Upph\u00e6\u00f0' },
  'payroll.ytdUnits':            { EN:'YTD units',              IS:'Einingar (\u00e1r)' },
  'payroll.taxComputed':         { EN:'Computed tax',           IS:'ReiknuÃ° sta\u00f0greiÃ°sla' },
  'payroll.employerPension':     { EN:'Employer pension',       IS:'M\u00f3tframlag l\u00edfeyriss' },
  'payroll.endurhaefingarsjodur':{ EN:'Rehabilitation fund',    IS:'EndurhÃ¦fingarsj\u00f3\u00f0ur' },
  'payroll.now':                 { EN:'Now',                    IS:'N\u00fa' },
};

window.s = function s(key, vars, lang) {
  const L   = lang || (typeof getLang === 'function' ? getLang() : 'EN');
  const entry = STRINGS[key];
  if (!entry) {
    // Fail gracefully: return the key itself so missing strings are obvious
    console.warn('[strings] missing key:', key);
    return key;
  }
  let str = entry[L] || entry['EN'] || key;
  if (vars) {
    str = str.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? vars[k] : '{' + k + '}'));
  }
  return str;
};

/**
 * Apply strings to DOM elements via data-s="key" attributes.
 * Call applyStrings() once after the DOM is ready on any page that
 * uses static HTML labels (as opposed to JS-rendered content).
 *
 * Usage in HTML:  <label data-s="lbl.name"></label>
 *                 <button data-s="btn.save"></button>
 *                 <span data-s="nav.weather" data-s-attr="title"></span>
 */
window.applyStrings = function applyStrings(root) {
  (root || document).querySelectorAll('[data-s]').forEach(el => {
    const key  = el.dataset.s;
    const attr = el.dataset.sAttr;
    const val  = window.s(key);
    if (attr) el.setAttribute(attr, val);
    else      el.textContent = val;
  });
  'payroll.config': { EN:'Config',                         IS:'Stillingar' },
  'payroll.configPayroll': { EN:'Payroll settings',               IS:'Launastillingar' },
  'payroll.pensionFunds': { EN:'Pension funds',                  IS:'LÃ­feyrissjÃ³Ã°ir' },
  'payroll.addFund': { EN:'Add fund',                       IS:'BÃ¦ta viÃ° sjÃ³Ã°i' },
  'payroll.fundName': { EN:'Fund name',                      IS:'Heiti sjÃ³Ã°s' },
  'payroll.fundNameEN': { EN:'Fund name (EN)',                  IS:'Heiti sjÃ³Ã°s (EN)' },
  'payroll.unions': { EN:'Unions',                         IS:'StÃ©ttarfÃ©lÃ¶g' },
  'payroll.addUnion': { EN:'Add union',                      IS:'BÃ¦ta viÃ° fÃ©lagi' },
  'payroll.unionName': { EN:'Union name',                     IS:'Heiti fÃ©lags' },
  'payroll.deductionLines': { EN:'Deduction lines',                IS:'FrÃ¡drÃ¡ttsliÃ°ir' },
  'payroll.lineLabel': { EN:'Label',                          IS:'Heiti' },
  'payroll.lineLabelEN': { EN:'Label (EN)',                     IS:'Heiti (EN)' },
  'payroll.empRate': { EN:'Employee %',                     IS:'StarfsmaÃ°ur %' },
  'payroll.emprRate': { EN:'Employer %',                     IS:'LaunagreiÃ°andi %' },
  'payroll.otRules': { EN:'Overtime rules',                 IS:'Yfirvinnureglur' },
  'payroll.otEligible': { EN:'Overtime eligible',              IS:'RÃ©ttindi til yfirvinnu' },
  'payroll.otPeriods': { EN:'OT periods',                     IS:'YfirvinnuterÃºr' },
  'payroll.otDays': { EN:'Days (0=Sunâ¦6=Sat)',         IS:'Dagar (0=Sunâ¦6=Lau)' },
  'payroll.otFrom': { EN:'From hour',                      IS:'FrÃ¡ klukkustund' },
  'payroll.otTo': { EN:'To hour',                        IS:'AÃ° klukkustund' },
  'payroll.otMultiplier': { EN:'Multiplier',                     IS:'Margfaldari' },
  'payroll.personuafslattrUnit': { EN:'Personal credit unit (krâ¯=â¯1.0)', IS:'PersÃ³nuafslÃ¡ttur eining (krâ¯=â¯1,0)' },
  'payroll.personuafslattrFrac': { EN:'Personal credit (fraction)',     IS:'Hlutfall persÃ³nuafslÃ¡ttar' },
  'payroll.pensionFundIds': { EN:'Pension fund(s)',                IS:'LÃ­feyrissjÃ³Ã°ur' },
  'payroll.unionId': { EN:'Union',                          IS:'StÃ©ttarfÃ©lag' },
  'payroll.none': { EN:'None',                           IS:'Ekkert' },
  // ââ Payroll config & new UI keys added 2026-03-27
  'payroll.personuafslattrFraction': { EN:'Personal credit fraction',     IS:'Hlutfall persÃ³nuafslÃ¡ttar' },

};
