var _STRINGS_FLAT = {
  "nav.staffHub": "⚓️ Staff",
  "nav.memberHub": "⛵ Home",
  "nav.admin": "⚙️ Admin",
  "nav.weather": "⛅️ Weather",
  "nav.logbook": "📖 Logbook",
  "nav.back": "← Back",
  "nav.signOut": "Sign out",
  "nav.langToggle": "IS",
  "btn.save": "Save",
  "btn.saveClose": "Save & close",
  "btn.cancel": "Cancel",
  "btn.delete": "Delete",
  "btn.edit": "Edit",
  "btn.add": "+ Add",
  "btn.close": "Close",
  "btn.confirm": "Confirm",
  "btn.resolve": "Resolve",
  "btn.saveDraft": "Save draft",
  "btn.signOff": "Save & Sign off",
  "btn.submit": "Submit",
  "btn.addComment": "Add comment",
  "btn.viewAll": "View all →",
  "lbl.loading": "Loading…",
  "lbl.on": "On",
  "lbl.off": "Off",
  "lbl.noData": "No data",
  "lbl.name": "Name",
  "lbl.date": "Date",
  "lbl.time": "Time",
  "lbl.notes": "Notes",
  "lbl.status": "Status",
  "lbl.phone": "Phone",
  "lbl.email": "Email",
  "lbl.location": "Location",
  "lbl.boat": "Boat",
  "lbl.crew": "Crew",
  "lbl.role": "Role",
  "lbl.member": "Member",
  "lbl.guest": "Guest",
  "lbl.guardian": "Guardian",
  "lbl.minor": "MINOR",
  "lbl.verified": "✓ Verified",
  "lbl.pending": "Pending review",
  "lbl.optional": "optional",
  "lbl.filter": "FILTER:",
  "lbl.active": "Active",
  "lbl.inactive": "Inactive",
  "lbl.season": "Season",
  "lbl.category": "Category",
  "lbl.description": "Description",
  "lbl.severity": "Severity",
  "lbl.type": "Type",
  "lbl.phase": "Phase",
  "lbl.sortOrder": "Sort order",
  "lbl.selectDots": "Select…",
  "lbl.noneDash": "— none —",
  "toast.saved": "Saved",
  "toast.saveFailed": "Save failed",
  "toast.deleted": "Deleted",
  "toast.error": "Something went wrong. Try again.",
  "toast.loadFailed": "Load failed",
  "toast.signedOff": "Signed off ✓",
  "toast.checkedIn": "Checked in ✓",
  "toast.noPhone": "No phone on record",
  "flag.green.label": "Green",
  "flag.green.advice": "Good conditions.",
  "flag.yellow.label": "Yellow",
  "flag.yellow.advice": "Marginal — experienced sailors only.",
  "flag.orange.label": "Orange",
  "flag.orange.advice": "Difficult — keelboats only, staff auth for dinghies.",
  "flag.red.label": "Red",
  "flag.red.advice": "Do not sail — all sailing suspended.",
  "flag.currentLabel": "CURRENT FLAG",
  "flag.allLevels": "All levels →",
  "flag.conditions": "Sailing Conditions",
  "wx.wind": "WIND",
  "wx.gusts": "GUSTS",
  "wx.waves": "WAVES",
  "wx.pressure": "PRESSURE",
  "wx.loading": "Loading conditions…",
  "wx.unavailable": "⚠️ Weather unavailable",
  "wx.fullForecast": "Full forecast →",
  "wx.updated": "Updated",
  "login.title": "Ýmir Sailing Club",
  "login.subtitle": "Sailing Club",
  "login.kennitala": "Kennitala",
  "login.placeholder": "0000000000",
  "login.btn": "Sign in",
  "login.loading": "Signing in…",
  "login.notFound": "Member not found or account inactive.",
  "login.tooShort": "Please enter your 10-digit kennitala.",
  "login.error": "Login failed. Try again.",
  "login.welcome": "Welcome,",
  "login.chooseView": "How would you like to sign in?",
  "login.back": "← Sign in as someone else",
  "login.admin.label": "Admin Panel",
  "login.admin.desc": "Manage members, boats, locations, settings",
  "login.staff.label": "Staff Dashboard",
  "login.staff.desc": "Daily log, fleet status, maintenance, incidents",
  "login.member.label": "Member Hub",
  "login.member.desc": "Go sailing, logbook, volunteer",
  "member.launchBoat": "🚀 Launch a Boat",
  "member.checkIn": "✓ Check In",
  "member.reportIssue": "🔧 Report Issue",
  "member.myCheckout": "BOATS OUT NOW",
  "member.myCheckoutSub": "Tap your boat to check in",
  "member.tabFleet": "Fleet",
  "member.tabTrips": "Log a Trip",
  "member.tabLogbook": "Logbook",
  "member.tabCerts": "Credentials",
  "member.fleetAvail": "AVAILABLE BOATS",
  "member.tripTabHint": "Tap a recent trip below to add it to your logbook as crew, or log a trip manually.",
  "member.statTrips": "TOTAL TRIPS",
  "member.statHours": "HOURS SAILED",
  "member.statBoat": "MOST-SAILED BOAT",
  "member.statSeason": "TRIPS THIS SEASON",
  "member.noTrips": "No trips in your logbook yet.",
  "member.noCheckouts": "No boats out.",
  "member.noBoats": "No boats available.",
  "member.noCerts": "No credentials on file.",
  "member.boatOut": "Out",
  "member.boatOos": "Out of service",
  "member.boatAvail": "Available",
  "member.skipper": "skipper",
  "member.crewRole": "crew",
  "member.addAsCrew": "Add as crew",
  "member.tripsTapHint": "Tap a trip for details",
  "member.departed": "Departed",
  "member.returned": "Returned",
  "member.duration": "Duration",
  "member.loadFailed": "Load failed",
  "member.logManual": "+ Log manually",
  "member.recentTrips": "RECENT PUBLIC TRIPS",
  "member.noRecent": "No recent trips",
  "member.myLogbook": "MY LOGBOOK",
  "member.myCerts": "MY CREDENTIALS",
  "member.launchTitle": "Launch a Boat",
  "member.nonClubBoat": "Non-club boat",
  "member.nonClubHint": "Use your own boat or a boat from another club",
  "member.checkInTitle": "Check In",
  "member.manualTrip": "Log a Trip",
  "member.pendingConfirmations": "Pending Confirmations",
  "member.confirmationsTitle": "Trip Confirmations",
  "member.incoming": "REQUESTS FOR YOU",
  "member.outgoing": "YOUR REQUESTS",
  "member.noIncoming": "No pending requests.",
  "member.noOutgoing": "No outgoing requests.",
  "member.crewAssigned": "recorded you as crew",
  "member.crewJoin": "wants to join your trip",
  "member.helmReq": "recorded you as helm",
  "member.confirmBtn": "Confirm",
  "member.rejectBtn": "Reject",
  "member.statusPending": "pending",
  "member.statusConfirmed": "confirmed",
  "member.statusRejected": "rejected",
  "member.rejectReason": "Reason for rejection (optional):",
  "member.shareRecord": "SHARE YOUR RECORD",
  "member.shareDesc": "Generate a link to share your sailing record with charter agents or other parties. The link shows sessions up to today's date.",
  "member.btnGenerate": "+ Generate share link",
  "member.noTokens": "No share links generated yet.",
  "member.tokenCreated": "Share link created.",
  "settings.title": "Settings",
  "settings.initials": "Initials",
  "settings.initialsHint": "Auto-generated from your name. Override below.",
  "settings.language": "Language",
  "settings.windUnit": "Wind units",
  "settings.windUnit.bft": "Beaufort (Force 4)",
  "settings.windUnit.ms": "m/s",
  "settings.windUnit.kts": "Knots",
  "settings.windUnit.kmh": "km/h",
  "settings.windUnit.mph": "mph",
  "settings.windUnitHint": "Controls wind display in your logbook.",
  "settings.theme": "Appearance",
  "settings.theme.dark": "Dark",
  "settings.theme.light": "Light",
  "settings.theme.auto": "Auto",
  "settings.stats": "Stats visibility",
  "settings.statsHint": "Choose which stats appear on your logbook page.",
  "settings.stats.ytd": "Trips this year (YTD)",
  "settings.stats.career": "Total trips (career)",
  "settings.stats.hours": "Hours sailed",
  "settings.stats.skipper": "As skipper",
  "settings.stats.byCategory": "Hours by category",
  "settings.stats.distance": "Total distance (nm)",
  "settings.stats.longest": "Longest trip",
  "settings.stats.avgWind": "Average wind",
  "settings.stats.streak": "Weekly streak",
  "settings.stats.boats": "Unique boats sailed",
  "settings.stats.crew": "Trips as crew",
  "settings.stats.heavy": "Heavy weather (F5+)",
  "settings.stats.night": "Night sails",
  "settings.stats.avgDuration": "Avg trip duration",
  "settings.stats.locations": "Locations sailed",
  "settings.stats.verified": "Verified trips",
  "settings.statsGroup.activity": "Activity",
  "settings.statsGroup.sailing": "Sailing",
  "settings.statsGroup.roles": "Roles & boats",
  "settings.statsGroup.conditions": "Conditions",
  "settings.statsGroup.other": "Other",
  "settings.saved": "Settings saved",
  "settings.saveFailed": "Failed to save settings",
  "nav.settings": "⚙ Settings",
  "logbook.shareBtn": "Share your logbook",
  "logbook.sharePhotos": "Include photos",
  "logbook.shareTracks": "Include GPS tracks",
  "logbook.shareCopy": "Generate & copy link",
  "logbook.exportCsv": "Export as CSV",
  "logbook.shareCopied": "Link copied!",
  "logbook.activeTokens": "Active share tokens",
  "logbook.editTrip": "Edit trip",
  "logbook.addGps": "Add GPS",
  "logbook.addPhotos": "Add photos",
  "logbook.shareWithCrew": "Share with crew",
  "logbook.clubMayUse": "Club may use",
  "logbook.photoSharedHint": "Shared photos are visible to other trip members. Club-use photos may be used for promotional purposes.",
  "logbook.tripUpdated": "Trip updated",
  "logbook.trackAdded": "GPS track added",
  "logbook.photosAdded": "Photos added",
  "logbook.skipperOnly": "Only the skipper can edit this trip",
  "staff.dashTitle": "Staff Dashboard",
  "staff.fleet": "FLEET STATUS",
  "staff.expandAll": "expand all",
  "staff.collapseAll": "collapse all",
  "staff.recentCheckins": "RECENT CHECK-INS (24H)",
  "staff.overdue": "OVERDUE",
  "staff.overdueMinor": "OVERDUE — MINOR",
  "staff.maintenance": "OPEN MAINTENANCE",
  "staff.maintDetail": "Issue Detail",
  "staff.dailyLog": "Daily Log",
  "staff.dailyLogDesc": "Tides, weather records, checklists, activities, sign-off",
  "staff.logbook": "Logbook Review",
  "staff.logbookDesc": "Verify member trips & assign credentials",
  "staff.incidents": "Incidents",
  "staff.incidentsDesc": "File or review safety incident reports",
  "staff.maintenanceDesc": "Report and track boat & equipment issues",
  "staff.noOverdue": "No overdue checkouts.",
  "staff.noMaint": "No open requests.",
  "staff.silence": "Silence",
  "staff.snooze": "Snooze",
  "staff.minsOverdue": "{n} min overdue",
  "staff.hrsOverdue": "{h}h {m}min overdue",
  "staff.expectedReturn": "Expected return",
  "staff.checkIn": "✓ Check In",
  "staff.deleteCheckout": "Delete",
  "staff.availCount": "{n} available",
  "staff.activeCheckouts": "ACTIVE CHECKOUTS",
  "staff.boatsOutNow": "BOATS OUT NOW",
  "staff.checkOutBtn": "Boat Checkout",
  "staff.groupCheckout": "Group Checkout",
  "staff.newCheckout": "NEW CHECKOUT",
  "staff.statBoats": "BOATS OUT",
  "staff.statPeople": "PEOPLE OUT",
  "staff.statOverdue": "OVERDUE",
  "staff.toolsLabel": "TOOLS",
  "staff.fullForecast": "⛅️ Full Forecast →",
  "staff.tideHeader": "TIDES · FAXAFLÓI",
  "tide.rising": "Rising",
  "tide.falling": "Falling",
  "tide.high": "High",
  "tide.low": "Low",
  "tide.next": "NEXT",
  "tide.autoFill": "↻ Auto-fill tides",
  "tide.autoFilled": "Auto-filled from prediction",
  "staff.coForm.departure": "Departure",
  "staff.coForm.estReturn": "Est. return",
  "staff.coForm.crew": "Crew on board",
  "staff.coForm.notes": "Notes (optional)",
  "staff.coForm.submit": "Check Out",
  "staff.coForm.memberPlaceholder": "Name or kennitala…",
  "staff.coForm.notesPlaceholder": "Any notes…",
  "staff.coForm.errMember": "Select a member.",
  "staff.coForm.errBoat": "Select a boat.",
  "staff.coForm.errLocation": "Select a sailing area.",
  "staff.coForm.checkedOut": "Checked out ✓",
  "staff.coDetail.title": "Checkout Details",
  "staff.coDetail.tripLabel": "TRIP",
  "staff.coDetail.out": "OUT",
  "staff.coDetail.return": "EST. RETURN",
  "staff.noBoatsOut": "No boats currently out.",
  "staff.noRecentCheckins": "No check-ins in the last 24 hours.",
  "daily.title": "Daily Log",
  "daily.today": "Today",
  "daily.tripsToday": "TRIPS TODAY",
  "daily.openingChecklist": "OPENING CHECKLIST",
  "daily.closingChecklist": "CLOSING CHECKLIST",
  "daily.activities": "ACTIVITIES",
  "daily.addActivity": "+ Add",
  "daily.staffNotes": "STAFF NOTES",
  "daily.notesPlaceholder": "General notes, conditions summary…",
  "daily.incidentReport": "INCIDENTS",
  "daily.fileIncident": "Submit an Incident Report",
  "daily.incidentSub": "Injuries, near-misses, property damage, safety concerns",
  "daily.noIncidents": "No incidents reported.",
  "daily.wxLog": "WEATHER LOG",
  "daily.tides": "TIDES",
  "daily.signedOff": "Signed off",
  "daily.readOnly": "Read-only",
  "daily.noActivities": "No activities recorded yet.",
  "daily.noTrips": "No trips recorded today.",
  "daily.activityModal": "Add Activity",
  "daily.actType": "Type",
  "daily.actNameLabel": "Name / description",
  "daily.actNameHint": "e.g. Junior lesson, club race…",
  "daily.actParticipants": "Participants",
  "daily.actPartHint": "e.g. 12 juniors",
  "daily.actNotes": "Notes",
  "daily.actNotesHint": "optional",
  "daily.startTime": "Start time",
  "daily.endTime": "End time",
  "daily.wxLogBtn": "📸 Log snapshot",
  "daily.noWxData": "No weather data yet.",
  "daily.signOffConfirm": "PM checklist not complete ({done}/{total}). Sign off anyway?",
  "daily.saveDraftSaving": "Saving…",
  "daily.signOffSaving": "Signing off…",
  "daily.signedOffBy": "✓ Signed off by ",
  "incident.title": "Incidents",
  "incident.viewList": "View incidents",
  "incident.fileNew": "File new report",
  "incident.typeLabel": "Incident type(s)",
  "incident.noIncidents": "No incidents filed.",
  "incident.description": "Description",
  "incident.involved": "Person(s) involved",
  "incident.witnesses": "Witnesses",
  "incident.immediateAction": "Immediate action taken",
  "incident.followUp": "Follow-up required",
  "incident.handOff": "Handed off to",
  "incident.staffNotes": "Staff notes",
  "incident.addNote": "Add note",
  "incident.resolved": "Resolved",
  "incident.open": "Open",
  "incident.markResolved": "Close review, save & file",
  "incident.markOpen": "Reopen",
  "incident.filedBy": "Filed by",
  "incident.boatLabel": "Boat (if applicable)",
  "incident.personsInvolved": "Persons involved",
  "incident.witnessHint": "Names / contact info…",
  "incident.actionHint": "First aid, evacuation, coastguard called…",
  "incident.followUpHint": "Referral, repair, investigation…",
  "incident.handoffSection": "Hand-off",
  "incident.handoffTo": "Handed off to",
  "incident.handoffName": "Contact name / ref.",
  "incident.handoffNotes": "Handoff notes",
  "incident.fileBtn": "File Report",
  "incident.descRequired": "Description is required.",
  "incident.typeRequired": "Select at least one incident type.",
  "incident.sevRequired": "Select severity.",
  "incident.filed": "Report filed ✓",
  "incident.addNoteBtn": "Add note",
  "incident.notePlaceholder": "Add a note…",
  "incident.type.injury": "🩹 Injury",
  "incident.type.capsize": "⛵ Capsize",
  "incident.type.collision": "💥 Collision",
  "incident.type.equipment": "🔧 Equipment failure",
  "incident.type.medical": "🏥 Medical",
  "incident.type.nearMiss": "⚡️ Near miss",
  "incident.type.missing": "🔍 Missing person",
  "incident.type.propertyDmg": "🏗️ Property damage",
  "incident.type.stranding": "⚓️ Ran aground",
  "incident.type.other": "📌 Other",
  "incident.saveCloseFile": "Save, close & file",
  "incident.saveForReview": "Save for follow-up / review",
  "incident.statusReview": "Needs review or follow-up",
  "incident.reviewerNotes": "Reviewer comments",
  "incident.addReviewerNote": "Add reviewer comment",
  "incident.sev.low": "Low",
  "incident.sev.medium": "Medium",
  "incident.sev.high": "High",
  "incident.sev.critical": "Critical",
  "maint.title": "Maintenance",
  "maint.newRequest": "+ Report issue",
  "maint.category": "Category",
  "maint.catBoat": "Boat",
  "maint.catEquipment": "Equipment",
  "maint.catFacility": "Facility",
  "maint.part": "Location / part",
  "maint.severity": "Severity",
  "maint.sevLow": "Low — no rush",
  "maint.sevMedium": "Medium — fix soon",
  "maint.sevHigh": "High — affects safety",
  "maint.markOos": "Mark boat out of service",
  "maint.reportedBy": "Reported by",
  "maint.noRequests": "No open maintenance requests.",
  "maint.resolved": "Resolved",
  "maint.open": "Open",
  "maint.resolveBtn": "Mark resolved",
  "maint.comments": "Comments",
  "maint.descPlaceholder": "Describe the issue…",
  "maint.partPlaceholder": "e.g. hull, mast, clubhouse roof…",
  "maint.newTitle": "NEW MAINTENANCE REQUEST",
  "maint.filterOpen": "Open",
  "maint.filterAll": "All",
  "maint.filterBoat": "Boat",
  "maint.filterEquipment": "Equipment",
  "maint.filterFacility": "Facility",
  "maint.commentPlaceholder": "Add a comment…",
  "maint.addCommentBtn": "Add",
  "maint.oosConfirm": "Mark this boat out of service?",
  "maint.resolveConfirm": "Mark this request as resolved?",
  "maint.statOpen": "OPEN",
  "maint.statHigh": "HIGH / CRITICAL",
  "maint.statOos": "BOATS OOS",
  "sauma.pageTitle": "🧵 Sewing Circle",
  "sauma.pageSubtitle": "Community maintenance projects",
  "sauma.toggle": "Sewing Circle Project",
  "sauma.toggleHint": "Mark as a sewing circle project",
  "sauma.verkstjori": "Project Lead",
  "sauma.verkstjoriHint": "If left blank, any member can adopt this project.",
  "sauma.filterOpen": "Open",
  "sauma.filterMy": "My Projects",
  "sauma.filterUnassigned": "Unassigned",
  "sauma.filterCompleted": "Completed",
  "sauma.filterResolved": "Resolved",
  "sauma.filterAll": "All",
  "sauma.needsVerkstjori": "Needs verkstjóri",
  "sauma.emptyDefault": "No projects match this filter.",
  "sauma.emptyMy": "No projects you are involved in.",
  "sauma.suggestBtn": "+ New sewing circle project",
  "sauma.suggestTitle": "🧵 New sewing circle project",
  "sauma.pendingReview": "Pending Review",
  "sauma.approve": "Approve",
  "sauma.pendingMsg": "Project submitted for review.",
  "maint.statPending": "PENDING REVIEW",
  "sauma.priority": "Priority",
  "sauma.description": "Description",
  "sauma.materials": "Materials Needed",
  "sauma.photoLabel": "Photo (optional, max 5 MB)",
  "sauma.viewList": "List",
  "sauma.viewBoard": "Board",
  "sauma.colTodo": "To Do",
  "sauma.colInProgress": "In Progress",
  "sauma.colOnHold": "On Hold",
  "sauma.colDone": "Done",
  "sauma.colEmpty": "No projects",
  "sauma.myBoardFilter": "My projects only",
  "sauma.holdBtn": "Put On Hold",
  "sauma.resumeBtn": "Resume",
  "sauma.holdConfirm": "Put this project on hold?",
  "sauma.resumeConfirm": "Resume this project?",
  "sauma.filterOnHold": "On Hold",
  "nav.saumaklubbur": "🧵 Sewing Circle",
  "staff.maintAndSauma": "Maintenance & Projects",
  "staff.maintAndSaumaDesc": "Maintenance requests & sewing circle projects",
  "logrev.title": "Logbook Review",
  "logrev.subtitle": "Verify member trips · assign credentials",
  "logrev.totalTrips": "TOTAL TRIPS",
  "logrev.pending": "PENDING REVIEW",
  "logrev.verified": "VERIFIED",
  "logrev.verify": "Verify",
  "logrev.unverify": "Unverify",
  "logrev.staffComment": "Staff comment (optional)",
  "logrev.noTrips": "No trips to review.",
  "logrev.filterAll": "All",
  "logrev.filterPending": "Pending",
  "logrev.filterVerified": "Verified",
  "logrev.filterName": "Filter by name…",
  "logrev.filterFrom": "From",
  "logrev.filterTo": "To",
  "logrev.assignCert": "ASSIGN CREDENTIAL",
  "logrev.assignedDate": "Assigned date",
  "logrev.expires": "Expires",
  "logrev.assignBtn": "Assign",
  "logrev.certModal": "Credentials",
  "logrev.noCerts": "No credentials on file.",
  "logrev.validationRequests": "Validation requests",
  "logrev.showAll": "Show all trips",
  "logrev.certSearch": "Search for a member above to view their credentials.",
  "logrev.certSearchPlaceholder": "Search member name...",
  "logrev.certModeByMember": "By member",
  "logrev.certModeByType": "By credential",
  "logrev.certSelectType": "— Select credential —",
  "logrev.certNoMatches": "No members found with this credential.",
  "logrev.verifyRequest": "VERIFICATION REQUEST",
  "admin.tabMembers": "Members",
  "admin.tabSettings": "Settings",
  "admin.tabBoats": "Boats",
  "admin.tabLocations": "Locations",
  "admin.tabChecklists": "Checklists",
  "admin.tabActTypes": "Activity Types",
  "admin.tabCerts": "Credentials",
  "admin.tabAlerts": "Alerts",
  "admin.tabPayroll": "💰 Payroll",
  "admin.tabFlags": "Flags",
  "admin.tabReservations": "Charters",
  "admin.bulkSchedule": "BULK SCHEDULE",
  "admin.chartersDesc": "Charter slots are recurring, bookable time windows that captains can reserve for rowing teams or private charters. Create a recurring pattern to make slots available on selected days, then captains can book them from their page.",
  "admin.importCsv": "⇪ Import CSV",
  "admin.searchMembers": "Search name or kennitala…",
  "admin.noMembers": "No members yet.",
  "admin.addMember": "+ Add member",
  "admin.addBoat": "+ Add boat",
  "admin.addLocation": "+ Add location",
  "admin.addItem": "+ Add item",
  "admin.addType": "+ Add type",
  "admin.importUpdated": "updated",
  "admin.importMissing": "not in import",
  "admin.importUnchanged": "unchanged",
  "admin.saveChanges": "Save changes",
  "admin.alertFirstMins": "First alert after (min)",
  "admin.alertRepeatMins": "Repeat every (min)",
  "admin.alertSnoozeMins": "Snooze duration (min)",
  "admin.alertEnabled": "Alerts enabled",
  "admin.flagThresholds": "Flag thresholds",
  "admin.windYellow": "Wind yellow (Bft)",
  "admin.windOrange": "Wind orange (Bft)",
  "admin.windRed": "Wind red (Bft)",
  "admin.waveYellow": "Wave yellow (m)",
  "admin.waveOrange": "Wave orange (m)",
  "admin.waveRed": "Wave red (m)",
  "admin.memberModal.add": "Add Member",
  "admin.memberModal.edit": "Edit Member",
  "admin.fullName": "Full name",
  "admin.birthYear": "Birth year",
  "admin.isMinor": "Minor (under 18)",
  "admin.guardianSection": "GUARDIAN / PARENT",
  "admin.guardianName": "Guardian name",
  "admin.guardianPhone": "Guardian phone",
  "admin.guardianKt": "Guardian kennitala",
  "admin.boatModal.add": "Add Boat",
  "admin.boatModal.edit": "Edit Boat",
  "admin.boatName": "Boat name",
  "admin.boatCategory": "Category",
  "admin.boatOos": "Out of service",
  "admin.boatOosReason": "OOS reason",
  "admin.locModal.add": "Add Location",
  "admin.locModal.edit": "Edit Location",
  "admin.clPhase": "Phase",
  "admin.clPhaseAm": "AM",
  "admin.clPhasePm": "PM",
  "admin.clTextEN": "Text (EN)",
  "admin.clTextIS": "Text (IS)",
  "admin.actTypeEN": "Name (EN)",
  "admin.actTypeIS": "Name (IS)",
  "admin.certName": "Cert name (EN)",
  "admin.certRenewal": "Renewal (days, 0 = permanent)",
  "admin.certTypes": "CREDENTIAL TYPES",
  "admin.certAssign": "ASSIGN CREDENTIALS",
  "admin.certAddType": "+ Add credential type",
  "admin.certAddModal": "Add Credential Type",
  "admin.certEditModal": "Edit Credential Type",
  "admin.certDesc": "Description",
  "admin.certDescOptional": "(optional)",
  "admin.certRenewalPerm": "Permanent",
  "admin.certRenewalAnnual": "Annual (365 days)",
  "admin.certRenewalBiennial": "Biennial (730 days)",
  "admin.certRenewalCustom": "Custom…",
  "admin.certDaysUntilExpiry": "Days until expiry",
  "admin.certSearchMember": "Search member…",
  "admin.certAllTypes": "All cert types",
  "admin.noBoats": "No boats.",
  "admin.noLocations": "No locations.",
  "admin.backToList": "← Back to list",
  "admin.importFromCsv": "Import from Abler.io CSV",
  "cert.noCerts": "No credentials on file.",
  "cert.assignedBy": "Assigned by",
  "cert.assignedAt": "Assigned",
  "cert.expires": "Expires",
  "cert.expired": "Expired",
  "cert.permanent": "Does not expire",
  "cert.level": "Level / Subcategory",
  "cert.assign": "Assign",
  "cert.remove": "Remove",
  "cert.issuingAuthority": "Issuing Authority",
  "cert.renewalDays": "Renewal (days)",
  "cert.renewalOverride": "Renewal (days, overrides parent)",
  "cert.fixedExpiry": "Fixed Expiry Date",
  "cert.fixedExpiryOverride": "Fixed Expiry Date (overrides renewal)",
  "cert.subcats": "Subcategories",
  "cert.subcatHint": "Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce \"higher replaces lower\" logic. Per-subtype issuing authority, renewal days, or a fixed expiry date will override the parent values.",
  "cert.noSubcats": "No subcategories",
  "cert.subcatLabel": "Label (e.g. Level 1)",
  "cert.subcatDesc": "Description",
  "cert.subcatRank": "Rank",
  "cert.rankHint": "Rank (higher replaces lower on assign)",
  "cert.cardColour": "Card colour",
  "cert.colourAuto": "auto if blank",
  "cert.deleteConfirm": "Delete this credential type? This won't remove existing assignments.",
  "cert.deleteSubConfirm": "Remove this subtype?",
  "cert.saved": "Credential type saved.",
  "cert.deleted": "Credential type deleted.",
  "cert.assigned": "Credential assigned.",
  "cert.removed": "Credential removed.",
  "cert.nameRequired": "Name required.",
  "cert.typeRequired": "Select a credential type.",
  "cert.levelRequired": "Select a level / subcategory.",
  "cert.clubEndorsements": "CLUB ENDORSEMENTS",
  "cert.loadError": "Could not load credentials.",
  "payroll.tabTimeReporting": "Time Reporting",
  "payroll.tabTimesheets": "Timesheets / Payslips",
  "payroll.tabEmployees": "Employees",
  "payroll.tabLaunamidlar": "Export Data",
  "payroll.definePeriod": "Define Pay Period",
  "payroll.periodFrom": "From",
  "payroll.periodTo": "To",
  "payroll.previewPayslips": "Preview Payslips",
  "payroll.approvePeriod": "Approve & Close Period",
  "payroll.approveConfirm": "Approve payslips for all employees and close this period?",
  "payroll.periodClosed": "Period closed ✓",
  "payroll.exportPdf": "Export PDF",
  "payroll.exportXml": "Export XML",
  "payroll.noPeriodDefined": "No pay period defined yet.",
  "payroll.noClosedPeriods": "No closed periods yet.",
  "payroll.hoursFromSheets": "Hours from timesheets",
  "payroll.hoursConfirm": "Confirm hours before approving",
  "payroll.manualLines": "Manual line items",
  "payroll.addLine": "+ Add line",
  "payroll.lineDescription": "Description",
  "payroll.lineDescriptionIS": "Description (IS)",
  "payroll.lineAmount": "Amount (kr)",
  "payroll.regularHours": "Regular hours",
  "payroll.ot1Hours": "Overtime 1.33×",
  "payroll.ot2Hours": "Overtime 1.55×",
  "payroll.correctedHours": "Corrected hours",
  "payroll.hoursNote": "Note / reason for correction",
  "payroll.confirmHours": "Confirm hours",
  "payroll.periodApproved": "Approved",
  "payroll.periodOpen": "Open",
  "payroll.periodLabel": "Pay period",
  "payroll.employeeCount": "{n} employees",
  "payroll.grossLabel": "Gross",
  "payroll.netLabel": "Net",
  "payroll.paymentDate": "Payment date",
  "payroll.slipNumber": "Slip no.",
  "payroll.personuafslattr": "Personal tax credit (kr/month)",
  "payroll.personuafslattrPct": "% of standard credit used here",
  "payroll.configTitle": "Payroll Config",
  "payroll.ot1Rate": "Overtime tier 1 multiplier",
  "payroll.ot2Rate": "Overtime tier 2 multiplier",
  "payroll.orlofsRate": "Holiday pay rate",
  "payroll.empPensionRate": "Employee pension %",
  "payroll.emplPensionRate": "Employer pension %",
  "payroll.taxBracket1": "Tax bracket 1 rate (up to 583,854 kr)",
  "payroll.taxBracket2": "Tax bracket 2 rate (up to 1,645,733 kr)",
  "payroll.taxBracket3": "Tax bracket 3 rate",
  "payroll.unionDuesRate": "Union dues rate",
  "payroll.hoursTotal": "Total hours",
  "payroll.editEntry": "Edit",
  "payroll.notEnabled": "Not in payroll",
  "payroll.enablePayroll": "Enable payroll",
  "payroll.calView": "Calendar",
  "payroll.listView": "List",
  "payroll.addEntry": "+ Add entry",
  "payroll.deleteEntry": "Delete",
  "payroll.deleteConfirm": "Delete this time entry?",
  "payroll.allStaff": "All staff",
  "payroll.employee": "Employee",
  "payroll.totalHours": "total",
  "payroll.clockInLabel": "Clock in",
  "payroll.clockOutLabel": "Clock out",
  "payroll.minsLabel": "Duration (minutes)",
  "payroll.noteOptional": "Note (optional)",
  "payroll.notePlaceholder": "e.g. forgotten punch-in",
  "payroll.autoCalc": "auto-calculated, override if needed",
  "payroll.entryRequired": "Employee, clock-in and clock-out are required.",
  "payroll.clockOutAfterIn": "Clock-out must be after clock-in.",
  "payroll.moreEntries": "more",
  "payroll.pastPeriods": "Past periods",
  "payroll.titleField": "Title",
  "payroll.bankAccount": "Bank account",
  "payroll.orlofsreikningur": "Holiday account",
  "payroll.union": "Union",
  "payroll.sereignRate": "Private pension %",
  "payroll.pension": "Pension",
  "lbl.year": "Year",
  "lbl.duration": "Duration",
  "lbl.edited": "edited",
  "lbl.view": "View",
  "lbl.admin": "admin",
  "lbl.staff": "staff",
  "lbl.monShort": "Mon",
  "lbl.tueShort": "Tue",
  "lbl.wedShort": "Wed",
  "lbl.thuShort": "Thu",
  "lbl.friShort": "Fri",
  "lbl.satShort": "Sat",
  "lbl.sunShort": "Sun",
  "payroll.earningsSection": "Earnings",
  "payroll.deductionsSection": "Deductions",
  "payroll.accumulatedSection": "Accumulated",
  "payroll.employerSection": "Employer contribution",
  "payroll.ytdSection": "Year to date",
  "payroll.totalDeductions": "Total deductions",
  "payroll.orlofslaun": "Holiday pay (bank)",
  "payroll.payslip": "Payslip",
  "payroll.baseRate": "Base rate (kr/hr)",
  "payroll.dagvinna": "Regular time",
  "payroll.ot1Label": "Overtime 1.33×",
  "payroll.ot2Label": "Overtime 1.55×",
  "payroll.units": "Units",
  "payroll.rate": "Rate",
  "payroll.amount": "Amount",
  "payroll.ytdUnits": "YTD units",
  "payroll.taxComputed": "Computed tax",
  "payroll.employerPension": "Employer pension",
  "payroll.endurhaefingarsjodur": "Rehabilitation fund",
  "payroll.now": "Now",
  "payroll.config": "Config",
  "payroll.configPayroll": "Payroll settings",
  "payroll.pensionFunds": "Pension funds",
  "payroll.addFund": "Add fund",
  "payroll.fundName": "Fund name",
  "payroll.fundNameEN": "Fund name (EN)",
  "payroll.unions": "Unions",
  "payroll.addUnion": "Add union",
  "payroll.unionName": "Union name",
  "payroll.deductionLines": "Deduction lines",
  "payroll.lineLabel": "Label",
  "payroll.lineLabelEN": "Label (EN)",
  "payroll.empRate": "Employee %",
  "payroll.emprRate": "Employer %",
  "payroll.otRules": "Overtime rules",
  "payroll.otEligible": "Overtime eligible",
  "payroll.otPeriods": "OT periods",
  "payroll.otDays": "Days (0=Sun…6=Sat)",
  "payroll.otFrom": "From hour",
  "payroll.otTo": "To hour",
  "payroll.otMultiplier": "Multiplier",
  "payroll.personuafslattrUnit": "Personal credit unit (kr = 1.0)",
  "payroll.personuafslattrFrac": "Personal credit (fraction)",
  "payroll.pensionFundIds": "Pension fund(s)",
  "payroll.unionId": "Union",
  "payroll.none": "None",
  "payroll.personuafslattrFraction": "Personal credit fraction",
  "payroll.section": "TIME CLOCK",
  "payroll.otTierLabel": "Label",
  "payroll.otTierLabelEN": "Label (EN)",
  "payroll.addOTTier": "+ Add OT tier",
  "payroll.deleteOTTier": "Remove",
  "payroll.taxBrackets": "Tax brackets",
  "payroll.taxBracketUpTo": "Up to (kr)",
  "payroll.taxBracketRate": "Rate (%)",
  "payroll.taxBracketUnlimited": "∞ (top bracket)",
  "payroll.addTaxBracket": "+ Add bracket",
  "payroll.tabExportData": "Export Data",
  "payroll.exportWithholding": "XML — Withholding",
  "payroll.exportPayslipXml": "XML — Payslip data",
  "payroll.exportPensionCsv": "CSV — Pension data",
  "payroll.exportLaunamidlar": "XML — Launamiðlar",
  "payroll.exportPlaceholder": "Not yet implemented — coming soon",
  "payroll.selectPeriod": "— Select period —",
  "payroll.exportCsv": "Export CSV",
  "payroll.stadEmployerInfo": "Employer info — Withholding",
  "payroll.stadKt": "Employer kennitala",
  "payroll.stadEmail": "Contact email",
  "payroll.stadVeflykill": "Web key",
  "payroll.stadForrit": "Software ID",
  "payroll.stadIsat": "Industry code (ISAT 2008)",
  "payroll.stadKtRequired": "Employer kennitala is required",
  "payroll.starfshlutfall": "Employment %",
  "payroll.istarf95": "Job code",
  "payroll.taxWithheld": "Tax withheld",
  "payroll.clockIn": "Clock In",
  "payroll.clockOut": "Clock Out",
  "payroll.startBreak": "Start Break",
  "payroll.endBreak": "End Break",
  "payroll.currentShift": "On shift",
  "payroll.onBreak": "On break since",
  "payroll.clockedInAt": "Clocked in at",
  "payroll.recentShifts": "Recent shifts",
  "payroll.noShifts": "No shifts logged yet",
  "payroll.shiftSummary": "Shift summary",
  "payroll.totalWorked": "Total worked",
  "payroll.totalBreak": "Total break",
  "payroll.confirmShift": "Done",
  "payroll.allowBreaks": "Allow break logging",
  "logbook.distanceNm": "Distance (nm)",
  "logbook.departurePort": "Departure port",
  "logbook.arrivalPort": "Arrival port",
  "logbook.portsOptional": "Ports — optional",
  "logbook.addPort": "+ Add \"{name}\" to ports list",
  "logbook.nonClubToggle": "Non-club trip",
  "logbook.nonClubHint": "— log a trip outside the club system",
  "logbook.boatNameLabel": "Boat name",
  "logbook.boatNamePh": "e.g. Sunfish, RIB, etc.",
  "logbook.boatCategory": "Category",
  "logbook.locationNamePh": "e.g. Lake Thingvallavatn",
  "logbook.useMyLocation": "Use my location",
  "logbook.locating": "Locating…",
  "logbook.locationDenied": "Location access denied",
  "logbook.enterBoatName": "Please enter a boat name.",
  "logbook.enterLocation": "Please enter a location.",
  "logbook.gpsTrack": "GPS Track — GPX / KML / KMZ",
  "logbook.photos": "Photos",
  "logbook.trackReady": "Ready: {name}",
  "logbook.trackAttached": "📍 GPS track",
  "logbook.portSame": "⚓️ {port}",
  "logbook.portRoute": "⚓️ {from} → {to}",
  "logbook.noDriveConfig": "File upload not configured — trip saved without attachment.",
  "boat.registrationNo": "Registration no.",
  "boat.sailNo": "Sail no.",
  "boat.loa": "LOA (ft)",
  "boat.typeModel": "Type / model",
  "boat.defaultPort": "Default port",
  "location.type": "Type",
  "location.typePort": "Port",
  "location.typeLocation": "Sailing area",
  "location.lat": "Latitude",
  "location.lng": "Longitude",
  "fleet.badgeAvail": "AVAIL",
  "fleet.badgeOut": "OUT",
  "fleet.badgeOverdue": "OVERDUE",
  "fleet.badgeOos": "OOS",
  "fleet.badgeYours": "YOURS",
  "fleet.aboard": "{n} aboard",
  "fleet.outTime": "Out {t}",
  "fleet.checkIn": "Check In",
  "fleet.delete": "Delete",
  "fleet.badgeChartered": "CHARTERED",
  "fleet.badgePrivate": "PRIVATE",
  "fleet.ownedBy": "Owner: {name}",
  "fleet.actionCheckout": "Check Out",
  "fleet.actionMaint": "Request Maintenance",
  "fleet.actionMarkOos": "Mark Unavailable",
  "fleet.actionMarkAvail": "Mark Available",
  "boat.ownership": "Ownership",
  "boat.ownershipClub": "Club boat",
  "boat.ownershipPrivate": "Private boat",
  "boat.owner": "Owner",
  "boat.accessMode": "Access Mode",
  "boat.accessFree": "Free Access",
  "boat.accessControlled": "Controlled Access",
  "boat.gateCert": "Required Certification",
  "boat.gateCertNone": "None (allowlist only)",
  "boat.allowlist": "Allowed Members",
  "boat.allowlistAdd": "Add member…",
  "boat.reservations": "Assign Charter",
  "boat.addReservation": "Add Charter",
  "boat.removeReservation": "Remove",
  "boat.reservationSaved": "Charter saved",
  "boat.reservationRemoved": "Charter removed",
  "boat.reservedFor": "Chartered to {name}",
  "boat.reservedUntil": "until {date}",
  "boat.reservationNote": "Note",
  "boat.accessDenied": "You do not have access to this boat",
  "boat.accessSaved": "Access settings saved",
  "fleet.badgeControlled": "CONTROLLED",
  "fleet.badgeRestricted": "RESTRICTED",
  "fleet.badgeAuthorized": "AUTHORIZED",
  "fleet.badgeReserved": "RESERVED",
  "boat.slotScheduling": "Enable session slot scheduling",
  "boat.availOutside": "Available outside scheduled slots",
  "boat.availOutsideHint": "If unchecked, boat can only be used during booked session slots.",
  "day.mon": "Mon",
  "day.tue": "Tue",
  "day.wed": "Wed",
  "day.thu": "Thu",
  "day.fri": "Fri",
  "day.sat": "Sat",
  "day.sun": "Sun",
  "month.jan": "Jan",
  "month.feb": "Feb",
  "month.mar": "Mar",
  "month.apr": "Apr",
  "month.may": "May",
  "month.jun": "Jun",
  "month.jul": "Jul",
  "month.aug": "Aug",
  "month.sep": "Sep",
  "month.oct": "Oct",
  "month.nov": "Nov",
  "month.dec": "Dec",
  "slot.filterBoat": "Boat",
  "slot.filterCrew": "Crew",
  "slot.allBoats": "All boats",
  "slot.today": "Today",
  "slot.addRecurring": "+ Recurring",
  "slot.noSlotBoats": "No boats with slot scheduling enabled",
  "slot.boat": "Boat",
  "slot.recurTitle": "Create Recurring Slots",
  "slot.editTitle": "Session Slot",
  "slot.newTitle": "New Slot",
  "slot.daysOfWeek": "Days of week",
  "slot.startTime": "Start time",
  "slot.endTime": "End time",
  "slot.fromDate": "From date",
  "slot.toDate": "To date",
  "slot.note": "Note",
  "slot.preview": "Preview",
  "slot.create": "Create",
  "slot.selectDays": "Select at least one day and date range",
  "slot.previewCount": "{count} slots will be created",
  "slot.created": "{count} slots created",
  "slot.missingFields": "Date and times are required",
  "slot.confirmDelete": "Delete this slot?",
  "slot.bookedBy": "Booked by",
  "slot.legendOpen": "Open",
  "slot.legendYours": "Yours",
  "slot.legendBooked": "Booked",
  "slot.booked": "Slot booked!",
  "slot.unbooked": "Booking cancelled",
  "slot.confirmUnbook": "Cancel this booking?",
  "slot.yours": "YOURS",
  "slot.clickToBook": "Click an open slot to book it.",
  "slot.date": "Date",
  "slot.bulkBook": "Bulk Book",
  "slot.bulkTitle": "Bulk Book Slots",
  "slot.bulkPreview": "{open} open slots of {total} will be booked",
  "slot.bulkNoSlots": "No open slots match your criteria",
  "slot.bulkBooked": "{count} slots booked!",
  "slot.bulkPartial": "{booked} booked, {skipped} already taken",
  "slot.createAndBook": "+ New Booking",
  "slot.createAndBookTitle": "Create & Book Slot",
  "slot.createdAndBooked": "Slot created and booked!",
  "cq.reservationsTitle": "CHARTERS",
  "nav.coxswainSeat": "🚣 Rowing Division",
  "cox.title": "Rowing Division",
  "cox.noBoats": "No controlled boats available",
  "cox.statsTrips": "TRIPS",
  "cox.statsHours": "HOURS",
  "cox.statsDist": "DISTANCE",
  "cox.boatAvailability": "BOAT AVAILABILITY",
  "cox.trips": "TRIPS",
  "cox.maintenance": "MAINTENANCE",
  "cox.readOnly": "View only — released rower endorsement required for changes",
  "cox.noCrewsShort": "No crews — create one first",
  "cox.createCrewFirst": "Create a crew first to book slots",
  "cox.noMaint": "No maintenance requests.",
  "cox.reservations": "CHARTERS",
  "cox.addReservation": "Add Charter",
  "cox.resMember": "Member",
  "cox.resStartDate": "Start date",
  "cox.resEndDate": "End date",
  "cox.resNote": "Note (optional)",
  "cox.makeAvailable": "Mark available",
  "cox.makeUnavailable": "Mark unavailable",
  "cox.myCrews": "MY CREWS",
  "cox.noCrews": "No crews yet. Create one to get started.",
  "cox.createCrew": "+ Create Crew",
  "cox.createCrewTitle": "Create Crew",
  "cox.crewName": "Crew name",
  "cox.crewNameRequired": "Crew name required",
  "cox.numPairs": "Number of pairs",
  "cox.yourPair": "Your pair assignment",
  "cox.pair": "Pair",
  "cox.empty": "empty",
  "cox.openSpots": "open",
  "cox.active": "ACTIVE",
  "cox.forming": "FORMING",
  "cox.inviteMember": "Invite Member",
  "cox.searchMember": "Member",
  "cox.pairAssignment": "Pair",
  "cox.sendInvite": "Send Invite",
  "cox.selectMember": "Select a member",
  "cox.selectPair": "Select a pair",
  "cox.inviteSent": "Invite sent!",
  "cox.pendingInvites": "PENDING INVITES",
  "cox.invitedBy": "Invited by",
  "cox.accept": "Accept",
  "cox.reject": "Reject",
  "cox.inviteAccepted": "Invite accepted!",
  "cox.inviteRejected": "Invite declined.",
  "cox.disband": "Disband",
  "cox.confirmDisband": "Disband this crew? This cannot be undone.",
  "cox.crewDisbanded": "Crew disbanded.",
  "cox.selectCrew": "Select a crew first",
  "cox.crewBoard": "CREW BOARD",
  "cox.crewBoardEmpty": "No crews yet. Create one or wait for others to post.",
  "cox.boat": "Boat",
  "cox.bow": "Bow",
  "cox.stern": "Stern",
  "cox.join": "Join",
  "cox.leave": "Leave",
  "cox.joined": "Joined crew!",
  "cox.left": "Left crew.",
  "cox.confirmLeave": "Leave this crew?",
  "cox.seatTaken": "This seat is taken",
  "cox.description": "Description",
  "cox.descPlaceholder": "e.g., Mon & Wed 7am, casual pace",
  "cox.visibility": "Visibility",
  "cox.visOpen": "Open — anyone can join",
  "cox.visInvite": "Invite only",
  "cox.yourSeat": "Your seat",
  "cox.seatBow": "Bow",
  "cox.seatStern": "Stern",
  "cox.numBoats": "Number of boats",
  "cox.needsMore": "needs {n} more",
  "cox.crewColor": "Color",
  "cq.bookingColor": "My booking color",
  "cox.tentative": "TENTATIVE",
  "cox.slotReservations": "SLOT RESERVATIONS",
  "pub.dash.title": "Club Dashboard",
  "pub.dash.subtitle": "Siglingafélagið Ýmir",
  "pub.dash.season": "{year} Season",
  "pub.dash.ytdTrips": "Trips This Season",
  "pub.dash.totalHours": "Hours Sailed",
  "pub.dash.byCategory": "By Boat Type",
  "pub.dash.locations": "Where We Sail",
  "pub.dash.onWater": "On the Water Now",
  "pub.dash.boats": "Boats Out",
  "pub.dash.people": "People",
  "pub.dash.captains": "Our Captains",
  "pub.dash.viewRecord": "View Sailing Record →",
  "pub.dash.noCaptains": "No captains registered yet.",
  "pub.dash.noActivity": "No boats on the water right now.",
  "pub.dash.trips": "trips",
  "pub.dash.hrs": "hrs",
  "pub.dash.bio": "Captain at Siglingafélagið Ýmir. Bio coming soon.",
  "pub.dash.loading": "Loading dashboard…",
  "pub.dash.error": "Could not load dashboard data.",
  "pub.dash.lastUpdated": "Last updated",
  "pub.dash.tripCount": "{n} trips",
  "pub.dash.hourCount": "{n} hrs",
  "pub.dash.conditions": "Conditions & Status",
  "pub.dash.weather": "Weather & Tides",
  "pub.dash.boatsOut": "Boats Out",
  "pub.dash.captainData": "Captain Data",
  "pub.dash.captainSoon": "Captain profiles and statistics will appear here soon.",
  "pub.dash.trips": "trips",
  "pub.dash.viewProfile": "View full profile",
  "pub.dash.comingSoon": "More information coming soon.",
  "admin.expectedColumns": "EXPECTED COLUMNS",
  "admin.colName": "Full name (required)",
  "admin.colKt": "10-digit ID (required)",
  "admin.colEmail": "Email address",
  "admin.colPhone": "Phone number",
  "admin.colDob": "Date of birth (YYYY-MM-DD)",
  "admin.colMemberType": "e.g. full, junior, family",
  "admin.csvDrop": "Drop CSV here or click to browse",
  "admin.csvEncoding": "UTF-8 encoded, comma or semicolon delimited",
  "admin.reviewImport": "Review import",
  "admin.rolesNeverOverwritten": "Admin/staff roles never overwritten.",
  "admin.confirmImport": "Confirm import",
  "admin.importAnother": "Import another",
  "admin.viewMembers": "View members",
  "admin.addCategory": "+ Add category",
  "admin.preLaunchLanding": "PRE-LAUNCH & LANDING CHECKLISTS (per category)",
  "admin.launch": "LAUNCH",
  "admin.landing": "LANDING",
  "admin.actTypesTitle": "ACTIVITY TYPES",
  "admin.credentialsTitle": "CREDENTIALS",
  "admin.manageCreds": "Credentials",
  "admin.overdueAlerts": "OVERDUE ALERTS",
  "admin.notifChannels": "NOTIFICATION CHANNELS",
  "admin.chanWeb": "Web (in-app banner)",
  "admin.chanEmail": "Email",
  "admin.chanSms": "SMS",
  "admin.requiresBackend": "requires backend setup",
  "admin.emailRecipients": "Email recipients (comma-separated)",
  "admin.smsRecipients": "SMS recipients (comma-separated)",
  "admin.saveAlertSettings": "Save alert settings",
  "admin.scoreThresholds": "SCORE THRESHOLDS",
  "admin.scoreThresholdsSub": "total points → flag level",
  "admin.yellowGte": "Yellow ≥",
  "admin.orangeGte": "Orange ≥",
  "admin.redGte": "Red ≥",
  "admin.closedGte": "Closed ≥",
  "admin.windScoring": "WIND SCORING (Force → points)",
  "admin.windScoringHint": "Each band applies when Force ≤ maxForce. List in ascending order.",
  "admin.dirGustMods": "DIRECTION & GUST MODIFIERS",
  "admin.easterlyMod": "Easterly modifier (pts)",
  "admin.easterlyModHint": "Added when wind is from an easterly sector",
  "admin.gustMod1": "Gust modifier +1 Force (pts)",
  "admin.gustMod1Hint": "Added when gusts are exactly 1 Force level above sustained",
  "admin.gustMod2": "Gust modifier +2 Force (pts)",
  "admin.gustMod2Hint": "Added when gusts are 2+ Force levels above sustained",
  "admin.easterlyDirs": "Easterly directions (comma-separated)",
  "admin.waveScoring": "WAVE HEIGHT SCORING (metres → points)",
  "admin.sstScoring": "SEA TEMPERATURE SCORING (°C → points)",
  "admin.sstHint": "First band where SST ≥ minC applies. List highest minC first.",
  "admin.airTempScoring": "AIR TEMPERATURE SCORING (°C → points)",
  "admin.visScoring": "VISIBILITY SCORING",
  "admin.visGood": "Good (pts)",
  "admin.visReduced": "Reduced (pts)",
  "admin.visPoor": "Poor <500m (pts)",
  "admin.flagLabelsAdvice": "FLAG LABELS & ADVICE TEXT",
  "admin.livePreview": "LIVE PREVIEW",
  "admin.saveFlagSettings": "Save flag settings",
  "admin.resetDefaults": "Reset to defaults",
  "admin.addBand": "+ Add band",
  "admin.memberModal.title": "Add Member",
  "admin.kennitala": "Kennitala",
  "admin.initials": "Initials",
  "admin.initialsPlaceholder": "Auto-generated",
  "admin.dob": "Date of birth",
  "admin.membershipType": "Membership type",
  "admin.memFull": "Full",
  "admin.memJunior": "Junior",
  "admin.memFamily": "Family",
  "admin.memStudent": "Student",
  "admin.memHonorary": "Honorary",
  "admin.memOther": "Other",
  "admin.deactivate": "Deactivate",
  "admin.boatCatModal.add": "Add Boat Category",
  "admin.nameEN": "Name (English)",
  "admin.nameIS": "Name (Íslenska)",
  "admin.emoji": "Emoji",
  "admin.keyAutoSet": "Key (auto-set)",
  "admin.keyHint": "The key is used internally to link boats and checklists. It cannot be changed after boats are assigned.",
  "admin.locModal.name": "Name",
  "admin.clModal.add": "Add Checklist Item",
  "admin.clPhaseOpening": "Opening",
  "admin.clPhaseClosing": "Closing",
  "admin.clLaunchPhase": "Launch",
  "admin.clLandingPhase": "Landing",
  "admin.actTypeModal.add": "Add Activity Type",
  "admin.subtypes": "SUBTYPES",
  "admin.certDefModal.add": "Add Credential Type",
  "admin.certDescLabel": "Description",
  "admin.certIssuing": "Issuing Authority",
  "admin.certClubEndorsement": "Club endorsement",
  "admin.certCardColour": "Card colour",
  "admin.certAutoBlank": "auto if blank",
  "admin.certExpires": "This credential expires",
  "admin.certExpiryDate": "EXPIRY DATE",
  "admin.certHasId": "This credential has an ID / licence number",
  "admin.certSubcategories": "SUBCATEGORIES",
  "admin.certSubcatHint": "Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce \"higher replaces lower\" logic. Per-subtype issuing authority or expiry date will override the parent values.",
  "admin.certCurrent": "CURRENT",
  "admin.certNoneAssigned": "No credentials assigned.",
  "admin.certAssignTitle": "ASSIGN CERTIFICATION",
  "admin.certLicenceNo": "Licence / ID Number",
  "admin.certExpiryHint": "leave blank if permanent",
  "admin.certExpiryLabel": "Expiry date",
  "admin.certAssignedDate": "Assigned date",
  "admin.certCategory": "Category",
  "admin.certCategorySelect": "Select category…",
  "admin.certAddCategory": "+ Add category…",
  "admin.certTitle": "Credential title",
  "admin.certIdNumber": "ID number",
  "admin.certIssuingAuth": "Issuing authority",
  "admin.certIssueDate": "Issue date",
  "admin.certExpires2": "Does this credential expire?",
  "admin.certExpiryDate2": "Expiration date",
  "admin.certDescription": "Additional description",
  "admin.certCustomType": "— Enter custom credential —",
  "admin.certTitleRequired": "Title is required.",
  "admin.certAuthorityReq": "Issuing authority is required.",
  "admin.certExpiryReq": "Expiration date required when credential expires.",
  "admin.certCategoryReq": "Category is required.",
  "admin.certDefCategory": "Default category",
  "admin.certCategoriesTitle": "CREDENTIAL CATEGORIES",
  "admin.certManageCategories": "Manage categories",
  "cq.assignCred": "Assign Credential",
  "cq.assignCredTitle": "ASSIGN CREDENTIAL TO CREW",
  "cq.searchMember": "Search crew member…",
  "cq.selectMember": "Select member",
  "admin.qrScanHint": "Scan → available: launch flow · your boat out: return flow · someone else's: shows status.",
  "admin.printPdf": "Print / PDF",
  "admin.ownerClub": "Club boat",
  "admin.ownerPrivate": "Private boat",
  "admin.searchMember": "Search member...",
  "admin.oosReason": "OOS reason",
  "admin.openingChecklist": "OPENING CHECKLIST",
  "admin.closingChecklist": "CLOSING CHECKLIST",
  "admin.homePort": "Home port",
  "admin.loadFailed": "Load failed",
  "admin.nameKtRequired": "Name and kennitala required.",
  "admin.nameKeyRequired": "Name and key required.",
  "admin.nameRequired": "Name required.",
  "admin.textENRequired": "English text required.",
  "admin.saveBoatFirst": "Save the boat first.",
  "admin.selectMember": "Select a member.",
  "admin.setDatesRequired": "Set start and end dates.",
  "admin.memberDatesRequired": "Member and dates required.",
  "admin.categoryExists": "Category already exists.",
  "admin.categoryAdded": "Category added.",
  "admin.categoryRemoved": "Category removed.",
  "admin.certDefSaved": "Credential type saved.",
  "admin.parseError": "Parse error",
  "admin.importing": "Importing…",
  "admin.importFailed": "Import failed",
  "admin.importComplete": "Import complete: {added} added, {updated} updated.",
  "admin.importDeactivated": "{count} deactivated.",
  "admin.confirmDeactivateMember": "Deactivate this member?",
  "admin.confirmRemoveBoatCat": "Remove this category? Boats assigned to it will still exist but may show under 'other'.",
  "admin.confirmDeleteBoat": "Delete this boat?",
  "admin.confirmDeleteLocation": "Delete this location?",
  "admin.confirmDeleteItem": "Delete this item?",
  "admin.confirmDeleteActType": "Delete this activity type?",
  "admin.confirmRemoveCategory": "Remove this category?",
  "admin.confirmDeleteCertDef": "Delete this credential type? This won't remove existing assignments.",
  "admin.confirmResetFlags": "Reset all flag settings to defaults?",
  "admin.noCategories": "No categories.",
  "admin.noItems": "No items.",
  "admin.noActTypes": "No activity types.",
  "admin.noCertCategories": "No categories defined. Defaults will be used.",
  "admin.noCertDefs": "No credential types defined.",
  "admin.noSubcategories": "No subcategories",
  "admin.noSubtypes": "No subtypes yet.",
  "admin.boatCatModal.edit": "Edit Category",
  "admin.clModal.edit": "Edit Item",
  "admin.lcModal.add": "Add Item",
  "admin.lcModal.edit": "Edit Item",
  "admin.actTypeModal.edit": "Edit Type",
  "admin.optionNone": "— none —",
  "admin.certCategoryNone": "None",
  "staff.crewMembers": "Crew members",
  "staff.crewOptional": "optional — search by name",
  "staff.crewAutoLog": "Named crew get this trip logged in their logbook automatically.",
  "staff.departurePort": "Departure Port",
  "staff.recentIn": "In",
  "staff.recentMember": "Member",
  "staff.recentBoat": "Boat",
  "staff.recentArea": "Sailing area",
  "staff.recentDuration": "Duration",
  "member.departurePort": "Departure Port",
  "member.homePort": "Home port",
  "member.crewMembers": "Crew members",
  "member.crewOptional": "optional — search by name",
  "member.crewAutoLog": "Named crew get this trip logged in their logbook automatically.",
  "member.back": "Back",
  "member.continue": "Continue →",
  "member.preLaunch": "PRE-LAUNCH",
  "member.noChecklist": "No pre-launch checklist configured for this category.",
  "member.confirmAllItems": "Please confirm all items.",
  "daily.ablerRegistered": "Activity details registered in Abler",
  "daily.linkedGroupCo": "Linked group checkouts",
  "daily.linkGroupCo": "+ Link group checkout",
  "daily.linkGroupCoTitle": "Link Group Checkout",
  "daily.noActiveGroups": "No active group checkouts today.",
  "daily.linkSelected": "Link selected",
  "daily.groupCheckout": "Group checkout",
  "daily.group": "group",
  "daily.groups": "groups",
  "nav.captainQuarters": "🚢 Captain's Quarters",
  "cq.title": "Captain's Quarters",
  "cq.subtitle": "Keelboat captain dashboard",
  "cq.ytdHours": "YTD HOURS",
  "cq.ytdDistance": "YTD DISTANCE",
  "cq.ytdTrips": "YTD TRIPS",
  "cq.nm": "nm",
  "cq.hrs": "hrs",
  "cq.maintTitle": "KEELBOAT MAINTENANCE",
  "cq.maintOpen": "Open",
  "cq.maintClosed": "Closed",
  "cq.maintAll": "All",
  "cq.noMaint": "No maintenance requests.",
  "cq.validationTitle": "VALIDATION REQUESTS",
  "cq.noValidation": "No pending validation requests.",
  "cq.crewTitle": "CREW APPROVALS",
  "cq.noCrew": "No pending crew approvals.",
  "cq.tripsTitle": "KEELBOAT TRIPS",
  "cq.myTrips": "My Trips",
  "cq.allTrips": "All Keelboat Trips",
  "cq.noTrips": "No trips found.",
  "cq.bioTitle": "BIO & PROFILE",
  "cq.bioPlaceholder": "Write a short bio that appears on your public captain profile…",
  "cq.headshotLabel": "Profile photo (max 5 MB)",
  "cq.bioSaved": "Bio saved",
  "cq.headshotUploaded": "Photo uploaded",
  "cq.boatsTitle": "MY BOATS",
  "cq.noBoats": "No private boats registered.",
  "cq.makeUnavailable": "Mark unavailable",
  "cq.makeAvailable": "Mark available",
  "cq.changePort": "Change home port",
  "cq.viewPublicProfile": "View public profile →",
  "cq.reservations": "CHARTERS",
  "cq.noReservations": "No charters.",
  "cq.addReservation": "Add Charter",
  "cq.resStartDate": "Start date",
  "cq.resEndDate": "End date",
  "cq.resNote": "Note (optional)",
  "cq.resMember": "Member",
  "tc.skipper": "Skipper",
  "tc.crew": "Crew",
  "tc.helm": "Helm",
  "tc.student": "Student",
  "tc.guest": "Guest",
  "tc.me": "Me",
  "tc.nonClub": "Non-club",
  "tc.pending": "pending",
  "tc.verificationPending": "Verification pending",
  "tc.requestVerification": "Request verification",
  "tc.windSpeed": "Wind speed",
  "tc.direction": "Direction",
  "tc.gusts": "Gusts",
  "tc.conditions": "Conditions",
  "tc.airTemp": "Air temp",
  "tc.feelsLike": "Feels like",
  "tc.seaTemp": "Sea temp",
  "tc.waveHeight": "Wave height",
  "tc.pressure": "Pressure",
  "tc.weatherFlag": "Weather flag",
  "tc.departurePort": "Departure port",
  "tc.arrivalPort": "Arrival port",
  "tc.skipperLabel": "Skipper",
  "tc.crewAboard": "Crew aboard",
  "tc.atTheHelm": "At the helm",
  "tc.regNo": "Registration no.",
  "tc.sailNo": "Sail no.",
  "tc.typeModel": "Type / model",
  "tc.loa": "LOA",
  "tc.distance": "Distance",
  "tc.gpsTrack": "GPS Track",
  "tc.deleteTrack": "Delete track",
  "tc.clickToExpand": "Click to expand",
  "tc.downloadFile": "Download file",
  "tc.viewTrack": "View track",
  "tc.skipperNote": "Skipper's comments",
  "tc.visibleToCrew": "visible to crew",
  "tc.fromSkipper": "from skipper",
  "tc.noNoteYet": "No note yet",
  "tc.edit": "Edit",
  "tc.privateNote": "Personal comments",
  "tc.onlyYou": "only you",
  "tc.noPrivateNoteYet": "No note yet",
  "tc.photos": "Photos",
  "tc.delete": "Delete",
  "tc.shared": "Shared",
  "tc.private": "Private",
  "tc.club": "Club",
  "tc.editTrip": "✏️ Edit trip",
  "tc.addGps": "📍 Add GPS",
  "tc.addPhotos": "📷 Add photos",
  "tc.boatDetails": "Boat Details",
  "tc.tripDetails": "Trip Details",
  "tc.departed": "Departed",
  "tc.returned": "Returned",
  "tc.sailingArea": "Sailing area",
  "tc.duration": "Duration",
  "tc.weather": "Weather",
  "tc.notesPhotosTrack": "Notes, Photos & Track",
  "maint.sevHint.low": "Minor issue — no immediate action required.",
  "maint.sevHint.medium": "Functional issue, usable with care.",
  "maint.sevHint.high": "Significant problem — assess before use.",
  "maint.sevHint.critical": "Safety risk — take out of service immediately.",
  "maint.oosTag": "OOS",
  "maint.inService": "In service",
  "maint.confirmBtn": "Confirm",
  "maint.cancelBtn": "Cancel",
  "maint.defaultAuthor": "Staff",
  "maint.deleteComment": "Delete comment",
  "maint.addCommentPh": "Add comment…",
  "maint.postBtn": "Post",
  "maint.postingBtn": "Posting…",
  "maint.approvingBtn": "Approving…",
  "maint.approveBtn": "Approve",
  "maint.saumaBadge": "Saumaklúbbur",
  "maint.onHoldBadge": "On Hold",
  "maint.noVerkstjori": "No verkstjóri assigned",
  "maint.adoptProject": "Adopt Project",
  "maint.reportedByLabel": "Reported by",
  "maint.pendingReview": "Pending staff review",
  "maint.pendingReviewAlert": "{count} saumaklúbbur project(s) awaiting staff review — tap to review",
  "maint.markCompleted": "Mark Completed",
  "maint.markResolved2": "Mark Resolved",
  "maint.resumeBtn": "Resume",
  "maint.putOnHold": "Put On Hold",
  "maint.deleteBtn": "Delete",
  "maint.completedStatus": "Completed",
  "maint.resolvedStatus": "Resolved",
  "maint.severityLabel": "Severity",
  "maint.priorityLabel": "Priority",
  "maint.changeSevConfirm": "Change severity to \"{sev}\" without resolving?",
  "maint.adoptConfirm": "Become verkstjóri for this project?",
  "maint.deleteCommentConfirm": "Delete this comment?",
  "maint.holdConfirm": "Put this project on hold?",
  "maint.resumeConfirm": "Resume this project?",
  "maint.completeConfirm": "Mark this project as completed?",
  "maint.resolveConfirm2": "Mark this issue as resolved?",
  "maint.deleteConfirm": "Delete this issue? This cannot be undone.",
  "maint.returnToService": "Return to service without resolving?",
  "maint.markOosConfirm": "Mark as Out of Service without resolving?",
  "maint.maxFileSize": "Max 5 MB",
  "maint.materials": "MATERIALS",
  "maint.addMaterialPh": "e.g. Sandpaper 120-grit…",
  "maint.addMaterialBtn": "+ Add",
  "maint.removeMaterial": "Remove material",
  "maint.removeMaterialConfirm": "Remove this material?",
  "alert.overdueTitle": "OVERDUE BOATS",
  "alert.minOverdue": "{n} min overdue",
  "alert.hrsOverdue": "{h}h {m}min overdue",
  "alert.guardian": "Guardian:",
  "alert.snoozedPill": "Snoozed — reappears in {n} min",
  "alert.snoozeBtn": "Snooze {n}m",
  "alert.silenceBtn": "Silence",
  "wx.staffOnDuty": "Staff on duty",
  "wx.supportBoatOut": "Support boat out",
  "wx.poorVisibility": "Poor visibility",
  "wx.reducedVisibility": "Reduced visibility",
  "tc.flagGreen": "Green",
  "tc.flagYellow": "Yellow",
  "tc.flagOrange": "Orange",
  "tc.flagRed": "Red",
  "tc.flagBlack": "Black",
  "logbook.deleteTrack": "Delete this GPS track?",
  "logbook.deletePhoto": "Delete this photo?",
  "logbook.revokeLink": "Revoke this link?",
  "logbook.noFilter": "No trips match this filter.",
  "logbook.loadingTrips": "Loading recent trips…",
  "logbook.noClubTrips": "No recent club trips found.",
  "logbook.ports": "PORTS",
  "logbook.portsOptional2": "PORTS — OPTIONAL",
  "logbook.helmLabel": "Helm",
  "logbook.studentLabel": "Student",
  "logbook.errKtOrPhone": "Please enter a kennitala/birth year or phone number.",
  "logbook.errSaveFailed": "Save failed: {msg}",
  "logbook.errFailed": "Failed: {msg}",
  "logbook.readingFile": "Reading file…",
  "logbook.fileReady": "Ready: {name}",
  "logbook.readError": "Read error",
  "logbook.noTripSelected": "No trip selected",
  "logbook.sendingRequest": "Sending request…",
  "logbook.requestSent": "Request sent to skipper ✓",
  "logbook.addToLogbook": "Add to my logbook",
  "logbook.alreadyInLog": "This trip is already in your logbook.",
  "logbook.requestToJoin": "Request to join",
  "logbook.errDepartureTime": "Invalid departure time (HH:MM).",
  "logbook.errReturnTime": "Invalid return time (HH:MM).",
  "logbook.errDate": "Please enter a date.",
  "logbook.errBoat": "Please select a boat.",
  "logbook.errSkipper": "Please select a skipper.",
  "logbook.errDuplicate": "You already have a trip logged with this boat on this date. Please check your logbook.",
  "logbook.uploading": "Uploading…",
  "logbook.uploadNoConfig": "File upload not configured — trip saved without attachment.",
  "logbook.gpsUploadFailed": "GPS upload failed: {msg}",
  "logbook.photoNoConfig": "File upload not configured",
  "logbook.photoUploadFailed": "Photo upload failed: {msg}",
  "logbook.saveToLogbook": "Save to logbook",
  "logbook.showLess": "Show less",
  "logbook.showMore": "Show more",
  "logbook.departure": "Departure",
  "logbook.arrival": "Arrival",
  "logbook.trackDeleted": "Track deleted",
  "logbook.photoDeleted": "Photo deleted",
  "logbook.upTo": "Up to",
  "logbook.views": "views",
  "logbook.copy": "Copy",
  "logbook.revoke": "Revoke",
  "logbook.linkRevoked": "Link revoked.",
  "logbook.loadFailed": "Could not load logbook: {msg}",
  "logbook.loadFailed2": "Could not load: {msg}",
  "logbook.studentBadge": "Student badge",
  "logbook.tripVerification": "Trip verification",
  "logbook.dismissAllResolved": "Dismiss all resolved",
  "logbook.from": "from",
  "logbook.dismiss": "Dismiss",
  "logbook.confirmed": "Confirmed ✓",
  "logbook.rejected": "Rejected",
  "logbook.skipperNoteLabel": "Skipper's comments (visible to crew):",
  "logbook.privateNoteLabel": "Personal comments (only you):",
  "logbook.noteSaved": "Note saved",
  "logbook.dismissed": "Dismissed",
  "logbook.allDismissed": "All dismissed",
  "logbook.onlySkipper": "Only the skipper can edit this trip",
  "logbook.selectBoat": "Select boat…",
  "logbook.selectLocation": "Select location…",
  "logbook.editTripTitle": "Edit trip",
  "logbook.saveChanges": "Save changes",
  "logbook.saving": "Saving…",
  "logbook.tripUpdated2": "Trip updated",
  "logbook.uploadingTrack": "Uploading GPS track…",
  "logbook.uploadFailed": "Upload failed",
  "logbook.trackAdded2": "GPS track added",
  "logbook.addPhotosTitle": "Add photos",
  "logbook.photoHint": "Shared photos are visible to other trip members. Club-use photos may be used for promotional purposes.",
  "logbook.uploadPhotos": "Upload photos",
  "logbook.noPhotosSelected": "No photos selected",
  "logbook.photosAdded2": "Photos added",
  "logbook.uploadFailed2": "Upload failed: {msg}",
  "logbook.windLabel": "Wind ({unit})",
  "logbook.gustsLabel": "Gusts ({unit})",
  "logbook.crewSearchPh": "Crew member {n} — search by name…",
  "logbook.addAsGuest": "+ Add \"{name}\" as guest",
  "logbook.portAdded": "Port added ✓",
  "logbook.verificationReq": "Verification requested",
  "logbook.errGeneric": "Error: {msg}",
  "member.gpsTrackLabel": "GPS TRACK — GPX/KML",
  "member.photosLabel": "PHOTOS",
  "member.distanceLabel": "DISTANCE (NM)",
  "member.arrivalPortLabel": "ARRIVAL PORT",
  "member.sameAsDeparture": "Same as departure",
  "member.reportDamage": "Report damage",
  "member.reportIncident": "Report incident",
  "member.helmLabel": "HELM",
  "member.youLabel": "(you)",
  "member.loadingCrew": "Loading crew…",
  "member.skipperNotes": "SKIPPER'S COMMENTS",
  "member.notesVisibleAll": "Visible to everyone on this trip.",
  "member.notesPlaceholder": "Trip note (visible to crew)",
  "member.personalNotes": "PERSONAL COMMENTS",
  "member.onlyVisibleYou": "Only visible to you",
  "member.guestLabel": "Guest",
  "member.noNamedCrew": "No named crew",
  "member.readingFile": "Reading…",
  "member.fileReady": "Ready: {name}",
  "member.readError": "Read error",
  "member.gpsNoConfig": "GPS upload not configured",
  "member.gpsUploadFailed": "GPS upload failed: {msg}",
  "member.photoNoConfig": "Photo upload not configured",
  "member.photoUploadFailed": "Photo upload failed: {msg}",
  "member.checkInBtn": "Check In",
  "staff.boatNotFound": "Boat not found.",
  "staff.groupCheckoutTitle": "Group Checkout",
  "staff.selectBoats": "Select boats",
  "staff.participants": "Participants (Iðkendur)",
  "staff.activityType": "Activity type",
  "staff.errSelectBoat": "Select at least one boat.",
  "staff.errSailingArea": "Select a sailing area.",
  "staff.errStaffRequired": "At least one staff member on water is required.",
  "staff.errStaffFromList": "Please select staff from the list: {names}",
  "staff.groupLaunched": "Group launched ✓",
  "staff.searchStaff": "Search staff name…",
  "staff.addAsGuest": "+ Add \"{name}\" as guest",
  "staff.crewSearchPh": "Crew member {n} — search by name…",
  "staff.errKtOrPhone": "Please enter a kennitala/birth year or phone number.",
  "staff.guestSaveFailed": "Failed to save guest: {msg}",
  "staff.checkInClose": "Check in & close",
  "staff.noActivities": "No activities in today's log yet.",
  "staff.linkedDailyLog": "Linked to daily log ✓",
  "staff.payrollUnavail": "Payroll not available — deploy backend first",
  "staff.onWaterTotal": "{n} on water total, {b} {boatWord}",
  "staff.boat": "boat",
  "staff.boats": "boats",
  "staff.peopleOnWater": "people on water",
  "staff.checkInAll": "Check In All",
  "staff.noneOption": "— None —",
  "staff.oosTitle": "Out of service",
  "staff.alreadyOut": "Already out",
  "staff.staffOnDuty": "Staff on duty",
  "staff.noStaffOnDuty": "No staff on duty",
  "staff.supportBoat": "Support boat out",
  "staff.noSupportBoat": "No support boat",
  "staff.updatedShort": "Upd.",
  "staff.guardianLabel": "Guardian",
  "staff.phoneLabel": "Phone",
  "staff.expectedBack": "Expected back",
  "staff.overdueBy": "Overdue by",
  "staff.hrsMin": "{h}h {m}min",
  "staff.minOnly": "{m} min",
  "staff.snoozeBtn": "Snooze ({n} min)",
  "staff.silenceBtn": "Silence",
  "maint.noFilterMatch": "No requests match this filter.",
  "maint.loadFailed": "Failed to load: {msg}",
  "maint.errCategory": "Please select a category.",
  "maint.errSeverity": "Please select a severity level.",
  "maint.errDescription": "Please describe the issue.",
  "maint.errBoat": "Please select a boat.",
  "maint.imgTooLarge": "Image too large ({size} MB). Max is 5 MB.",
  "maint.submitting": "Submitting…",
  "maint.uploadingPhoto": "Uploading photo…",
  "maint.submitBtn": "Submit",
  "maint.submitted": "Request submitted ✓",
  "maint.resolvedToast": "Resolved ✓",
  "maint.commentAdded": "Comment added.",
  "cert.removeConfirm": "Remove this credential?",
  "cq.allBoats": "All boats",
  "cq.allYears": "All years",
  "cq.allCategories": "All categories",
  "cq.allCaptains": "All captains",
  "cq.allMembers": "All members",
  "cq.fileTooLarge": "File too large (max 5 MB)",
  "cq.memberDatesRequired": "Member and dates required.",
  "cq.noTripsMatch": "No trips match this filter.",
  "cq.crewJoinRequest": "Requesting to join as crew",
  "cq.crewAssignPending": "Crew assignment pending",
  "cox.memberDatesRequired": "Member and dates required.",
  "wx.fetching": "Fetching weather data…",
  "wx.updating": "Updating…",
  "wx.checkConnection": "Check connection and try again.",
  "wx.failed": "Failed",
  "wx.refresh": "Refresh",
  "wx.pressureUnavail": "Pressure data unavailable",
  "logrev.noMemberSelected": "No member selected.",
  "logrev.memberNotFound": "Member not found.",
  "logrev.credentialRemoved": "Credential removed",
  "sauma.imgTooLarge": "Image too large. Max is 5 MB.",
  "sauma.submitting": "Submitting…",
  "sauma.uploadingPhoto": "Uploading photo…",
  "sauma.submitted": "Project submitted for review.",
  "sauma.selectCategory": "Please select a category.",
  "sauma.selectPriority": "Please select a priority.",
  "sauma.describeProject": "Please describe the project.",
  "sauma.selectBoat": "Please select a boat.",
  "passport.title": "ROWING PASSPORT",
  "passport.historyNote": "history",
  "passport.signerMode": "Sign-off mode — tap items to sign.",
  "passport.confirmSign": "Sign off this passport item?",
  "passport.signed": "Signed off.",
  "passport.promoted": "Passport complete — promoted to Released Rower!",
  "passport.adminTitle": "Rowing Passport",
  "passport.importCsv": "Import CSV",
  "passport.exportCsv": "Export CSV",
  "passport.csvHelp": "Columns: passport_id,category_id,category_label_en,category_label_is,item_id,assessment,item_label_en,item_label_is,description_en,description_is. assessment is 'theory' or 'practical'.",
  "passport.theory": "Theory",
  "passport.practical": "Practical",
  "passport.viewMember": "VIEW MEMBER",
  "passport.viewSelf": "My passport",
  "passport.revokeReason": "Reason for revoking this sign-off?",
  "passport.revoked": "Sign-off revoked.",
  "passport.addCategory": "+ Add category",
  "passport.addItem": "+ Add item",
  "passport.retire": "Retire",
  "passport.unretire": "Restore",
  "passport.save": "Save changes",
  "passport.saved": "Passport saved.",
  "passport.unsavedChanges": "You have unsaved changes. Discard?"
};
