// ═══════════════════════════════════════════════════════════════════════════════
// ÝMIR — shared/strings.js
//
// Single source of truth for all user-visible strings across every page.
// Loaded after shared/api.js (which provides getLang()).
//
// USAGE
// ─────
//   s("key")              → string in current language, fallback to EN
//   s("key", {n:3})       → interpolate: "3 trips" / "3 ferðir"
//   s("key", null, "IS")  → force a specific language (for email templates etc.)
//
// KEY NAMESPACES
// ──────────────
//   nav.*        Header navigation
//   btn.*        Generic buttons (Save, Cancel, Delete …)
//   lbl.*        Generic labels (Loading, Name, Date …)
//   toast.*      Toast / feedback messages
//   flag.*       Sailing flag labels & advice
//   wx.*         Weather widget strings
//   login.*      Login page
//   member.*     Member hub
//   staff.*      Staff hub + coForm.*
//   daily.*      Daily log
//   incident.*   Incidents
//   maint.*      Maintenance
//   logrev.*     Logbook review
//   admin.*      Admin panel
//   cert.*       Certifications
// ═══════════════════════════════════════════════════════════════════════════════

const STRINGS = {

  // ── Navigation ─────────────────────────────────────────────────────────────
  'nav.staffHub':      { EN:'⚓️ Staff Hub',      IS:'⚓️ Starfsmaenn' },
  'nav.memberHub':     { EN:'⛵ Members',         IS:'⛵ Félagssvæði' },
  'nav.admin':         { EN:'⚙️ Admin',            IS:'⚙️ Stjórnborð' },
  'nav.weather':       { EN:'⛅️ Weather',          IS:'⛅️ Veður' },
  'nav.logbook':       { EN:'📖 Logbook',         IS:'📖 Siglingabók' },
  'nav.back':          { EN:'← Back',            IS:'← Tilbaka' },
  'nav.signOut':       { EN:'Sign out',            IS:'Skrá út' },
  'nav.langToggle':    { EN:'IS',                  IS:'EN' },

  // ── Generic buttons ────────────────────────────────────────────────────────
  'btn.save':          { EN:'Save',                IS:'Vista' },
  'btn.cancel':        { EN:'Cancel',              IS:'Hætta við' },
  'btn.delete':        { EN:'Delete',              IS:'Eyða' },
  'btn.edit':          { EN:'Edit',                IS:'Breyta' },
  'btn.add':           { EN:'+ Add',               IS:'+ Bæta við' },
  'btn.close':         { EN:'Close',               IS:'Loka' },
  'btn.confirm':       { EN:'Confirm',             IS:'Staðfesta' },
  'btn.resolve':       { EN:'Resolve',             IS:'Ljúka' },
  'btn.saveDraft':     { EN:'Save draft',          IS:'Vista drög' },
  'btn.signOff':       { EN:'Save & Sign off',     IS:'Vista & Undirrita' },
  'btn.submit':        { EN:'Submit',              IS:'Senda inn' },
  'btn.addComment':    { EN:'Add comment',         IS:'Bæta við athugasemd' },
  'btn.viewAll':       { EN:'View all →',          IS:'Sjá allt →' },

  // ── Generic labels ─────────────────────────────────────────────────────────
  'lbl.loading':       { EN:'Loading…',            IS:'Hleður…' },
  'lbl.on':            { EN:'On',                  IS:'Kveikt' },
  'lbl.off':           { EN:'Off',                 IS:'Slökkt' },
  'lbl.noData':        { EN:'No data',            IS:'Engin gögn' },
  'lbl.name':          { EN:'Name',                IS:'Nafn' },
  'lbl.date':          { EN:'Date',                IS:'Dagsetning' },
  'lbl.time':          { EN:'Time',                IS:'Tími' },
  'lbl.notes':         { EN:'Notes',               IS:'Athugasemdir' },
  'lbl.status':        { EN:'Status',              IS:'Staða' },
  'lbl.phone':         { EN:'Phone',               IS:'Sími' },
  'lbl.email':         { EN:'Email',               IS:'Netfang' },
  'lbl.location':      { EN:'Location',            IS:'Staðsetning' },
  'lbl.boat':          { EN:'Boat',                IS:'Bátur' },
  'lbl.crew':          { EN:'Crew',                IS:'Áhöfn' },
  'lbl.role':          { EN:'Role',                IS:'Hlutverk' },
  'lbl.member':        { EN:'Member',              IS:'Félagi' },
  'lbl.guest':         { EN:'Guest',               IS:'Gestur' },
  'lbl.guardian':      { EN:'Guardian',            IS:'Forráðamaður' },
  'lbl.minor':         { EN:'MINOR',               IS:'Ólögráða' },
  'lbl.verified':      { EN:'✓ Verified',          IS:'✓ Staðfest' },
  'lbl.pending':       { EN:'Pending review',      IS:'Bíður yfirferðar' },
  'lbl.optional':      { EN:'optional',            IS:'valfrjálst' },
  'lbl.filter':        { EN:'FILTER:',             IS:'SÍA:' },
  'lbl.active':        { EN:'Active',              IS:'Virkt' },
  'lbl.inactive':      { EN:'Inactive',            IS:'Óvirkt' },
  'lbl.season':        { EN:'Season',              IS:'Tímabil' },
  'lbl.category':      { EN:'Category',            IS:'Flokkur' },
  'lbl.description':   { EN:'Description',         IS:'Lýsing' },
  'lbl.severity':      { EN:'Severity',            IS:'Alvarleiki' },
  'lbl.type':          { EN:'Type',                IS:'Tegund' },
  'lbl.phase':         { EN:'Phase',               IS:'Fasi' },
  'lbl.sortOrder':     { EN:'Sort order',          IS:'Röðun' },
  'lbl.selectDots':    { EN:'Select…',             IS:'Veldu…' },
  'lbl.noneDash':      { EN:'— none —',            IS:'— ekkert —' },

  // ── Toast / feedback ───────────────────────────────────────────────────────
  'toast.saved':       { EN:'Saved',              IS:'Vistað' },
  'toast.saveFailed':  { EN:'Save failed',         IS:'Mistókst að vista' },
  'toast.deleted':     { EN:'Deleted',            IS:'Eytt' },
  'toast.error':       { EN:'Something went wrong. Try again.', IS:'Eitthvað fór úrskeiðis. Reyndu aftur.' },
  'toast.loadFailed':  { EN:'Load failed',         IS:'Hleðsla mistókst' },
  'toast.signedOff':   { EN:'Signed off ✓',        IS:'Undirritað ✓' },
  'toast.checkedIn':   { EN:'Checked in ✓',        IS:'Skráð inn ✓' },
  'toast.noPhone':     { EN:'No phone on record',  IS:'Ekkert símanúmer skráð' },

  // ── Sailing flags ──────────────────────────────────────────────────────────
  'flag.green.label':  { EN:'Green',               IS:'Grænn' },
  'flag.green.advice': { EN:'Good conditions.',    IS:'Gott veðurlag.' },
  'flag.yellow.label': { EN:'Yellow',              IS:'Gulur' },
  'flag.yellow.advice':{ EN:'Marginal — experienced sailors only.', IS:'Krefjandi — aðeins reyndir siglingamenn.' },
  'flag.orange.label': { EN:'Orange',              IS:'Appelsínugulur' },
  'flag.orange.advice':{ EN:'Difficult — keelboats only, staff auth for dinghies.', IS:'Erfitt — takmörkuð siglingar.' },
  'flag.red.label':    { EN:'Red',                 IS:'Rauður' },
  'flag.red.advice':   { EN:'Do not sail — all sailing suspended.', IS:'Ekki sigla — Öll siglingar stöðvaðar.' },
  'flag.currentLabel': { EN:'CURRENT FLAG',        IS:'NÚVERANDI FÁNI' },
  'flag.allLevels':    { EN:'All levels →',        IS:'Allar stigur →' },
  'flag.conditions':   { EN:'Sailing Conditions',  IS:'Siglingaraðstæður' },

  // ── Weather widget ─────────────────────────────────────────────────────────
  'wx.wind':           { EN:'WIND',                IS:'VINDUR' },
  'wx.gusts':          { EN:'GUSTS',               IS:'HVIÐA' },
  'wx.waves':          { EN:'WAVES',               IS:'BYLGJUR' },
  'wx.pressure':       { EN:'PRESSURE',            IS:'LOFTÞRÝSTINGUR' },
  'wx.loading':        { EN:'Loading conditions…', IS:'Sæki veðurgögn…' },
  'wx.unavailable':    { EN:'⚠️ Weather unavailable', IS:'⚠️ Veður ekki tiltækt' },
  'wx.fullForecast':   { EN:'Full forecast →',     IS:'Heildarspá →' },
  'wx.updated':        { EN:'Updated',             IS:'Uppfært' },

  // ── Login ──────────────────────────────────────────────────────────────────
  'login.title':       { EN:'Ýmir Sailing Club',   IS:'Siglingafélagið Ýmir' },
  'login.subtitle':    { EN:'Sailing Club', IS:'Siglingafélagið' },
  'login.kennitala':   { EN:'Kennitala',            IS:'Kennitala' },
  'login.placeholder': { EN:'0000000000',           IS:'0000000000' },
  'login.btn':         { EN:'Sign in',              IS:'Skrá inn' },
  'login.loading':     { EN:'Signing in…',          IS:'Skrái inn…' },
  'login.notFound':    { EN:'Member not found or account inactive.', IS:'Félagi finnst ekki eða aðgangur er óvirkur.' },
  'login.tooShort':    { EN:'Please enter your 10-digit kennitala.', IS:'Vinsamlegast sláðu inn 10 stafa kennitölu.' },
  'login.error':       { EN:'Login failed. Try again.', IS:'Innskráning mistókst. Reyndu aftur.' },
  'login.welcome':     { EN:'Welcome,',              IS:'Velkomin/n,' },
  'login.chooseView':  { EN:'How would you like to sign in?', IS:'Hvernig viltu skrá þig inn?' },
  'login.back':        { EN:'← Sign in as someone else', IS:'← Skrá inn sem annan notandi' },
  'login.admin.label': { EN:'Admin Panel',           IS:'Stjórnborð' },
  'login.admin.desc':  { EN:'Manage members, boats, locations, settings', IS:'Stjórna félaga, bátum, stöðum, stillingum' },
  'login.staff.label': { EN:'Staff Dashboard',       IS:'Starfsmannaþjónusta' },
  'login.staff.desc':  { EN:'Daily log, fleet status, incidents', IS:'Daglegur rekstur, flotinn, tilvik' },
  'login.member.label':{ EN:'Member Hub',            IS:'Félagssvæði' },
  'login.member.desc': { EN:'Check in/out, logbook, my trips', IS:'Inn/útskráning, dagbók, mínar ferðir' },

  // ── Member hub ─────────────────────────────────────────────────────────────
  'member.launchBoat':   { EN:'🚀 Launch a Boat',   IS:'🚀 Fara á sjó' },
  'member.checkIn':      { EN:'✓ Check In',          IS:'✓ Skrá inn' },
  'member.reportIssue':  { EN:'🔧 Report Issue',     IS:'🔧 Tilkynna vandamál' },
  'member.myCheckout':   { EN:'BOATS OUT NOW',       IS:'BÁTAR Á SJÓNUM' },
  'member.myCheckoutSub':{ EN:'tap your boat to check in', IS:'smelltu á þinn bát til að skrá inn' },
  'member.tabFleet':     { EN:'Fleet',               IS:'Flotinn' },
  'member.tabTrips':     { EN:'Log a Trip',          IS:'Skrá siglingu' },
  'member.tabLogbook':   { EN:'Logbook',             IS:'Dagbók' },
  'member.tabCerts':     { EN:'Credentials',                  IS:'Skírteini' },
  'member.fleetAvail':   { EN:'AVAILABLE BOATS',     IS:'LAUSIR BÁTAR' },
  'member.tripTabHint':  { EN:'Tap a recent trip below to add it to your logbook as crew, or log a trip manually.', IS:'Smelltu á nýlega siglingu til að bæta henni við dagbókina þína sem áhöfn, eða skráðu siglingu handvirkt.' },
  'member.statTrips':    { EN:'TOTAL TRIPS',         IS:'SAMTALS SIGLINGAR' },
  'member.statHours':    { EN:'HOURS SAILED',        IS:'SIGLINGATÍMAR' },
  'member.statBoat':     { EN:'MOST-SAILED BOAT',    IS:'MEST NOTAÐI BÁTUR' },
  'member.statSeason':   { EN:'TRIPS THIS SEASON',   IS:'SIGLINGAR Í TÍMABILI' },
  'member.noTrips':      { EN:'No trips in your logbook yet.', IS:'Engar siglingard í dagbókinni þinni enn.' },
  'member.noCheckouts':  { EN:'No boats out.',        IS:'Engir bátar á sjó.' },
  'member.noBoats':      { EN:'No boats available.', IS:'Engir bátar lausir.' },
  'member.noCerts':      { EN:'No credentials on file.', IS:'Engin skírteini skráð.' },
  'member.boatOut':      { EN:'Out',                 IS:'Úti' },
  'member.boatOos':      { EN:'Out of service',      IS:'Utan þjónustu' },
  'member.boatAvail':    { EN:'Available',           IS:'Laus' },
  'member.skipper':      { EN:'skipper',             IS:'skipstjóri' },
  'member.crewRole':     { EN:'crew',                IS:'áhöfn' },
  'member.addAsCrew':        { EN:'Add as crew',                IS:'Bæta við sem áhöfn' },
  'member.tripsTapHint':     { EN:'Tap a trip for details',     IS:'Smelltu á siglingu til að sjá nánar' },
  'member.departed':     { EN:'Departed',            IS:'Lagt af stað' },
  'member.returned':     { EN:'Returned',            IS:'Komið tilbaka' },
  'member.duration':     { EN:'Duration',            IS:'Tímalengd' },
  'member.loadFailed':   { EN:'Load failed',         IS:'Hleðsla mistókst' },
  'member.logManual':    { EN:'+ Log manually',      IS:'+ Skrá handvirkt' },
  'member.recentTrips':  { EN:'RECENT PUBLIC TRIPS', IS:'NÝLEGAR SIGLINGAR' },
  'member.noRecent':     { EN:'No recent trips',    IS:'Engar nýlegar siglingar' },
  'member.myLogbook':    { EN:'MY LOGBOOK',          IS:'MÍN DAGBÓK' },
  'member.myCerts':      { EN:'MY CREDENTIALS',     IS:'MÍN SKÍRTEINI' },
  'member.launchTitle':  { EN:'Launch a Boat',       IS:'Fara á sjó' },
  'member.checkInTitle': { EN:'Check In',            IS:'Skrá inn' },
  'member.manualTrip':   { EN:'Log a Trip',          IS:'Skrá siglingu' },
  'member.pendingConfirmations': { EN:'Pending Confirmations', IS:'Beiðnir í bið' },
  'member.confirmationsTitle':   { EN:'Trip Confirmations',    IS:'Staðfestingar siglinga' },
  'member.incoming':    { EN:'REQUESTS FOR YOU',     IS:'BEIÐNIR TIL ÞÍN' },
  'member.outgoing':    { EN:'YOUR REQUESTS',        IS:'ÞÍNAR BEIÐNIR' },
  'member.noIncoming':  { EN:'No pending requests.',  IS:'Engar beiðnir í bið.' },
  'member.noOutgoing':  { EN:'No outgoing requests.', IS:'Engar beiðnir sendar.' },
  'member.crewAssigned':{ EN:'assigned you as crew on', IS:'skráði þig sem áhöfn á' },
  'member.crewJoin':    { EN:'wants to join your trip on', IS:'vill taka þátt í siglingu þinni á' },
  'member.helmReq':     { EN:'marked you as helm on',  IS:'merkti þig sem stýrimann á' },
  'member.confirmBtn':  { EN:'Confirm',   IS:'Staðfesta' },
  'member.rejectBtn':   { EN:'Reject',    IS:'Hafna' },
  'member.statusPending':   { EN:'pending',    IS:'í bið' },
  'member.statusConfirmed': { EN:'confirmed',  IS:'staðfest' },
  'member.statusRejected':  { EN:'rejected',   IS:'hafnað' },
  'member.rejectReason':    { EN:'Reason for rejection (optional):', IS:'Ástæða höfnunar (valfrjálst):' },
  'member.shareRecord':  { EN:'SHARE YOUR RECORD',   IS:'DEILA SKRÁNINGU' },
  'member.shareDesc':    { EN:'Generate a link to share your sailing record with charter agents or other parties. The link shows sessions up to today\'s date.', IS:'Búðu til hlekk til að deila siglingaskráningunni þinni með leiguaðilum eða öðrum. Hlekkurinn sýnir siglingalotur til og með deginum í dag.' },
  'member.btnGenerate':  { EN:'+ Generate share link', IS:'+ Búa til deilingarhlekk' },
  'member.noTokens':     { EN:'No share links generated yet.', IS:'Engir deilingarhlekkir búnir til enn.' },
  'member.tokenCreated': { EN:'Share link created.', IS:'Deilingarhlekkur búinn til.' },

  // ── Member settings ────────────────────────────────────────────────────────
  'settings.title':           { EN:'Settings',                 IS:'Stillingar' },
  'settings.initials':        { EN:'Initials',                 IS:'Upphafsstafir' },
  'settings.initialsHint':    { EN:'Auto-generated from your name. Override below.', IS:'Sjálfvirkt búið til úr nafni. Breyttu hér að neðan.' },
  'settings.language':        { EN:'Language',                 IS:'Tungumál' },
  'settings.windUnit':        { EN:'Wind units',               IS:'Vindeining' },
  'settings.windUnit.bft':    { EN:'Beaufort (Force 4)',       IS:'Beaufort (Force 4)' },
  'settings.windUnit.ms':     { EN:'m/s',                      IS:'m/s' },
  'settings.windUnit.kts':    { EN:'Knots',                    IS:'Hnútar' },
  'settings.windUnit.kmh':    { EN:'km/h',                     IS:'km/klst' },
  'settings.windUnit.mph':    { EN:'mph',                      IS:'mph' },
  'settings.windUnitHint':    { EN:'Controls wind display in your logbook.', IS:'Stýrir hvernig vindur birtist í dagbókinni þinni.' },
  'settings.theme':           { EN:'Appearance',               IS:'Útlit' },
  'settings.theme.dark':      { EN:'Dark',                     IS:'Dökkt' },
  'settings.theme.light':     { EN:'Light',                    IS:'Ljóst' },
  'settings.theme.auto':      { EN:'Auto',                     IS:'Sjálfvirkt' },
  'settings.stats':           { EN:'Stats visibility',         IS:'Tölfræði sýnileiki' },
  'settings.statsHint':       { EN:'Choose which stats appear on your logbook page.', IS:'Veldu hvaða tölfræði birtist á dagbókarsíðunni þinni.' },
  'settings.stats.ytd':       { EN:'Trips this year (YTD)',    IS:'Siglingar á þessu ári' },
  'settings.stats.career':    { EN:'Total trips (career)',     IS:'Samtals siglingar (ferill)' },
  'settings.stats.hours':     { EN:'Hours sailed',             IS:'Siglingatímar' },
  'settings.stats.skipper':   { EN:'As skipper',               IS:'Sem skipstjóri' },
  'settings.stats.byCategory':{ EN:'Hours by category',        IS:'Tímar eftir flokki' },
  'settings.stats.distance':  { EN:'Total distance (nm)',       IS:'Heildar vegalengd (nm)' },
  'settings.stats.longest':   { EN:'Longest trip',              IS:'Lengsta sigling' },
  'settings.stats.avgWind':   { EN:'Average wind',              IS:'Meðalvindur' },
  'settings.stats.streak':    { EN:'Weekly streak',              IS:'Vikuleg röð' },
  'settings.stats.boats':     { EN:'Unique boats sailed',       IS:'Einstök bátar sigld' },
  'settings.stats.crew':      { EN:'Trips as crew',             IS:'Siglingar sem áhöfn' },
  'settings.stats.heavy':     { EN:'Heavy weather (F5+)',       IS:'Hörð veður (F5+)' },
  'settings.stats.night':     { EN:'Night sails',               IS:'Nætursiglingar' },
  'settings.stats.avgDuration':{ EN:'Avg trip duration',        IS:'Meðal siglingatími' },
  'settings.stats.locations': { EN:'Locations sailed',           IS:'Staðir sigldir' },
  'settings.stats.verified':  { EN:'Verified trips',            IS:'Staðfestar siglingar' },
  'settings.statsGroup.activity':   { EN:'Activity',           IS:'Virkni' },
  'settings.statsGroup.sailing':    { EN:'Sailing',            IS:'Sigling' },
  'settings.statsGroup.roles':      { EN:'Roles & boats',      IS:'Hlutverk og bátar' },
  'settings.statsGroup.conditions': { EN:'Conditions',         IS:'Aðstæður' },
  'settings.statsGroup.other':      { EN:'Other',              IS:'Annað' },
  'settings.saved':           { EN:'Settings saved',           IS:'Stillingar vistaðar' },
  'settings.saveFailed':      { EN:'Failed to save settings',  IS:'Mistókst að vista stillingar' },
  'nav.settings':             { EN:'⚙ Settings',              IS:'⚙ Stillingar' },

  // ── Logbook share ─────────────────────────────────────────────────────────
  'logbook.shareBtn':     { EN:'Share your logbook',      IS:'Deila dagbókinni þinni' },
  'logbook.sharePhotos':  { EN:'Include photos',         IS:'Taka myndir með' },
  'logbook.shareTracks':  { EN:'Include GPS tracks',     IS:'Taka GPS-leiðir með' },
  'logbook.shareCopy':    { EN:'Generate & copy link',   IS:'Búa til og afrita hlekk' },
  'logbook.shareCopied':  { EN:'Link copied!',           IS:'Hlekkur afritaður!' },
  'logbook.editTrip':     { EN:'Edit trip',              IS:'Breyta ferð' },
  'logbook.addGps':       { EN:'Add GPS',                IS:'Bæta við GPS' },
  'logbook.addPhotos':    { EN:'Add photos',             IS:'Bæta við myndum' },
  'logbook.shareWithCrew':{ EN:'Share with crew',        IS:'Deila með áhöfn' },
  'logbook.clubMayUse':   { EN:'Club may use',           IS:'Félagið má nota' },
  'logbook.photoSharedHint':  { EN:'Shared photos are visible to other trip members. Club-use photos may be used for promotional purposes.', IS:'Deildar myndir sjást öðrum í ferðinni. Myndir merktar fyrir félagið má nota í kynningarefni.' },
  'logbook.tripUpdated':  { EN:'Trip updated',           IS:'Ferð uppfærð' },
  'logbook.trackAdded':   { EN:'GPS track added',        IS:'GPS-leið bætt við' },
  'logbook.photosAdded':  { EN:'Photos added',           IS:'Myndir bættar við' },
  'logbook.skipperOnly':  { EN:'Only the skipper can edit this trip', IS:'Aðeins skipstj��ri getur breytt ferðinni' },

  // ── Staff hub ──────────────────────────────────────────────────────────────
  'staff.dashTitle':         { EN:'Staff Dashboard',          IS:'Stjórnborð starfsmanna' },
  'staff.fleet':             { EN:'FLEET STATUS',             IS:'STAÐA FLOTANS' },
  'staff.expandAll':         { EN:'expand all',               IS:'sýna allt' },
  'staff.collapseAll':       { EN:'collapse all',             IS:'fela allt' },
  'staff.recentCheckins':    { EN:'RECENT CHECK-INS (24H)',   IS:'NÝLEGAR INNSKRÁNINGAR (24H)' },
  'staff.overdue':           { EN:'OVERDUE',                  IS:'UMFRAM ÁÆTLUN' },
  'staff.overdueMinor':      { EN:'OVERDUE — MINOR',          IS:'UMFRAM ÁÆTLUN — BARN' },
  'staff.maintenance':       { EN:'OPEN MAINTENANCE',         IS:'OPIN VIÐHALDSMÁL' },
  'staff.maintDetail':        { EN: 'Issue Detail',           IS: 'Upplýsingar' },
  'staff.dailyLog':          { EN:'Daily Log',                IS:'Dagbók félagsins' },
  'staff.dailyLogDesc':      { EN:'Tides, weather records, checklists, activities, sign-off', IS:'Flóð, veðurskráning, gátlistar, starfsemi, undirskrift' },
  'staff.logbook':           { EN:'Logbook Review',           IS:'Dagbókarskoðun' },
  'staff.logbookDesc':       { EN:'Verify member trips & assign credentials', IS:'Staðfesta ferðir félaga og úthluta skírteinum' },
  'staff.incidents':         { EN:'Incidents',                IS:'Tilvik' },
  'staff.incidentsDesc':     { EN:'File or review safety incident reports', IS:'Skrá eða fara yfir öryggistilvik' },
  'staff.maintenanceDesc':   { EN:'Report and track boat & equipment issues', IS:'Tilkynna og fylgjast með vandamálum á bátum og búnaði' },
  'staff.noOverdue':         { EN:'No overdue checkouts.',    IS:'Engar yfirtíma útskráningar.' },
  'staff.noMaint':           { EN:'No open requests.',        IS:'Engar opnar beiðnir.' },
  'staff.silence':           { EN:'Silence',                  IS:'Þagga' },
  'staff.snooze':            { EN:'Snooze',                   IS:'Fresta' },
  'staff.minsOverdue':       { EN:'{n} min overdue',          IS:'{n} mín yfirtíma' },
  'staff.hrsOverdue':        { EN:'{h}h {m}min overdue',     IS:'{h}klst {m}mín yfirtíma' },
  'staff.expectedReturn':    { EN:'Expected return',          IS:'Áætlaður skilatími' },
  'staff.checkIn':           { EN:'✓ Check In',               IS:'✓ Skrá inn' },
  'staff.deleteCheckout':    { EN:'Delete',                   IS:'Eyða' },
  'staff.availCount':        { EN:'{n} available',            IS:'{n} tiltækir' },
  'staff.activeCheckouts':   { EN:'ACTIVE CHECKOUTS',         IS:'VIRKAR ÚTSKRÁNINGAR' },
  'staff.boatsOutNow':       { EN:'BOATS OUT NOW',            IS:'BÁTAR Á SJÓNUM' },
  'staff.checkOutBtn':         { EN:'Boat Checkout',            IS:'Uthluta bati' },
  'staff.groupCheckout':      { EN:'Group Checkout',           IS:'Hópaúthlutun' },
  'staff.newCheckout':       { EN:'NEW CHECKOUT',             IS:'NÝ ÚTSKRÁNING' },
  'staff.statBoats':         { EN:'BOATS OUT',                IS:'BÁTAR Á SJÓ' },
  'staff.statPeople':        { EN:'PEOPLE OUT',               IS:'FÓLK Á SJÓ' },
  'staff.statOverdue':       { EN:'OVERDUE',                  IS:'YFIRTÍMA' },
  'staff.toolsLabel':        { EN:'TOOLS',                    IS:'VERKFÆRI' },
  'staff.fullForecast':      { EN:'⛅️ Full Forecast →',        IS:'⛅️ Heildarlíkan →' },
  'staff.tideHeader':        { EN:'TIDES · FAXAFLÓI',         IS:'FLÓÐ · FAXAFLÓI' },
  'tide.rising':             { EN:'Rising',                   IS:'Hækkandi' },
  'tide.falling':            { EN:'Falling',                  IS:'Lækkandi' },
  'tide.high':               { EN:'High',                     IS:'Flóð' },
  'tide.low':                { EN:'Low',                      IS:'Fjara' },
  'tide.next':               { EN:'NEXT',                     IS:'NÆST' },
  'tide.autoFill':           { EN:'↻ Auto-fill tides',        IS:'↻ Fylla sjálfkrafa' },
  'tide.autoFilled':         { EN:'Auto-filled from prediction', IS:'Sjálfkrafa fyllt úr spá' },
  // Checkout form sub-keys
  'staff.coForm.departure':         { EN:'Departure',               IS:'Brottför' },
  'staff.coForm.estReturn':         { EN:'Est. return',             IS:'Áætl. heimkoma' },
  'staff.coForm.crew':              { EN:'Crew on board',           IS:'Áhöfn um borð' },
  'staff.coForm.notes':             { EN:'Notes (optional)',        IS:'Athugasemdir (valfrjálst)' },
  'staff.coForm.submit':            { EN:'Check Out',               IS:'Útskrá' },
  'staff.coForm.memberPlaceholder': { EN:'Name or kennitala…',      IS:'Nafn eða kennitala…' },
  'staff.coForm.notesPlaceholder':  { EN:'Any notes…',              IS:'Einhverjar athugasemdir…' },
  'staff.coForm.errMember':         { EN:'Select a member.',        IS:'Veldu félaga.' },
  'staff.coForm.errBoat':           { EN:'Select a boat.',          IS:'Veldu bát.' },
  'staff.coForm.errLocation':       { EN:'Select a sailing area.',   IS:'Veldu siglingasvæði.' },
  'staff.coForm.checkedOut':        { EN:'Checked out ✓',           IS:'Útskráð ✓' },
  // Detail modal sub-keys
  'staff.coDetail.title':     { EN:'Checkout Details',   IS:'Upplýsingar um útskráningu' },
  'staff.coDetail.tripLabel': { EN:'TRIP',               IS:'FERÐ' },
  'staff.coDetail.out':       { EN:'OUT',                IS:'FÓRT' },
  'staff.coDetail.return':    { EN:'EST. RETURN',        IS:'ÁÆTL. HEIMKOMA' },
  'staff.noBoatsOut':         { EN:'No boats currently out.', IS:'Engir bátar á sjónum.' },
  'staff.noRecentCheckins':   { EN:'No check-ins in the last 24 hours.', IS:'Engar innkráningar síðustu 24 klukkustundir.' },

  // ── Daily log ──────────────────────────────────────────────────────────────
  'daily.title':           { EN:'Daily Log',               IS:'Dagleg skráning' },
  'daily.today':           { EN:'Today',                   IS:'Í dag' },
  'daily.tripsToday':      { EN:'TRIPS TODAY',             IS:'FERÐIR Í DAG' },
  'daily.openingChecklist':{ EN:'OPENING CHECKLIST',       IS:'OPNUNARGÁTLISTI' },
  'daily.closingChecklist':{ EN:'CLOSING CHECKLIST',       IS:'LOKUNARGÁTLISTI' },
  'daily.activities':      { EN:'ACTIVITIES',              IS:'STARFSEMI' },
  'daily.addActivity':     { EN:'+ Add',                   IS:'+ Bæta við' },
  'daily.staffNotes':      { EN:'STAFF NOTES',             IS:'ATHUGASEMDIR STARFSMANNA' },
  'daily.notesPlaceholder':{ EN:'General notes, conditions summary…', IS:'Almennar athugasemdir, samantekt á aðstæðum…' },
  'daily.incidentReport':  { EN:'INCIDENTS',               IS:'TILVIK' },
  'daily.fileIncident':    { EN:'Submit an Incident Report', IS:'Senda tilviksskýrslu' },
  'daily.incidentSub':     { EN:'Injuries, near-misses, property damage, safety concerns', IS:'Meiðsli, næstum slys, eignatjón, öryggismál' },
  'daily.noIncidents':     { EN:'No incidents reported.',   IS:'Engin tilvik tilkynnt.' },
  'daily.wxLog':           { EN:'WEATHER LOG',             IS:'VEÐURSKRÁNING' },
  'daily.tides':           { EN:'TIDES',                   IS:'FLÓÐ OG EBB' },
  'daily.signedOff':       { EN:'Signed off',              IS:'Undirritað' },
  'daily.readOnly':        { EN:'Read-only',               IS:'Lesaðgangur' },
  'daily.noActivities':    { EN:'No activities recorded yet.', IS:'Engin starfsemi skráð enn.' },
  'daily.noTrips':         { EN:'No trips recorded today.', IS:'Engar ferðir skráðar í dag.' },
  'daily.activityModal':   { EN:'Add Activity',            IS:'Bæta við starfsemi' },
  'daily.actType':         { EN:'Type',                    IS:'Tegund' },
  'daily.actNameLabel':    { EN:'Name / description',      IS:'Nafn / lýsing' },
  'daily.actNameHint':     { EN:'e.g. Junior lesson, club race…', IS:'t.d. Unglingakennsla, félagskeppni…' },
  'daily.actParticipants': { EN:'Participants',            IS:'Þátttakendur' },
  'daily.actPartHint':     { EN:'e.g. 12 juniors',         IS:'t.d. 12 unglingar' },
  'daily.actNotes':        { EN:'Notes',                   IS:'Athugasemdir' },
  'daily.actNotesHint':    { EN:'optional',                IS:'valfrjálst' },
  'daily.startTime':       { EN:'Start time',              IS:'Byrjunartími' },
  'daily.endTime':         { EN:'End time',                IS:'Lokatími' },
  'daily.wxLogBtn':        { EN:'📸 Log snapshot',         IS:'📸 Taka veðurmynd' },
  'daily.noWxData':        { EN:'No weather data yet.',    IS:'Engin veðurgögn enn.' },
  'daily.signOffConfirm':  { EN:'PM checklist not complete ({done}/{total}). Sign off anyway?', IS:'PM gátlisti er ekki fullkláraður ({done}/{total}). Undirrita samt?' },
  'daily.saveDraftSaving': { EN:'Saving…',                 IS:'Vista…' },
  'daily.signOffSaving':   { EN:'Signing off…',            IS:'Undirritun…' },
  'daily.signedOffBy':     { EN:'✓ Signed off by ',        IS:'✓ Undirritað af ' },

  // ── Incidents ──────────────────────────────────────────────────────────────
  'incident.title':        { EN:'Incidents',               IS:'Tilvik' },
  'incident.viewList':     { EN:'View incidents',          IS:'Skoða tilvik' },
  'incident.fileNew':      { EN:'File new report',         IS:'Skrá nýja skýrslu' },
  'incident.typeLabel':    { EN:'Incident type(s)',         IS:'Tegund tilviks' },
  'incident.noIncidents':  { EN:'No incidents filed.',     IS:'Engin tilvik skráð.' },
  'incident.description':  { EN:'Description',             IS:'Lýsing' },
  'incident.involved':     { EN:'Person(s) involved',      IS:'Hlutaðeigandi aðilar' },
  'incident.witnesses':    { EN:'Witnesses',               IS:'Vitni' },
  'incident.immediateAction':{ EN:'Immediate action taken',IS:'Bráðabirgðaaðgerðir' },
  'incident.followUp':     { EN:'Follow-up required',      IS:'Nauðsynleg eftirfylgni' },
  'incident.handOff':      { EN:'Handed off to',           IS:'Framselt til' },
  'incident.staffNotes':   { EN:'Staff notes',             IS:'Athugasemdir starfsmanna' },
  'incident.addNote':      { EN:'Add note',                IS:'Bæta við athugasemd' },
  'incident.resolved':     { EN:'Resolved',                IS:'Lokið' },
  'incident.open':         { EN:'Open',                    IS:'Opið' },
  'incident.markResolved': { EN:'Mark resolved',           IS:'Merkja sem lokið' },
  'incident.markOpen':     { EN:'Reopen',                  IS:'Enduropna' },
  'incident.filedBy':      { EN:'Filed by',                IS:'Skráð af' },
  'incident.boatLabel':    { EN:'Boat (if applicable)',    IS:'Bátur (ef við á)' },
  'incident.personsInvolved':{ EN:'Persons involved',      IS:'Aðilar að máli' },
  'incident.witnessHint':  { EN:'Names / contact info…',   IS:'Nöfn / tengiliðaupplýsingar…' },
  'incident.actionHint':   { EN:'First aid, evacuation, coastguard called…', IS:'Skyndihjálp, rýming, landhelgisgæslan…' },
  'incident.followUpHint': { EN:'Referral, repair, investigation…', IS:'Tilvísun, viðgerð, rannsókn…' },
  'incident.handoffSection':{ EN:'Hand-off',               IS:'Framsending' },
  'incident.handoffTo':    { EN:'Handed off to',           IS:'Framselt til' },
  'incident.handoffName':  { EN:'Contact name / ref.',     IS:'Nafn tengiliðar / tilvísun' },
  'incident.handoffNotes': { EN:'Handoff notes',           IS:'Athugasemdir um framsendingu' },
  'incident.fileBtn':      { EN:'File Report',             IS:'Skrá skýrslu' },
  'incident.descRequired': { EN:'Description is required.', IS:'Lýsing er skylda.' },
  'incident.typeRequired': { EN:'Select at least one incident type.', IS:'Veldu að minnsta kosti eina tegund tilviks.' },
  'incident.sevRequired':  { EN:'Select severity.',        IS:'Veldu alvarleika.' },
  'incident.filed':        { EN:'Report filed ✓',          IS:'Skýrsla skráð ✓' },
  'incident.addNoteBtn':   { EN:'Add note',                IS:'Bæta við athugasemd' },
  'incident.notePlaceholder':{ EN:'Add a note…',           IS:'Bæta við athugasemd…' },
  'incident.type.injury':     { EN:'🩹 Injury',            IS:'🩹 Meiðsli' },
  'incident.type.capsize':    { EN:'⛵ Capsize',            IS:'⛵ Kæning' },
  'incident.type.collision':  { EN:'💥 Collision',         IS:'💥 Árekstur' },
  'incident.type.equipment':  { EN:'🔧 Equipment failure', IS:'🔧 Búnaðarbilun' },
  'incident.type.medical':    { EN:'🏥 Medical',           IS:'🏥 Læknisfræðilegt' },
  'incident.type.nearMiss':   { EN:'⚡️ Near miss',          IS:'⚡️ Nákvæmt miss' },
  'incident.type.missing':    { EN:'🔍 Missing person',    IS:'🔍 Saknað manneskja' },
  'incident.type.propertyDmg':{ EN:'🏗️ Property damage',  IS:'🏗️ Eignatjón' },
  'incident.type.other':      { EN:'📌 Other',             IS:'📌 Annað' },
  'incident.sev.low':         { EN:'Low',                  IS:'Lágt' },
  'incident.sev.medium':      { EN:'Medium',               IS:'Miðlungs' },
  'incident.sev.high':        { EN:'High',                 IS:'Hátt' },
  'incident.sev.critical':    { EN:'Critical',             IS:'Bráðavarsamt' },

  // ── Maintenance ────────────────────────────────────────────────────────────
  'maint.title':           { EN:'Maintenance',             IS:'Viðhald' },
  'maint.newRequest':      { EN:'+ Report issue',          IS:'+ Tilkynna vandamál' },
  'maint.category':        { EN:'Category',                IS:'Flokkur' },
  'maint.catBoat':         { EN:'Boat',                    IS:'Bátur' },
  'maint.catEquipment':    { EN:'Equipment',               IS:'Búnaður' },
  'maint.catFacility':     { EN:'Facility',                IS:'Aðstaða' },
  'maint.part':            { EN:'Part / item',             IS:'Hluti' },
  'maint.severity':        { EN:'Severity',                IS:'Alvarleiki' },
  'maint.sevLow':          { EN:'Low — no rush',           IS:'Lágt — engin haste' },
  'maint.sevMedium':       { EN:'Medium — fix soon',       IS:'Miðlungs — laga fljótt' },
  'maint.sevHigh':         { EN:'High — affects safety',   IS:'Hátt — hefur áhrif á öryggi' },
  'maint.markOos':         { EN:'Mark boat out of service', IS:'Merkja bát utan þjónustu' },
  'maint.reportedBy':      { EN:'Reported by',             IS:'Tilkynnt af' },
  'maint.noRequests':      { EN:'No open maintenance requests.', IS:'Engar opnar viðhaldsbeiðnir.' },
  'maint.resolved':        { EN:'Resolved',                IS:'Lokið' },
  'maint.open':            { EN:'Open',                    IS:'Opið' },
  'maint.resolveBtn':      { EN:'Mark resolved',           IS:'Merkja sem lokið' },
  'maint.comments':        { EN:'Comments',                IS:'Athugasemdir' },
  'maint.descPlaceholder': { EN:'Describe the issue…',     IS:'Lýstu vandamálinu…' },
  'maint.partPlaceholder': { EN:'e.g. rudder, jib halyard…', IS:'t.d. stýrið, forskatbylja…' },
  'maint.newTitle':        { EN:'NEW MAINTENANCE REQUEST', IS:'NÝ VIÐHALDSBEIÐNI' },
  'maint.filterOpen':      { EN:'Open',                    IS:'Opið' },
  'maint.filterAll':       { EN:'All',                     IS:'Allt' },
  'maint.filterBoat':      { EN:'Boat',                    IS:'Bátur' },
  'maint.filterEquipment': { EN:'Equipment',               IS:'Búnaður' },
  'maint.filterFacility':  { EN:'Facility',                IS:'Aðstaða' },
  'maint.commentPlaceholder':{ EN:'Add a comment…',        IS:'Bæta við athugasemd…' },
  'maint.addCommentBtn':   { EN:'Add',                     IS:'Bæta við' },
  'maint.oosConfirm':      { EN:'Mark this boat out of service?', IS:'Merkja þennan bát utan þjónustu?' },
  'maint.resolveConfirm':  { EN:'Mark this request as resolved?', IS:'Merkja þessa beiðni sem lokna?' },
  'maint.statOpen':        { EN:'OPEN',                    IS:'OPIÐ' },
  'maint.statHigh':        { EN:'HIGH / CRITICAL',         IS:'HÁTT / BRÁÐAVARSAMT' },
  'maint.statOos':         { EN:'BOATS OOS',               IS:'BÁTAR UTAN ÞJÓNUSTU' },

  // ── Saumaklúbbur (Sewing Circle) ──────────────────────────────────────────
  'sauma.pageTitle':       { EN:'🧵 Sewing Circle',         IS:'🧵 Saumaklúbbur' },
  'sauma.pageSubtitle':    { EN:'Community maintenance projects', IS:'Samfélagsverkefni í viðhaldi' },
  'sauma.toggle':          { EN:'Sewing Circle Project',    IS:'Saumaklúbbsverkefni' },
  'sauma.toggleHint':      { EN:'Mark as a sewing circle project', IS:'Merkja sem saumaklúbbsverkefni' },
  'sauma.verkstjori':      { EN:'Project Lead',              IS:'Verkstjóri' },
  'sauma.verkstjoriHint':  { EN:'If left blank, any member can adopt this project.', IS:'Ef autt, getur hvaða félagi sem er tekið verkefnið að sér.' },
  'sauma.filterOpen':      { EN:'Open',                     IS:'Opið' },
  'sauma.filterMy':        { EN:'My Projects',              IS:'Mín verkefni' },
  'sauma.filterUnassigned':{ EN:'Unassigned',               IS:'Ótilnefnd' },
  'sauma.filterCompleted': { EN:'Completed',                IS:'Lokið' },
  'sauma.filterResolved':  { EN:'Resolved',                 IS:'Lokið' },
  'sauma.filterAll':       { EN:'All',                      IS:'Allt' },
  'sauma.needsVerkstjori': { EN:'Needs verkstjóri',         IS:'Þarf verkstjóra' },
  'sauma.emptyDefault':    { EN:'No projects match this filter.', IS:'Engin verkefni passa við þessa síu.' },
  'sauma.emptyMy':         { EN:'No projects you are involved in.', IS:'Engin verkefni sem þú tekur þátt í.' },
  'sauma.suggestBtn':      { EN:'+ New sewing circle project', IS:'+ Nýtt saumaklúbbsverkefni' },
  'sauma.suggestTitle':    { EN:'🧵 New sewing circle project', IS:'🧵 Nýtt saumaklúbbsverkefni' },
  'sauma.pendingReview':   { EN:'Pending Review',           IS:'Bíður samþykktar' },
  'sauma.approve':         { EN:'Approve',                  IS:'Samþykkja' },
  'sauma.pendingMsg':      { EN:'Project submitted for review.', IS:'Verkefni sent til samþykktar.' },
  'maint.statPending':     { EN:'PENDING REVIEW',           IS:'BÍÐUR SAMÞYKKTAR' },
  'sauma.priority':        { EN:'Priority',                 IS:'Forgangur' },
  'sauma.description':     { EN:'Description',              IS:'Lýsing' },
  'sauma.materials':       { EN:'Materials Needed',         IS:'Efni sem þarf' },
  'sauma.photoLabel':      { EN:'Photo (optional, max 5 MB)', IS:'Mynd (valfrjálst, hámark 5 MB)' },
  'nav.saumaklubbur':      { EN:'🧵 Sewing Circle',         IS:'🧵 Saumaklúbbur' },
  'staff.maintAndSauma':   { EN:'Maintenance & Projects',   IS:'Viðhald & Verkefni' },
  'staff.maintAndSaumaDesc':{ EN:'Maintenance requests & sewing circle projects', IS:'Viðhaldsbeiðnir & saumaklúbbsverkefni' },

  // ── Logbook review ─────────────────────────────────────────────────────────
  'logrev.title':          { EN:'Logbook Review',          IS:'Dagbókarskoðun' },
  'logrev.subtitle':       { EN:'Verify member trips · assign credentials', IS:'Staðfesta ferðir félaga · úthluta skírteinum' },
  'logrev.totalTrips':     { EN:'TOTAL TRIPS',             IS:'SAMTALS FERÐIR' },
  'logrev.pending':        { EN:'PENDING REVIEW',          IS:'BÍÐUR SKOÐUNAR' },
  'logrev.verified':       { EN:'VERIFIED',                IS:'STAÐFEST' },
  'logrev.verify':         { EN:'Verify',                  IS:'Staðfesta' },
  'logrev.unverify':       { EN:'Unverify',                IS:'Afstaðfesta' },
  'logrev.staffComment':   { EN:'Staff comment (optional)',IS:'Athugasemd starfsmanns (valfrjálst)' },
  'logrev.noTrips':        { EN:'No trips to review.',     IS:'Engar ferðir til skoðunar.' },
  'logrev.filterAll':      { EN:'All',                     IS:'Allt' },
  'logrev.filterPending':  { EN:'Pending',                 IS:'Í bið' },
  'logrev.filterVerified': { EN:'Verified',                IS:'Staðfest' },
  'logrev.filterName':     { EN:'Filter by name…',         IS:'Sía eftir nafni…' },
  'logrev.filterFrom':     { EN:'From',                    IS:'Frá' },
  'logrev.filterTo':       { EN:'To',                      IS:'Til' },
  'logrev.assignCert':     { EN:'ASSIGN CREDENTIAL',       IS:'ÚTHLUTA SKÍRTEINI' },
  'logrev.assignedDate':   { EN:'Assigned date',           IS:'Úthlutunardagur' },
  'logrev.expires':        { EN:'Expires',                 IS:'Rennur út' },
  'logrev.assignBtn':      { EN:'Assign',                  IS:'Úthluta' },
  'logrev.certModal':      { EN:'Credentials',             IS:'Skírteini' },
  'logrev.noCerts':        { EN:'No credentials on file.', IS:'Engin skírteini skráð.' },
  'logrev.validationRequests':    { EN:'Validation requests',                                       IS:'Beiðnir um staðfestingu'                                   },
  'logrev.showAll':               { EN:'Show all trips',                                             IS:'Sýna allar ferðir'                                         },
  'logrev.certSearch':            { EN:'Search for a member above to view their credentials.',      IS:'Leitaðu að félaga hér að ofan til að skoða skírteini.'     },
  'logrev.certSearchPlaceholder': { EN:'Search member name...',                                     IS:'Leita að nafni félaga...'   },
  'logrev.certModeByMember':      { EN:'By member',                                                 IS:'Eftir félaga'                                              },
  'logrev.certModeByType':        { EN:'By credential',                                             IS:'Eftir skírteini'                                           },
  'logrev.certSelectType':        { EN:'— Select credential —',                                     IS:'— Veldu skírteini —'                                       },
  'logrev.certNoMatches':         { EN:'No members found with this credential.',                     IS:'Engir félagar fundust með þetta skírteini.'                },
  'logrev.verifyRequest':         { EN:'VERIFICATION REQUEST',                                      IS:'STAÐFESTINGARBEIÐNI'                                       },
  
    // ── Admin panel ────────────────────────────────────────────────────────────
  'admin.tabMembers':      { EN:'Members',                 IS:'Félagar' },
  'admin.tabSettings':     { EN:'Settings',                IS:'Stillingar' },
  'admin.tabBoats':        { EN:'Boats',                   IS:'Bátar' },                               
  'admin.tabLocations':    { EN:'Locations',               IS:'Staðir' },
  'admin.tabChecklists':   { EN:'Checklists',              IS:'Gátlistar' },
  'admin.tabActTypes':     { EN:'Activity Types',          IS:'Tegundir starfsemi' },
  'admin.tabCerts':        { EN:'Credentials',             IS:'Skírteini' },
  'admin.tabAlerts':       { EN:'Alerts',                  IS:'Viðvaranir' },
  'admin.tabPayroll':      { EN:'💰 Payroll',             IS:'💰 Launakerfi' },
  'admin.tabFlags':        { EN:'🚩 Flags',                IS:'🚩 Fánar' },
  'admin.importCsv':       { EN:'⇪ Import CSV',            IS:'⇪ Flytja inn CSV' },
  'admin.searchMembers':   { EN:'Search name or kennitala…', IS:'Leita að nafni eða kennitölu…' },
  'admin.noMembers':       { EN:'No members yet.',         IS:'Engir félagar ennþá.' },
  'admin.addMember':       { EN:'+ Add member',            IS:'+ Bæta við félaga' },
  'admin.addBoat':         { EN:'+ Add boat',              IS:'+ Bæta við bát' },
  'admin.addLocation':     { EN:'+ Add location',          IS:'+ Bæta við stað' },
  'admin.addItem':         { EN:'+ Add item',              IS:'+ Bæta við atriði' },
  'admin.addType':         { EN:'+ Add type',              IS:'+ Bæta við tegund' },
  'admin.importUpdated':   { EN:'updated',                 IS:'uppfært' },
  'admin.importMissing':   { EN:'not in import',           IS:'ekki í innflutningi' },
  'admin.importUnchanged': { EN:'unchanged',               IS:'óbreytt' },
  'admin.saveChanges':     { EN:'Save changes',            IS:'Vista breytingar' },
  'admin.alertFirstMins':  { EN:'First alert after (min)', IS:'Fyrsta viðvörun eftir (mín)' },
  'admin.alertRepeatMins': { EN:'Repeat every (min)',      IS:'Endurtaka á (mín)' },
  'admin.alertSnoozeMins': { EN:'Snooze duration (min)',   IS:'Frestunarlengd (mín)' },
  'admin.alertEnabled':    { EN:'Alerts enabled',          IS:'Viðvaranir virkar' },
  'admin.flagThresholds':  { EN:'Flag thresholds',         IS:'Mörk fána' },
  'admin.windYellow':      { EN:'Wind yellow (Bft)',        IS:'Vindur gulur (Bft)' },
  'admin.windOrange':      { EN:'Wind orange (Bft)',        IS:'Vindur appelsínugulur (Bft)' },
  'admin.windRed':         { EN:'Wind red (Bft)',           IS:'Vindur rauður (Bft)' },
  'admin.waveYellow':      { EN:'Wave yellow (m)',          IS:'Bylgja gul (m)' },
  'admin.waveOrange':      { EN:'Wave orange (m)',          IS:'Bylgja appelsínugul (m)' },
  'admin.waveRed':         { EN:'Wave red (m)',             IS:'Bylgja rauð (m)' },
  'admin.memberModal.add': { EN:'Add Member',              IS:'Bæta við félaga' },
  'admin.memberModal.edit':{ EN:'Edit Member',             IS:'Breyta félaga' },
  'admin.fullName':        { EN:'Full name',               IS:'Fullt nafn' },
  'admin.birthYear':       { EN:'Birth year',              IS:'Fæðingarár' },
  'admin.isMinor':         { EN:'Minor (under 18)',        IS:'Barn (undir 18)' },
  'admin.guardianSection': { EN:'GUARDIAN / PARENT',       IS:'FORRÁÐAMAÐUR / FORELDRI' },
  'admin.guardianName':    { EN:'Guardian name',           IS:'Nafn forráðamanns' },
  'admin.guardianPhone':   { EN:'Guardian phone',          IS:'Sími forráðamanns' },
  'admin.guardianKt':      { EN:'Guardian kennitala',      IS:'Kennitala forráðamanns' },
  'admin.boatModal.add':   { EN:'Add Boat',                IS:'Bæta við bát' },
  'admin.boatModal.edit':  { EN:'Edit Boat',               IS:'Breyta bát' },
  'admin.boatName':        { EN:'Boat name',               IS:'Nafn báts' },
  'admin.boatCategory':    { EN:'Category',                IS:'Flokkur' },
  'admin.boatOos':         { EN:'Out of service',          IS:'Utan þjónustu' },
  'admin.boatOosReason':   { EN:'OOS reason',              IS:'Ástæða OOS' },
  'admin.locModal.add':    { EN:'Add Location',            IS:'Bæta við stað' },
  'admin.locModal.edit':   { EN:'Edit Location',           IS:'Breyta stað' },
  'admin.clPhase':         { EN:'Phase',                   IS:'Fasi' },
  'admin.clPhaseAm':       { EN:'AM',                      IS:'AM' },
  'admin.clPhasePm':       { EN:'PM',                      IS:'PM' },
  'admin.clTextEN':        { EN:'Text (EN)',                IS:'Texti (EN)' },
  'admin.clTextIS':        { EN:'Text (IS)',                IS:'Texti (IS)' },
  'admin.actTypeEN':       { EN:'Name (EN)',                IS:'Nafn (EN)' },
  'admin.actTypeIS':       { EN:'Name (IS)',                IS:'Nafn (IS)' },
  'admin.certName':           { EN:'Cert name (EN)',              IS:'Nafn skírteinis (EN)' },
  'admin.certRenewal':        { EN:'Renewal (days, 0 = permanent)', IS:'Endurnýjun (dagar, 0 = varanlegt)' },
  'admin.certTypes':          { EN:'CREDENTIAL TYPES',            IS:'TEGUNDIR SKÍRTEINA' },
  'admin.certAssign':         { EN:'ASSIGN CREDENTIALS',          IS:'ÚTHLUTA SKÍRTEINUM' },
  'admin.certAddType':        { EN:'+ Add credential type',       IS:'+ Bæta við tegund skírteinis' },
  'admin.certAddModal':       { EN:'Add Credential Type',         IS:'Bæta við tegund skírteinis' },
  'admin.certEditModal':      { EN:'Edit Credential Type',        IS:'Breyta tegund skírteinis' },
  'admin.certDesc':           { EN:'Description',                 IS:'Lýsing' },
  'admin.certDescOptional':   { EN:'(optional)',                  IS:'(valfrjálst)' },
  'admin.certRenewalPerm':    { EN:'Permanent',                   IS:'Varanlegt' },
  'admin.certRenewalAnnual':  { EN:'Annual (365 days)',           IS:'Árlegt (365 dagar)' },
  'admin.certRenewalBiennial':{ EN:'Biennial (730 days)',         IS:'Annað hvert ár (730 dagar)' },
  'admin.certRenewalCustom':  { EN:'Custom…',                    IS:'Sérsniðið…' },
  'admin.certDaysUntilExpiry':{ EN:'Days until expiry',          IS:'Dagar þar til rennur út' },
  'admin.certSearchMember':   { EN:'Search member…',             IS:'Leita að félaga…' },
  'admin.certAllTypes':       { EN:'All cert types',             IS:'Allar tegundir skírteina' },
  'admin.noBoats':         { EN:'No boats.',               IS:'Engir bátar.' },
  'admin.noLocations':     { EN:'No locations.',           IS:'Engir staðir.' },
  'admin.backToList':      { EN:'← Back to list',          IS:'← Aftur á lista' },
  'admin.importFromCsv':   { EN:'Import from Abler.io CSV', IS:'Flytja inn úr Abler.io CSV' },

  // ── Certifications ─────────────────────────────────────────────────────────
  'cert.noCerts':              { EN:'No credentials on file.',          IS:'Engin skírteini skráð.' },
  'cert.assignedBy':           { EN:'Assigned by',                      IS:'Úthlutað af' },
  'cert.assignedAt':           { EN:'Assigned',                         IS:'Úthlutað' },
  'cert.expires':              { EN:'Expires',                          IS:'Rennur út' },
  'cert.expired':              { EN:'Expired',                          IS:'Útrunnið' },
  'cert.permanent':            { EN:'Does not expire',                  IS:'Varanlegt' },
  'cert.level':                { EN:'Level / Subcategory',              IS:'Stig / Undirflokkur' },
  'cert.assign':               { EN:'Assign',                           IS:'Úthluta' },
  'cert.remove':               { EN:'Remove',                           IS:'Fjarlægja' },
  'cert.issuingAuthority':     { EN:'Issuing Authority',                IS:'Útgefandi' },
  'cert.renewalDays':          { EN:'Renewal (days)',                   IS:'Endurnýjun (dagar)' },
  'cert.renewalOverride':      { EN:'Renewal (days, overrides parent)', IS:'Endurnýjun (dagar, hnekkir yfirflokki)' },
  'cert.fixedExpiry':          { EN:'Fixed Expiry Date',                IS:'Föst lokadagsetning' },
  'cert.fixedExpiryOverride':  { EN:'Fixed Expiry Date (overrides renewal)', IS:'Föst lokadagsetning (hnekkir endurnýjun)' },
  'cert.subcats':              { EN:'Subcategories',                    IS:'Undirflokkar' },
  'cert.subcatHint':           { EN:'Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce "higher replaces lower" logic. Per-subtype issuing authority, renewal days, or a fixed expiry date will override the parent values.',
                                  IS:'Bættu við undirflokkum ef skírteinið hefur stig (t.d. Stig 1, 2, 3). Stilltu röð til að framfylgja „hærra kemur í stað lægra" rök. Útgefandi, endurnýjunardagar eða föst lokadagsetning á undirflokki hnekkir gildum yfirflokksins.' },
  'cert.noSubcats':            { EN:'No subcategories',                 IS:'Engir undirflokkar' },
  'cert.subcatLabel':          { EN:'Label (e.g. Level 1)',             IS:'Merking (t.d. Stig 1)' },
  'cert.subcatDesc':           { EN:'Description',                      IS:'Lýsing' },
  'cert.subcatRank':           { EN:'Rank',                             IS:'Röð' },
  'cert.rankHint':             { EN:'Rank (higher replaces lower on assign)', IS:'Röð (hærra kemur í stað lægra við úthlutun)' },
  'cert.cardColour':           { EN:'Card colour',                      IS:'Litur korts' },
  'cert.colourAuto':           { EN:'auto if blank',                    IS:'sjálfvirkt ef autt' },
  'cert.deleteConfirm':        { EN:"Delete this credential type? This won't remove existing assignments.", IS:'Eyða þessari tegund skírteinis? Þetta mun ekki fjarlægja fyrirliggjandi úthlutanir.' },
  'cert.deleteSubConfirm':     { EN:'Remove this subtype?',             IS:'Fjarlægja þennan undirflokk?' },
  'cert.saved':                { EN:'Credential type saved.',           IS:'Tegund skírteinis vistuð.' },
  'cert.deleted':              { EN:'Credential type deleted.',         IS:'Tegund skírteinis eytt.' },
  'cert.assigned':             { EN:'Credential assigned.',             IS:'Skírteini úthlutað.' },
  'cert.removed':              { EN:'Credential removed.',              IS:'Skírteini fjarlægt.' },
  'cert.nameRequired':         { EN:'Name required.',                   IS:'Nafn vantar.' },
  'cert.typeRequired':         { EN:'Select a credential type.',        IS:'Veldu tegund skírteinis.' },
  'cert.levelRequired':        { EN:'Select a level / subcategory.',    IS:'Veldu stig / undirflokk.' },
  'cert.clubEndorsements':     { EN:'CLUB ENDORSEMENTS',                IS:'ÁRITANIR KLÚBBSINS' },
  'cert.loadError':            { EN:'Could not load credentials.',      IS:'Gat ekki hlaðið skírteinum.' },
  
  // ── Payroll — tab labels (renamed) ──────────────────────────────────────────
  'payroll.tabTimeReporting': { EN:'Time Reporting', IS:'Tímaskráning' },
  'payroll.tabTimesheets':    { EN:'Timesheets / Payslips', IS:'Launaseðlar' },
  'payroll.tabEmployees':     { EN:'Employees', IS:'Starfsmenn' },
  'payroll.tabLaunamidlar':   { EN:'Export Data', IS:'Útflutningur' },

  // ── Payroll — period & approval flow ────────────────────────────────────────
  'payroll.definePeriod':      { EN:'Define Pay Period', IS:'Skilgreina launatímabil' },
  'payroll.periodFrom':        { EN:'From', IS:'Frá' },
  'payroll.periodTo':          { EN:'To', IS:'Til' },
  'payroll.previewPayslips':   { EN:'Preview Payslips', IS:'Forskoða launaseðla' },
  'payroll.approvePeriod':     { EN:'Approve & Close Period', IS:'Samþykkja og loka tímabili' },
  'payroll.approveConfirm':    { EN:'Approve payslips for all employees and close this period?', IS:'Samþykkja launaseðla allra starfsmanna og loka þessu tímabili?' },
  'payroll.periodClosed':      { EN:'Period closed ✓', IS:'Tímabili lokað ✓' },
  'payroll.exportPdf':         { EN:'Export PDF', IS:'Sækja PDF' },
  'payroll.exportXml':         { EN:'Export XML', IS:'Sækja XML' },
  'payroll.noPeriodDefined':   { EN:'No pay period defined yet.', IS:'Ekkert launatímabil skilgreint enn.' },
  'payroll.noClosedPeriods':   { EN:'No closed periods yet.', IS:'Engin lokuð tímabil enn.' },
  'payroll.hoursFromSheets':   { EN:'Hours from timesheets', IS:'Tímar úr tímaskráningu' },
  'payroll.hoursConfirm':      { EN:'Confirm hours before approving', IS:'Staðfestu tíma áður en samþykkt er' },
  'payroll.manualLines':       { EN:'Manual line items', IS:'Handvirðar línur' },
  'payroll.addLine':           { EN:'+ Add line', IS:'+ Bæta við línu' },
  'payroll.lineDescription':   { EN:'Description', IS:'Lýsing' },
  'payroll.lineDescriptionIS': { EN:'Description (IS)', IS:'Lýsing (IS)' },
  'payroll.lineAmount':        { EN:'Amount (kr)', IS:'Upphæð (kr)' },
  'payroll.regularHours':      { EN:'Regular hours', IS:'Dagvinna (klst)' },
  'payroll.ot1Hours':          { EN:'Overtime 1.33×', IS:'Eftirvinna 1,33' },
  'payroll.ot2Hours':          { EN:'Overtime 1.55×', IS:'Eftirvinna 1,55' },
  'payroll.correctedHours':    { EN:'Corrected hours', IS:'Leiðréttir tímar' },
  'payroll.hoursNote':         { EN:'Note / reason for correction', IS:'Athugasemd / ástæða leiðréttingar' },
  'payroll.confirmHours':      { EN:'Confirm hours', IS:'Staðfesta tíma' },
  'payroll.periodApproved':    { EN:'Approved', IS:'Samþykkt' },
  'payroll.periodOpen':        { EN:'Open', IS:'Opið' },
  'payroll.periodLabel':       { EN:'Pay period', IS:'Launatímabil' },
  'payroll.employeeCount':     { EN:'{n} employees', IS:'{n} starfsmenn' },
  'payroll.grossLabel':        { EN:'Gross', IS:'Heildarlaun' },
  'payroll.netLabel':          { EN:'Net', IS:'Útborgun' },
  'payroll.paymentDate':       { EN:'Payment date', IS:'Greiðsludagur' },
  'payroll.slipNumber':        { EN:'Slip no.', IS:'Seðilnúmer' },
  'payroll.personuafslattr':   { EN:'Personal tax credit (kr/month)', IS:'Persónuafsláttur (kr/mán.)' },
  'payroll.personuafslattrPct':{ EN:'% of standard credit used here', IS:'% af staðlaðri upphæð hér' },
  'payroll.configTitle':       { EN:'Payroll Config', IS:'Stillingar launakerfis' },
  'payroll.ot1Rate':           { EN:'Overtime tier 1 multiplier', IS:'Eftirvinna þrep 1 margfaldari' },
  'payroll.ot2Rate':           { EN:'Overtime tier 2 multiplier', IS:'Eftirvinna þrep 2 margfaldari' },
  'payroll.orlofsRate':        { EN:'Holiday pay rate', IS:'Orlofslaun hlutfall' },
  'payroll.empPensionRate':    { EN:'Employee pension %', IS:'Lífeyrissjóður starfsmann %' },
  'payroll.emplPensionRate':   { EN:'Employer pension %', IS:'Mótframlag lífeyrissjóður %' },
  'payroll.taxBracket1':       { EN:'Tax bracket 1 rate (up to 583,854 kr)', IS:'Skattstigi 1 (upp að 583.854 kr)' },
  'payroll.taxBracket2':       { EN:'Tax bracket 2 rate (up to 1,645,733 kr)', IS:'Skattstigi 2 (upp að 1.645.733 kr)' },
  'payroll.taxBracket3':       { EN:'Tax bracket 3 rate', IS:'Skattstigi 3' },
  'payroll.unionDuesRate':     { EN:'Union dues rate', IS:'Stéttarfélagsgjald hlutfall' },
  'payroll.hoursTotal':        { EN:'Total hours', IS:'Heildartímar' },
  'payroll.editEntry':         { EN:'Edit', IS:'Breyta' },
  'payroll.notEnabled':        { EN:'Not in payroll', IS:'Ekki í launakerfi' },
  'payroll.enablePayroll':     { EN:'Enable payroll', IS:'Virkja í launakerfi' },
  'payroll.calView':           { EN:'Calendar',            IS:'Dagatal' },
  'payroll.listView':          { EN:'List',                IS:'Listi' },
  'payroll.addEntry':          { EN:'+ Add entry',         IS:'+ Bæta við færslu' },
  'payroll.deleteEntry':       { EN:'Delete',              IS:'Eyða' },
  'payroll.deleteConfirm':     { EN:'Delete this time entry?', IS:'Eyða þessari tímafærslu?' },
  'payroll.allStaff':          { EN:'All staff',           IS:'Allir starfsmenn' },
  'payroll.employee':          { EN:'Employee',            IS:'Starfsmaður' },
  'payroll.totalHours':        { EN:'total',               IS:'samtals' },
  'payroll.clockInLabel':      { EN:'Clock in',            IS:'Stimpla inn' },
  'payroll.clockOutLabel':     { EN:'Clock out',           IS:'Stimpla út' },
  'payroll.minsLabel':         { EN:'Duration (minutes)',  IS:'Tímalengd (mínútur)' },
  'payroll.noteOptional':      { EN:'Note (optional)',     IS:'Athugasemd (valfrjálst)' },
  'payroll.notePlaceholder':   { EN:'e.g. forgotten punch-in', IS:'t.d. gleymt innstimpl' },
  'payroll.autoCalc':          { EN:'auto-calculated, override if needed', IS:'reiknast sjálft, hnekktu ef þarf' },
  'payroll.entryRequired':  { EN:'Employee, clock-in and clock-out are required.', IS:'Starfsma\u00f0ur, innstimplun og \u00fatstimplun eru nauðsynleg.' },
  'payroll.clockOutAfterIn':{ EN:'Clock-out must be after clock-in.', IS:'\u00datstimplun ver\u00f0ur a\u00f0 vera eftir innstimplun.' },
  'payroll.moreEntries':    { EN:'more',                        IS:'\u00ed vi\u00f0b\u00f3t' },
  'payroll.pastPeriods':    { EN:'Past periods',                IS:'Fyrri t\u00edmabil' },
  'payroll.titleField':     { EN:'Title',                       IS:'Starfsheiti' },
  'payroll.bankAccount':    { EN:'Bank account',                IS:'Launareikningur' },
  'payroll.orlofsreikningur':{ EN:'Holiday account',           IS:'Orlofsreikningur' },
  'payroll.union':          { EN:'Union',                       IS:'St\u00e9ttarf\u00e9lag' },
  'payroll.sereignRate':    { EN:'Private pension %',           IS:'S\u00e9reign %' },
  'payroll.pension':        { EN:'Pension',                     IS:'L\u00edfeyrissjó\u00f0ur' },
  'lbl.year':               { EN:'Year',                        IS:'\u00c1r' },
  'lbl.duration':           { EN:'Duration',                    IS:'T\u00edmal\u00e6ngd' },
  'lbl.edited':             { EN:'edited',                      IS:'breytt' },
  'lbl.view':               { EN:'View',                        IS:'Sj\u00e1' },
  'lbl.admin':              { EN:'admin',                       IS:'stjórnandi' },
  'lbl.staff':              { EN:'staff',                       IS:'starfsma\u00f0ur' },
  'lbl.monShort':           { EN:'Mon',                         IS:'M\u00e1n' },
  'lbl.tueShort':           { EN:'Tue',                         IS:'\u00deri' },
  'lbl.wedShort':           { EN:'Wed',                         IS:'Mi\u00f0' },
  'lbl.thuShort':           { EN:'Thu',                         IS:'Fim' },
  'lbl.friShort':           { EN:'Fri',                         IS:'F\u00f6s' },
  'lbl.satShort':           { EN:'Sat',                         IS:'Lau' },
  'lbl.sunShort':           { EN:'Sun',                         IS:'Sun' },
  'payroll.earningsSection':   { EN:'Earnings',          IS:'Laun' },
  'payroll.deductionsSection': { EN:'Deductions',        IS:'Fr\u00e1dr\u00e1ttur' },
  'payroll.accumulatedSection':{ EN:'Accumulated',       IS:'Til uppsafnanar' },
  'payroll.employerSection':   { EN:'Employer contribution', IS:'Framlag launagrei\u00f0anda' },
  'payroll.ytdSection':        { EN:'Year to date',      IS:'\u00c1r til \u00fea gs' },
  'payroll.totalDeductions':   { EN:'Total deductions',  IS:'Heildarf r\u00e1dr\u00e1ttur' },
  'payroll.orlofslaun':        { EN:'Holiday pay (bank)',IS:'Orlof \u00ed banka' },
  'payroll.payslip':           { EN:'Payslip',           IS:'Launase\u00f0ill' },
  'payroll.baseRate':          { EN:'Base rate (kr/hr)', IS:'Grunntaxti (kr/klst)' },
  'payroll.dagvinna':            { EN:'Regular time',           IS:'Dagvinna' },
  'payroll.ot1Label':            { EN:'Overtime 1.33\u00d7',    IS:'Eftirvinna 1,33' },
  'payroll.ot2Label':            { EN:'Overtime 1.55\u00d7',    IS:'Eftirvinna 1,55' },
  'payroll.units':               { EN:'Units',                  IS:'Einingar' },
  'payroll.rate':                { EN:'Rate',                   IS:'Taxti' },
  'payroll.amount':              { EN:'Amount',                 IS:'Upph\u00e6\u00f0' },
  'payroll.ytdUnits':            { EN:'YTD units',              IS:'Einingar (\u00e1r)' },
  'payroll.taxComputed':         { EN:'Computed tax',           IS:'Reiknuð sta\u00f0greiðsla' },
  'payroll.employerPension':     { EN:'Employer pension',       IS:'M\u00f3tframlag l\u00edfeyriss' },
  'payroll.endurhaefingarsjodur':{ EN:'Rehabilitation fund',    IS:'Endurhæfingarsj\u00f3\u00f0ur' },
  'payroll.now':                 { EN:'Now',                    IS:'N\u00fa' },
  'payroll.config': { EN:'Config',                         IS:'Stillingar' },
  'payroll.configPayroll': { EN:'Payroll settings',               IS:'Launastillingar' },
  'payroll.pensionFunds': { EN:'Pension funds',                  IS:'Lífeyrissjóðir' },
  'payroll.addFund': { EN:'Add fund',                       IS:'Bæta við sjóði' },
  'payroll.fundName': { EN:'Fund name',                      IS:'Heiti sjóðs' },
  'payroll.fundNameEN': { EN:'Fund name (EN)',                  IS:'Heiti sjóðs (EN)' },
  'payroll.unions': { EN:'Unions',                         IS:'Stéttarfélög' },
  'payroll.addUnion': { EN:'Add union',                      IS:'Bæta við félagi' },
  'payroll.unionName': { EN:'Union name',                     IS:'Heiti félags' },
  'payroll.deductionLines': { EN:'Deduction lines',                IS:'Frádráttsliðir' },
  'payroll.lineLabel': { EN:'Label',                          IS:'Heiti' },
  'payroll.lineLabelEN': { EN:'Label (EN)',                     IS:'Heiti (EN)' },
  'payroll.empRate': { EN:'Employee %',                     IS:'Starfsmaður %' },
  'payroll.emprRate': { EN:'Employer %',                     IS:'Launagreiðandi %' },
  'payroll.otRules': { EN:'Overtime rules',                 IS:'Yfirvinnureglur' },
  'payroll.otEligible': { EN:'Overtime eligible',              IS:'Réttindi til yfirvinnu' },
  'payroll.otPeriods': { EN:'OT periods',                     IS:'Yfirvinnuterúr' },
  'payroll.otDays': { EN:'Days (0=Sun…6=Sat)',         IS:'Dagar (0=Sun…6=Lau)' },
  'payroll.otFrom': { EN:'From hour',                      IS:'Frá klukkustund' },
  'payroll.otTo': { EN:'To hour',                        IS:'Að klukkustund' },
  'payroll.otMultiplier': { EN:'Multiplier',                     IS:'Margfaldari' },
  'payroll.personuafslattrUnit': { EN:'Personal credit unit (kr = 1.0)', IS:'Persónuafsláttur eining (kr = 1,0)' },
  'payroll.personuafslattrFrac': { EN:'Personal credit (fraction)',     IS:'Hlutfall persónuafsláttar' },
  'payroll.pensionFundIds': { EN:'Pension fund(s)',                IS:'Lífeyrissjóður' },
  'payroll.unionId': { EN:'Union',                          IS:'Stéttarfélag' },
  'payroll.none': { EN:'None',                           IS:'Ekkert' },
  // ── Payroll config & new UI keys added 2026-03-27
  'payroll.personuafslattrFraction': { EN:'Personal credit fraction',     IS:'Hlutfall persónuafsláttar' },

  // ── Payroll — punch clock section label (was missing, caused raw key display)
  'payroll.section':           { EN:'TIME CLOCK',                     IS:'STIMPILKLUKKA' },

  // ── Payroll — dynamic OT tiers
  'payroll.otTierLabel':       { EN:'Label',                          IS:'Heiti' },
  'payroll.otTierLabelEN':     { EN:'Label (EN)',                     IS:'Heiti (EN)' },
  'payroll.addOTTier':         { EN:'+ Add OT tier',                  IS:'+ Bæta við yfirvinnuþrepi' },
  'payroll.deleteOTTier':      { EN:'Remove',                         IS:'Fjarlægja' },

  // ── Payroll — tax brackets (dynamic)
  'payroll.taxBrackets':       { EN:'Tax brackets',                   IS:'Skattþrep' },
  'payroll.taxBracketUpTo':    { EN:'Up to (kr)',                     IS:'Upp að (kr)' },
  'payroll.taxBracketRate':    { EN:'Rate (%)',                       IS:'Hlutfall (%)' },
  'payroll.taxBracketUnlimited':{ EN:'∞ (top bracket)',              IS:'∞ (hæsta þrep)' },
  'payroll.addTaxBracket':     { EN:'+ Add bracket',                  IS:'+ Bæta við þrepi' },

  // ── Payroll — export data tab
  'payroll.tabExportData':     { EN:'Export Data',                    IS:'Útflutningur' },
  'payroll.exportWithholding': { EN:'XML — Withholding',                IS:'XML — Staðgreiðsla' },
  'payroll.exportPayslipXml':  { EN:'XML — Payslip data',             IS:'XML — Launaseðlagögn' },
  'payroll.exportPensionCsv':  { EN:'CSV — Pension data',             IS:'CSV — Lífeyrissjóðsgögn' },
  'payroll.exportLaunamidlar': { EN:'XML — Launamiðlar',              IS:'XML — Launamiðlar' },
  'payroll.exportPlaceholder': { EN:'Not yet implemented — coming soon', IS:'Ekki tilbúið — kemur bráðlega' },
  'payroll.selectPeriod':      { EN:'— Select period —',                 IS:'— Velja tímabil —' },
  'payroll.exportCsv':         { EN:'Export CSV',                        IS:'Sækja CSV' },
  'payroll.stadEmployerInfo':  { EN:'Employer info — Withholding',        IS:'Upplýsingar um launagreiðanda — Staðgreiðsla' },
  'payroll.stadKt':            { EN:'Employer kennitala',                 IS:'Kennitala launagreiðanda' },
  'payroll.stadEmail':         { EN:'Contact email',                      IS:'Tölvupóstfang' },
  'payroll.stadVeflykill':     { EN:'Web key',                            IS:'Veflykill' },
  'payroll.stadForrit':        { EN:'Software ID',                        IS:'Kerfisheiti' },
  'payroll.stadIsat':          { EN:'Industry code (ISAT 2008)',          IS:'Atvinnuvegaflokkun (ISAT 2008)' },
  'payroll.stadKtRequired':    { EN:'Employer kennitala is required',     IS:'Kennitala launagreiðanda vantar' },
  'payroll.starfshlutfall':    { EN:'Employment %',                       IS:'Starfshlutfall (%)' },
  'payroll.istarf95':          { EN:'Job code',                           IS:'Starfaflokkun' },
  'payroll.taxWithheld':       { EN:'Tax withheld',                   IS:'Staðgreiðsla' },
  // ── Punch clock widget ──────────────────────────────────────────────────────
  'payroll.clockIn':           { EN:'Clock In',              IS:'Stimpla inn' },
  'payroll.clockOut':          { EN:'Clock Out',             IS:'Stimpla út' },
  'payroll.startBreak':        { EN:'Start Break',           IS:'Fara í hlé' },
  'payroll.endBreak':          { EN:'End Break',             IS:'Ljúka hlé' },
  'payroll.currentShift':      { EN:'On shift',              IS:'Á vakt' },
  'payroll.onBreak':           { EN:'On break since',        IS:'Í hléi síðan' },
  'payroll.clockedInAt':       { EN:'Clocked in at',         IS:'Stimplaðist inn' },
  'payroll.recentShifts':      { EN:'Recent shifts',         IS:'Nýlegar vaktir' },
  'payroll.noShifts':          { EN:'No shifts logged yet',  IS:'Engar vaktir skráðar' },
  'payroll.shiftSummary':      { EN:'Shift summary',         IS:'Samantekt vaktar' },
  'payroll.totalWorked':       { EN:'Total worked',          IS:'Vann samtals' },
  'payroll.totalBreak':        { EN:'Total break',           IS:'Hlé samtals' },
  'payroll.confirmShift':      { EN:'Done',                  IS:'Loka' },
  'payroll.editEntry':         { EN:'Edit',                  IS:'Breyta' },
  'payroll.allowBreaks':       { EN:'Allow break logging',   IS:'Leyfa hléaskráningu' },

  // ── Keelboat / logbook expanded (Phase 1) ──────────────────────────────────
  'logbook.distanceNm':      { EN:'Distance (nm)',                         IS:'Vegalengd (sjómílur)' },
  'logbook.departurePort':   { EN:'Departure port',                        IS:'Brottfararstaður' },
  'logbook.arrivalPort':     { EN:'Arrival port',                          IS:'Komustaður' },
  'logbook.portsOptional':   { EN:'Ports — optional',                      IS:'Höfnar — valfrjálst' },
  'logbook.addPort':         { EN:'+ Add "{name}" to ports list',          IS:'+ Bæta „{name}" við höfnalista' },
  'logbook.gpsTrack':        { EN:'GPS Track — GPX / KML / KMZ',           IS:'GPS-leið — GPX / KML / KMZ' },
  'logbook.photos':          { EN:'Photos',                                IS:'Myndir' },
  'logbook.trackReady':      { EN:'Ready: {name}',                         IS:'Tilbúið: {name}' },
  'logbook.trackAttached':   { EN:'📍 GPS track',                          IS:'📍 GPS-leið' },
  'logbook.portSame':        { EN:'⚓️ {port}',                             IS:'⚓️ {port}' },
  'logbook.portRoute':       { EN:'⚓️ {from} → {to}',                      IS:'⚓️ {from} → {to}' },
  'logbook.noDriveConfig':   { EN:'File upload not configured — trip saved without attachment.',
                               IS:'Skráarupphal ekki stillt — ferð vistuð án viðhengis.' },
  'boat.registrationNo':     { EN:'Registration no.',                      IS:'Skráningarnúmer' },
  'boat.sailNo':             { EN:'Sail no.',                              IS:'Seglnúmer' },
  'boat.loa':                { EN:'LOA (ft)',                              IS:'Heildarlengd (fet)' },
  'boat.typeModel':          { EN:'Type / model',                          IS:'Tegund / gerð' },
  'boat.defaultPort':        { EN:'Default port',                          IS:'Heimahöfn' },
  'location.type':           { EN:'Type',                                  IS:'Tegund' },
  'location.typePort':       { EN:'Port',                                  IS:'Höfn' },
  'location.typeLocation':   { EN:'Sailing area',                          IS:'Siglingasvæði' },
  'location.lat':            { EN:'Latitude',                              IS:'Breiddargráða' },
  'location.lng':            { EN:'Longitude',                             IS:'Lengdargráða' },

  // ── Fleet card badges & labels ─────────────────────────────────────────────
  'fleet.badgeAvail':        { EN:'AVAIL',                                 IS:'LAUST' },
  'fleet.badgeOut':          { EN:'OUT',                                   IS:'ÚTI' },
  'fleet.badgeOverdue':      { EN:'OVERDUE',                               IS:'TÍMABÆRT' },
  'fleet.badgeOos':          { EN:'OOS',                                   IS:'ÓTÆ.' },
  'fleet.badgeYours':        { EN:'YOURS',                                 IS:'ÞITT' },
  'fleet.aboard':            { EN:'{n} aboard',                            IS:'{n} um borð' },
  'fleet.outTime':           { EN:'Out {t}',                               IS:'Út {t}' },
  'fleet.checkIn':           { EN:'Check In',                              IS:'Skrá inn' },
  'fleet.delete':            { EN:'Delete',                                IS:'Eyða' },
  'fleet.badgeChartered':    { EN:'CHARTERED',                             IS:'LEIGÐUR' },
  'fleet.badgePrivate':      { EN:'PRIVATE',                               IS:'EINKABÁTUR' },
  'fleet.charteredTo':       { EN:'Chartered to {name}',                   IS:'Leigður til {name}' },
  'fleet.charteredUntil':    { EN:'until {date}',                          IS:'til {date}' },
  'fleet.ownedBy':           { EN:'Owner: {name}',                         IS:'Eigandi: {name}' },
  'fleet.charterOverride':   { EN:'This boat is chartered to {name} until {date}. Override and check out anyway?',
                               IS:'Þessi bátur er leigður til {name} til {date}. Viltu taka hann út samt?' },

  // ── Boat ownership & charter ──────────────────────────────────────────────
  'boat.ownership':          { EN:'Ownership',                             IS:'Eignarhald' },
  'boat.ownershipClub':      { EN:'Club boat',                             IS:'Klúbbsbátur' },
  'boat.ownershipPrivate':   { EN:'Private boat',                          IS:'Einkabátur' },
  'boat.owner':              { EN:'Owner',                                 IS:'Eigandi' },
  'boat.charter':            { EN:'Charter',                               IS:'Leiga' },
  'boat.charterMember':      { EN:'Chartered to',                          IS:'Leigður til' },
  'boat.charterStart':       { EN:'Start date',                            IS:'Upphafsdagur' },
  'boat.charterEnd':         { EN:'End date',                              IS:'Lokadagur' },
  'boat.setCharter':         { EN:'Set Charter',                           IS:'Skrá leigu' },
  'boat.removeCharter':      { EN:'Remove Charter',                        IS:'Fjarlægja leigu' },
  'boat.charterSaved':       { EN:'Charter saved',                         IS:'Leiga vistuð' },
  'boat.charterRemoved':     { EN:'Charter removed',                       IS:'Leiga fjarlægð' },

  // ── Public dashboard ──────────────────────────────────────────────────────
  'pub.dash.title':          { EN:'Club Dashboard',                        IS:'Yfirlit klúbbs' },
  'pub.dash.subtitle':       { EN:'Siglingafélagið Ýmir',                  IS:'Siglingafélagið Ýmir' },
  'pub.dash.season':         { EN:'{year} Season',                         IS:'Tímabil {year}' },
  'pub.dash.ytdTrips':       { EN:'Trips This Season',                     IS:'Siglingar á tímabilinu' },
  'pub.dash.totalHours':     { EN:'Hours Sailed',                          IS:'Klukkustundir á sjó' },
  'pub.dash.byCategory':     { EN:'By Boat Type',                          IS:'Eftir bátategund' },
  'pub.dash.locations':      { EN:'Where We Sail',                         IS:'Hvar við siglum' },
  'pub.dash.onWater':        { EN:'On the Water Now',                      IS:'Á sjónum núna' },
  'pub.dash.boats':          { EN:'Boats Out',                             IS:'Bátar úti' },
  'pub.dash.people':         { EN:'People',                                IS:'Fólk' },
  'pub.dash.captains':       { EN:'Our Captains',                          IS:'Skipstjórar okkar' },
  'pub.dash.viewRecord':     { EN:'View Sailing Record →',                 IS:'Skoða siglingaskrá →' },
  'pub.dash.noCaptains':     { EN:'No captains registered yet.',           IS:'Engir skipstjórar skráðir ennþá.' },
  'pub.dash.noActivity':     { EN:'No boats on the water right now.',      IS:'Engir bátar á sjónum núna.' },
  'pub.dash.trips':          { EN:'trips',                                 IS:'siglingar' },
  'pub.dash.hrs':            { EN:'hrs',                                   IS:'klst' },
  'pub.dash.bio':            { EN:'Captain at Siglingafélagið Ýmir. Bio coming soon.',
                               IS:'Skipstjóri hjá Siglingafélaginu Ými. Ævisaga í vinnslu.' },
  'pub.dash.loading':        { EN:'Loading dashboard…',                    IS:'Hleður yfirliti…' },
  'pub.dash.error':          { EN:'Could not load dashboard data.',        IS:'Gat ekki hlaðið yfirlitsgögnum.' },
  'pub.dash.lastUpdated':    { EN:'Last updated',                          IS:'Síðast uppfært' },
  'pub.dash.tripCount':      { EN:'{n} trips',                             IS:'{n} siglingar' },
  'pub.dash.hourCount':      { EN:'{n} hrs',                               IS:'{n} klst' },
  'pub.dash.conditions':     { EN:'Conditions & Status',                    IS:'Aðstæður og staða' },
  'pub.dash.weather':        { EN:'Weather & Tides',                        IS:'Veður og sjávarföll' },
  'pub.dash.boatsOut':       { EN:'Boats Out',                              IS:'Bátar úti' },
  'pub.dash.captainData':    { EN:'Captain Data',                           IS:'Skipstjóragögn' },
  'pub.dash.captainSoon':    { EN:'Captain profiles and statistics will appear here soon.', IS:'Upplýsingar um skipstjóra og tölfræði birtast hér fljótlega.' },
  'pub.dash.comingSoon':     { EN:'More information coming soon.',          IS:'Frekari upplýsingar birtast fljótlega.' },

  // ── Admin — CSV import & modals ─────────────────────────────────────────────
  'admin.expectedColumns':   { EN:'EXPECTED COLUMNS',                    IS:'VÆNTIR DÁLKAR' },
  'admin.colName':           { EN:'Full name (required)',                IS:'Fullt nafn (áskilið)' },
  'admin.colKt':             { EN:'10-digit ID (required)',             IS:'10 stafa kennitala (áskilið)' },
  'admin.colEmail':          { EN:'Email address',                      IS:'Netfang' },
  'admin.colPhone':          { EN:'Phone number',                       IS:'Símanúmer' },
  'admin.colDob':            { EN:'Date of birth (YYYY-MM-DD)',         IS:'Fæðingardagur (ÁÁÁÁ-MM-DD)' },
  'admin.colMemberType':     { EN:'e.g. full, junior, family',          IS:'t.d. full, junior, family' },
  'admin.csvDrop':           { EN:'Drop CSV here or click to browse',   IS:'Dragðu CSV hingað eða smelltu' },
  'admin.csvEncoding':       { EN:'UTF-8 encoded, comma or semicolon delimited', IS:'UTF-8, kommu- eða semíkommuaðskilið' },
  'admin.reviewImport':      { EN:'Review import',                      IS:'Yfirfara innflutning' },
  'admin.rolesNeverOverwritten': { EN:'Admin/staff roles never overwritten.', IS:'Stjórnanda-/starfsmannahlutverk aldrei yfirskrifuð.' },
  'admin.confirmImport':     { EN:'Confirm import',                     IS:'Staðfesta innflutning' },
  'admin.importAnother':     { EN:'Import another',                     IS:'Flytja inn annað' },
  'admin.viewMembers':       { EN:'View members',                       IS:'Sjá félaga' },
  'admin.addCategory':       { EN:'+ Add category',                     IS:'+ Bæta við flokki' },
  'admin.preLaunchLanding':  { EN:'PRE-LAUNCH & LANDING CHECKLISTS (per category)', IS:'SJÓSETNINGAR- OG LENDINGARLISTAR (eftir flokki)' },
  'admin.launch':            { EN:'LAUNCH',                             IS:'SJÓSETNING' },
  'admin.landing':           { EN:'LANDING',                            IS:'LENDING' },
  'admin.actTypesTitle':     { EN:'ACTIVITY TYPES',                     IS:'TEGUNDIR STARFSEMI' },
  'admin.credentialsTitle':  { EN:'CREDENTIALS',                        IS:'SKÍRTEINI' },
  'admin.overdueAlerts':     { EN:'OVERDUE ALERTS',                     IS:'VIÐVARANIR YFIRTÍMA' },
  'admin.notifChannels':     { EN:'NOTIFICATION CHANNELS',              IS:'TILKYNNINGALEIÐIR' },
  'admin.chanWeb':           { EN:'Web (in-app banner)',                IS:'Vef (borði í appi)' },
  'admin.chanEmail':         { EN:'Email',                              IS:'Tölvupóstur' },
  'admin.chanSms':           { EN:'SMS',                                IS:'SMS' },
  'admin.requiresBackend':   { EN:'requires backend setup',             IS:'krefst bakendauppsetningar' },
  'admin.emailRecipients':   { EN:'Email recipients (comma-separated)', IS:'Viðtakendur tölvupósts (kommuaðskildir)' },
  'admin.smsRecipients':     { EN:'SMS recipients (comma-separated)',   IS:'Viðtakendur SMS (kommuaðskildir)' },
  'admin.saveAlertSettings': { EN:'Save alert settings',                IS:'Vista viðvörunarstillingar' },
  'admin.scoreThresholds':   { EN:'SCORE THRESHOLDS',                   IS:'STIGAMÖRK' },
  'admin.scoreThresholdsSub':{ EN:'total points → flag level',          IS:'heildarstig → fánastig' },
  'admin.yellowGte':         { EN:'Yellow ≥',                           IS:'Gulur ≥' },
  'admin.orangeGte':         { EN:'Orange ≥',                           IS:'Appelsínugulur ≥' },
  'admin.redGte':            { EN:'Red ≥',                              IS:'Rauður ≥' },
  'admin.closedGte':         { EN:'Closed ≥',                           IS:'Lokað ≥' },
  'admin.windScoring':       { EN:'WIND SCORING (Force → points)',      IS:'VINDASTIG (Force → stig)' },
  'admin.windScoringHint':   { EN:'Each band applies when Force ≤ maxForce. List in ascending order.', IS:'Hvert bil gildir þegar Force ≤ hámarksForce. Raðað í hækkandi röð.' },
  'admin.dirGustMods':       { EN:'DIRECTION & GUST MODIFIERS',         IS:'ÁTTIR OG HVÍÐUBREYTINGAR' },
  'admin.easterlyMod':       { EN:'Easterly modifier (pts)',             IS:'Austanáttarbreyting (stig)' },
  'admin.easterlyModHint':   { EN:'Added when wind is from an easterly sector', IS:'Bætt við þegar vindur er frá austanátt' },
  'admin.gustMod1':          { EN:'Gust modifier +1 Force (pts)',        IS:'Hvíðubreyting +1 Force (stig)' },
  'admin.gustMod1Hint':      { EN:'Added when gusts are exactly 1 Force level above sustained', IS:'Bætt við þegar hvíður eru nákvæmlega 1 Force-stigi yfir meðalvindi' },
  'admin.gustMod2':          { EN:'Gust modifier +2 Force (pts)',        IS:'Hvíðubreyting +2 Force (stig)' },
  'admin.gustMod2Hint':      { EN:'Added when gusts are 2+ Force levels above sustained', IS:'Bætt við þegar hvíður eru 2+ Force-stigum yfir meðalvindi' },
  'admin.easterlyDirs':      { EN:'Easterly directions (comma-separated)', IS:'Austanáttir (kommuaðskildar)' },
  'admin.waveScoring':       { EN:'WAVE HEIGHT SCORING (metres → points)', IS:'BYLGJUHÆÐARSTIG (metrar → stig)' },
  'admin.sstScoring':        { EN:'SEA TEMPERATURE SCORING (°C → points)', IS:'SJÁVARHITASTIG (°C → stig)' },
  'admin.sstHint':           { EN:'First band where SST ≥ minC applies. List highest minC first.', IS:'Fyrsta bil þar sem sjávarhiti ≥ lágmarksC gildir. Raðað hæsta gildi efst.' },
  'admin.airTempScoring':    { EN:'AIR TEMPERATURE SCORING (°C → points)', IS:'LOFTHITASTIG (°C → stig)' },
  'admin.visScoring':        { EN:'VISIBILITY SCORING',                  IS:'SKYGGNI-STIG' },
  'admin.visGood':           { EN:'Good (pts)',                          IS:'Gott (stig)' },
  'admin.visReduced':        { EN:'Reduced (pts)',                       IS:'Skert (stig)' },
  'admin.visPoor':           { EN:'Poor <500m (pts)',                    IS:'Slæmt <500m (stig)' },
  'admin.flagLabelsAdvice':  { EN:'FLAG LABELS & ADVICE TEXT',           IS:'FÁNATEXTAR OG RÁÐLEGGINGAR' },
  'admin.livePreview':       { EN:'LIVE PREVIEW',                        IS:'FORSÝNING' },
  'admin.saveFlagSettings':  { EN:'Save flag settings',                  IS:'Vista fánastillingar' },
  'admin.resetDefaults':     { EN:'Reset to defaults',                   IS:'Endurstilla sjálfgefin gildi' },
  'admin.addBand':           { EN:'+ Add band',                          IS:'+ Bæta við bili' },
  'admin.memberModal.title': { EN:'Add Member',                          IS:'Bæta við félaga' },
  'admin.kennitala':         { EN:'Kennitala',                           IS:'Kennitala' },
  'admin.initials':          { EN:'Initials',                            IS:'Upphafsstafir' },
  'admin.initialsPlaceholder': { EN:'Auto-generated',                    IS:'Sjálfvirkt' },
  'admin.dob':               { EN:'Date of birth',                       IS:'Fæðingardagur' },
  'admin.membershipType':    { EN:'Membership type',                     IS:'Tegund aðildar' },
  'admin.memFull':           { EN:'Full',                                IS:'Full' },
  'admin.memJunior':         { EN:'Junior',                              IS:'Unglingur' },
  'admin.memFamily':         { EN:'Family',                              IS:'Fjölskylda' },
  'admin.memStudent':        { EN:'Student',                             IS:'Nemandi' },
  'admin.memHonorary':       { EN:'Honorary',                            IS:'Heiðursfélagi' },
  'admin.memOther':          { EN:'Other',                               IS:'Annað' },
  'admin.deactivate':        { EN:'Deactivate',                          IS:'Gera óvirkt' },
  'admin.boatCatModal.add':  { EN:'Add Boat Category',                   IS:'Bæta við bátaflokki' },
  'admin.nameEN':            { EN:'Name (English)',                       IS:'Nafn (enska)' },
  'admin.nameIS':            { EN:'Name (Íslenska)',                      IS:'Nafn (íslenska)' },
  'admin.emoji':             { EN:'Emoji',                               IS:'Emoji' },
  'admin.keyAutoSet':        { EN:'Key (auto-set)',                       IS:'Lykill (sjálfkrafa)' },
  'admin.keyHint':           { EN:'The key is used internally to link boats and checklists. It cannot be changed after boats are assigned.', IS:'Lykillinn er notaður innbyrðis til að tengja báta og gátlista. Honum er ekki hægt að breyta eftir að bátum er úthlutað.' },
  'admin.locModal.name':     { EN:'Name',                                IS:'Nafn' },
  'admin.clModal.add':       { EN:'Add Checklist Item',                  IS:'Bæta við gátlistaatriði' },
  'admin.clPhaseOpening':    { EN:'Opening',                             IS:'Opnun' },
  'admin.clPhaseClosing':    { EN:'Closing',                             IS:'Lokun' },
  'admin.clLaunchPhase':     { EN:'Launch',                              IS:'Sjósetning' },
  'admin.clLandingPhase':    { EN:'Landing',                             IS:'Lending' },
  'admin.actTypeModal.add':  { EN:'Add Activity Type',                   IS:'Bæta við tegund starfsemi' },
  'admin.subtypes':          { EN:'SUBTYPES',                            IS:'UNDIRTEGUNDIR' },
  'admin.certDefModal.add':  { EN:'Add Credential Type',                 IS:'Bæta við tegund skírteinis' },
  'admin.certDescLabel':     { EN:'Description',                         IS:'Lýsing' },
  'admin.certIssuing':       { EN:'Issuing Authority',                   IS:'Útgefandi' },
  'admin.certClubEndorsement': { EN:'Club endorsement',                  IS:'Áritun félagsins' },
  'admin.certCardColour':    { EN:'Card colour',                         IS:'Litur korts' },
  'admin.certAutoBlank':     { EN:'auto if blank',                       IS:'sjálfvirkt ef autt' },
  'admin.certExpires':       { EN:'This credential expires',             IS:'Þetta skírteini rennur út' },
  'admin.certExpiryDate':    { EN:'EXPIRY DATE',                         IS:'LOKADAGSETNING' },
  'admin.certHasId':         { EN:'This credential has an ID / licence number', IS:'Þetta skírteini hefur auðkenni / leyfisnúmer' },
  'admin.certSubcategories': { EN:'SUBCATEGORIES',                       IS:'UNDIRFLOKKAR' },
  'admin.certSubcatHint':    { EN:'Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce "higher replaces lower" logic. Per-subtype issuing authority or expiry date will override the parent values.', IS:'Bættu við undirflokkum ef skírteinið hefur stig (t.d. Stig 1, 2, 3). Stilltu röð til að framfylgja „hærra kemur í stað lægra" rök. Útgefandi eða lokadagsetning undirflokks hnekkir gildum yfirflokksins.' },
  'admin.certCurrent':       { EN:'CURRENT',                             IS:'NÚVERANDI' },
  'admin.certNoneAssigned':  { EN:'No credentials assigned.',            IS:'Engin skírteini úthlutað.' },
  'admin.certAssignTitle':   { EN:'ASSIGN CERTIFICATION',                IS:'ÚTHLUTA SKÍRTEINI' },
  'admin.certLicenceNo':     { EN:'Licence / ID Number',                 IS:'Leyfisnúmer / auðkenni' },
  'admin.certExpiryHint':    { EN:'leave blank if permanent',            IS:'skildu eftir autt ef varanlegt' },
  'admin.certExpiryLabel':   { EN:'Expiry date',                         IS:'Lokadagsetning' },
  'admin.certAssignedDate':  { EN:'Assigned date',                       IS:'Úthlutunardagur' },
  'admin.qrScanHint':        { EN:'Scan → available: launch flow · your boat out: return flow · someone else\'s: shows status.', IS:'Skannaðu → laus: sjósetningarflæði · þinn bátur úti: skilaflæði · annars: sýnir stöðu.' },
  'admin.printPdf':          { EN:'Print / PDF',                         IS:'Prenta / PDF' },
  'admin.ownerClub':         { EN:'Club boat',                           IS:'Klúbbsbátur' },
  'admin.ownerPrivate':      { EN:'Private boat',                        IS:'Einkabátur' },
  'admin.searchMember':      { EN:'Search member...',                    IS:'Leita að félaga...' },
  'admin.saveCharter':       { EN:'Save Charter',                        IS:'Vista leigu' },
  'admin.oosReason':         { EN:'OOS reason',                          IS:'Ástæða' },
  'admin.openingChecklist':  { EN:'OPENING CHECKLIST',                   IS:'OPNUNARGÁTLISTI' },
  'admin.closingChecklist':  { EN:'CLOSING CHECKLIST',                   IS:'LOKUNARGÁTLISTI' },
  'admin.homePort':          { EN:'Home port',                           IS:'Heimahöfn' },

  // ── Staff — checkout form hardcoded strings ────────────────────────────────
  'staff.crewMembers':       { EN:'Crew members',                        IS:'Áhöfn' },
  'staff.crewOptional':      { EN:'optional — search by name',           IS:'valfrjálst — leita eftir nafni' },
  'staff.crewAutoLog':       { EN:'Named crew get this trip logged in their logbook automatically.', IS:'Nefnd áhöfn fær þessa ferð sjálfkrafa skráða í dagbókina sína.' },
  'staff.departurePort':     { EN:'Departure Port',                      IS:'Brottfararhöfn' },
  'staff.recentIn':          { EN:'In',                                  IS:'Inn' },
  'staff.recentMember':      { EN:'Member',                              IS:'Félagi' },
  'staff.recentBoat':        { EN:'Boat',                                IS:'Bátur' },
  'staff.recentArea':        { EN:'Sailing area',                        IS:'Siglingasvæði' },
  'staff.recentDuration':    { EN:'Duration',                            IS:'Tímalengd' },

  // ── Member — launch flow hardcoded strings ─────────────────────────────────
  'member.departurePort':    { EN:'Departure Port',                      IS:'Brottfararhöfn' },
  'member.homePort':         { EN:'Home port',                           IS:'Heimahöfn' },
  'member.crewMembers':      { EN:'Crew members',                        IS:'Áhöfn' },
  'member.crewOptional':     { EN:'optional — search by name',           IS:'valfrjálst — leita eftir nafni' },
  'member.crewAutoLog':      { EN:'Named crew get this trip logged in their logbook automatically.', IS:'Nefnd áhöfn fær þessa ferð sjálfkrafa skráða í dagbókina sína.' },
  'member.back':             { EN:'Back',                                IS:'Til baka' },
  'member.continue':         { EN:'Continue →',                          IS:'Áfram →' },
  'member.preLaunch':        { EN:'PRE-LAUNCH',                          IS:'UNDIRBÚNINGUR' },
  'member.noChecklist':      { EN:'No pre-launch checklist configured for this category.', IS:'Enginn gátlisti stilltur fyrir þennan flokk.' },
  'member.confirmAllItems':  { EN:'Please confirm all items before proceeding.', IS:'Vinsamlegast staðfestu alla liði.' },

  // ── Daily log — hardcoded strings ──────────────────────────────────────────
  'daily.ablerRegistered':   { EN:'Activity details registered in Abler', IS:'Starfsemi skráð í Abler' },
  'daily.linkedGroupCo':     { EN:'Linked group checkouts',              IS:'Tengdar hópaútskráningar' },
  'daily.linkGroupCo':       { EN:'+ Link group checkout',               IS:'+ Tengja hópaútskráningu' },
  'daily.linkGroupCoTitle':  { EN:'Link Group Checkout',                 IS:'Tengja hópaútskráningu' },
  'daily.noActiveGroups':    { EN:'No active group checkouts today.',    IS:'Engar virkar hópaútskráningar í dag.' },
  'daily.linkSelected':      { EN:'Link selected',                       IS:'Tengja valið' },
  'daily.groupCheckout':     { EN:'Group checkout',                      IS:'Hópaútskráning' },
  'daily.group':             { EN:'group',                               IS:'hópur' },
  'daily.groups':            { EN:'groups',                              IS:'hópar' },

};

window.s = function s(key, vars, lang) {
  const L   = lang || (typeof getLang === 'function' ? getLang() : 'EN');
  const entry = STRINGS[key];
  if (!entry) {
    // Fail gracefully: return the key itself so missing strings are obvious
    console.warn('[strings] missing key:', key);
    return key;
  }
  let str = entry[L] || entry['EN'] || key;
  if (vars) {
    str = str.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? vars[k] : '{' + k + '}'));
  }
  return str;
};

/**
 * Apply strings to DOM elements via data-s="key" attributes.
 * Call applyStrings() once after the DOM is ready on any page that
 * uses static HTML labels (as opposed to JS-rendered content).
 *
 * Usage in HTML:  <label data-s="lbl.name"></label>
 *                 <button data-s="btn.save"></button>
 *                 <span data-s="nav.weather" data-s-attr="title"></span>
 */
window.applyStrings = function applyStrings(root) {
  (root || document).querySelectorAll('[data-s]').forEach(el => {
    const key  = el.dataset.s;
    const attr = el.dataset.sAttr;
    const val  = window.s(key);
    if (attr) el.setAttribute(attr, val);
    else      el.textContent = val;
  });
};
