var _STRINGS_FLAT = {
  "nav.staffHub": "Staff",
  "nav.memberHub": "Home",
  "nav.admin": "Admin",
  "nav.logbook": "Logbook",
  "nav.signOut": "Sign out",
  "nav.langToggle": "IS",
  "btn.save": "Save",
  "btn.saveClose": "Save & close",
  "btn.cancel": "Cancel",
  "btn.delete": "Delete",
  "btn.edit": "Edit",
  "btn.add": "+ Add",
  "btn.close": "Close",
  "btn.confirm": "Confirm",
  "btn.signOff": "Save & Sign off",
  "btn.submit": "Submit",
  "btn.viewAll": "View all →",
  "lbl.loading": "Loading…",
  "lbl.on": "On",
  "lbl.off": "Off",
  "lbl.noData": "No data",
  "lbl.unknown": "Unknown",
  "lbl.name": "Name",
  "lbl.date": "Date",
  "lbl.time": "Time",
  "lbl.notes": "Notes",
  "lbl.phone": "Phone",
  "lbl.email": "Email",
  "lbl.location": "Location",
  "lbl.boat": "Boat",
  "lbl.crew": "Crew",
  "lbl.role": "Role",
  "lbl.member": "Member",
  "lbl.guest": "Guest",
  "lbl.guardian": "Guardian",
  "lbl.minor": "MINOR",
  "lbl.verified": "✓ Verified",
  "lbl.optional": "optional",
  "lbl.filter": "FILTER:",
  "lbl.active": "Active",
  "lbl.category": "Category",
  "lbl.description": "Description",
  "lbl.severity": "Severity",
  "lbl.type": "Type",
  "lbl.sortOrder": "Sort order",
  "lbl.selectDots": "Select…",
  "lbl.noneDash": "— none —",
  "msg.unsavedChanges": "You have unsaved changes. Discard them?",
  "toast.saved": "Saved",
  "toast.saveFailed": "Save failed",
  "toast.deleted": "Deleted",
  "toast.error": "Something went wrong. Try again.",
  "toast.loadFailed": "Load failed",
  "toast.signedOff": "Signed off ✓",
  "toast.checkedIn": "Checked in ✓",
  "wx.wind": "WIND",
  "wx.gusts": "GUSTS",
  "wx.waves": "WAVES",
  "wx.pressure": "PRESSURE",
  "wx.loading": "Loading conditions…",
  "wx.unavailable": "⚠️ Weather unavailable",
  "wx.birkConditions": "BIRK — CONDITIONS",
  "wx.airTemp": "AIR TEMP",
  "wx.conditions": "CONDITIONS",
  "wx.sea": "SEA",
  "wx.surface": "Surface",
  "wx.force": "Force",
  "wx.feelsLike": "Feels like {t}°",
  "wx.birkObs": "BIRK obs",
  "wx.pressureRising": "rising",
  "wx.pressureFalling": "falling",
  "wx.pressureSteady": "steady",
  "wx.noScoring": "No scoring factors.",
  "wx.totalScore": "Total score",
  "wx.scoreBreakdown": "SCORE BREAKDOWN",
  "wx.justNow": "just now",
  "wx.minAgo": "{n} min ago",
  "wx.hrAgo": "{n}h ago",
  "wx.noStaffOnDuty": "No staff on duty",
  "wx.noSupportBoat": "No support boat on the water",
  "wx.pts": "pts",
  "wx.bft0": "Calm",
  "wx.bft1": "Light air",
  "wx.bft2": "Light breeze",
  "wx.bft3": "Gentle breeze",
  "wx.bft4": "Moderate breeze",
  "wx.bft5": "Fresh breeze",
  "wx.bft6": "Strong breeze",
  "wx.bft7": "Near gale",
  "wx.bft8": "Gale",
  "wx.bft9": "Strong gale",
  "wx.bft10": "Storm",
  "wx.bft11": "Violent storm",
  "wx.bft12": "Hurricane",
  "wx.bdWind": "Wind Force {n} ({desc})",
  "wx.bdWindDir": "Wind from {dir}",
  "wx.bdGusts": "Gusts Force {n} (sustained Force {sust})",
  "wx.bdWaves": "Waves {h} m",
  "wx.bdSst": "Sea temp {t}°C",
  "wx.bdFeelsLike": "Feels like {t}°C",
  "login.subtitle": "Sailing Club",
  "login.kennitala": "Kennitala",
  "login.placeholder": "0000000000",
  "login.username": "Username",
  "login.usernamePlaceholder": "Kennitala or initials",
  "login.password": "Password",
  "login.passwordPlaceholder": "Password",
  "login.stayLoggedIn": "Stay logged in on this device",
  "login.usernameRequired": "Please enter your kennitala or initials.",
  "login.passwordRequired": "Please enter your password.",
  "login.badPassword": "Incorrect password.",
  "login.ambiguous": "More than one member uses those initials — please sign in with your kennitala.",
  "login.btn": "Sign in",
  "login.loading": "Signing in…",
  "login.notFound": "Member not found or account inactive.",
  "login.tooShort": "Please enter your 10-digit kennitala.",
  "login.error": "Login failed. Try again.",
  "login.rateLimited": "Too many failed attempts. Please try again in 15 minutes.",
  "login.welcome": "Welcome,",
  "login.chooseView": "How would you like to sign in?",
  "login.chooseAccount": "Which account would you like to open?",
  "login.changePw.title": "choose a password",
  "login.changePw.hint": "You're signed in with the club's default password. Please pick one of your own before continuing.",
  "login.changePw.save": "Save and continue",
  "login.yourAccount": "Your account",
  "login.guardianAccount": "Guardian settings",
  "login.wardMinor": "minor",
  "login.wardSwitchError": "Could not switch to that account.",
  "login.back": "← Sign in as someone else",
  "guardian.sub": "Open a minor's account or manage your own sign-in settings.",
  "guardian.noWards": "No active minors are linked to your kennitala.",
  "guardian.loadError": "Could not load your minors. Please try again.",
  "nav.actingAs": "Signed in as {name}",
  "nav.backToGuardian": "↶ Back to {name}",
  "login.admin.label": "Admin Panel",
  "login.admin.desc": "Manage members, boats, locations, settings",
  "login.staff.label": "Staff Dashboard",
  "login.staff.desc": "Daily log, fleet status, maintenance, incidents",
  "login.member.label": "Member Hub",
  "login.member.desc": "Go sailing, logbook, volunteer",
  "member.launchBoat": "Launch a Boat",
  "member.reportIssue": "Report Damage",
  "member.myCheckout": "BOATS OUT NOW",
  "member.myCheckoutSub": "Tap your boat to check in",
  "member.tabFleet": "Fleet",
  "member.tabCerts": "Credentials",
  "member.fleetAvail": "AVAILABLE BOATS",
  "member.noCheckouts": "No boats out.",
  "member.noBoats": "No boats available.",
  "member.departed": "Departed",
  "member.returned": "Returned",
  "member.launchTitle": "Launch a Boat",
  "member.nonClubBoat": "Non-club boat",
  "member.nonClubHint": "Use your own boat or a boat from another club",
  "member.checkInTitle": "Check In",
  "member.manualTrip": "Log a Trip",
  "member.pendingConfirmations": "Pending Confirmations",
  "member.confirmationsTitle": "Trip Confirmations",
  "member.incoming": "REQUESTS FOR YOU",
  "member.outgoing": "YOUR REQUESTS",
  "member.noIncoming": "No pending requests.",
  "member.noOutgoing": "No outgoing requests.",
  "member.crewAssigned": "recorded you as crew",
  "member.crewJoin": "wants to join your trip",
  "member.helmReq": "recorded you as helm",
  "member.crewAssignedOut": "You recorded {name} as crew",
  "member.crewJoinOut": "You requested to join {name}'s trip",
  "member.helmReqOut": "You recorded {name} as helm",
  "member.crewDeclined": "declined to join — crew count adjusted",
  "member.confirmBtn": "Confirm",
  "member.rejectBtn": "Reject",
  "member.ackBtn": "Got it",
  "member.statusPending": "pending",
  "member.statusRejected": "rejected",
  "member.rejectReason": "Reason for rejection (optional):",
  "settings.title": "Settings",
  "settings.initials": "Initials",
  "settings.initialsHint": "Auto-generated from your name. Override below.",
  "settings.language": "Language",
  "settings.windUnit": "Wind units",
  "settings.windUnit.bft": "Beaufort (Force 4)",
  "settings.windUnit.ms": "m/s",
  "settings.windUnit.kts": "Knots",
  "settings.windUnit.kmh": "km/h",
  "settings.windUnit.mph": "mph",
  "settings.windUnitHint": "Controls wind display in your logbook.",
  "settings.theme": "Appearance",
  "settings.theme.dark": "Dark",
  "settings.theme.light": "Light",
  "settings.theme.auto": "Auto",
  "settings.privacy": "Privacy",
  "settings.sharePhoneVol": "Share phone with volunteer coordinators",
  "settings.sharePhoneVolHint": "When enabled, your phone number is shown next to your name in the admin volunteer signup list so coordinators can reach you.",
  "settings.logbookPage": "Logbook page",
  "settings.showHeatmap": "Show personal heatmap",
  "settings.showHeatmapHint": "When enabled, a map of your trips and GPS tracks appears at the top of your logbook page.",
  "settings.stats": "Stats visibility",
  "settings.statsHint": "Choose which stats appear on your logbook page.",
  "settings.stats.ytd": "Trips this year (YTD)",
  "settings.stats.career": "Total trips (career)",
  "settings.stats.hours": "Hours sailed",
  "settings.stats.skipper": "As skipper",
  "settings.stats.byCategory": "Hours by boat category",
  "settings.stats.distance": "Total distance (nm)",
  "settings.stats.longest": "Longest trip",
  "settings.stats.avgWind": "Average wind",
  "settings.stats.streak": "Weekly streak",
  "settings.stats.boats": "Unique boats sailed",
  "settings.stats.crew": "Trips as crew",
  "settings.stats.heavy": "Heavy weather (F5+)",
  "settings.stats.avgDuration": "Avg trip duration",
  "settings.stats.locations": "Locations sailed",
  "settings.stats.verified": "Verified trips",
  "settings.stats.helmHours": "Hours as helm",
  "settings.stats.student": "Trips as student",
  "settings.stats.favBoat": "Favorite boat",
  "settings.stats.favLocation": "Favorite location",
  "settings.stats.peakWind": "Peak wind",
  "settings.statsGroup.activity": "Activity",
  "settings.statsGroup.sailing": "Sailing",
  "settings.statsGroup.roles": "Roles & boats",
  "settings.statsGroup.conditions": "Conditions",
  "settings.statsGroup.other": "Other",
  "settings.saved": "Settings saved",
  "settings.saveFailed": "Failed to save settings",
  "settings.signIn": "Sign-in",
  "settings.usernameStyle": "Preferred username",
  "settings.usernameStyle.kt": "Kennitala",
  "settings.usernameStyle.initials": "Initials",
  "settings.usernameStyleHint": "Either works at sign-in; this is just a reminder for yourself.",
  "settings.stayLoggedIn": "Stay logged in on this device",
  "settings.stayLoggedInHint": "Pin the site to your home screen and it behaves like an app — you won't have to sign in every time.",
  "settings.currentPassword": "Current password",
  "settings.newPassword": "New password",
  "settings.confirmPassword": "Confirm new password",
  "settings.changePassword": "Change password",
  "settings.passwordHint": "Pick something only you know — at least 4 characters.",
  "settings.passwordChanged": "Password changed.",
  "settings.passwordTooShort": "Password must be at least 4 characters.",
  "settings.passwordMismatch": "New passwords do not match.",
  "settings.passwordWrongCurrent": "Current password is incorrect.",
  "settings.passwordSaveFailed": "Could not change password.",
  "settings.passwordChangedSignedOut": "Password changed. Other devices signed out: {n}.",
  "settings.signInActivity": "Sign-in activity",
  "settings.signInActivityHint": "Devices currently signed in with your account. Sign out any you don't recognise.",
  "settings.signInActivityEmpty": "No active sessions.",
  "settings.signInActivityError": "Could not load active sessions.",
  "settings.signInActivityCurrent": "Current device",
  "settings.signInActivityLastSeen": "Last active",
  "settings.signInActivityCreated": "Signed in",
  "settings.signInActivitySignOut": "Sign out",
  "settings.signOutEverywhereElse": "Sign out of every other device",
  "settings.signOutEverywhereElseConfirm": "Sign out of every other device? You will stay signed in on this one.",
  "settings.signedOutEverywhereElse": "Signed out of {n} devices.",
  "nav.settings": "Settings",
  "logbook.shareBtn": "Share your logbook",
  "logbook.sharePhotos": "Include photos",
  "logbook.shareTracks": "Include GPS tracks",
  "logbook.shareCopy": "Generate & copy link",
  "logbook.exportCsv": "Export as CSV",
  "logbook.noTrips": "No trips",
  "logbook.shareCopied": "Link copied!",
  "logbook.activeTokens": "Active share tokens",
  "logbook.shareWithCrew": "Share with crew",
  "logbook.clubMayUse": "Club may use",
  "logbook.sectTitle": "Logbook",
  "logbook.filterAllYears": "All years",
  "logbook.filterAllBoats": "All boats",
  "logbook.filterAnyRole": "Any role",
  "logbook.filterRoleSkipper": "Skipper",
  "logbook.filterRoleCrew": "Crew",
  "logbook.filterRoleHelm": "Helm",
  "logbook.filterRoleStudent": "Student",
  "logbook.filterRoleGuest": "Guest",
  "logbook.filterAnyWind": "Any wind",
  "logbook.filterWindCalm": "Calm (Force 0–2)",
  "logbook.filterWindLight": "Light (Force 3–4)",
  "logbook.filterWindModerate": "Moderate (Force 5–6)",
  "logbook.filterWindStrong": "Strong (Force 7+)",
  "logbook.filterWindGt4": "Above Force 4",
  "logbook.filterWindLte4": "Force 4 or under",
  "logbook.searchPh": "Search…",
  "logbook.searchByNamePh": "Search by name…",
  "logbook.loading": "Loading…",
  "wx.condClearSky": "Clear sky",
  "wx.condMainlyClear": "Mainly clear",
  "wx.condPartlyCloudy": "Partly cloudy",
  "wx.condOvercast": "Overcast",
  "wx.condFog": "Fog",
  "wx.condDrizzle": "Drizzle",
  "wx.condRain": "Rain",
  "wx.condSnow": "Snow",
  "wx.condThunderstorm": "Thunderstorm",
  "wx.loadingWeather": "Loading weather…",
  "staff.dashTitle": "Staff Dashboard",
  "staff.fleet": "FLEET STATUS",
  "staff.recentCheckins": "RECENT CHECK-INS (24H)",
  "staff.maintenance": "OPEN MAINTENANCE",
  "staff.dailyLog": "Daily Log",
  "staff.dailyLogDesc": "Tides, weather records, checklists, activities, sign-off",
  "staff.logbook": "Logbook Review",
  "staff.logbookDesc": "Verify member trips & assign credentials",
  "staff.incidents": "Incidents",
  "staff.incidentsDesc": "File or review safety incident reports",
  "staff.noOverdue": "No overdue checkouts.",
  "staff.noMaint": "No open requests.",
  "staff.checkIn": "✓ Check In",
  "staff.deleteCheckout": "Delete",
  "staff.activeCheckouts": "ACTIVE CHECKOUTS",
  "staff.boatsOutNow": "BOATS OUT NOW",
  "staff.checkOutBtn": "Boat Checkout",
  "staff.groupCheckout": "Group Checkout",
  "staff.newCheckout": "NEW CHECKOUT",
  "staff.statBoats": "BOATS OUT",
  "staff.statPeople": "PEOPLE OUT",
  "staff.statOverdue": "OVERDUE",
  "staff.toolsLabel": "TOOLS",
  "staff.coForm.departure": "Departure",
  "staff.coForm.estReturn": "Est. return",
  "staff.coForm.crew": "Crew on board",
  "staff.coForm.notes": "Notes (optional)",
  "staff.coForm.submit": "Check Out",
  "staff.coForm.memberPlaceholder": "Name or kennitala…",
  "staff.coForm.notesPlaceholder": "Any notes…",
  "staff.coForm.errMember": "Select a member.",
  "staff.coForm.errBoat": "Select a boat.",
  "staff.coForm.errLocation": "Select a sailing area.",
  "staff.coForm.checkedOut": "Checked out ✓",
  "staff.coDetail.tripLabel": "TRIP",
  "staff.coDetail.out": "OUT",
  "staff.coDetail.return": "EST. RETURN",
  "daily.today": "Today",
  "daily.tripsToday": "TRIPS TODAY",
  "daily.openingChecklist": "OPENING CHECKLIST",
  "daily.closingChecklist": "CLOSING CHECKLIST",
  "daily.activities": "ACTIVITIES",
  "daily.addActivity": "+ Add",
  "daily.staffNotes": "STAFF NOTES",
  "daily.notesPlaceholder": "General notes, conditions summary…",
  "daily.incidentReport": "INCIDENTS",
  "daily.noIncidents": "No incidents reported.",
  "daily.wxLog": "WEATHER LOG",
  "daily.tides": "TIDES",
  "daily.signedOff": "Signed off",
  "daily.readOnly": "Read-only",
  "daily.noActivities": "No activities recorded yet.",
  "daily.noTrips": "No trips recorded today.",
  "daily.activityModal": "Add Activity",
  "daily.actType": "Type",
  "daily.actNameLabel": "Name / description",
  "daily.actNameHint": "e.g. Junior lesson, club race…",
  "daily.actParticipants": "Participants",
  "daily.actPartHint": "e.g. 12 juniors",
  "daily.actNotes": "Notes",
  "daily.actNotesHint": "optional",
  "daily.startTime": "Start time",
  "daily.endTime": "End time",
  "daily.wxLogBtn": "📸 Log snapshot",
  "daily.signOffConfirm": "PM checklist not complete ({done}/{total}). Sign off anyway?",
  "daily.signOffSaving": "Signing off…",
  "daily.signedOffBy": "✓ Signed off by ",
  "incident.title": "Incidents",
  "incident.viewList": "View incidents",
  "incident.fileNew": "File new report",
  "incident.typeLabel": "Incident type(s)",
  "incident.noIncidents": "No incidents filed.",
  "incident.description": "Description",
  "incident.witnesses": "Witnesses",
  "incident.immediateAction": "Immediate action taken",
  "incident.followUp": "Follow-up required",
  "incident.staffNotes": "Staff notes",
  "incident.resolved": "Resolved",
  "incident.open": "Open",
  "incident.markResolved": "Close review, save & file",
  "incident.markOpen": "Reopen",
  "incident.filedBy": "Filed by",
  "incident.boatLabel": "Boat (if applicable)",
  "incident.personsInvolved": "Persons involved",
  "incident.witnessHint": "Names / contact info…",
  "incident.actionHint": "First aid, evacuation, coastguard called…",
  "incident.followUpHint": "Referral, repair, investigation…",
  "incident.handoffSection": "Hand-off",
  "incident.handoffTo": "Handed off to",
  "incident.handoffName": "Contact name / ref.",
  "incident.handoffNotes": "Handoff notes",
  "incident.handoff.guardian": "Guardian",
  "incident.handoff.self": "Self",
  "incident.filterStatusLbl": "Status",
  "incident.filterAll": "All",
  "incident.filterReview": "Review",
  "incident.noMatching": "No incidents match the current filters.",
  "incident.descRequired": "Description is required.",
  "incident.typeRequired": "Select at least one incident type.",
  "incident.sevRequired": "Select severity.",
  "incident.filed": "Report filed ✓",
  "incident.type.injury": "🩹 Injury",
  "incident.type.capsize": "⛵ Capsize",
  "incident.type.collision": "💥 Collision",
  "incident.type.equipment": "🔧 Equipment failure",
  "incident.type.medical": "🏥 Medical",
  "incident.type.nearMiss": "⚡️ Near miss",
  "incident.type.missing": "🔍 Missing person",
  "incident.type.propertyDmg": "🏗️ Property damage",
  "incident.type.stranding": "⚓️ Ran aground",
  "incident.type.other": "📌 Other",
  "incident.saveCloseFile": "Save, close & file",
  "incident.saveForReview": "Save for follow-up / review",
  "incident.statusReview": "Needs review or follow-up",
  "incident.reviewerNotes": "Reviewer comments",
  "incident.addReviewerNote": "Add reviewer comment",
  "incident.sev.low": "Low",
  "incident.sev.medium": "Medium",
  "incident.sev.high": "High",
  "incident.sev.critical": "Critical",
  "maint.category": "Category",
  "maint.part": "Location / part",
  "maint.resolveConfirm": "Mark this request as resolved?",
  "sauma.pageTitle": "🧵 Sewing Circle",
  "sauma.pageSubtitle": "Community maintenance projects",
  "sauma.verkstjori": "Project Lead",
  "sauma.verkstjoriHint": "If left blank, any member can adopt this project.",
  "sauma.filterOpen": "Open",
  "sauma.filterMy": "My Projects",
  "sauma.filterUnassigned": "Unassigned",
  "sauma.filterCompleted": "Completed",
  "sauma.filterAll": "All",
  "sauma.needsVerkstjori": "Needs verkstjóri",
  "sauma.emptyDefault": "No projects match this filter.",
  "sauma.emptyMy": "No projects you are involved in.",
  "sauma.suggestBtn": "+ New sewing circle project",
  "sauma.suggestTitle": "🧵 New sewing circle project",
  "sauma.priority": "Priority",
  "sauma.description": "Description",
  "sauma.materials": "Materials Needed",
  "sauma.photoLabel": "Photo (optional, max 5 MB)",
  "sauma.viewList": "List",
  "sauma.viewBoard": "Board",
  "sauma.colTodo": "To Do",
  "sauma.colInProgress": "In Progress",
  "sauma.colOnHold": "On Hold",
  "sauma.colDone": "Done",
  "sauma.colEmpty": "No projects",
  "sauma.myBoardFilter": "My projects only",
  "sauma.filterOnHold": "On Hold",
  "sauma.filterMyProjects": "My Projects",
  "sauma.filterPending": "Pending Review",
  "sauma.catBoat": "⛵ Boat",
  "sauma.catEquipment": "🦺 Equipment",
  "sauma.catFacility": "🏠 Facility",
  "sauma.selectBoatPh": "Select boat…",
  "sauma.partPh": "e.g. Hull, mast, clubhouse roof…",
  "sauma.descPh": "Describe the project…",
  "sauma.materialPh": "e.g. Sandpaper 120-grit…",
  "sauma.pendingReview": "⏳ Pending staff review",
  "sauma.completedBy": "✓ Completed {date} by {by}",
  "sauma.verkstjoriLabel": "Verkstjóri:",
  "sauma.loadFailed": "Failed to load: {msg}",
  "maint.pageTitle": "🔧 Maintenance",
  "maint.newBtn": "+ New maintenance request",
  "maint.newSaumaBtn": "🧵 New sewing circle project",
  "maint.newTitle": "🔧 New Maintenance Request",
  "maint.statOpen": "OPEN",
  "maint.statCritical": "CRITICAL",
  "maint.statOos": "BOATS OOS",
  "maint.statPending": "PENDING REVIEW",
  "maint.statResolved": "RESOLVED",
  "maint.groupStatus": "STATUS",
  "maint.groupType": "TYPE",
  "maint.groupCategory": "CATEGORY",
  "maint.groupSeverity": "SEVERITY",
  "maint.groupSauma": "SAUMAKLÚBBUR",
  "maint.filterOpen": "Open",
  "maint.filterResolved": "Resolved",
  "maint.filterMaintenance": "Maintenance",
  "maint.filterSauma": "🧵 Saumaklúbbur",
  "maint.filterCatBoat": "Boats",
  "maint.filterCatEquipment": "Equipment",
  "maint.filterCatFacility": "Facility",
  "maint.filterCritical": "Critical",
  "maint.filterHigh": "High",
  "maint.filterMedium": "Medium",
  "maint.filterLow": "Low",
  "maint.filterUnassigned": "Unassigned",
  "maint.filterMyProjects": "My Projects",
  "maint.filterPending": "Pending Review",
  "maint.catBoat": "⛵ Boat",
  "maint.catEquipment": "🦺 Equipment",
  "maint.catFacility": "🏠 Facility",
  "maint.boatLabel": "Boat",
  "maint.selectBoatPh": "Select boat…",
  "maint.markOosLabel": "Mark boat Out of Service?",
  "maint.markOosHint": "Take this boat OOS until repaired",
  "maint.partPh": "e.g. Hull, mast, clubhouse roof…",
  "maint.severity": "Severity",
  "maint.priority": "Priority",
  "maint.sevLow": "LOW",
  "maint.sevMedium": "MEDIUM",
  "maint.sevHigh": "HIGH",
  "maint.sevCritical": "CRITICAL",
  "maint.description": "Description",
  "maint.descPh": "Describe the issue…",
  "maint.verkstjoriLabel": "Verkstjóri (Project Lead)",
  "maint.verkstjoriPh": "Name or leave blank…",
  "maint.materialPh": "e.g. Sandpaper 120-grit…",
  "maint.photoLabel": "Photo (optional, max 5 MB)",
  "maint.verkstjoriPrefix": "Verkstjóri:",
  "maint.completedBy": "✓ Completed {date} by {by}",
  "maint.resolvedBy": "✓ Resolved {date} by {by}",
  "maint.attachPhoto": "Attach photo",
  "nav.saumaklubbur": "Sewing Circle",
  "staff.maintAndSauma": "Maintenance & Projects",
  "staff.maintAndSaumaDesc": "Maintenance requests & sewing circle projects",
  "logrev.title": "Logbook Review",
  "logrev.subtitle": "Verify member trips · assign credentials",
  "logrev.pending": "PENDING REVIEW",
  "logrev.verified": "VERIFIED",
  "logrev.verify": "Verify",
  "logrev.unverify": "Unverify",
  "logrev.staffComment": "Staff comment (optional)",
  "logrev.noTrips": "No trips to review.",
  "logrev.filterAll": "All",
  "logrev.filterPending": "Pending",
  "logrev.filterVerified": "Verified",
  "logrev.filterName": "Filter by name…",
  "logrev.filterFrom": "From",
  "logrev.filterTo": "To",
  "logrev.assignCert": "ASSIGN CREDENTIAL",
  "logrev.assignedDate": "Assigned date",
  "logrev.expires": "Expires",
  "logrev.assignBtn": "Assign",
  "logrev.certModal": "Credentials",
  "logrev.validationRequests": "Validation requests",
  "logrev.showAll": "Show all trips",
  "logrev.certSearch": "Search for a member above to view their credentials.",
  "logrev.certSearchPlaceholder": "Search member name...",
  "logrev.certNoMatches": "No members found with this credential.",
  "logrev.verifyRequest": "VERIFICATION REQUEST",
  "admin.tabMembers": "Members",
  "admin.tabSettings": "Settings",
  "admin.tabBoats": "Boats",
  "admin.tabLocations": "Locations",
  "admin.tabChecklists": "Checklists",
  "admin.tabActTypes": "Activities",
  "admin.tabCerts": "Credentials",
  "admin.tabAlerts": "Alerts",
  "admin.tabPayroll": "Payroll",
  "admin.tabFlags": "Flags",
  "admin.tabReservations": "Charters",
  "admin.bulkSchedule": "BULK SCHEDULE",
  "admin.chartersDesc": "Charter slots are recurring, bookable time windows that captains can reserve for rowing teams or private charters. Create a recurring pattern to make slots available on selected days, then captains can book them from their page.",
  "admin.importCsv": "⇪ Import CSV",
  "admin.searchMembers": "Search name or kennitala…",
  "admin.noMembers": "No members yet.",
  "admin.addMember": "+ Add member",
  "admin.addLocation": "+ Add location",
  "admin.addItem": "+ Add item",
  "admin.addType": "+ Add type",
  "admin.alertFirstMins": "First alert after (min)",
  "admin.alertRepeatMins": "Repeat every (min)",
  "admin.alertSnoozeMins": "Snooze duration (min)",
  "admin.alertEnabled": "Alerts enabled",
  "admin.memberModal.add": "Add Member",
  "admin.memberModal.edit": "Edit Member",
  "admin.guardianName": "Guardian name",
  "admin.guardianPhone": "Guardian phone",
  "admin.guardianKt": "Guardian kennitala",
  "admin.boatModal.add": "Add Boat",
  "admin.boatModal.edit": "Edit Boat",
  "admin.boatCategory": "Category",
  "admin.boatOos": "Out of service",
  "admin.locModal.add": "Add Location",
  "admin.locModal.edit": "Edit Location",
  "admin.clPhase": "Phase",
  "admin.clTextEN": "Text (EN)",
  "admin.clTextIS": "Text (IS)",
  "admin.actTypeEN": "Name (EN)",
  "admin.actTypeIS": "Name (IS)",
  "admin.certTypes": "CREDENTIAL TYPES",
  "admin.certAddType": "+ Add credential type",
  "admin.certAddModal": "Add Credential Type",
  "admin.certEditModal": "Edit Credential Type",
  "admin.certDescOptional": "(optional)",
  "admin.noBoats": "No boats.",
  "admin.noLocations": "No locations.",
  "admin.backToList": "← Back to list",
  "admin.importFromCsv": "Import from Abler.io CSV",
  "cert.noCerts": "No credentials on file.",
  "cert.level": "Level / Subcategory",
  "cert.assign": "Assign",
  "cert.assigned": "Credential assigned.",
  "cert.removed": "Credential removed.",
  "cert.typeRequired": "Select a credential type.",
  "cert.levelRequired": "Select a level / subcategory.",
  "cert.clubEndorsements": "CLUB ENDORSEMENTS",
  "cert.loadError": "Could not load credentials.",
  "payroll.tabTimeReporting": "Time Reporting",
  "payroll.tabEmployees": "Employees",
  "payroll.periodFrom": "From",
  "payroll.periodTo": "To",
  "payroll.noPeriodDefined": "No pay period defined yet.",
  "payroll.editEntry": "Edit",
  "payroll.notEnabled": "Not in payroll",
  "payroll.enablePayroll": "Enable payroll",
  "payroll.calView": "Calendar",
  "payroll.listView": "List",
  "payroll.addEntry": "+ Add entry",
  "payroll.deleteEntry": "Delete",
  "payroll.deleteConfirm": "Delete this time entry?",
  "payroll.allStaff": "All staff",
  "payroll.employee": "Employee",
  "payroll.totalHours": "total",
  "payroll.clockInLabel": "Clock in",
  "payroll.clockOutLabel": "Clock out",
  "payroll.minsLabel": "Duration (minutes)",
  "payroll.noteOptional": "Note (optional)",
  "payroll.notePlaceholder": "e.g. forgotten punch-in",
  "payroll.autoCalc": "auto-calculated, override if needed",
  "payroll.entryRequired": "Employee, clock-in and clock-out are required.",
  "payroll.clockOutAfterIn": "Clock-out must be after clock-in.",
  "payroll.moreEntries": "more",
  "payroll.titleField": "Title",
  "lbl.duration": "Duration",
  "lbl.edited": "edited",
  "lbl.admin": "admin",
  "lbl.staff": "staff",
  "lbl.monShort": "Mon",
  "lbl.tueShort": "Tue",
  "lbl.wedShort": "Wed",
  "lbl.thuShort": "Thu",
  "lbl.friShort": "Fri",
  "lbl.satShort": "Sat",
  "lbl.sunShort": "Sun",
  "payroll.section": "TIME CLOCK",
  "payroll.clockIn": "Clock In",
  "payroll.clockOut": "Clock Out",
  "payroll.startBreak": "Start Break",
  "payroll.endBreak": "End Break",
  "payroll.onBreak": "On break since",
  "payroll.clockedInAt": "Clocked in at",
  "payroll.recentShifts": "Recent shifts",
  "payroll.noShifts": "No shifts logged yet",
  "payroll.shiftSummary": "Shift summary",
  "payroll.totalWorked": "Total worked",
  "payroll.totalBreak": "Total break",
  "payroll.confirmShift": "Done",
  "payroll.allowBreaks": "Allow break logging",
  "payroll.export": "Export",
  "payroll.externalUrl": "External payroll app URL",
  "payroll.externalUrlHint": "Google Apps Script web app endpoint that receives the time data.",
  "payroll.exportSent": "Time data sent ✓",
  "payroll.exportFailed": "Export failed",
  "payroll.urlNotSet": "Set the external payroll app URL first.",
  "logbook.nonClubToggle": "Non-club trip",
  "logbook.nonClubHint": "— log a trip outside the club system",
  "logbook.boatNameLabel": "Boat name",
  "logbook.boatNamePh": "e.g. Sunfish, RIB, etc.",
  "logbook.boatCategory": "Category",
  "logbook.locationNamePh": "e.g. Lake Thingvallavatn",
  "logbook.useMyLocation": "Use my location",
  "logbook.locating": "Locating…",
  "logbook.locationDenied": "Location access denied",
  "logbook.enterBoatName": "Please enter a boat name.",
  "logbook.enterLocation": "Please enter a location.",
  "boat.registrationNo": "Registration no.",
  "boat.sailNo": "Sail no.",
  "boat.loa": "LOA (ft)",
  "boat.typeModel": "Type / model",
  "boat.defaultPort": "Default port",
  "location.type": "Type",
  "location.typePort": "Port",
  "location.typeLocation": "Sailing area",
  "location.lat": "Latitude",
  "location.lng": "Longitude",
  "fleet.badgeAvail": "AVAIL",
  "fleet.badgeOut": "OUT",
  "fleet.badgeOverdue": "OVERDUE",
  "fleet.badgeOos": "OOS",
  "fleet.badgeYours": "YOURS",
  "fleet.aboard": "{n} aboard",
  "fleet.outTime": "Out {t}",
  "fleet.checkIn": "Check In",
  "fleet.delete": "Delete",
  "fleet.badgeChartered": "CHARTERED",
  "fleet.badgePrivate": "PRIVATE",
  "fleet.ownedBy": "Owner: {name}",
  "fleet.actionCheckout": "Check Out",
  "fleet.actionMaint": "Request Maintenance",
  "fleet.actionMarkOos": "Mark Unavailable",
  "fleet.actionMarkAvail": "Mark Available",
  "boat.ownership": "Ownership",
  "boat.owner": "Owner",
  "boat.accessMode": "Access Mode",
  "boat.accessFree": "Free Access",
  "boat.accessControlled": "Controlled Access",
  "boat.gateCert": "Required Certification",
  "boat.gateCertNone": "None (Specific members only)",
  "boat.gateCertAny": "any level",
  "boat.gateCertOrHigher": "or higher",
  "boat.allowlist": "Allowed Members",
  "boat.reservations": "Charter Status",
  "boat.addReservation": "Assign Charter",
  "boat.removeReservation": "Remove",
  "boat.reservationSaved": "Charter saved",
  "boat.reservationRemoved": "Charter removed",
  "boat.reservedFor": "Chartered to {name}",
  "boat.reservedUntil": "until {date}",
  "fleet.badgeControlled": "CONTROLLED",
  "fleet.badgeRestricted": "RESTRICTED",
  "fleet.badgeAuthorized": "AUTHORIZED",
  "boat.slotScheduling": "Enable session slot scheduling",
  "boat.availOutside": "Available outside scheduled slots",
  "boat.availOutsideHint": "If unchecked, the boat can only be used during bookable session slots. Otherwise, allowed members can use the boat at any time.",
  "day.mon": "Mon",
  "day.tue": "Tue",
  "day.wed": "Wed",
  "day.thu": "Thu",
  "day.fri": "Fri",
  "day.sat": "Sat",
  "day.sun": "Sun",
  "month.jan": "Jan",
  "month.feb": "Feb",
  "month.mar": "Mar",
  "month.apr": "Apr",
  "month.may": "May",
  "month.jun": "Jun",
  "month.jul": "Jul",
  "month.aug": "Aug",
  "month.sep": "Sep",
  "month.oct": "Oct",
  "month.nov": "Nov",
  "month.dec": "Dec",
  "slot.filterBoat": "Boat",
  "slot.filterCrew": "Crew",
  "slot.allBoats": "All boats",
  "slot.today": "Today",
  "slot.addRecurring": "+ Recurring",
  "slot.addSingle": "+ Single",
  "slot.selectBoatFirst": "Select a specific boat first",
  "slot.noSlotBoats": "No boats with slot scheduling enabled",
  "slot.boat": "Boat",
  "slot.recurTitle": "Create Recurring Slots",
  "slot.editTitle": "Session Slot",
  "slot.newTitle": "New Slot",
  "slot.daysOfWeek": "Days of week",
  "slot.startTime": "Start time",
  "slot.endTime": "End time",
  "slot.fromDate": "From date",
  "slot.toDate": "To date",
  "slot.note": "Note",
  "slot.preview": "Preview",
  "slot.create": "Create",
  "slot.selectDays": "Select at least one day and date range",
  "slot.previewCount": "{count} slots will be created",
  "slot.created": "{count} slots created",
  "slot.missingFields": "Date and times are required",
  "slot.confirmDelete": "Delete this slot?",
  "slot.bookedBy": "Booked by",
  "slot.legendOpen": "Open",
  "slot.legendYours": "Yours",
  "slot.legendBooked": "Booked",
  "slot.booked": "Slot booked!",
  "slot.unbooked": "Booking cancelled",
  "slot.confirmUnbook": "Cancel this booking?",
  "slot.yours": "YOURS",
  "slot.date": "Date",
  "slot.bulkBook": "Bulk Booking",
  "slot.bulkTitle": "Bulk Booking Slots",
  "slot.bulkPreview": "{open} open slots of {total} will be booked",
  "slot.bulkNoSlots": "No open slots match your criteria",
  "slot.bulkBooked": "{count} slots booked!",
  "slot.bulkPartial": "{booked} booked, {skipped} already taken",
  "slot.createAndBook": "+ New Booking",
  "slot.createAndBookTitle": "Create & Book Slot",
  "slot.createdAndBooked": "Slot created and booked!",
  "slot.conflict": "That time overlaps an existing slot for this boat",
  "cq.reservationsTitle": "CHARTERS",
  "nav.coxswainSeat": "Rowing Division",
  "cox.title": "Rowing Division",
  "cox.tabCrews": "Crews & Slots",
  "cox.tabPassport": "Passport",
  "cox.statsTrips": "TRIPS",
  "cox.statsHours": "HOURS",
  "cox.statsDist": "DISTANCE",
  "cox.maintenance": "MAINTENANCE",
  "cox.readOnly": "View only — released rower endorsement required for changes",
  "cox.noCrewsShort": "No crews — create one first",
  "cox.createCrewFirst": "Create a crew first to book slots",
  "cox.noMaint": "No maintenance requests.",
  "cox.createCrew": "+ Create Crew",
  "cox.createCrewTitle": "Create Crew",
  "cox.crewName": "Crew name",
  "cox.crewNameRequired": "Crew name required",
  "cox.openSpots": "open",
  "cox.active": "ACTIVE",
  "cox.forming": "FORMING",
  "cox.inviteMember": "Invite Member",
  "cox.searchMember": "Member",
  "cox.pairAssignment": "Pair",
  "cox.sendInvite": "Send Invite",
  "cox.selectMember": "Select a member",
  "cox.selectPair": "Select a pair",
  "cox.inviteSent": "Invite sent!",
  "cox.pendingInvites": "PENDING INVITES",
  "cox.invitedBy": "Invited by",
  "cox.accept": "Accept",
  "cox.reject": "Reject",
  "cox.inviteAccepted": "Invite accepted!",
  "cox.inviteRejected": "Invite declined.",
  "cox.disband": "Disband",
  "cox.confirmDisband": "Disband this crew? This cannot be undone.",
  "cox.crewDisbanded": "Crew disbanded.",
  "cox.crewBoard": "CREW BOARD",
  "cox.crewBoardEmpty": "No crews yet. Create one or wait for others to post.",
  "cox.boat": "Boat",
  "cox.bow": "Bow",
  "cox.stern": "Stern",
  "cox.join": "Join",
  "cox.leave": "Leave",
  "cox.joined": "Joined crew!",
  "cox.left": "Left crew.",
  "cox.confirmLeave": "Leave this crew?",
  "cox.description": "Description",
  "cox.descPlaceholder": "e.g., Mon & Wed 7am, casual pace",
  "cox.visibility": "Visibility",
  "cox.visOpen": "Open — anyone can join",
  "cox.visInvite": "Invite only",
  "cox.yourSeat": "Your seat",
  "cox.seatBow": "Bow",
  "cox.seatStern": "Stern",
  "cox.numBoats": "Number of boats",
  "cox.needsMore": "needs {n} more",
  "cox.crewColor": "Color",
  "cq.bookingColor": "My bookings:",
  "cox.tentative": "TENTATIVE",
  "cox.slotReservations": "SLOT RESERVATIONS",
  "pub.dash.subtitle": "Siglingafélagið Ýmir",
  "pub.dash.ytdTrips": "Trips This Season",
  "pub.dash.totalHours": "Hours Sailed",
  "pub.dash.byCategory": "By Boat Type",
  "pub.dash.locations": "Where We Sail",
  "pub.dash.onWater": "On the Water Now",
  "pub.dash.noActivity": "No boats on the water right now.",
  "pub.dash.trips": "trips",
  "pub.dash.loading": "Loading dashboard…",
  "pub.dash.error": "Could not load dashboard data.",
  "pub.dash.lastUpdated": "Last updated",
  "pub.dash.tripCount": "{n} trips",
  "pub.dash.hourCount": "{n} hrs",
  "pub.dash.weather": "Weather & Tides",
  "pub.dash.boatsOut": "Boats Out",
  "pub.dash.captainData": "Captain Data",
  "pub.dash.captainSoon": "Captain profiles and statistics will appear here soon.",
  "pub.dash.trips": "trips",
  "pub.dash.comingSoon": "More information coming soon.",
  "pub.dash.activeMembers": "Active Members",
  "pub.dash.becomeMember": "Become a Member",
  "admin.confirmImport": "Confirm import",
  "admin.addCategory": "+ Add category",
  "admin.actTypesTitle": "ACTIVITIES",
  "admin.credentialsTitle": "CREDENTIALS",
  "admin.manageCreds": "Credentials",
  "admin.overdueAlerts": "OVERDUE ALERTS",
  "admin.scoreThresholds": "SCORE THRESHOLDS",
  "admin.scoreThresholdsSub": "total points → flag level",
  "admin.yellowGte": "Yellow ≥",
  "admin.orangeGte": "Orange ≥",
  "admin.redGte": "Red ≥",
  "admin.closedGte": "Closed ≥",
  "admin.windScoring": "WIND SCORING (Force → points)",
  "admin.windScoringHint": "Each band applies when Force ≤ maxForce. List in ascending order.",
  "admin.dirGustMods": "DIRECTION & GUST MODIFIERS",
  "admin.windDirMod": "Wind direction modifier (pts)",
  "admin.windDirModHint": "Added when wind is from one of the listed directions",
  "admin.gustMod1": "Gust modifier +1 Force (pts)",
  "admin.gustMod1Hint": "Added when gusts are exactly 1 Force level above sustained",
  "admin.gustMod2": "Gust modifier +2 Force (pts)",
  "admin.gustMod2Hint": "Added when gusts are 2+ Force levels above sustained",
  "admin.windDirDirs": "Flagged wind directions (comma-separated)",
  "admin.waveScoring": "WAVE HEIGHT SCORING (metres → points)",
  "admin.sstScoring": "SEA TEMPERATURE SCORING (°C → points)",
  "admin.sstHint": "First band where SST ≥ minC applies. List highest minC first.",
  "admin.airTempScoring": "AIR TEMPERATURE SCORING (°C → points)",
  "admin.visScoring": "VISIBILITY SCORING",
  "admin.visGood": "Good (pts)",
  "admin.visReduced": "Reduced (pts)",
  "admin.visPoor": "Poor <500m (pts)",
  "admin.flagLabelsAdvice": "FLAG LABELS & ADVICE TEXT",
  "admin.livePreview": "LIVE PREVIEW",
  "admin.saveFlagSettings": "Save flag settings",
  "admin.resetDefaults": "Reset to defaults",
  "admin.addBand": "+ Add band",
  "admin.kennitala": "Kennitala",
  "admin.initials": "Initials",
  "admin.initialsPlaceholder": "Auto-generated",
  "admin.dob": "Date of birth",
  "admin.deactivate": "Deactivate",
  "admin.password": "Password",
  "admin.hasCustomPassword": "Custom password set",
  "admin.usingDefaultPassword": "Using temporary password",
  "admin.resetPassword": "Issue temporary password",
  "admin.resetPasswordConfirm": "Issue a new temporary password for {name}? Every device they're signed in on will be signed out.",
  "admin.resetPasswordDone": "Temporary password issued. Sessions ended: {n}.",
  "admin.tempPasswordTitle": "Temporary password",
  "admin.tempPasswordTitlePlural": "Temporary passwords",
  "admin.tempPasswordWarning": "Share this with the member now — it will not be shown again. They'll be prompted to choose their own password on first login.",
  "admin.tempPasswordCopy": "Copy",
  "admin.tempPasswordCopied": "Copied",
  "admin.boatCatModal.add": "Add Boat Category",
  "admin.nameEN": "Name (English)",
  "admin.nameIS": "Name (Íslenska)",
  "admin.emoji": "Emoji",
  "admin.keyAutoSet": "Key (auto-set)",
  "admin.keyHint": "The key is used internally to link boats and checklists. It cannot be changed after boats are assigned.",
  "admin.clModal.add": "Add Checklist Item",
  "admin.clPhaseOpening": "Opening",
  "admin.clPhaseClosing": "Closing",
  "admin.clLaunchPhase": "Launch",
  "admin.clLandingPhase": "Landing",
  "admin.actTypeModal.add": "Add Activity",
  "admin.subtypes": "SUBTYPES",
  "admin.certDefModal.add": "Add Credential Type",
  "admin.certDescLabel": "Description",
  "admin.certDescEN": "Description (EN)",
  "admin.certDescIS": "Description (IS)",
  "admin.subcatLabelEN": "Label (EN, e.g. Level 1)",
  "admin.subcatLabelIS": "Label (IS, t.d. Stig 1)",
  "admin.subcatDescEN": "Description (EN)",
  "admin.subcatDescIS": "Description (IS)",
  "admin.certCatModal.add": "Add Credential Category",
  "admin.certCatModal.edit": "Edit Credential Category",
  "admin.certCatKeyHint": "The key is stable and cannot be changed after creation — it keeps existing member credentials linked to this category.",
  "admin.certIssuing": "Issuing Authority",
  "admin.certClubEndorsement": "Club endorsement",
  "admin.certCardColour": "Card colour",
  "admin.certAutoBlank": "auto if blank",
  "admin.certExpires": "This credential expires",
  "admin.certHasId": "This credential has an ID / licence number",
  "admin.certSubcategories": "SUBCATEGORIES",
  "admin.certSubcatHint": "Add subcategories if this cert has levels (e.g. Level 1, 2, 3). Set rank to enforce \"higher replaces lower\" logic. Per-subtype issuing authority or expiry date will override the parent values.",
  "admin.certCurrent": "CURRENT",
  "admin.certAssignTitle": "ASSIGN CERTIFICATION",
  "admin.certCategory": "Category",
  "admin.certCategorySelect": "Select category…",
  "admin.certAddCategory": "+ Add category…",
  "admin.certTitle": "Credential title",
  "admin.certIdNumber": "ID number",
  "admin.certIssuingAuth": "Issuing authority",
  "admin.certIssueDate": "Issue date",
  "admin.certExpires2": "Does this credential expire?",
  "admin.certExpiryDate2": "Expiration date",
  "admin.certDescription": "Additional description",
  "admin.certCustomType": "— Enter custom credential —",
  "admin.certTitleRequired": "Title is required.",
  "admin.certAuthorityReq": "Issuing authority is required.",
  "admin.certExpiryReq": "Expiration date required when credential expires.",
  "admin.certCategoryReq": "Category is required.",
  "admin.certDefCategory": "Default category",
  "admin.certCategoriesTitle": "CREDENTIAL CATEGORIES",
  "cq.assignCred": "Assign Credential",
  "cq.assignCredTitle": "ASSIGN CREDENTIAL TO CREW",
  "cq.searchMember": "Search crew member…",
  "cq.selectMember": "Select member",
  "admin.qrScanHint": "Scan → available: launch flow · your boat out: return flow · someone else's: shows status.",
  "admin.printPdf": "Print / PDF",
  "qr.scanTitle": "Scan boat QR",
  "qr.scanBtn": "📷 Scan QR",
  "qr.starting": "Starting camera…",
  "qr.loading": "Loading QR decoder…",
  "qr.loadFailed": "Could not load QR decoder — check your connection",
  "qr.scanning": "Point camera at QR code",
  "qr.noCamera": "Camera not available on this device",
  "qr.permDenied": "Camera permission denied — allow access and try again",
  "qr.error": "Camera error",
  "qr.boatNotFound": "Scanned boat not found",
  "qr.boatOutByOther": "{name} has this boat out",
  "qr.boatOos": "This boat is out of service",
  "qr.invalidCode": "QR code is not a boat code",
  "admin.ownerClub": "Club boat",
  "admin.ownerPrivate": "Private boat",
  "admin.searchMember": "Search member...",
  "admin.oosReason": "OOS reason",
  "admin.openingChecklist": "OPENING CHECKLIST",
  "admin.closingChecklist": "CLOSING CHECKLIST",
  "admin.homePort": "Home port",
  "admin.loadFailed": "Load failed",
  "admin.nameKtRequired": "Name and kennitala required.",
  "admin.nameKeyRequired": "Name and key required.",
  "admin.nameRequired": "Name required.",
  "admin.textENRequired": "English text required.",
  "admin.memberDatesRequired": "Member and dates required.",
  "admin.categoryExists": "Category already exists.",
  "admin.categoryAdded": "Category added.",
  "admin.categoryRemoved": "Category removed.",
  "admin.certDefSaved": "Credential type saved.",
  "admin.parseError": "Parse error",
  "admin.importing": "Importing…",
  "admin.importFailed": "Import failed",
  "admin.importComplete": "Import complete: {added} added, {updated} updated.",
  "admin.importDeactivated": "{count} deactivated.",
  "admin.confirmDeactivateMember": "Deactivate this member?",
  "admin.confirmRemoveBoatCat": "Remove this category? Boats assigned to it will still exist but may show under 'other'.",
  "admin.confirmDeleteBoat": "Delete this boat?",
  "admin.confirmDeleteLocation": "Delete this location?",
  "admin.confirmDeleteItem": "Delete this item?",
  "admin.confirmDeleteActType": "Delete this activity? Any linked volunteer events will also be removed.",
  "admin.confirmDeleteActTypeCascade": "This will also remove {n} volunteer event(s) and {m} signup(s). Continue?",
  "admin.actTypeDeletedCascade": "Activity deleted — also removed {n} volunteer event(s) and {m} signup(s).",
  "admin.confirmRemoveCategory": "Remove this category?",
  "admin.confirmDeleteCertDef": "Delete this credential type? This won't remove existing assignments.",
  "admin.confirmResetFlags": "Reset all flag settings to defaults?",
  "admin.noCategories": "No categories.",
  "admin.noItems": "No items.",
  "admin.noActTypes": "No activities.",
  "admin.noCertCategories": "No categories defined. Defaults will be used.",
  "admin.noCertDefs": "No credential types defined.",
  "admin.noSubcategories": "No subcategories",
  "admin.noSubtypes": "No subtypes yet.",
  "admin.boatCatModal.edit": "Edit Category",
  "admin.clModal.edit": "Edit Item",
  "admin.lcModal.add": "Add Item",
  "admin.lcModal.edit": "Edit Item",
  "admin.actTypeModal.edit": "Edit Type",
  "admin.optionNone": "— none —",
  "admin.certCategoryNone": "None",
  "staff.departurePort": "Departure Port",
  "staff.recentIn": "In",
  "staff.recentMember": "Member",
  "staff.recentBoat": "Boat",
  "staff.recentArea": "Sailing area",
  "staff.recentDuration": "Duration",
  "member.departurePort": "Departure Port",
  "member.homePort": "Home port",
  "member.back": "Back",
  "member.continue": "Continue →",
  "member.noChecklist": "No pre-launch checklist configured for this category.",
  "member.confirmAllItems": "Please confirm all items.",
  "daily.linkSelected": "Link selected",
  "daily.group": "group",
  "daily.groups": "groups",
  "nav.captainQuarters": "Captain's Quarters",
  "cq.title": "Captain's Quarters",
  "cq.subtitle": "Keelboat captain dashboard",
  "cq.ytdHours": "YTD HOURS",
  "cq.ytdDistance": "YTD DISTANCE",
  "cq.ytdTrips": "YTD TRIPS",
  "cq.nm": "nm",
  "cq.hrs": "hrs",
  "cq.maintTitle": "KEELBOAT MAINTENANCE",
  "cq.maintOpen": "Open",
  "cq.maintClosed": "Closed",
  "cq.maintAll": "All",
  "cq.noMaint": "No maintenance requests.",
  "cq.validationTitle": "VALIDATION REQUESTS",
  "cq.noValidation": "No pending validation requests.",
  "cq.crewTitle": "CREW APPROVALS",
  "cq.noCrew": "No pending crew approvals.",
  "cq.bioTitle": "BIO & PROFILE",
  "cq.bioPlaceholder": "Write a short bio that appears on your public captain profile…",
  "cq.headshotLabel": "Profile photo (max 5 MB)",
  "cq.bioSaved": "Bio saved",
  "cq.headshotUploaded": "Photo uploaded",
  "cq.boatsTitle": "MY BOATS",
  "cq.noBoats": "No private boats registered.",
  "cq.makeUnavailable": "Mark unavailable",
  "cq.makeAvailable": "Mark available",
  "cq.changePort": "Change home port",
  "cq.reservations": "CHARTERS",
  "cq.addReservation": "Add Charter",
  "cq.resStartDate": "Start date",
  "cq.resEndDate": "End date",
  "cq.resNote": "Note (optional)",
  "cq.resMember": "Member",
  "tc.skipper": "Skipper",
  "tc.crew": "Crew",
  "tc.helm": "Helm",
  "tc.student": "Student",
  "tc.guest": "Guest",
  "tc.me": "Me",
  "tc.nonClub": "Non-club",
  "tc.pending": "pending",
  "tc.verificationPending": "Verification pending",
  "tc.requestVerification": "Request verification",
  "tc.windSpeed": "Wind speed",
  "tc.direction": "Direction",
  "tc.gusts": "Gusts",
  "tc.conditions": "Conditions",
  "tc.airTemp": "Air temp",
  "tc.feelsLike": "Feels like",
  "tc.seaTemp": "Sea temp",
  "tc.waveHeight": "Wave height",
  "tc.pressure": "Pressure",
  "tc.weatherFlag": "Weather flag",
  "tc.departurePort": "Departure port",
  "tc.arrivalPort": "Arrival port",
  "tc.crewAboard": "Crew aboard",
  "tc.regNo": "Registration no.",
  "tc.sailNo": "Sail no.",
  "tc.typeModel": "Type / model",
  "tc.loa": "LOA",
  "tc.distance": "Distance",
  "tc.gpsTrack": "GPS Track",
  "tc.deleteTrack": "Delete track",
  "tc.clickToExpand": "Click to expand",
  "tc.downloadFile": "Download file",
  "tc.viewTrack": "View track",
  "tc.skipperNote": "Skipper's comments",
  "tc.visibleToCrew": "visible to crew",
  "tc.fromSkipper": "from skipper",
  "tc.noNoteYet": "No note yet",
  "tc.edit": "Edit",
  "tc.privateNote": "Personal comments",
  "tc.onlyYou": "only you",
  "tc.noPrivateNoteYet": "No note yet",
  "tc.photos": "Photos",
  "tc.delete": "Delete",
  "tc.shared": "Shared",
  "tc.private": "Private",
  "tc.club": "Club",
  "tc.editTrip": "✏️ Edit trip",
  "tc.addGps": "📍 Add GPS",
  "tc.addPhotos": "📷 Add photos",
  "tc.boatDetails": "Boat Details",
  "tc.tripDetails": "Trip Details",
  "tc.departed": "Departed",
  "tc.returned": "Returned",
  "tc.sailingArea": "Sailing area",
  "tc.duration": "Duration",
  "tc.weather": "Weather",
  "tc.notesPhotosTrack": "Notes, Photos & Track",
  "maint.sevHint.low": "Minor issue — no immediate action required.",
  "maint.sevHint.medium": "Functional issue, usable with care.",
  "maint.sevHint.high": "Significant problem — assess before use.",
  "maint.sevHint.critical": "Safety risk — take out of service immediately.",
  "maint.oosTag": "OOS",
  "maint.inService": "In service",
  "maint.confirmBtn": "Confirm",
  "maint.cancelBtn": "Cancel",
  "maint.defaultAuthor": "Staff",
  "maint.deleteComment": "Delete comment",
  "maint.addCommentPh": "Add comment…",
  "maint.postBtn": "Post",
  "maint.postingBtn": "Posting…",
  "maint.approvingBtn": "Approving…",
  "maint.approveBtn": "Approve",
  "maint.saumaBadge": "Saumaklúbbur",
  "maint.onHoldBadge": "On Hold",
  "maint.noVerkstjori": "No verkstjóri assigned",
  "maint.adoptProject": "Adopt Project",
  "maint.reportedByLabel": "Reported by",
  "maint.pendingReview": "Pending staff review",
  "maint.pendingReviewAlert": "{count} saumaklúbbur project(s) awaiting staff review — tap to review",
  "maint.markCompleted": "Mark Completed",
  "maint.markResolved2": "Mark Resolved",
  "maint.resumeBtn": "Resume",
  "maint.putOnHold": "Put On Hold",
  "maint.deleteBtn": "Delete",
  "maint.completedStatus": "Completed",
  "maint.resolvedStatus": "Resolved",
  "maint.severityLabel": "Severity",
  "maint.priorityLabel": "Priority",
  "maint.changeSevConfirm": "Change severity to \"{sev}\" without resolving?",
  "maint.adoptConfirm": "Become verkstjóri for this project?",
  "maint.deleteCommentConfirm": "Delete this comment?",
  "maint.holdConfirm": "Put this project on hold?",
  "maint.resumeConfirm": "Resume this project?",
  "maint.completeConfirm": "Mark this project as completed?",
  "maint.resolveConfirm2": "Mark this issue as resolved?",
  "maint.deleteConfirm": "Delete this issue? This cannot be undone.",
  "maint.returnToService": "Return to service without resolving?",
  "maint.markOosConfirm": "Mark as Out of Service without resolving?",
  "maint.maxFileSize": "Max 5 MB",
  "maint.materials": "MATERIALS",
  "maint.addMaterialPh": "e.g. Sandpaper 120-grit…",
  "maint.addMaterialBtn": "+ Add",
  "maint.removeMaterial": "Remove material",
  "maint.removeMaterialConfirm": "Remove this material?",
  "maint.editTitle": "Edit request",
  "maint.untitled": "Untitled request",
  "maint.updated": "Updated ✓",
  "alert.overdueTitle": "OVERDUE BOATS",
  "alert.minOverdue": "{n} min overdue",
  "alert.hrsOverdue": "{h}h {m}min overdue",
  "alert.guardian": "Guardian:",
  "alert.snoozedPill": "Snoozed — reappears in {n} min",
  "alert.snoozeBtn": "Snooze {n}m",
  "alert.silenceBtn": "Silence",
  "wx.staffOnDuty": "Staff on duty",
  "wx.supportBoatOut": "Support boat on the water",
  "wx.poorVisibility": "Poor visibility",
  "wx.reducedVisibility": "Reduced visibility",
  "wx.overrideBadge": "OVERRIDE",
  "wx.overrideBy": "Set by {name}",
  "wx.overrideResetsMidnight": "Reverts at midnight UTC",
  "wx.autoScoreWouldBe": "AUTOMATIC SCORE",
  "tc.flagGreen": "Green",
  "tc.flagYellow": "Yellow",
  "tc.flagOrange": "Orange",
  "tc.flagRed": "Red",
  "tc.flagBlack": "Black",
  "logbook.deleteTrack": "Delete this GPS track?",
  "logbook.deletePhoto": "Delete this photo?",
  "logbook.revokeLink": "Revoke this link?",
  "logbook.noFilter": "No trips match this filter.",
  "logbook.loadingTrips": "Loading recent trips…",
  "logbook.noClubTrips": "No recent club trips found.",
  "logbook.ports": "PORTS",
  "logbook.portsOptional2": "PORTS — OPTIONAL",
  "logbook.helmLabel": "Helm",
  "logbook.studentLabel": "Student",
  "logbook.errKtOrPhone": "Please enter a kennitala/birth year or phone number.",
  "logbook.errSaveFailed": "Save failed: {msg}",
  "logbook.errFailed": "Failed: {msg}",
  "guest.title":       "Add guest",
  "guest.intro":       "This person is not in the member list. Enter their details to add them as a guest.",
  "guest.ktOrYear":    "Kennitala or birth year",
  "guest.phone":       "Phone number",
  "guest.addBtn":      "Add guest",
  "logbook.readingFile": "Reading file…",
  "logbook.fileReady": "Ready: {name}",
  "logbook.readError": "Read error",
  "logbook.noTripSelected": "No trip selected",
  "logbook.sendingRequest": "Sending request…",
  "logbook.requestSent": "Request sent to skipper ✓",
  "logbook.addToLogbook": "Add to my logbook",
  "logbook.alreadyInLog": "This trip is already in your logbook.",
  "logbook.requestToJoin": "Request to join",
  "logbook.errDepartureTime": "Invalid departure time (HH:MM).",
  "logbook.errReturnTime": "Invalid return time (HH:MM).",
  "logbook.errDate": "Please enter a date.",
  "logbook.errBoat": "Please select a boat.",
  "logbook.errSkipper": "Please select a skipper.",
  "logbook.errDuplicate": "You already have a trip logged with this boat on this date. Please check your logbook.",
  "logbook.uploading": "Uploading…",
  "logbook.uploadNoConfig": "File upload not configured — trip saved without attachment.",
  "logbook.gpsUploadFailed": "GPS upload failed: {msg}",
  "logbook.photoNoConfig": "File upload not configured",
  "logbook.photoUploadFailed": "Photo upload failed: {msg}",
  "logbook.saveToLogbook": "Save to logbook",
  "logbook.showLess": "Show less",
  "logbook.showMore": "Show more",
  "logbook.departure": "Departure",
  "logbook.arrival": "Arrival",
  "logbook.trackDeleted": "Track deleted",
  "logbook.photoDeleted": "Photo deleted",
  "logbook.upTo": "Up to",
  "logbook.views": "views",
  "logbook.copy": "Copy",
  "logbook.revoke": "Revoke",
  "logbook.linkRevoked": "Link revoked.",
  "logbook.loadFailed": "Could not load logbook: {msg}",
  "logbook.loadFailed2": "Could not load: {msg}",
  "logbook.studentBadge": "Student badge",
  "logbook.tripVerification": "Trip verification",
  "logbook.from": "from",
  "logbook.confirmed": "Confirmed ✓",
  "logbook.rejected": "Rejected",
  "logbook.skipperNoteLabel": "Skipper's comments (visible to crew):",
  "logbook.privateNoteLabel": "Personal comments (only you):",
  "logbook.noteSaved": "Note saved",
  "logbook.dismissed": "Dismissed",
  "logbook.allDismissed": "All dismissed",
  "logbook.onlySkipper": "Only the skipper can edit this trip",
  "logbook.selectBoat": "Select boat…",
  "logbook.selectLocation": "Select location…",
  "logbook.editTripTitle": "Edit trip",
  "logbook.saveChanges": "Save changes",
  "logbook.saving": "Saving…",
  "logbook.tripUpdated2": "Trip updated",
  "logbook.uploadingTrack": "Uploading GPS track…",
  "logbook.uploadFailed": "Upload failed",
  "logbook.trackAdded2": "GPS track added",
  "logbook.addPhotosTitle": "Add photos",
  "logbook.photoHint": "Shared photos are visible to other trip members. Club-use photos may be used for promotional purposes.",
  "logbook.uploadPhotos": "Upload photos",
  "logbook.noPhotosSelected": "No photos selected",
  "logbook.photosAdded2": "Photos added",
  "logbook.uploadFailed2": "Upload failed: {msg}",
  "logbook.windLabel": "Wind ({unit})",
  "logbook.gustsLabel": "Gusts ({unit})",
  "logbook.crewSearchPh": "Crew member {n} — search by name…",
  "logbook.addAsGuest": "+ Add \"{name}\" as guest",
  "logbook.portAdded": "Port added ✓",
  "logbook.verificationReq": "Verification requested",
  "logbook.errGeneric": "Error: {msg}",
  "member.gpsTrackLabel": "GPS TRACK — GPX/KML",
  "member.photosLabel": "PHOTOS",
  "member.distanceLabel": "DISTANCE (NM)",
  "member.arrivalPortLabel": "ARRIVAL PORT",
  "member.sameAsDeparture": "Same as departure",
  "member.reportDamage": "Report damage",
  "member.reportIncident": "Report incident",
  "member.helmLabel": "HELM",
  "member.youLabel": "(you)",
  "member.loadingCrew": "Loading crew…",
  "member.skipperNotes": "SKIPPER'S COMMENTS",
  "member.notesVisibleAll": "Visible to everyone on this trip.",
  "member.notesPlaceholder": "Trip note (visible to crew)",
  "member.personalNotes": "PERSONAL COMMENTS",
  "member.onlyVisibleYou": "Only visible to you",
  "member.guestLabel": "Guest",
  "member.noNamedCrew": "No named crew",
  "member.readingFile": "Reading…",
  "member.fileReady": "Ready: {name}",
  "member.readError": "Read error",
  "member.gpsNoConfig": "GPS upload not configured",
  "member.gpsUploadFailed": "GPS upload failed: {msg}",
  "member.photoNoConfig": "Photo upload not configured",
  "member.photoUploadFailed": "Photo upload failed: {msg}",
  "member.checkInBtn": "Check In",
  "staff.boatNotFound": "Boat not found.",
  "staff.groupCheckoutTitle": "Group Checkout",
  "staff.selectBoats": "Select boats",
  "staff.participants": "Participants (Iðkendur)",
  "staff.activityType": "Activity",
  "staff.errSelectBoat": "Select at least one boat.",
  "staff.errSailingArea": "Select a sailing area.",
  "staff.errStaffRequired": "At least one staff member on water is required.",
  "staff.errStaffFromList": "Please select staff from the list: {names}",
  "staff.groupLaunched": "Group launched ✓",
  "staff.searchStaff": "Search staff name…",
  "staff.addAsGuest": "+ Add \"{name}\" as guest",
  "staff.crewSearchPh": "Crew member {n} — search by name…",
  "staff.errKtOrPhone": "Please enter a kennitala/birth year or phone number.",
  "staff.guestSaveFailed": "Failed to save guest: {msg}",
  "staff.checkInClose": "Check in & close",
  "staff.noActivities": "No activities in today's log yet.",
  "staff.linkedDailyLog": "Linked to daily log ✓",
  "staff.payrollUnavail": "Payroll not available — deploy backend first",
  "staff.onWaterTotal": "{n} on water total, {b} {boatWord}",
  "staff.boat": "boat",
  "staff.boats": "boats",
  "staff.peopleOnWater": "people on water",
  "staff.checkInAll": "Check In All",
  "staff.noneOption": "— None —",
  "staff.oosTitle": "Out of service",
  "staff.alreadyOut": "Already out",
  "staff.staffOnDuty": "Staff on duty",
  "staff.noStaffOnDuty": "No staff on duty",
  "staff.supportBoat": "Support boat on the water",
  "staff.noSupportBoat": "No support boat on the water",
  "staff.updatedShort": "Upd.",
  "staff.flagOverrideLabel": "WEATHER FLAG OVERRIDE",
  "staff.flagOverrideHint": "Using live scoring. Set an override to post a staff-picked flag + note until midnight.",
  "staff.flagOverrideSet": "Set override",
  "staff.flagOverrideClear": "Clear override",
  "staff.flagOverrideNotes": "Notes (shown to members)",
  "staff.flagOverrideNotesIS": "Notes (Icelandic)",
  "staff.flagOverrideSave": "Save override",
  "staff.flagOverrideMidnight": "Auto-reverts to live data at midnight UTC.",
  "staff.flagOverrideBy": "By {name}",
  "staff.flagOverrideSaveFail": "Override saved — sync when online",
  "staff.guardianLabel": "Guardian",
  "staff.phoneLabel": "Phone",
  "staff.expectedBack": "Expected back",
  "staff.overdueBy": "Overdue by",
  "staff.hrsMin": "{h}h {m}min",
  "staff.minOnly": "{m} min",
  "staff.snoozeBtn": "Snooze ({n} min)",
  "staff.silenceBtn": "Silence",
  "maint.noFilterMatch": "No requests match this filter.",
  "maint.loadFailed": "Failed to load: {msg}",
  "maint.errCategory": "Please select a category.",
  "maint.errSeverity": "Please select a severity level.",
  "maint.errDescription": "Please describe the issue.",
  "maint.errBoat": "Please select a boat.",
  "maint.imgTooLarge": "Image too large ({size} MB). Max is 5 MB.",
  "maint.submitting": "Submitting…",
  "maint.uploadingPhoto": "Uploading photo…",
  "maint.submitBtn": "Submit",
  "maint.submitted": "Request submitted ✓",
  "maint.resolvedToast": "Resolved ✓",
  "maint.commentAdded": "Comment added.",
  "cert.removeConfirm": "Remove this credential?",
  "cq.allBoats": "All boats",
  "cq.allYears": "All years",
  "cq.allCategories": "All categories",
  "cq.allCaptains": "All captains",
  "cq.allMembers": "All members",
  "cq.fileTooLarge": "File too large (max 5 MB)",
  "cq.memberDatesRequired": "Member and dates required.",
  "cq.noTripsMatch": "No trips match this filter.",
  "cq.crewJoinRequest": "Requesting to join as crew",
  "cq.crewAssignPending": "Crew assignment pending",
  "wx.fetching": "Fetching weather data…",
  "wx.updating": "Updating…",
  "wx.checkConnection": "Check connection and try again.",
  "wx.failed": "Failed",
  "wx.refresh": "Refresh",
  "wx.pressureUnavail": "Pressure data unavailable",
  "wx.useMyLocation": "📍 My location",
  "wx.useFossvogur": "⚓ Fossvogur",
  "wx.locating": "Locating…",
  "wx.geoUnavailable": "Geolocation not available",
  "wx.geoDenied": "Location denied or unavailable",
  "wx.myLocation": "My location",
  "wx.openForecast": "Full forecast →",
  "logrev.noMemberSelected": "No member selected.",
  "logrev.memberNotFound": "Member not found.",
  "logrev.credentialRemoved": "Credential removed",
  "sauma.imgTooLarge": "Image too large. Max is 5 MB.",
  "sauma.submitting": "Submitting…",
  "sauma.uploadingPhoto": "Uploading photo…",
  "sauma.submitted": "Project submitted for review.",
  "sauma.selectCategory": "Please select a category.",
  "sauma.selectPriority": "Please select a priority.",
  "sauma.describeProject": "Please describe the project.",
  "sauma.selectBoat": "Please select a boat.",
  "passport.title": "ROWING PASSPORT",
  "passport.historyNote": "history",
  "passport.signerMode": "Sign-off mode — tap items to sign.",
  "passport.confirmSign": "Sign off this passport item?",
  "passport.signed": "Signed off.",
  "passport.promoted": "Passport complete — promoted to Released Rower!",
  "passport.adminTitle": "Rowing Passport",
  "passport.importCsv": "Import CSV",
  "passport.exportCsv": "Export CSV",
  "passport.csvHelp": "Columns: passport_id, category_id, category_label_en, category_label_is, item_id, assessment, module, item_label_en, item_label_is, description_en, description_is. Only item_label_en is required per row — item_id and category_id are auto-generated from the English label if blank (re-used from existing items with matching labels so old sign-offs stay valid). assessment is 'theory' or 'practical' (defaults to 'practical'). module is a positive integer reflecting the teaching order (blank or 0 = unassigned); modules cross-cut categories.",
  "passport.theory": "Theoretical",
  "passport.practical": "Practical",
  "passport.viewMember": "VIEW MEMBER",
  "passport.viewSelf": "My passport",
  "passport.revokeReason": "Reason for revoking this sign-off?",
  "passport.revoked": "Sign-off revoked.",
  "passport.addCategory": "+ Add category",
  "passport.addItem": "+ Add item",
  "passport.retire": "Retire",
  "passport.unretire": "Restore",
  "passport.save": "Save changes",
  "passport.saved": "Passport saved.",
  "passport.unsavedChanges": "You have unsaved changes. Discard?",
  "passport.editSettings": "Edit passport settings",
  "passport.settingsTitle": "Passport settings",
  "passport.nameEN": "Name (English)",
  "passport.nameIS": "Name (Icelandic)",
  "passport.requiredSigs": "Required signatures",
  "passport.promoteCertId": "Promotes certificate",
  "passport.fromSub": "From sub-category",
  "passport.toSub": "To sub-category",
  "passport.itemTitle": "Passport item",
  "passport.itemNameEN": "Item name (English)",
  "passport.itemNameIS": "Item name (Icelandic)",
  "passport.itemDescEN": "Description (English)",
  "passport.itemDescIS": "Description (Icelandic)",
  "passport.assessmentType": "Assessment type",
  "passport.categoryTitle": "Passport category",
  "passport.categoryNameEN": "Category name (English)",
  "passport.categoryNameIS": "Category name (Icelandic)",
  "passport.deleteCategory": "Delete category",
  "passport.confirmDeleteCategory": "Delete this category and all its items?",
  "passport.confirmDeleteItem": "Delete this item? Items with existing sign-offs are retired instead.",
  "passport.retiredBadge": "retired",
  "passport.noDescription": "No description",
  "passport.editItem": "Edit",
  "passport.editCategory": "Edit category",
  "passport.activeCount": "active",
  "passport.requiresSignatures": "requires {n} signatures",
  "passport.promotesTo": "promotes {cert}",
  "passport.newItem": "New item",
  "passport.newCategory": "New category",
  "passport.itemDeleted": "Item removed.",
  "passport.itemRetiredSoft": "Item retired (existing sign-offs preserved).",
  "passport.categoryDeleted": "Category removed.",
  "passport.nameRequired": "English name is required.",
  "passport.idReadOnly": "ID (read-only)",
  "passport.itemModule": "Module (teaching order)",
  "passport.moduleLabel": "Module",
  "passport.moduleShort": "Mod",
  "passport.unassignedModule": "Unassigned module",
  "passport.sortBy": "Sort by",
  "passport.sortCatMod": "Category → Module",
  "passport.sortModCat": "Module → Category",
  "passport.addItemHint": "Add a new item to a category:",

  "admin.tabVolunteers": "Volunteers",
  "admin.volunteerType": "Volunteer activity",
  "admin.volEventsTitle": "VOLUNTEER EVENTS",
  "admin.addVolEvent": "+ Add event",
  "admin.volEventModal.add": "Add Volunteer Event",
  "admin.volEventModal.edit": "Edit Event",
  "admin.volTitle": "Title (EN)",
  "admin.volTitleIS": "Title (IS)",
  "admin.volDate": "Date",
  "admin.volEndDate": "End date (optional)",
  "admin.volEndDateHint": "Leave blank for a single-day event",
  "admin.volStartTime": "Start time",
  "admin.volEndTime": "End time",
  "admin.volActType": "Activity",
  "admin.volActTypeNone": "— None —",
  "admin.volRoles": "ROLES",
  "admin.volRoleName": "ROLE (EN)",
  "admin.volRoleNameIS": "ROLE (IS)",
  "admin.volRoleDescEN": "DESCRIPTION (EN)",
  "admin.volRoleDescIS": "DESCRIPTION (IS)",
  "admin.volRolePickPreset": "— Pick standard role —",
  "admin.volSlots": "SLOTS",
  "admin.volLeader": "Person in charge",
  "admin.volLeaderPhone": "Phone number",
  "admin.volShowPhone": "Show phone on event card",
  "admin.volNotes": "Notes (EN)",
  "admin.volNotesIS": "Notes (IS)",
  "admin.noVolEvents": "No volunteer events.",
  "admin.confirmDeleteVolEvent": "Delete this volunteer event?",
  "admin.volSignups": "signups",
  "admin.noRoles": "No roles defined.",
  "admin.roleEndorsement": "Required endorsement",
  "admin.roleNoRestriction": "— No restriction —",
  "admin.bulkUsesDefaultTimes": "Uses default times",
  "admin.bulkSetDefaultTimes": "Set default start/end times above to use with bulk schedule.",
  "admin.volFromActType": "FROM ACTIVITY TYPE",
  "admin.volShowPast": "Show past events ({n})",
  "admin.volHidePast": "Hide past events",

  "member.volunteerEvents": "VOLUNTEER EVENTS",
  "member.volSignUp": "Sign up",
  "member.volWithdraw": "Withdraw",
  "member.volFull": "Full",
  "member.volSignedUp": "Signed up",
  "member.volSlotsLeft": "{n} left",
  "member.volLeader": "In charge",
  "member.volNeedsEndorsement": "Endorsement required",
  "member.noVolEvents": "No upcoming volunteer events.",
  "member.calendar": "Calendar",
  "member.calTitle": "CLUB CALENDARS",
  "member.calEmpty": "No calendars have been set up yet.",
  "member.calOpen": "Open in Google Calendar",
  "nav.volunteer": "Volunteer",
  "volunteer.title": "Volunteer",
  "volunteer.subtitle": "Sign up to help out at club events",
  "volunteer.tabList": "List",
  "volunteer.tabCalendar": "Calendar",
  "volunteer.upcoming": "UPCOMING EVENTS",
  "volunteer.inCharge": "In charge",
  "volunteer.me": "Me",
  "volunteer.more": "more",
  "volunteer.youSignedUp": "You're signed up",
  "volunteer.noEventsThisDay": "No events on this day.",
  "volunteer.filterAll": "All",
  "volunteer.filterMine": "My events",
  "volunteer.noMyEvents": "You haven't signed up for any upcoming events.",
  "volunteer.showMore": "Show more ({n})",
  "volunteer.unfilledRoles": "open volunteer slots",
  "admin.tabCalendars": "Calendars",
  "admin.calDesc": "Add Google Calendar IDs that members can view from the member hub. Each calendar appears as an embedded view.",
  "admin.calName": "Name",
  "admin.calId": "Calendar ID",
  "admin.calPlaceholder": "e.g. abc123@group.calendar.google.com",
  "admin.calAdd": "+ Add calendar",
  "admin.calEmpty": "No calendars added.",
  "admin.calRemove": "Remove",

  "member.notifPending": "pending",
  "sauma.follow": "★ Follow",
  "sauma.unfollow": "★ Following",
  "sauma.followed": "Following project ★",
  "sauma.unfollowed": "Unfollowed project"
};
