var _STRINGS_FLAT = {
  "nav.staffHub": "Vakt",
  "nav.memberHub": "Forsíða",
  "nav.admin": "Stjórn",
  "nav.logbook": "Siglingabók",
  "nav.signOut": "Skrá út",
  "nav.langToggle": "EN",
  "btn.save": "Vista",
  "btn.saveClose": "Vista & loka",
  "btn.cancel": "Hætta við",
  "btn.delete": "Eyða",
  "btn.edit": "Breyta",
  "btn.add": "+ Bæta við",
  "btn.close": "Loka",
  "btn.confirm": "Staðfesta",
  "btn.signOff": "Vista & Undirrita",
  "btn.submit": "Senda inn",
  "btn.viewAll": "Sjá allt →",
  "lbl.loading": "Hleður…",
  "lbl.on": "Kveikt",
  "lbl.off": "Slökkt",
  "lbl.noData": "Engin gögn",
  "lbl.unknown": "Óþekkt",
  "lbl.name": "Nafn",
  "lbl.date": "Dagsetning",
  "lbl.time": "Tími",
  "lbl.notes": "Athugasemdir",
  "lbl.phone": "Sími",
  "lbl.email": "Netfang",
  "lbl.location": "Staðsetning",
  "lbl.boat": "Bátur",
  "lbl.crew": "Áhöfn",
  "lbl.role": "Hlutverk",
  "lbl.member": "Félagi",
  "lbl.guest": "Gestur",
  "lbl.guardian": "Forráðamaður",
  "lbl.minor": "Ólögráða",
  "lbl.verified": "✓ Staðfest",
  "lbl.optional": "valfrjálst",
  "lbl.filter": "SÍA:",
  "lbl.active": "Virkt",
  "lbl.category": "Flokkur",
  "lbl.description": "Lýsing",
  "lbl.severity": "Alvarleiki",
  "lbl.type": "Tegund",
  "lbl.sortOrder": "Röðun",
  "lbl.selectDots": "Veldu…",
  "lbl.noneDash": "— ekkert —",
  "msg.unsavedChanges": "Þú átt óvistaðar breytingar. Henda þeim?",
  "toast.saved": "Vistað",
  "toast.saveFailed": "Mistókst að vista",
  "toast.deleted": "Eytt",
  "toast.error": "Eitthvað fór úrskeiðis. Reyndu aftur.",
  "toast.loadFailed": "Hleðsla mistókst",
  "toast.signedOff": "Undirritað ✓",
  "toast.checkedIn": "Skráð inn ✓",
  "wx.wind": "VINDUR",
  "wx.gusts": "HVIÐA",
  "wx.waves": "BYLGJUR",
  "wx.pressure": "LOFTÞRÝSTINGUR",
  "wx.loading": "Sæki veðurgögn…",
  "wx.unavailable": "⚠️ Veður ekki tiltækt",
  "wx.birkConditions": "BIRK — Aðstæður",
  "wx.airTemp": "LOFTHITI",
  "wx.conditions": "AÐSTÆÐUR",
  "wx.sea": "SJÓR",
  "wx.surface": "Yfirborð",
  "wx.force": "Vindstig",
  "wx.feelsLike": "líður eins og {t}°",
  "wx.birkObs": "BIRK mælingar",
  "wx.pressureRising": "hækkun",
  "wx.pressureFalling": "lækkun",
  "wx.pressureSteady": "stöðugt",
  "wx.noScoring": "Engin stigagjöf.",
  "wx.totalScore": "Heildarstig",
  "wx.scoreBreakdown": "STIGAÚTREIKNINGUR",
  "wx.justNow": "Rétt á þessu",
  "wx.minAgo": "fyrir {n} mín",
  "wx.hrAgo": "fyrir {n} klst",
  "wx.noStaffOnDuty": "Enginn starfsmaður á vakt",
  "wx.noSupportBoat": "Enginn gæslubátur á sjó",
  "wx.pts": "stig",
  "wx.bft0": "Logn",
  "wx.bft1": "Andvari",
  "wx.bft2": "Kul",
  "wx.bft3": "Gola",
  "wx.bft4": "Stinningsgola",
  "wx.bft5": "Kaldi",
  "wx.bft6": "Stinningskaldi",
  "wx.bft7": "Allhvass vindur",
  "wx.bft8": "Hvassviðri",
  "wx.bft9": "Stormur",
  "wx.bft10": "Rok",
  "wx.bft11": "Ofsaveður",
  "wx.bft12": "Fárviðri",
  "wx.bdWind": "Vindur Vindstig {n} ({desc})",
  "wx.bdEasterly": "Austlægur vindur ({dir})",
  "wx.bdGusts": "Hviður Vindstig {n} (sust. Vindstig {sust})",
  "wx.bdWaves": "Bylgjur {h} m",
  "wx.bdSst": "Sjávarhiti {t}°C",
  "wx.bdFeelsLike": "Líður eins og {t}°C",
  "login.subtitle": "Siglingafélagið",
  "login.kennitala": "Kennitala",
  "login.placeholder": "0000000000",
  "login.username": "Notandanafn",
  "login.usernamePlaceholder": "Kennitala eða upphafsstafir",
  "login.password": "Lykilorð",
  "login.passwordPlaceholder": "Lykilorð",
  "login.stayLoggedIn": "Halda mér innskráðum á þessu tæki",
  "login.usernameRequired": "Sláðu inn kennitölu eða upphafsstafi.",
  "login.passwordRequired": "Sláðu inn lykilorð.",
  "login.badPassword": "Rangt lykilorð.",
  "login.ambiguous": "Fleiri en einn félagi er með þessa upphafsstafi — skráðu þig inn með kennitölu.",
  "login.btn": "Skrá inn",
  "login.loading": "Skrái inn…",
  "login.notFound": "Félagi finnst ekki eða aðgangur er óvirkur.",
  "login.tooShort": "Vinsamlegast sláðu inn 10 stafa kennitölu.",
  "login.error": "Innskráning mistókst. Reyndu aftur.",
  "login.rateLimited": "Of margar misheppnaðar tilraunir. Reyndu aftur eftir 15 mínútur.",
  "login.welcome": "Velkomin/n,",
  "login.chooseView": "Hvernig viltu skrá þig inn?",
  "login.chooseAccount": "Hvaða aðgang viltu opna?",
  "login.changePw.title": "veldu lykilorð",
  "login.changePw.hint": "Þú ert skráð/ur inn með sameiginlegu lykilorði félagsins. Veldu þitt eigið áður en þú heldur áfram.",
  "login.changePw.save": "Vista og halda áfram",
  "login.yourAccount": "Þinn aðgangur",
  "login.guardianAccount": "Stillingar forráðamanns",
  "login.wardMinor": "barn",
  "login.wardSwitchError": "Ekki tókst að skipta yfir á þann aðgang.",
  "login.back": "← Skrá inn sem annan notandi",
  "guardian.sub": "Opnaðu aðgang barns eða stilltu þína eigin innskráningu.",
  "guardian.noWards": "Engin virk börn eru tengd kennitölunni þinni.",
  "guardian.loadError": "Ekki tókst að sækja börnin þín. Reyndu aftur.",
  "nav.actingAs": "Skráð(ur) inn sem {name}",
  "nav.backToGuardian": "↶ Til baka á {name}",
  "login.admin.label": "Stjórnborð",
  "login.admin.desc": "Stjórna félaga, bátum, stöðum, stillingum",
  "login.staff.label": "Starfsmannaþjónusta",
  "login.staff.desc": "Daglegur rekstur, flotinn, atvik",
  "login.member.label": "Félagssvæði",
  "login.member.desc": "Inn/útskráning, dagbók, mínar ferðir",
  "member.launchBoat": "Fara á sjó",
  "member.reportIssue": "Tilkynna viðhaldsmál",
  "member.myCheckout": "BÁTAR Á SJÓNUM",
  "member.myCheckoutSub": "smelltu á bát til að skrá inn",
  "member.tabFleet": "Flotinn",
  "member.tabCerts": "Skírteini",
  "member.fleetAvail": "LAUSIR BÁTAR",
  "member.noCheckouts": "Engir bátar á sjó.",
  "member.noBoats": "Engir bátar lausir.",
  "member.departed": "Lagt af stað",
  "member.returned": "Komið tilbaka",
  "member.launchTitle": "Fara á sjó",
  "member.nonClubBoat": "Bátur utan félags",
  "member.nonClubHint": "Notaðu þinn eigin bát eða bát frá öðru félagi",
  "member.checkInTitle": "Skrá inn",
  "member.manualTrip": "Skrá siglingu",
  "member.pendingConfirmations": "Beiðnir í bið",
  "member.confirmationsTitle": "Staðfestingar siglinga",
  "member.incoming": "BEIÐNIR TIL ÞÍN",
  "member.outgoing": "ÞÍNAR BEIÐNIR",
  "member.noIncoming": "Engar beiðnir í bið.",
  "member.noOutgoing": "Engar beiðnir sendar.",
  "member.crewAssigned": "skráði þig sem áhöfn",
  "member.crewJoin": "vill taka þátt í siglingu þinni",
  "member.helmReq": "merkti þig sem stýrimann",
  "member.crewAssignedOut": "Þú skráðir {name} sem áhöfn",
  "member.crewJoinOut": "Þú baðst um að taka þátt í siglingu {name}",
  "member.helmReqOut": "Þú merktir {name} sem stýrimann",
  "member.crewDeclined": "hafnaði þátttöku — fjöldi áhafnar uppfærður",
  "member.confirmBtn": "Staðfesta",
  "member.rejectBtn": "Hafna",
  "member.ackBtn": "Skil",
  "member.statusPending": "í bið",
  "member.statusRejected": "hafnað",
  "member.rejectReason": "Ástæða höfnunar (valfrjálst):",
  "settings.title": "Stillingar",
  "settings.initials": "Upphafsstafir",
  "settings.initialsHint": "Sjálfvirkt búið til úr nafni. Breyttu hér að neðan.",
  "settings.language": "Tungumál",
  "settings.windUnit": "Vindeining",
  "settings.windUnit.bft": "Beaufort (Force 4)",
  "settings.windUnit.ms": "m/s",
  "settings.windUnit.kts": "Hnútar",
  "settings.windUnit.kmh": "km/klst",
  "settings.windUnit.mph": "mph",
  "settings.windUnitHint": "Stýrir hvernig vindur birtist í dagbókinni þinni.",
  "settings.theme": "Útlit",
  "settings.theme.dark": "Dökkt",
  "settings.theme.light": "Ljóst",
  "settings.theme.auto": "Sjálfvirkt",
  "settings.privacy": "Persónuvernd",
  "settings.sharePhoneVol": "Deila síma með sjálfboðaumsjón",
  "settings.sharePhoneVolHint": "Þegar kveikt er á þessu birtist símanúmerið þitt við hliðina á nafninu þínu í skráningarlistanum í stjórnborðinu, svo að umsjónarmenn geti náð í þig.",
  "settings.logbookPage": "Dagbókarsíða",
  "settings.showHeatmap": "Sýna persónulegt hitakort",
  "settings.showHeatmapHint": "Þegar kveikt er á þessu birtist kort af siglingum þínum og GPS-ferlum efst á dagbókarsíðunni.",
  "settings.stats": "Tölfræði sýnileiki",
  "settings.statsHint": "Veldu hvaða tölfræði birtist á dagbókarsíðunni þinni.",
  "settings.stats.ytd": "Siglingar á þessu ári",
  "settings.stats.career": "Samtals siglingar (ferill)",
  "settings.stats.hours": "Siglingatímar",
  "settings.stats.skipper": "Sem skipstjóri",
  "settings.stats.byCategory": "Tímar eftir bátaflokki",
  "settings.stats.distance": "Heildar vegalengd (nm)",
  "settings.stats.longest": "Lengsta sigling",
  "settings.stats.avgWind": "Meðalvindur",
  "settings.stats.streak": "Vikuleg röð",
  "settings.stats.boats": "Einstök bátar sigld",
  "settings.stats.crew": "Siglingar sem áhöfn",
  "settings.stats.heavy": "Hörð veður (F5+)",
  "settings.stats.avgDuration": "Meðal siglingatími",
  "settings.stats.locations": "Staðir sigldir",
  "settings.stats.verified": "Staðfestar siglingar",
  "settings.stats.helmHours": "Tímar við stýri",
  "settings.stats.student": "Siglingar sem nemandi",
  "settings.stats.favBoat": "Uppáhalds bátur",
  "settings.stats.favLocation": "Uppáhalds staður",
  "settings.stats.peakWind": "Hámarksvindur",
  "settings.statsGroup.activity": "Virkni",
  "settings.statsGroup.sailing": "Sigling",
  "settings.statsGroup.roles": "Hlutverk og bátar",
  "settings.statsGroup.conditions": "Aðstæður",
  "settings.statsGroup.other": "Annað",
  "settings.saved": "Stillingar vistaðar",
  "settings.saveFailed": "Mistókst að vista stillingar",
  "settings.signIn": "Innskráning",
  "settings.usernameStyle": "Notandanafn",
  "settings.usernameStyle.kt": "Kennitala",
  "settings.usernameStyle.initials": "Upphafsstafir",
  "settings.usernameStyleHint": "Bæði virka við innskráningu; þetta er bara áminning fyrir þig.",
  "settings.stayLoggedIn": "Halda mér innskráðum á þessu tæki",
  "settings.stayLoggedInHint": "Festu síðuna á heimaskjáinn og hún hegðar sér eins og app — þú þarft ekki að skrá þig inn í hvert sinn.",
  "settings.currentPassword": "Núverandi lykilorð",
  "settings.newPassword": "Nýtt lykilorð",
  "settings.confirmPassword": "Staðfestu nýtt lykilorð",
  "settings.changePassword": "Breyta lykilorði",
  "settings.passwordHint": "Veldu eitthvað sem einungis þú veist — að lágmarki 4 stafir.",
  "settings.passwordChanged": "Lykilorði breytt.",
  "settings.passwordTooShort": "Lykilorð verður að vera að lágmarki 4 stafir.",
  "settings.passwordMismatch": "Ný lykilorð passa ekki saman.",
  "settings.passwordWrongCurrent": "Núverandi lykilorð er rangt.",
  "settings.passwordSaveFailed": "Ekki tókst að breyta lykilorði.",
  "settings.passwordChangedSignedOut": "Lykilorði breytt. Önnur tæki skráð út: {n}.",
  "settings.signInActivity": "Virk innskráning",
  "settings.signInActivityHint": "Tækin sem eru skráð inn með þínum aðgangi núna. Skráðu út þau sem þú þekkir ekki.",
  "settings.signInActivityEmpty": "Engar virkar lotur.",
  "settings.signInActivityError": "Ekki tókst að sækja virkar lotur.",
  "settings.signInActivityCurrent": "Þessi búnaður",
  "settings.signInActivityLastSeen": "Síðast virk",
  "settings.signInActivityCreated": "Skráð inn",
  "settings.signInActivitySignOut": "Skrá út",
  "settings.signOutEverywhereElse": "Skrá út af öllum öðrum tækjum",
  "settings.signOutEverywhereElseConfirm": "Skrá út af öllum öðrum tækjum? Þú verður áfram skráð/ur inn á þessu tæki.",
  "settings.signedOutEverywhereElse": "Skráð út af {n} tækjum.",
  "nav.settings": "Stillingar",
  "logbook.shareBtn": "Deila dagbókinni þinni",
  "logbook.sharePhotos": "Taka myndir með",
  "logbook.shareTracks": "Taka GPS-leiðir með",
  "logbook.shareCopy": "Búa til og afrita hlekk",
  "logbook.exportCsv": "Hlaða niður sem CSV",
  "logbook.noTrips": "Engar ferðir",
  "logbook.shareCopied": "Hlekkur afritaður!",
  "logbook.activeTokens": "Virk deilingartóken",
  "logbook.shareWithCrew": "Deila með áhöfn",
  "logbook.clubMayUse": "Félagið má nota",
  "logbook.sectTitle": "Siglingabók",
  "logbook.filterAllYears": "Öll ár",
  "logbook.filterAllBoats": "Allir bátar",
  "logbook.filterAnyRole": "Öll hlutverk",
  "logbook.filterRoleSkipper": "Skipari",
  "logbook.filterRoleCrew": "Áhöfn",
  "logbook.filterAnyWind": "Allur vindur",
  "logbook.filterWindCalm": "Logn (Vindstig 0–2)",
  "logbook.filterWindLight": "Hægur (Vindstig 3–4)",
  "logbook.filterWindModerate": "Miðlungs (Vindstig 5–6)",
  "logbook.filterWindStrong": "Hvass (Vindstig 7+)",
  "logbook.filterWindGt4": "Yfir vindstig 4",
  "logbook.filterWindLte4": "Vindstig 4 eða minna",
  "logbook.searchPh": "Leita…",
  "logbook.searchByNamePh": "Leita eftir nafni…",
  "logbook.loading": "Hleður…",
  "wx.condClearSky": "Heiðskírt",
  "wx.condMainlyClear": "Léttskýjað",
  "wx.condPartlyCloudy": "Skýjað að hluta",
  "wx.condOvercast": "Alskýjað",
  "wx.condFog": "Þoka",
  "wx.condDrizzle": "Súld",
  "wx.condRain": "Rigning",
  "wx.condSnow": "Snjókoma",
  "wx.condThunderstorm": "Þrumuveður",
  "wx.loadingWeather": "Sæki veðurgögn…",
  "staff.dashTitle": "Stjórnborð starfsmanna",
  "staff.fleet": "STAÐA FLOTANS",
  "staff.recentCheckins": "NÝLEGAR INNSKRÁNINGAR (24H)",
  "staff.maintenance": "OPIN VIÐHALDSMÁL",
  "staff.dailyLog": "Dagbók félagsins",
  "staff.dailyLogDesc": "Sjávarfjalla- og veðurskráning, gátlistar, starfsemi, undirskrift",
  "staff.logbook": "Dagbókarskoðun",
  "staff.logbookDesc": "Staðfesta ferðir félaga og úthluta skírteinum",
  "staff.incidents": "Atvik",
  "staff.incidentsDesc": "Skrá eða fara yfir öryggisatvik",
  "staff.noOverdue": "Engar yfirtíma útskráningar.",
  "staff.noMaint": "Engar opnar beiðnir.",
  "staff.checkIn": "✓ Skrá inn",
  "staff.deleteCheckout": "Eyða",
  "staff.activeCheckouts": "VIRKAR ÚTSKRÁNINGAR",
  "staff.boatsOutNow": "BÁTAR Á SJÓNUM",
  "staff.checkOutBtn": "Uthluta bati",
  "staff.groupCheckout": "Hópaúthlutun",
  "staff.newCheckout": "NÝ ÚTSKRÁNING",
  "staff.statBoats": "BÁTAR Á SJÓ",
  "staff.statPeople": "FÓLK Á SJÓ",
  "staff.statOverdue": "YFIRTÍMA",
  "staff.toolsLabel": "VERKFÆRI",
  "staff.coForm.departure": "Brottför",
  "staff.coForm.estReturn": "Áætl. heimkoma",
  "staff.coForm.crew": "Áhöfn um borð",
  "staff.coForm.notes": "Athugasemdir (valfrjálst)",
  "staff.coForm.submit": "Útskrá",
  "staff.coForm.memberPlaceholder": "Nafn eða kennitala…",
  "staff.coForm.notesPlaceholder": "Einhverjar athugasemdir…",
  "staff.coForm.errMember": "Veldu félaga.",
  "staff.coForm.errBoat": "Veldu bát.",
  "staff.coForm.errLocation": "Veldu siglingasvæði.",
  "staff.coForm.checkedOut": "Útskráð ✓",
  "staff.coDetail.tripLabel": "FERÐ",
  "staff.coDetail.out": "FÓRT",
  "staff.coDetail.return": "ÁÆTL. HEIMKOMA",
  "daily.today": "Í dag",
  "daily.tripsToday": "FERÐIR Í DAG",
  "daily.openingChecklist": "OPNUNARGÁTLISTI",
  "daily.closingChecklist": "LOKUNARGÁTLISTI",
  "daily.activities": "STARFSEMI",
  "daily.addActivity": "+ Bæta við",
  "daily.staffNotes": "ATHUGASEMDIR STARFSMANNA",
  "daily.notesPlaceholder": "Almennar athugasemdir, samantekt á aðstæðum…",
  "daily.incidentReport": "ATVIK",
  "daily.noIncidents": "Engin atvik tilkynnt.",
  "daily.wxLog": "VEÐURSKRÁNING",
  "daily.tides": "FLÓÐ OG EBB",
  "daily.signedOff": "Undirritað",
  "daily.readOnly": "Lesaðgangur",
  "daily.noActivities": "Engin starfsemi skráð enn.",
  "daily.noTrips": "Engar ferðir skráðar í dag.",
  "daily.activityModal": "Bæta við starfsemi",
  "daily.actType": "Tegund",
  "daily.actNameLabel": "Nafn / lýsing",
  "daily.actNameHint": "t.d. Unglingakennsla, félagskeppni…",
  "daily.actParticipants": "Þátttakendur",
  "daily.actPartHint": "t.d. 12 unglingar",
  "daily.actNotes": "Athugasemdir",
  "daily.actNotesHint": "valfrjálst",
  "daily.startTime": "Byrjunartími",
  "daily.endTime": "Lokatími",
  "daily.wxLogBtn": "📸 Taka veðurmynd",
  "daily.signOffConfirm": "PM gátlisti er ekki fullkláraður ({done}/{total}). Undirrita samt?",
  "daily.signOffSaving": "Undirritun…",
  "daily.signedOffBy": "✓ Undirritað af ",
  "incident.title": "Atvik",
  "incident.viewList": "Skoða atvik",
  "incident.fileNew": "Skrá nýja skýrslu",
  "incident.typeLabel": "Tegund atviks",
  "incident.noIncidents": "Engin atvik skráð.",
  "incident.description": "Lýsing",
  "incident.witnesses": "Vitni",
  "incident.immediateAction": "Bráðabirgðaaðgerðir",
  "incident.followUp": "Nauðsynleg eftirfylgni",
  "incident.staffNotes": "Athugasemdir starfsmanna",
  "incident.resolved": "Lokið",
  "incident.open": "Opið",
  "incident.markResolved": "Ljúka yfirferð, vista og skrá",
  "incident.markOpen": "Enduropna",
  "incident.filedBy": "Skráð af",
  "incident.boatLabel": "Bátur (ef við á)",
  "incident.personsInvolved": "Aðilar að máli",
  "incident.witnessHint": "Nöfn / tengiliðaupplýsingar…",
  "incident.actionHint": "Skyndihjálp, rýming, landhelgisgæslan…",
  "incident.followUpHint": "Tilvísun, viðgerð, rannsókn…",
  "incident.handoffSection": "Framsending",
  "incident.handoffTo": "Framselt til",
  "incident.handoffName": "Nafn tengiliðar / tilvísun",
  "incident.handoffNotes": "Athugasemdir um framsendingu",
  "incident.descRequired": "Lýsing er skylda.",
  "incident.typeRequired": "Veldu að minnsta kosti eina tegund atviks.",
  "incident.sevRequired": "Veldu alvarleika.",
  "incident.filed": "Skýrsla skráð ✓",
  "incident.type.injury": "🩹 Meiðsli",
  "incident.type.capsize": "⛵ Kæning",
  "incident.type.collision": "💥 Árekstur",
  "incident.type.equipment": "🔧 Búnaðarbilun",
  "incident.type.medical": "🏥 Læknisfræðilegt",
  "incident.type.nearMiss": "⚡️ Nákvæmt miss",
  "incident.type.missing": "🔍 Saknað manneskja",
  "incident.type.propertyDmg": "🏗️ Eignatjón",
  "incident.type.stranding": "⚓️ Strand",
  "incident.type.other": "📌 Annað",
  "incident.saveCloseFile": "Vista, loka og skrá",
  "incident.saveForReview": "Vista til eftirfylgni / yfirferðar",
  "incident.statusReview": "Þarf yfirferð eða eftirfylgni",
  "incident.reviewerNotes": "Athugasemdir yfirferðar",
  "incident.addReviewerNote": "Bæta við athugasemd",
  "incident.sev.low": "Lágt",
  "incident.sev.medium": "Miðlungs",
  "incident.sev.high": "Hátt",
  "incident.sev.critical": "Bráðavarsamt",
  "maint.category": "Flokkur",
  "maint.part": "Staðsetning / hluti",
  "maint.resolveConfirm": "Merkja þessa beiðni sem lokna?",
  "sauma.pageTitle": "🧵 Saumaklúbbur",
  "sauma.pageSubtitle": "Samfélagsverkefni í viðhaldi",
  "sauma.verkstjori": "Verkstjóri",
  "sauma.verkstjoriHint": "Ef autt, getur hvaða félagi sem er tekið verkefnið að sér.",
  "sauma.filterOpen": "Opið",
  "sauma.filterMy": "Mín verkefni",
  "sauma.filterUnassigned": "Ótilnefnd",
  "sauma.filterCompleted": "Lokið",
  "sauma.filterAll": "Allt",
  "sauma.needsVerkstjori": "Þarf verkstjóra",
  "sauma.emptyDefault": "Engin verkefni passa við þessa síu.",
  "sauma.emptyMy": "Engin verkefni sem þú tekur þátt í.",
  "sauma.suggestBtn": "+ Nýtt saumaklúbbsverkefni",
  "sauma.suggestTitle": "🧵 Nýtt saumaklúbbsverkefni",
  "sauma.priority": "Forgangur",
  "sauma.description": "Lýsing",
  "sauma.materials": "Efni sem þarf",
  "sauma.photoLabel": "Mynd (valfrjálst, hámark 5 MB)",
  "sauma.viewList": "Listi",
  "sauma.viewBoard": "Borð",
  "sauma.colTodo": "Verkefni",
  "sauma.colInProgress": "Í vinnslu",
  "sauma.colOnHold": "Í bið",
  "sauma.colDone": "Lokið",
  "sauma.colEmpty": "Engin verkefni",
  "sauma.myBoardFilter": "Aðeins mín verkefni",
  "sauma.filterOnHold": "Í bið",
  "sauma.filterMyProjects": "Mín verkefni",
  "sauma.filterPending": "Bíður skoðunar",
  "sauma.catBoat": "⛵ Bátur",
  "sauma.catEquipment": "🦺 Búnaður",
  "sauma.catFacility": "🏠 Hús",
  "sauma.selectBoatPh": "Veldu bát…",
  "sauma.partPh": "t.d. skrokkur, mastur, þak félagsheimilis…",
  "sauma.descPh": "Lýstu verkefninu…",
  "sauma.materialPh": "t.d. Sandpappír 120…",
  "sauma.pendingReview": "⏳ Bíður skoðunar starfsmanna",
  "sauma.completedBy": "✓ Lokið {date} af {by}",
  "sauma.verkstjoriLabel": "Verkstjóri:",
  "sauma.loadFailed": "Gat ekki hlaðið: {msg}",
  "maint.pageTitle": "🔧 Viðhald",
  "maint.newBtn": "+ Ný viðhaldsbeiðni",
  "maint.newSaumaBtn": "🧵 Nýtt saumaklúbbsverkefni",
  "maint.newTitle": "🔧 Ný viðhaldsbeiðni",
  "maint.statOpen": "OPNAR",
  "maint.statCritical": "ALVARLEG",
  "maint.statOos": "BÁTAR ÚR ÞJÓNUSTU",
  "maint.statPending": "BÍÐA SKOÐUNAR",
  "maint.statResolved": "LOKIÐ",
  "maint.groupStatus": "STAÐA",
  "maint.groupType": "TEGUND",
  "maint.groupCategory": "FLOKKUR",
  "maint.groupSeverity": "ALVARLEIKI",
  "maint.groupSauma": "SAUMAKLÚBBUR",
  "maint.filterOpen": "Opið",
  "maint.filterResolved": "Lokið",
  "maint.filterMaintenance": "Viðhald",
  "maint.filterSauma": "🧵 Saumaklúbbur",
  "maint.filterCatBoat": "Bátar",
  "maint.filterCatEquipment": "Búnaður",
  "maint.filterCatFacility": "Hús",
  "maint.filterCritical": "Alvarlegt",
  "maint.filterHigh": "Hátt",
  "maint.filterMedium": "Miðlungs",
  "maint.filterLow": "Lágt",
  "maint.filterUnassigned": "Ótilnefnd",
  "maint.filterMyProjects": "Mín verkefni",
  "maint.filterPending": "Bíður skoðunar",
  "maint.catBoat": "⛵ Bátur",
  "maint.catEquipment": "🦺 Búnaður",
  "maint.catFacility": "🏠 Hús",
  "maint.boatLabel": "Bátur",
  "maint.selectBoatPh": "Veldu bát…",
  "maint.markOosLabel": "Merkja bát úr þjónustu?",
  "maint.markOosHint": "Taka þennan bát úr þjónustu þar til viðgert",
  "maint.partPh": "t.d. skrokkur, mastur, þak félagsheimilis…",
  "maint.severity": "Alvarleiki",
  "maint.priority": "Forgangur",
  "maint.sevLow": "LÁGT",
  "maint.sevMedium": "MIÐLUNGS",
  "maint.sevHigh": "HÁTT",
  "maint.sevCritical": "ALVARLEGT",
  "maint.description": "Lýsing",
  "maint.descPh": "Lýstu vandamálinu…",
  "maint.verkstjoriLabel": "Verkstjóri (verkefnisstjóri)",
  "maint.verkstjoriPh": "Nafn eða skildu eftir autt…",
  "maint.materialPh": "t.d. Sandpappír 120…",
  "maint.photoLabel": "Mynd (valfrjálst, hámark 5 MB)",
  "maint.verkstjoriPrefix": "Verkstjóri:",
  "maint.completedBy": "✓ Lokið {date} af {by}",
  "maint.resolvedBy": "✓ Lokið {date} af {by}",
  "maint.attachPhoto": "Hengja mynd við",
  "nav.saumaklubbur": "Saumaklúbbur",
  "staff.maintAndSauma": "Viðhald & Verkefni",
  "staff.maintAndSaumaDesc": "Viðhaldsbeiðnir & saumaklúbbsverkefni",
  "logrev.title": "Dagbókarskoðun",
  "logrev.subtitle": "Staðfesta ferðir félaga · úthluta skírteinum",
  "logrev.pending": "BÍÐUR SKOÐUNAR",
  "logrev.verified": "STAÐFEST",
  "logrev.verify": "Staðfesta",
  "logrev.unverify": "Afstaðfesta",
  "logrev.staffComment": "Athugasemd starfsmanns (valfrjálst)",
  "logrev.noTrips": "Engar ferðir til skoðunar.",
  "logrev.filterAll": "Allt",
  "logrev.filterPending": "Í bið",
  "logrev.filterVerified": "Staðfest",
  "logrev.filterName": "Sía eftir nafni…",
  "logrev.filterFrom": "Frá",
  "logrev.filterTo": "Til",
  "logrev.assignCert": "ÚTHLUTA SKÍRTEINI",
  "logrev.assignedDate": "Úthlutunardagur",
  "logrev.expires": "Rennur út",
  "logrev.assignBtn": "Úthluta",
  "logrev.certModal": "Skírteini",
  "logrev.validationRequests": "Beiðnir um staðfestingu",
  "logrev.showAll": "Sýna allar ferðir",
  "logrev.certSearch": "Leitaðu að félaga hér að ofan til að skoða skírteini.",
  "logrev.certSearchPlaceholder": "Leita að nafni félaga...",
  "logrev.certNoMatches": "Engir félagar fundust með þetta skírteini.",
  "logrev.verifyRequest": "STAÐFESTINGARBEIÐNI",
  "admin.tabMembers": "Félagar",
  "admin.tabSettings": "Stillingar",
  "admin.tabBoats": "Bátar",
  "admin.tabLocations": "Staðir",
  "admin.tabChecklists": "Gátlistar",
  "admin.tabActTypes": "Tegundir starfsemi",
  "admin.tabCerts": "Skírteini",
  "admin.tabAlerts": "Viðvaranir",
  "admin.tabPayroll": "Launakerfi",
  "admin.tabFlags": "Fánar",
  "admin.tabReservations": "Leigur",
  "admin.bulkSchedule": "FJÖLDATÍMASETNING",
  "admin.chartersDesc": "Leigutímar eru endurteknir, bókanlegir tímaramar sem skipstjórar geta bókað fyrir róðrarlið eða einkaleigu. Búðu til endurtekið mynstur til að gera tíma aðgengilega á völdum dögum.",
  "admin.importCsv": "⇪ Flytja inn CSV",
  "admin.searchMembers": "Leita að nafni eða kennitölu…",
  "admin.noMembers": "Engir félagar ennþá.",
  "admin.addMember": "+ Bæta við félaga",
  "admin.addLocation": "+ Bæta við stað",
  "admin.addItem": "+ Bæta við atriði",
  "admin.addType": "+ Bæta við tegund",
  "admin.alertFirstMins": "Fyrsta viðvörun eftir (mín)",
  "admin.alertRepeatMins": "Endurtaka á (mín)",
  "admin.alertSnoozeMins": "Frestunarlengd (mín)",
  "admin.alertEnabled": "Viðvaranir virkar",
  "admin.memberModal.add": "Bæta við félaga",
  "admin.memberModal.edit": "Breyta félaga",
  "admin.guardianName": "Nafn forráðamanns",
  "admin.guardianPhone": "Sími forráðamanns",
  "admin.guardianKt": "Kennitala forráðamanns",
  "admin.boatModal.add": "Bæta við bát",
  "admin.boatModal.edit": "Breyta bát",
  "admin.boatCategory": "Flokkur",
  "admin.boatOos": "Utan þjónustu",
  "admin.locModal.add": "Bæta við stað",
  "admin.locModal.edit": "Breyta stað",
  "admin.clPhase": "Fasi",
  "admin.clTextEN": "Texti (EN)",
  "admin.clTextIS": "Texti (IS)",
  "admin.actTypeEN": "Nafn (EN)",
  "admin.actTypeIS": "Nafn (IS)",
  "admin.certTypes": "TEGUNDIR SKÍRTEINA",
  "admin.certAddType": "+ Bæta við tegund skírteinis",
  "admin.certAddModal": "Bæta við tegund skírteinis",
  "admin.certEditModal": "Breyta tegund skírteinis",
  "admin.certDescOptional": "(valfrjálst)",
  "admin.noBoats": "Engir bátar.",
  "admin.noLocations": "Engir staðir.",
  "admin.backToList": "← Aftur á lista",
  "admin.importFromCsv": "Flytja inn úr Abler.io CSV",
  "cert.noCerts": "Engin skírteini skráð.",
  "cert.level": "Stig / Undirflokkur",
  "cert.assign": "Úthluta",
  "cert.assigned": "Skírteini úthlutað.",
  "cert.removed": "Skírteini fjarlægt.",
  "cert.typeRequired": "Veldu tegund skírteinis.",
  "cert.levelRequired": "Veldu stig / undirflokk.",
  "cert.clubEndorsements": "ÁRITANIR KLÚBBSINS",
  "cert.loadError": "Gat ekki hlaðið skírteinum.",
  "payroll.tabTimeReporting": "Tímaskráning",
  "payroll.tabEmployees": "Starfsmenn",
  "payroll.periodFrom": "Frá",
  "payroll.periodTo": "Til",
  "payroll.noPeriodDefined": "Ekkert launatímabil skilgreint enn.",
  "payroll.editEntry": "Breyta",
  "payroll.notEnabled": "Ekki í launakerfi",
  "payroll.enablePayroll": "Virkja í launakerfi",
  "payroll.calView": "Dagatal",
  "payroll.listView": "Listi",
  "payroll.addEntry": "+ Bæta við færslu",
  "payroll.deleteEntry": "Eyða",
  "payroll.deleteConfirm": "Eyða þessari tímafærslu?",
  "payroll.allStaff": "Allir starfsmenn",
  "payroll.employee": "Starfsmaður",
  "payroll.totalHours": "samtals",
  "payroll.clockInLabel": "Stimpla inn",
  "payroll.clockOutLabel": "Stimpla út",
  "payroll.minsLabel": "Tímalengd (mínútur)",
  "payroll.noteOptional": "Athugasemd (valfrjálst)",
  "payroll.notePlaceholder": "t.d. gleymt innstimpl",
  "payroll.autoCalc": "reiknast sjálft, hnekktu ef þarf",
  "payroll.entryRequired": "Starfsmaður, innstimplun og útstimplun eru nauðsynleg.",
  "payroll.clockOutAfterIn": "Útstimplun verður að vera eftir innstimplun.",
  "payroll.moreEntries": "í viðbót",
  "payroll.titleField": "Starfsheiti",
  "lbl.duration": "Tímalængd",
  "lbl.edited": "breytt",
  "lbl.admin": "stjórnandi",
  "lbl.staff": "starfsmaður",
  "lbl.monShort": "Mán",
  "lbl.tueShort": "Þri",
  "lbl.wedShort": "Mið",
  "lbl.thuShort": "Fim",
  "lbl.friShort": "Fös",
  "lbl.satShort": "Lau",
  "lbl.sunShort": "Sun",
  "payroll.section": "STIMPILKLUKKA",
  "payroll.clockIn": "Stimpla inn",
  "payroll.clockOut": "Stimpla út",
  "payroll.startBreak": "Fara í hlé",
  "payroll.endBreak": "Ljúka hlé",
  "payroll.onBreak": "Í hléi síðan",
  "payroll.clockedInAt": "Stimplaðist inn",
  "payroll.recentShifts": "Nýlegar vaktir",
  "payroll.noShifts": "Engar vaktir skráðar",
  "payroll.shiftSummary": "Samantekt vaktar",
  "payroll.totalWorked": "Vann samtals",
  "payroll.totalBreak": "Hlé samtals",
  "payroll.confirmShift": "Loka",
  "payroll.allowBreaks": "Leyfa hléaskráningu",
  "payroll.export": "Senda út",
  "payroll.externalUrl": "Slóð á ytra launakerfi",
  "payroll.externalUrlHint": "Google Apps Script vefforrit sem tekur við tímagögnunum.",
  "payroll.exportSent": "Tímagögn send ✓",
  "payroll.exportFailed": "Útflutningur mistókst",
  "payroll.urlNotSet": "Settu inn slóð á ytra launakerfi fyrst.",
  "logbook.nonClubToggle": "Ferð utan félags",
  "logbook.nonClubHint": "— skrá ferð utan félagskerfisins",
  "logbook.boatNameLabel": "Nafn báts",
  "logbook.boatNamePh": "t.d. Sunfish, RIB, o.þ.h.",
  "logbook.boatCategory": "Flokkur",
  "logbook.locationNamePh": "t.d. Þingvallavatn",
  "logbook.useMyLocation": "Nota staðsetningu mína",
  "logbook.locating": "Staðsetning…",
  "logbook.locationDenied": "Staðsetningaraðgangur hafnaður",
  "logbook.enterBoatName": "Vinsamlegast sláðu inn nafn báts.",
  "logbook.enterLocation": "Vinsamlegast sláðu inn staðsetningu.",
  "boat.registrationNo": "Skráningarnúmer",
  "boat.sailNo": "Seglnúmer",
  "boat.loa": "Heildarlengd (fet)",
  "boat.typeModel": "Tegund / gerð",
  "boat.defaultPort": "Heimahöfn",
  "location.type": "Tegund",
  "location.typePort": "Höfn",
  "location.typeLocation": "Siglingasvæði",
  "location.lat": "Breiddargráða",
  "location.lng": "Lengdargráða",
  "fleet.badgeAvail": "LAUST",
  "fleet.badgeOut": "ÚTI",
  "fleet.badgeOverdue": "TÍMABÆRT",
  "fleet.badgeOos": "ÓTÆ.",
  "fleet.badgeYours": "ÞITT",
  "fleet.aboard": "{n} um borð",
  "fleet.outTime": "Út {t}",
  "fleet.checkIn": "Skrá inn",
  "fleet.delete": "Eyða",
  "fleet.badgeChartered": "LEIGÐUR",
  "fleet.badgePrivate": "EINKABÁTUR",
  "fleet.ownedBy": "Eigandi: {name}",
  "fleet.actionCheckout": "Útskrá",
  "fleet.actionMaint": "Beiðni um viðhald",
  "fleet.actionMarkOos": "Merkja ótiltækan",
  "fleet.actionMarkAvail": "Merkja tiltækan",
  "boat.ownership": "Eignarhald",
  "boat.owner": "Eigandi",
  "boat.accessMode": "Aðgangshamur",
  "boat.accessFree": "Frjáls aðgangur",
  "boat.accessControlled": "Stýrður aðgangur",
  "boat.gateCert": "Nauðsynleg vottun",
  "boat.gateCertNone": "Ekkert (aðeins listi)",
  "boat.gateCertAny": "hvaða stig sem er",
  "boat.gateCertOrHigher": "eða hærra",
  "boat.allowlist": "Leyfilegir meðlimir",
  "boat.reservations": "Úthluta leigu",
  "boat.addReservation": "Bæta við leigu",
  "boat.removeReservation": "Fjarlægja",
  "boat.reservationSaved": "Leiga vistuð",
  "boat.reservationRemoved": "Leiga fjarlægð",
  "boat.reservedFor": "Leigður til {name}",
  "boat.reservedUntil": "til {date}",
  "fleet.badgeControlled": "STÝRT",
  "fleet.badgeRestricted": "TAKMARKAÐ",
  "fleet.badgeAuthorized": "HEIMILAÐ",
  "boat.slotScheduling": "Virkja tímabókun",
  "boat.availOutside": "Tiltækt utan áætlaðra tíma",
  "boat.availOutsideHint": "Ef ekki merkt, er báturinn aðeins tiltækur á bókuðum tímum.",
  "day.mon": "Mán",
  "day.tue": "Þri",
  "day.wed": "Mið",
  "day.thu": "Fim",
  "day.fri": "Fös",
  "day.sat": "Lau",
  "day.sun": "Sun",
  "month.jan": "jan",
  "month.feb": "feb",
  "month.mar": "mar",
  "month.apr": "apr",
  "month.may": "maí",
  "month.jun": "jún",
  "month.jul": "júl",
  "month.aug": "ágú",
  "month.sep": "sep",
  "month.oct": "okt",
  "month.nov": "nóv",
  "month.dec": "des",
  "slot.filterBoat": "Bátur",
  "slot.filterCrew": "Áhöfn",
  "slot.allBoats": "Allir bátar",
  "slot.today": "Í dag",
  "slot.addRecurring": "+ Endurtekið",
  "slot.addSingle": "+ Stakur",
  "slot.selectBoatFirst": "Veldu tiltekinn bát fyrst",
  "slot.noSlotBoats": "Engir bátar með tímabókun virka",
  "slot.boat": "Bátur",
  "slot.recurTitle": "Búa til endurtekna tíma",
  "slot.editTitle": "Tímabil",
  "slot.newTitle": "Nýr tími",
  "slot.daysOfWeek": "Vikudagar",
  "slot.startTime": "Byrjunartími",
  "slot.endTime": "Lokatími",
  "slot.fromDate": "Frá dagsetningu",
  "slot.toDate": "Til dagsetningar",
  "slot.note": "Athugasemd",
  "slot.preview": "Forskoðun",
  "slot.create": "Búa til",
  "slot.selectDays": "Veldu amk einn dag og tímabil",
  "slot.previewCount": "{count} tímar verða búnir til",
  "slot.created": "{count} tímar búnir til",
  "slot.missingFields": "Dagsetning og tímar eru nauðsynlegir",
  "slot.confirmDelete": "Eyða þessum tíma?",
  "slot.bookedBy": "Bókað af",
  "slot.legendOpen": "Laust",
  "slot.legendYours": "Þitt",
  "slot.legendBooked": "Bókað",
  "slot.booked": "Tími bókaður!",
  "slot.unbooked": "Bókun afturkölluð",
  "slot.confirmUnbook": "Afturkalla þessa bókun?",
  "slot.yours": "ÞITT",
  "slot.date": "Dagsetning",
  "slot.bulkBook": "Fjöldabókun",
  "slot.bulkTitle": "Fjöldabókun tíma",
  "slot.bulkPreview": "{open} lausir tímar af {total} verða bókaðir",
  "slot.bulkNoSlots": "Engir lausir tímar passa við valin skilyrði",
  "slot.bulkBooked": "{count} tímar bókaðir!",
  "slot.bulkPartial": "{booked} bókaðir, {skipped} þegar teknir",
  "slot.createAndBook": "+ Ný bókun",
  "slot.createAndBookTitle": "Búa til og bóka tíma",
  "slot.createdAndBooked": "Tími búinn til og bókaður!",
  "slot.conflict": "Þessi tími skarast við annan tíma á þessum báti",
  "cq.reservationsTitle": "LEIGUR",
  "nav.coxswainSeat": "Róðrardeild",
  "cox.title": "Róðrardeild",
  "cox.tabCrews": "Hópar og tímar",
  "cox.tabPassport": "Passi",
  "cox.statsTrips": "FERÐIR",
  "cox.statsHours": "KLST.",
  "cox.statsDist": "VEGALENGD",
  "cox.maintenance": "VIÐHALD",
  "cox.readOnly": "Aðeins skoðun — krefst útgefinn róðramaður réttinda",
  "cox.noCrewsShort": "Engir hópar — búðu til einn fyrst",
  "cox.createCrewFirst": "Búðu til hóp fyrst til að bóka tíma",
  "cox.noMaint": "Engar viðhaldsbeiðnir.",
  "cox.createCrew": "+ Búa til hóp",
  "cox.createCrewTitle": "Búa til hóp",
  "cox.crewName": "Nafn hóps",
  "cox.crewNameRequired": "Nafn hóps er nauðsynlegt",
  "cox.openSpots": "laus",
  "cox.active": "VIRKT",
  "cox.forming": "Í MÓTUN",
  "cox.inviteMember": "Bjóða meðlim",
  "cox.searchMember": "Meðlimur",
  "cox.pairAssignment": "Par",
  "cox.sendInvite": "Senda boð",
  "cox.selectMember": "Veldu meðlim",
  "cox.selectPair": "Veldu par",
  "cox.inviteSent": "Boð sent!",
  "cox.pendingInvites": "BOÐANIR Í BIÐ",
  "cox.invitedBy": "Boðið af",
  "cox.accept": "Samþykkja",
  "cox.reject": "Hafna",
  "cox.inviteAccepted": "Boð samþykkt!",
  "cox.inviteRejected": "Boði hafnað.",
  "cox.disband": "Leysa upp",
  "cox.confirmDisband": "Leysa upp þennan hóp? Þetta er ekki afturkræft.",
  "cox.crewDisbanded": "Hópur leystur upp.",
  "cox.crewBoard": "ÁHAFNABORÐ",
  "cox.crewBoardEmpty": "Engir hópar ennþá. Búðu til einn eða bíddu eftir öðrum.",
  "cox.boat": "Bátur",
  "cox.bow": "Framstafn",
  "cox.stern": "Aftarstafn",
  "cox.join": "Ganga í",
  "cox.leave": "Hætta",
  "cox.joined": "Gekk í hóp!",
  "cox.left": "Hætti í hóp.",
  "cox.confirmLeave": "Hætta í þessum hóp?",
  "cox.description": "Lýsing",
  "cox.descPlaceholder": "t.d., Mán & Mið 7:00, hægur gangur",
  "cox.visibility": "Sýnileiki",
  "cox.visOpen": "Opið — allir geta gengið í",
  "cox.visInvite": "Aðeins boðið",
  "cox.yourSeat": "Þitt sæti",
  "cox.seatBow": "Framstafn",
  "cox.seatStern": "Aftarstafn",
  "cox.numBoats": "Fjöldi báta",
  "cox.needsMore": "vantar {n} í viðbót",
  "cox.crewColor": "Litur",
  "cq.bookingColor": "Bókunarlitur minn",
  "cox.tentative": "BRÁÐABIRGÐA",
  "cox.slotReservations": "BÓKANIR Á TÍMUM",
  "pub.dash.subtitle": "Siglingafélagið Ýmir",
  "pub.dash.ytdTrips": "Siglingar á tímabilinu",
  "pub.dash.totalHours": "Klukkustundir á sjó",
  "pub.dash.byCategory": "Eftir bátategund",
  "pub.dash.locations": "Hvar við siglum",
  "pub.dash.onWater": "Á sjónum núna",
  "pub.dash.noActivity": "Engir bátar á sjónum núna.",
  "pub.dash.trips": "siglingar",
  "pub.dash.loading": "Hleður yfirliti…",
  "pub.dash.error": "Gat ekki hlaðið yfirlitsgögnum.",
  "pub.dash.lastUpdated": "Síðast uppfært",
  "pub.dash.tripCount": "{n} siglingar",
  "pub.dash.hourCount": "{n} klst",
  "pub.dash.weather": "Veður og sjávarföll",
  "pub.dash.boatsOut": "Bátar úti",
  "pub.dash.captainData": "Skipstjóragögn",
  "pub.dash.captainSoon": "Upplýsingar um skipstjóra og tölfræði birtast hér fljótlega.",
  "pub.dash.trips": "siglingar",
  "pub.dash.comingSoon": "Frekari upplýsingar birtast fljótlega.",
  "pub.dash.activeMembers": "Virkir félagsmenn",
  "pub.dash.becomeMember": "Gerast félagi",
  "admin.confirmImport": "Staðfesta innflutning",
  "admin.addCategory": "+ Bæta við flokki",
  "admin.actTypesTitle": "TEGUNDIR STARFSEMI",
  "admin.credentialsTitle": "SKÍRTEINI",
  "admin.manageCreds": "Skírteini",
  "admin.overdueAlerts": "VIÐVARANIR YFIRTÍMA",
  "admin.scoreThresholds": "STIGAMÖRK",
  "admin.scoreThresholdsSub": "heildarstig → fánastig",
  "admin.yellowGte": "Gulur ≥",
  "admin.orangeGte": "Appelsínugulur ≥",
  "admin.redGte": "Rauður ≥",
  "admin.closedGte": "Lokað ≥",
  "admin.windScoring": "VINDASTIG (Force → stig)",
  "admin.windScoringHint": "Hvert bil gildir þegar Force ≤ hámarksForce. Raðað í hækkandi röð.",
  "admin.dirGustMods": "ÁTTIR OG HVÍÐUBREYTINGAR",
  "admin.easterlyMod": "Austanáttarbreyting (stig)",
  "admin.easterlyModHint": "Bætt við þegar vindur er frá austanátt",
  "admin.gustMod1": "Hvíðubreyting +1 Force (stig)",
  "admin.gustMod1Hint": "Bætt við þegar hvíður eru nákvæmlega 1 Force-stigi yfir meðalvindi",
  "admin.gustMod2": "Hvíðubreyting +2 Force (stig)",
  "admin.gustMod2Hint": "Bætt við þegar hvíður eru 2+ Force-stigum yfir meðalvindi",
  "admin.easterlyDirs": "Austanáttir (kommuaðskildar)",
  "admin.waveScoring": "BYLGJUHÆÐARSTIG (metrar → stig)",
  "admin.sstScoring": "SJÁVARHITASTIG (°C → stig)",
  "admin.sstHint": "Fyrsta bil þar sem sjávarhiti ≥ lágmarksC gildir. Raðað hæsta gildi efst.",
  "admin.airTempScoring": "LOFTHITASTIG (°C → stig)",
  "admin.visScoring": "SKYGGNI-STIG",
  "admin.visGood": "Gott (stig)",
  "admin.visReduced": "Skert (stig)",
  "admin.visPoor": "Slæmt <500m (stig)",
  "admin.flagLabelsAdvice": "FÁNATEXTAR OG RÁÐLEGGINGAR",
  "admin.livePreview": "FORSÝNING",
  "admin.saveFlagSettings": "Vista fánastillingar",
  "admin.resetDefaults": "Endurstilla sjálfgefin gildi",
  "admin.addBand": "+ Bæta við bili",
  "admin.kennitala": "Kennitala",
  "admin.initials": "Upphafsstafir",
  "admin.initialsPlaceholder": "Sjálfvirkt",
  "admin.dob": "Fæðingardagur",
  "admin.deactivate": "Gera óvirkt",
  "admin.password": "Lykilorð",
  "admin.hasCustomPassword": "Sérvalið lykilorð (virkt)",
  "admin.usingDefaultPassword": "Notar bráðabirgðalykilorð",
  "admin.resetPassword": "Gefa út bráðabirgðalykilorð",
  "admin.resetPasswordConfirm": "Gefa út nýtt bráðabirgðalykilorð fyrir {name}? Öll tæki verða skráð út.",
  "admin.resetPasswordDone": "Bráðabirgðalykilorð gefið út. Lotur útskráðar: {n}.",
  "admin.tempPasswordTitle": "Bráðabirgðalykilorð",
  "admin.tempPasswordTitlePlural": "Bráðabirgðalykilorð",
  "admin.tempPasswordWarning": "Sendu þetta til félaga núna — það verður ekki sýnt aftur. Hann verður beðinn að velja sér lykilorð við fyrstu innskráningu.",
  "admin.tempPasswordCopy": "Afrita",
  "admin.tempPasswordCopied": "Afritað",
  "admin.boatCatModal.add": "Bæta við bátaflokki",
  "admin.nameEN": "Nafn (enska)",
  "admin.nameIS": "Nafn (íslenska)",
  "admin.emoji": "Emoji",
  "admin.keyAutoSet": "Lykill (sjálfkrafa)",
  "admin.keyHint": "Lykillinn er notaður innbyrðis til að tengja báta og gátlista. Honum er ekki hægt að breyta eftir að bátum er úthlutað.",
  "admin.clModal.add": "Bæta við gátlistaatriði",
  "admin.clPhaseOpening": "Opnun",
  "admin.clPhaseClosing": "Lokun",
  "admin.clLaunchPhase": "Sjósetning",
  "admin.clLandingPhase": "Lending",
  "admin.actTypeModal.add": "Bæta við tegund starfsemi",
  "admin.subtypes": "UNDIRTEGUNDIR",
  "admin.certDefModal.add": "Bæta við tegund skírteinis",
  "admin.certDescLabel": "Lýsing",
  "admin.certDescEN": "Lýsing (EN)",
  "admin.certDescIS": "Lýsing (IS)",
  "admin.subcatLabelEN": "Heiti (EN, t.d. Level 1)",
  "admin.subcatLabelIS": "Heiti (IS, t.d. Stig 1)",
  "admin.subcatDescEN": "Lýsing (EN)",
  "admin.subcatDescIS": "Lýsing (IS)",
  "admin.certCatModal.add": "Bæta við flokki skírteinis",
  "admin.certCatModal.edit": "Breyta flokki skírteinis",
  "admin.certCatKeyHint": "Lykillinn er fastur og er ekki hægt að breyta eftir stofnun — hann tengir skírteini félagsmanna við þennan flokk.",
  "admin.certIssuing": "Útgefandi",
  "admin.certClubEndorsement": "Áritun félagsins",
  "admin.certCardColour": "Litur korts",
  "admin.certAutoBlank": "sjálfvirkt ef autt",
  "admin.certExpires": "Þetta skírteini rennur út",
  "admin.certHasId": "Þetta skírteini hefur auðkenni / leyfisnúmer",
  "admin.certSubcategories": "UNDIRFLOKKAR",
  "admin.certSubcatHint": "Bættu við undirflokkum ef skírteinið hefur stig (t.d. Stig 1, 2, 3). Stilltu röð til að framfylgja „hærra kemur í stað lægra\" rök. Útgefandi eða lokadagsetning undirflokks hnekkir gildum yfirflokksins.",
  "admin.certCurrent": "NÚVERANDI",
  "admin.certAssignTitle": "ÚTHLUTA SKÍRTEINI",
  "admin.certCategory": "Flokkur",
  "admin.certCategorySelect": "Veldu flokk…",
  "admin.certAddCategory": "+ Bæta við flokki…",
  "admin.certTitle": "Heiti skírteinis",
  "admin.certIdNumber": "Auðkennisnúmer",
  "admin.certIssuingAuth": "Útgefandi",
  "admin.certIssueDate": "Útgáfudagur",
  "admin.certExpires2": "Rennur þetta skírteini út?",
  "admin.certExpiryDate2": "Lokadagsetning",
  "admin.certDescription": "Viðbótarlýsing",
  "admin.certCustomType": "— Slá inn sérsniðið skírteini —",
  "admin.certTitleRequired": "Heiti vantar.",
  "admin.certAuthorityReq": "Útgefanda vantar.",
  "admin.certExpiryReq": "Lokadagsetning vantar þegar skírteini rennur út.",
  "admin.certCategoryReq": "Flokk vantar.",
  "admin.certDefCategory": "Sjálfgefinn flokkur",
  "admin.certCategoriesTitle": "FLOKKAR SKÍRTEINA",
  "cq.assignCred": "Úthluta skírteini",
  "cq.assignCredTitle": "ÚTHLUTA SKÍRTEINI TIL ÁHAFNAR",
  "cq.searchMember": "Leita að áhafnarmeðlimi…",
  "cq.selectMember": "Veldu félagann",
  "admin.qrScanHint": "Skannaðu → laus: sjósetningarflæði · þinn bátur úti: skilaflæði · annars: sýnir stöðu.",
  "admin.printPdf": "Prenta / PDF",
  "qr.scanTitle": "Skanna QR-kóða báts",
  "qr.scanBtn": "📷 Skanna QR",
  "qr.starting": "Ræsi myndavél…",
  "qr.loading": "Hleð inn QR-lesara…",
  "qr.loadFailed": "Ekki tókst að hlaða QR-lesara — athugaðu nettenginguna",
  "qr.scanning": "Beindu myndavélinni að QR-kóðanum",
  "qr.noCamera": "Engin myndavél fannst á tækinu",
  "qr.permDenied": "Aðgangur að myndavél synjaður — leyfðu aðgang og reyndu aftur",
  "qr.error": "Villa í myndavél",
  "qr.boatNotFound": "Báturinn finnst ekki",
  "qr.boatOutByOther": "{name} er með þennan bát úti",
  "qr.boatOos": "Þessi bátur er utan þjónustu",
  "qr.invalidCode": "QR-kóðinn er ekki bátakóði",
  "admin.ownerClub": "Klúbbsbátur",
  "admin.ownerPrivate": "Einkabátur",
  "admin.searchMember": "Leita að félaga...",
  "admin.oosReason": "Ástæða",
  "admin.openingChecklist": "OPNUNARGÁTLISTI",
  "admin.closingChecklist": "LOKUNARGÁTLISTI",
  "admin.homePort": "Heimahöfn",
  "admin.loadFailed": "Hleðsla mistókst",
  "admin.nameKtRequired": "Nafn og kennitala vantar.",
  "admin.nameKeyRequired": "Nafn og lykill vantar.",
  "admin.nameRequired": "Nafn vantar.",
  "admin.textENRequired": "Enskan texta vantar.",
  "admin.memberDatesRequired": "Félaga og dagsetningar vantar.",
  "admin.categoryExists": "Flokkur er þegar til.",
  "admin.categoryAdded": "Flokki bætt við.",
  "admin.categoryRemoved": "Flokki eytt.",
  "admin.certDefSaved": "Tegund skírteinis vistuð.",
  "admin.parseError": "Þáttunarvilla",
  "admin.importing": "Flytur inn…",
  "admin.importFailed": "Innflutningur mistókst",
  "admin.importComplete": "Innflutningi lokið: {added} bætt við, {updated} uppfært.",
  "admin.importDeactivated": "{count} gert óvirkt.",
  "admin.confirmDeactivateMember": "Gera þennan félaga óvirkan?",
  "admin.confirmRemoveBoatCat": "Eyða þessum flokki? Bátar sem eru í honum verða enn til en geta birst undir 'annað'.",
  "admin.confirmDeleteBoat": "Eyða þessum bát?",
  "admin.confirmDeleteLocation": "Eyða þessum stað?",
  "admin.confirmDeleteItem": "Eyða þessu atriði?",
  "admin.confirmDeleteActType": "Eyða þessari tegund starfsemi? Tengdir sjálfboðaviðburðir verða einnig fjarlægðir.",
  "admin.confirmDeleteActTypeCascade": "Þetta mun einnig fjarlægja {n} sjálfboðaviðburð(i) og {m} skráningu(m). Halda áfram?",
  "admin.actTypeDeletedCascade": "Starfsemi eytt — einnig fjarlægt {n} sjálfboðaviðburður og {m} skráning(ar).",
  "admin.confirmRemoveCategory": "Eyða þessum flokki?",
  "admin.confirmDeleteCertDef": "Eyða þessari tegund skírteinis? Þetta eyðir ekki núverandi úthlutunum.",
  "admin.confirmResetFlags": "Endurstilla allar fánastillingar á sjálfgefin gildi?",
  "admin.noCategories": "Engir flokkar.",
  "admin.noItems": "Engin atriði.",
  "admin.noActTypes": "Engar tegundir starfsemi.",
  "admin.noCertCategories": "Engir flokkar skilgreindir. Sjálfgefin gildi verða notuð.",
  "admin.noCertDefs": "Engar tegundir skírteina skilgreindar.",
  "admin.noSubcategories": "Engir undirflokkar",
  "admin.noSubtypes": "Engar undirtegundir ennþá.",
  "admin.boatCatModal.edit": "Breyta flokki",
  "admin.clModal.edit": "Breyta atriði",
  "admin.lcModal.add": "Bæta við atriði",
  "admin.lcModal.edit": "Breyta atriði",
  "admin.actTypeModal.edit": "Breyta tegund",
  "admin.optionNone": "— ekkert —",
  "admin.certCategoryNone": "Ekkert",
  "staff.departurePort": "Brottfararhöfn",
  "staff.recentIn": "Inn",
  "staff.recentMember": "Félagi",
  "staff.recentBoat": "Bátur",
  "staff.recentArea": "Siglingasvæði",
  "staff.recentDuration": "Tímalengd",
  "member.departurePort": "Brottfararhöfn",
  "member.homePort": "Heimahöfn",
  "member.back": "Til baka",
  "member.continue": "Áfram →",
  "member.noChecklist": "Enginn gátlisti stilltur fyrir þennan flokk.",
  "member.confirmAllItems": "Staðfestu alla liði.",
  "daily.linkSelected": "Tengja valið",
  "daily.group": "hópur",
  "daily.groups": "hópar",
  "nav.captainQuarters": "Skipstjóraklefi",
  "cq.title": "Skipstjóraklefi",
  "cq.subtitle": "Yfirlit skipstjóra kjölbáta",
  "cq.ytdHours": "KLUKKUST. Á ÁRI",
  "cq.ytdDistance": "VEGALENGD Á ÁRI",
  "cq.ytdTrips": "FERÐIR Á ÁRI",
  "cq.nm": "sm",
  "cq.hrs": "klst",
  "cq.maintTitle": "VIÐHALD KJÖLBÁTA",
  "cq.maintOpen": "Opin",
  "cq.maintClosed": "Lokað",
  "cq.maintAll": "Allt",
  "cq.noMaint": "Engar viðhaldsbeiðnir.",
  "cq.validationTitle": "STAÐFESTINGARBEIÐNIR",
  "cq.noValidation": "Engar staðfestingarbeiðnir í bið.",
  "cq.crewTitle": "SAMÞYKKI ÁHAFNAR",
  "cq.noCrew": "Engin áhafnarsamþykki í bið.",
  "cq.bioTitle": "LÝSING OG PRÓFÍLL",
  "cq.bioPlaceholder": "Skrifaðu stutta lýsingu sem birtist á opinberri skipstjórasíðu þinni…",
  "cq.headshotLabel": "Prófílmynd (hámark 5 MB)",
  "cq.bioSaved": "Lýsing vistuð",
  "cq.headshotUploaded": "Mynd hlaðið upp",
  "cq.boatsTitle": "MÍNIR BÁTAR",
  "cq.noBoats": "Engir einkabátar skráðir.",
  "cq.makeUnavailable": "Merkja ótiltækan",
  "cq.makeAvailable": "Merkja tiltækan",
  "cq.changePort": "Breyta heimahöfn",
  "cq.reservations": "LEIGUR",
  "cq.addReservation": "Bæta við leigu",
  "cq.resStartDate": "Upphafsdagur",
  "cq.resEndDate": "Lokadagur",
  "cq.resNote": "Athugasemd (valfrjálst)",
  "cq.resMember": "Meðlimur",
  "tc.skipper": "Skipstjóri",
  "tc.crew": "Áhöfn",
  "tc.helm": "Stýri",
  "tc.student": "Nemi",
  "tc.guest": "Gestur",
  "tc.me": "Ég",
  "tc.nonClub": "Utan félags",
  "tc.pending": "í bið",
  "tc.verificationPending": "Staðfesting í bið",
  "tc.requestVerification": "Óska eftir staðfestingu",
  "tc.windSpeed": "Vindhraði",
  "tc.direction": "Átt",
  "tc.gusts": "Vindhviður",
  "tc.conditions": "Aðstæður",
  "tc.airTemp": "Hitastig",
  "tc.feelsLike": "Finnst eins og",
  "tc.seaTemp": "Sjávarhiti",
  "tc.waveHeight": "Bylgjuhæð",
  "tc.pressure": "Loftþrýstingur",
  "tc.weatherFlag": "Veðurfáni",
  "tc.departurePort": "Brottfararstaður",
  "tc.arrivalPort": "Komustaður",
  "tc.crewAboard": "Áhöfn um borð",
  "tc.regNo": "Skráningarnúmer",
  "tc.sailNo": "Seglnúmer",
  "tc.typeModel": "Tegund / gerð",
  "tc.loa": "Heildarlengd",
  "tc.distance": "Vegalengd",
  "tc.gpsTrack": "GPS-leið",
  "tc.deleteTrack": "Eyða leið",
  "tc.clickToExpand": "Smelltu til að stækka",
  "tc.downloadFile": "Sækja skrá",
  "tc.viewTrack": "Skoða leið",
  "tc.skipperNote": "Athugasemdir skipstjóra",
  "tc.visibleToCrew": "sýnilegt áhöfn",
  "tc.fromSkipper": "frá skipstjóra",
  "tc.noNoteYet": "Engin skýring",
  "tc.edit": "Breyta",
  "tc.privateNote": "Persónulegar athugasemdir",
  "tc.onlyYou": "aðeins þú sérð",
  "tc.noPrivateNoteYet": "Engin athugasemd",
  "tc.photos": "Myndir",
  "tc.delete": "Eyða",
  "tc.shared": "Deilt",
  "tc.private": "Einka",
  "tc.club": "Félag",
  "tc.editTrip": "✏️ Breyta ferð",
  "tc.addGps": "📍 Bæta við GPS",
  "tc.addPhotos": "📷 Bæta við myndum",
  "tc.boatDetails": "Upplýsingar um bát",
  "tc.tripDetails": "Upplýsingar um ferð",
  "tc.departed": "Brottfarartími",
  "tc.returned": "Komutími",
  "tc.sailingArea": "Siglingasvæði",
  "tc.duration": "Tímalengd",
  "tc.weather": "Veður",
  "tc.notesPhotosTrack": "Athugasemdir og myndir",
  "maint.sevHint.low": "Minniháttar vandamál — engin tafarlaus aðgerð nauðsynleg.",
  "maint.sevHint.medium": "Nothæft vandamál, nothæft með varúð.",
  "maint.sevHint.high": "Verulegt vandamál — meta áður en notað.",
  "maint.sevHint.critical": "Öryggisáhætta — taka úr þjónustu strax.",
  "maint.oosTag": "ÚÞ",
  "maint.inService": "Í þjónustu",
  "maint.confirmBtn": "Staðfesta",
  "maint.cancelBtn": "Hætta við",
  "maint.defaultAuthor": "Starfsmaður",
  "maint.deleteComment": "Eyða athugasemd",
  "maint.addCommentPh": "Bæta við athugasemd…",
  "maint.postBtn": "Birta",
  "maint.postingBtn": "Birti…",
  "maint.approvingBtn": "Samþykki…",
  "maint.approveBtn": "Samþykkja",
  "maint.saumaBadge": "Saumaklúbbur",
  "maint.onHoldBadge": "Í bið",
  "maint.noVerkstjori": "Enginn verkstjóri úthlutaður",
  "maint.adoptProject": "Taka verkefni að mér",
  "maint.reportedByLabel": "Tilkynnt af",
  "maint.pendingReview": "Bíður samþykktar starfsmanna",
  "maint.pendingReviewAlert": "{count} saumaklúbbsverkefni bíða samþykktar — smelltu til að skoða",
  "maint.markCompleted": "Merkja lokið",
  "maint.markResolved2": "Merkja sem lokið",
  "maint.resumeBtn": "Halda áfram",
  "maint.putOnHold": "Setja í bið",
  "maint.deleteBtn": "Eyða",
  "maint.completedStatus": "Lokið",
  "maint.resolvedStatus": "Lokið",
  "maint.severityLabel": "Alvarleiki",
  "maint.priorityLabel": "Forgangur",
  "maint.changeSevConfirm": "Breyta alvarleika í \"{sev}\" án þess að leysa?",
  "maint.adoptConfirm": "Verða verkstjóri þessa verkefnis?",
  "maint.deleteCommentConfirm": "Eyða þessari athugasemd?",
  "maint.holdConfirm": "Setja þetta verkefni í bið?",
  "maint.resumeConfirm": "Halda áfram með þetta verkefni?",
  "maint.completeConfirm": "Merkja þetta verkefni sem lokið?",
  "maint.resolveConfirm2": "Merkja þetta vandamál sem lokið?",
  "maint.deleteConfirm": "Eyða þessu vandamáli? Þetta er ekki afturkræft.",
  "maint.returnToService": "Setja aftur í þjónustu án þess að leysa?",
  "maint.markOosConfirm": "Merkja utan þjónustu án þess að leysa?",
  "maint.maxFileSize": "Hámark 5 MB",
  "maint.materials": "EFNI",
  "maint.addMaterialPh": "t.d. Sandpappír 120…",
  "maint.addMaterialBtn": "+ Bæta við",
  "maint.removeMaterial": "Fjarlægja efni",
  "maint.removeMaterialConfirm": "Fjarlægja þetta efni?",
  "maint.editTitle": "Breyta beiðni",
  "maint.untitled": "Án titils",
  "maint.updated": "Uppfært ✓",
  "alert.overdueTitle": "BÁTAR YFIRTÍMA",
  "alert.minOverdue": "{n} mín yfirtíma",
  "alert.hrsOverdue": "{h}klst {m}mín yfirtíma",
  "alert.guardian": "Forráðamaður:",
  "alert.snoozedPill": "Frestað — birtist aftur eftir {n} mín",
  "alert.snoozeBtn": "Fresta {n}m",
  "alert.silenceBtn": "Þagga",
  "wx.staffOnDuty": "Starfsmaður á vakt",
  "wx.supportBoatOut": "Gæslubátur á sjó",
  "wx.poorVisibility": "Slæm sýn",
  "wx.reducedVisibility": "Skert sýn",
  "tc.flagGreen": "Grænn",
  "tc.flagYellow": "Gulur",
  "tc.flagOrange": "Appelsínugulur",
  "tc.flagRed": "Rauður",
  "tc.flagBlack": "Svartur",
  "logbook.deleteTrack": "Ertu viss um að þú viljir eyða GPS-leiðinni?",
  "logbook.deletePhoto": "Eyða þessari mynd?",
  "logbook.revokeLink": "Afturkalla þennan hlekk?",
  "logbook.noFilter": "Engar ferðir passa við þessa síu.",
  "logbook.loadingTrips": "Hleður nýlegum ferðum…",
  "logbook.noClubTrips": "Engar nýlegar félagssiglingar fundust.",
  "logbook.ports": "HÖFNAR",
  "logbook.portsOptional2": "HÖFNAR — VALFRJÁLST",
  "logbook.helmLabel": "Stýri",
  "logbook.studentLabel": "Nemi",
  "logbook.errKtOrPhone": "Vinsamlegast sláðu inn kennitölu/fæðingarár eða símanúmer.",
  "logbook.errSaveFailed": "Vistun mistókst: {msg}",
  "logbook.errFailed": "Mistókst: {msg}",
  "logbook.readingFile": "Lesur skrá…",
  "logbook.fileReady": "Tilbúið: {name}",
  "logbook.readError": "Lestur mistókst",
  "logbook.noTripSelected": "Engin ferð valin",
  "logbook.sendingRequest": "Sendir beiðni…",
  "logbook.requestSent": "Beiðni send til skipstjóra ✓",
  "logbook.addToLogbook": "Bæta við siglingabók",
  "logbook.alreadyInLog": "Þessi ferð er nú þegar í siglingabókinni þinni.",
  "logbook.requestToJoin": "Senda beiðni",
  "logbook.errDepartureTime": "Ógilt brottfarartími (HH:MM).",
  "logbook.errReturnTime": "Ógilt komutími (HH:MM).",
  "logbook.errDate": "Vinsamlegast sláðu inn dagsetningu.",
  "logbook.errBoat": "Vinsamlegast veldu bát.",
  "logbook.errSkipper": "Vinsamlegast veldu skipara.",
  "logbook.errDuplicate": "Þú hefur þegar skráð ferð með þessum bát á þessum degi. Vinsamlegast athugaðu siglingabókina.",
  "logbook.uploading": "Hleður upp…",
  "logbook.uploadNoConfig": "Skráarupphal ekki stillt — ferð vistuð án viðhengis.",
  "logbook.gpsUploadFailed": "GPS upphal mistókst: {msg}",
  "logbook.photoNoConfig": "Skráarupphal ekki stillt",
  "logbook.photoUploadFailed": "Mynda upphal mistókst: {msg}",
  "logbook.saveToLogbook": "Vista í siglingabók",
  "logbook.showLess": "Sýna minna",
  "logbook.showMore": "Sýna meira",
  "logbook.departure": "Brottför",
  "logbook.arrival": "Koma",
  "logbook.trackDeleted": "GPS-leið eytt",
  "logbook.photoDeleted": "Mynd eytt",
  "logbook.upTo": "Til",
  "logbook.views": "skoðanir",
  "logbook.copy": "Afrita",
  "logbook.revoke": "Afturkalla",
  "logbook.linkRevoked": "Hlekkur afturkallaður.",
  "logbook.loadFailed": "Gat ekki hlaðið siglingabók: {msg}",
  "logbook.loadFailed2": "Gat ekki hlaðið: {msg}",
  "logbook.studentBadge": "Nemamerking",
  "logbook.tripVerification": "Staðfesting ferðar",
  "logbook.from": "frá",
  "logbook.confirmed": "Staðfest ✓",
  "logbook.rejected": "Hafnað",
  "logbook.skipperNoteLabel": "Athugasemdir skipstjóra (sýnilegt áhöfn):",
  "logbook.privateNoteLabel": "Persónulegar athugasemdir (aðeins þú sérð):",
  "logbook.noteSaved": "Athugasemd vistuð",
  "logbook.dismissed": "Fjarlægt",
  "logbook.allDismissed": "Allar fjarlægðar",
  "logbook.onlySkipper": "Aðeins skipstjóri getur breytt ferðinni",
  "logbook.selectBoat": "Veldu bát…",
  "logbook.selectLocation": "Veldu staðsetningu…",
  "logbook.editTripTitle": "Breyta ferð",
  "logbook.saveChanges": "Vista breytingar",
  "logbook.saving": "Vista…",
  "logbook.tripUpdated2": "Ferð uppfærð",
  "logbook.uploadingTrack": "Hleð upp GPS-leið…",
  "logbook.uploadFailed": "Upphal mistókst",
  "logbook.trackAdded2": "GPS-leið bætt við",
  "logbook.addPhotosTitle": "Bæta við myndum",
  "logbook.photoHint": "Deildar myndir sjást öðrum í ferðinni. Myndir merktar fyrir félagið má nota í kynningarefni.",
  "logbook.uploadPhotos": "Hlaða upp myndum",
  "logbook.noPhotosSelected": "Engar myndir valdar",
  "logbook.photosAdded2": "Myndir bættar við",
  "logbook.uploadFailed2": "Upphal mistókst: {msg}",
  "logbook.windLabel": "Vindur ({unit})",
  "logbook.gustsLabel": "Hviður ({unit})",
  "logbook.crewSearchPh": "Áhöfn {n} — leita eftir nafni…",
  "logbook.addAsGuest": "+ Bæta við \"{name}\" sem gest",
  "logbook.portAdded": "Höfn bætt við",
  "logbook.verificationReq": "Óskað eftir staðfestingu",
  "logbook.errGeneric": "Villa: {msg}",
  "member.gpsTrackLabel": "GPS-LEIÐ — GPX/KML",
  "member.photosLabel": "MYNDIR",
  "member.distanceLabel": "VEGALENGD (NM)",
  "member.arrivalPortLabel": "KOMUSTAÐUR",
  "member.sameAsDeparture": "Sama og brottfararstaður",
  "member.reportDamage": "Tilkynna skemmdir",
  "member.reportIncident": "Tilkynna atvik",
  "member.helmLabel": "STÝRI",
  "member.youLabel": "(þú)",
  "member.loadingCrew": "Hleður áhöfn…",
  "member.skipperNotes": "ATHUGASEMDIR SKIPSTJÓRA",
  "member.notesVisibleAll": "Sýnileg öllum á ferðinni.",
  "member.notesPlaceholder": "Athugasemd um ferðina (sýnileg áhöfn)",
  "member.personalNotes": "PERSÓNULEGAR ATHUGASEMDIR",
  "member.onlyVisibleYou": "Aðeins sýnilegt þér",
  "member.guestLabel": "Gestur",
  "member.noNamedCrew": "Engin nefnd áhöfn",
  "member.readingFile": "Lesur skrá…",
  "member.fileReady": "Tilbúið: {name}",
  "member.readError": "Lestur mistókst",
  "member.gpsNoConfig": "GPS upphal ekki stillt",
  "member.gpsUploadFailed": "GPS upphal mistókst: {msg}",
  "member.photoNoConfig": "Skráarupphal ekki stillt",
  "member.photoUploadFailed": "Mynda upphal mistókst: {msg}",
  "member.checkInBtn": "Skrá inn",
  "staff.boatNotFound": "Bátur fannst ekki.",
  "staff.groupCheckoutTitle": "Hópaúthlutun",
  "staff.selectBoats": "Veldu báta",
  "staff.participants": "Iðkendur",
  "staff.activityType": "Tegund",
  "staff.errSelectBoat": "Veldu að minnsta kosti einn bát.",
  "staff.errSailingArea": "Veldu siglingasvæði.",
  "staff.errStaffRequired": "Þarf að skrá a.m.k. einn starfsmann.",
  "staff.errStaffFromList": "Vinsamlegast veldu starfsmann af listanum: {names}",
  "staff.groupLaunched": "Hópur sjósettur ✓",
  "staff.searchStaff": "Leita að starfsmanni…",
  "staff.addAsGuest": "+ Bæta við \"{name}\" sem gest",
  "staff.crewSearchPh": "Áhöfn {n} — leita eftir nafni…",
  "staff.errKtOrPhone": "Vinsamlegast sláðu inn kennitölu/fæðingarár eða símanúmer.",
  "staff.guestSaveFailed": "Gat ekki vistað gest: {msg}",
  "staff.checkInClose": "Skrá inn og loka",
  "staff.noActivities": "Engin starfsemi skráð í dagbók dagsins enn.",
  "staff.linkedDailyLog": "Tengt við dagbók ✓",
  "staff.payrollUnavail": "Launakerfi ekki tiltækt — settu upp bakenda fyrst",
  "staff.onWaterTotal": "{n} á sjónum samtals, {b} {boatWord}",
  "staff.boat": "bátur",
  "staff.boats": "bátar",
  "staff.peopleOnWater": "manns á sjó",
  "staff.checkInAll": "Taka inn",
  "staff.noneOption": "— Ekkert —",
  "staff.oosTitle": "Utan þjónustu",
  "staff.alreadyOut": "Nú þegar úti",
  "staff.staffOnDuty": "Starfsmaður á vakt",
  "staff.noStaffOnDuty": "Enginn starfsmaður á vakt",
  "staff.supportBoat": "Gæslubátur",
  "staff.noSupportBoat": "Enginn Gæslubátur á sjó",
  "staff.updatedShort": "Uppf.",
  "staff.guardianLabel": "Sými forráðamanns",
  "staff.phoneLabel": "Sími",
  "staff.expectedBack": "Skilar klukkan",
  "staff.overdueBy": "Seinn um",
  "staff.hrsMin": "{h}klst {m}mín",
  "staff.minOnly": "{m} mín",
  "staff.snoozeBtn": "Fresta ({n} mín)",
  "staff.silenceBtn": "Þagga",
  "maint.noFilterMatch": "Engar beiðnir passa við þessa síu.",
  "maint.loadFailed": "Gat ekki hlaðið: {msg}",
  "maint.errCategory": "Vinsamlegast veldu flokk.",
  "maint.errSeverity": "Vinsamlegast veldu alvarleikastig.",
  "maint.errDescription": "Vinsamlegast lýstu vandamálinu.",
  "maint.errBoat": "Vinsamlegast veldu bát.",
  "maint.imgTooLarge": "Mynd of stór ({size} MB). Hámark er 5 MB.",
  "maint.submitting": "Sendi…",
  "maint.uploadingPhoto": "Hleð upp mynd…",
  "maint.submitBtn": "Senda",
  "maint.submitted": "Beiðni send ✓",
  "maint.resolvedToast": "Lokið ✓",
  "maint.commentAdded": "Athugasemd bætt við.",
  "cert.removeConfirm": "Fjarlægja þetta skírteini?",
  "cq.allBoats": "Allir bátar",
  "cq.allYears": "Öll ár",
  "cq.allCategories": "Allir flokkar",
  "cq.allCaptains": "Allir skipstjórar",
  "cq.allMembers": "Allir félagar",
  "cq.fileTooLarge": "Skrá of stór (hámark 5 MB)",
  "cq.memberDatesRequired": "Meðlimur og dagsetningar eru nauðsynleg.",
  "cq.noTripsMatch": "Engar ferðir passa við þessa síu.",
  "cq.crewJoinRequest": "Biðst til liðs sem áhafnarmeðlimur",
  "cq.crewAssignPending": "Áhafnarúthlutun í bið",
  "wx.fetching": "Sæki veðurgögn…",
  "wx.updating": "Uppfæri…",
  "wx.checkConnection": "Athugaðu tengingu og reyndu aftur.",
  "wx.failed": "Mistókst",
  "wx.refresh": "Endurhlaða",
  "wx.pressureUnavail": "Þrýstingsgögn ekki tiltæk",
  "wx.useMyLocation": "📍 Mín staðsetning",
  "wx.useFossvogur": "⚓ Fossvogur",
  "wx.locating": "Staðset…",
  "wx.geoUnavailable": "Staðsetning ekki tiltæk",
  "wx.geoDenied": "Staðsetning hafnað eða ekki tiltæk",
  "wx.myLocation": "Mín staðsetning",
  "wx.openForecast": "Opna ítarlega spá →",
  "logrev.noMemberSelected": "Enginn meðlimur valinn.",
  "logrev.memberNotFound": "Meðlimur fannst ekki.",
  "logrev.credentialRemoved": "Skírteini fjarlægt",
  "sauma.imgTooLarge": "Mynd of stór. Hámark er 5 MB.",
  "sauma.submitting": "Sendi…",
  "sauma.uploadingPhoto": "Hleð upp mynd…",
  "sauma.submitted": "Verkefni sent til samþykktar.",
  "sauma.selectCategory": "Vinsamlegast veldu flokk.",
  "sauma.selectPriority": "Vinsamlegast veldu forgang.",
  "sauma.describeProject": "Vinsamlegast lýstu verkefninu.",
  "sauma.selectBoat": "Vinsamlegast veldu bát.",
  "passport.title": "RÆÐARAPASSI",
  "passport.historyNote": "saga",
  "passport.signerMode": "Undirritunarstilling — smelltu á atriði til að undirrita.",
  "passport.confirmSign": "Undirrita þetta atriði?",
  "passport.signed": "Undirritað.",
  "passport.promoted": "Passi kláraður — uppfærð(ur) í Released Rower!",
  "passport.adminTitle": "Ræðarapassi",
  "passport.importCsv": "Flytja inn CSV",
  "passport.exportCsv": "Flytja út CSV",
  "passport.csvHelp": "Dálkar: passport_id, category_id, category_label_en, category_label_is, item_id, assessment, module, item_label_en, item_label_is, description_en, description_is. Aðeins item_label_en er skyldudálkur — item_id og category_id eru sjálfkrafa búin til úr enska heitinu ef þau eru tóm (endurnýtt úr fyrri atriðum með sama heiti þannig að eldri undirritanir haldist). assessment er 'theory' eða 'practical' (sjálfgefið 'practical'). module er jákvæð heiltala sem endurspeglar kennsluröð (autt eða 0 = óúthlutað); einingar skera sig þvert á flokka.",
  "passport.theory": "Bóklegt",
  "passport.practical": "Verklegt",
  "passport.viewMember": "SKOÐA FÉLAGA",
  "passport.viewSelf": "Minn passi",
  "passport.revokeReason": "Ástæða fyrir afturköllun?",
  "passport.revoked": "Undirritun afturkölluð.",
  "passport.addCategory": "+ Bæta við flokki",
  "passport.addItem": "+ Bæta við atriði",
  "passport.retire": "Hætta",
  "passport.unretire": "Endurvirkja",
  "passport.save": "Vista breytingar",
  "passport.saved": "Passi vistaður.",
  "passport.unsavedChanges": "Óvistaðar breytingar. Henda?",
  "passport.editSettings": "Breyta passastillingum",
  "passport.settingsTitle": "Passastillingar",
  "passport.nameEN": "Heiti (enska)",
  "passport.nameIS": "Heiti (íslenska)",
  "passport.requiredSigs": "Fjöldi undirritana",
  "passport.promoteCertId": "Veitir skírteini",
  "passport.fromSub": "Úr undirflokki",
  "passport.toSub": "Í undirflokk",
  "passport.itemTitle": "Passaatriði",
  "passport.itemNameEN": "Heiti atriðis (enska)",
  "passport.itemNameIS": "Heiti atriðis (íslenska)",
  "passport.itemDescEN": "Lýsing (enska)",
  "passport.itemDescIS": "Lýsing (íslenska)",
  "passport.assessmentType": "Tegund mats",
  "passport.categoryTitle": "Passaflokkur",
  "passport.categoryNameEN": "Heiti flokks (enska)",
  "passport.categoryNameIS": "Heiti flokks (íslenska)",
  "passport.deleteCategory": "Eyða flokki",
  "passport.confirmDeleteCategory": "Eyða þessum flokki og öllum atriðum hans?",
  "passport.confirmDeleteItem": "Eyða þessu atriði? Atriði með undirritunum eru afvirkjuð í staðinn.",
  "passport.retiredBadge": "hætt",
  "passport.noDescription": "Engin lýsing",
  "passport.editItem": "Breyta",
  "passport.editCategory": "Breyta flokki",
  "passport.activeCount": "virk",
  "passport.requiresSignatures": "krefst {n} undirritana",
  "passport.promotesTo": "veitir {cert}",
  "passport.newItem": "Nýtt atriði",
  "passport.newCategory": "Nýr flokkur",
  "passport.itemDeleted": "Atriði fjarlægt.",
  "passport.itemRetiredSoft": "Atriði afvirkjað (fyrri undirritanir haldnar).",
  "passport.categoryDeleted": "Flokkur fjarlægður.",
  "passport.nameRequired": "Enska heiti er skylda.",
  "passport.idReadOnly": "Auðkenni (læst)",
  "passport.itemModule": "Eining (kennsluröð)",
  "passport.moduleLabel": "Eining",
  "passport.moduleShort": "Ein",
  "passport.unassignedModule": "Óúthlutuð eining",
  "passport.sortBy": "Raða eftir",
  "passport.sortCatMod": "Flokkur → Eining",
  "passport.sortModCat": "Eining → Flokkur",
  "passport.addItemHint": "Bæta við atriði í flokk:",

  "admin.tabVolunteers": "Sjálfboðaliðar",
  "admin.volunteerType": "Sjálfboðastarfsemi",
  "admin.volEventsTitle": "SJÁLFBOÐAVIÐBURÐIR",
  "admin.addVolEvent": "+ Bæta við viðburði",
  "admin.volEventModal.add": "Bæta við sjálfboðaviðburði",
  "admin.volEventModal.edit": "Breyta viðburði",
  "admin.volTitle": "Titill (EN)",
  "admin.volTitleIS": "Titill (IS)",
  "admin.volDate": "Dagsetning",
  "admin.volEndDate": "Lokadagsetning (valfrjálst)",
  "admin.volEndDateHint": "Hafðu autt ef viðburðurinn er einn dagur",
  "admin.volStartTime": "Byrjunartími",
  "admin.volEndTime": "Lokatími",
  "admin.volActType": "Starfsemi",
  "admin.volActTypeNone": "— Engin —",
  "admin.volRoles": "HLUTVERK",
  "admin.volRoleName": "HLUTVERK (EN)",
  "admin.volRoleNameIS": "HLUTVERK (IS)",
  "admin.volRoleDescEN": "LÝSING (EN)",
  "admin.volRoleDescIS": "LÝSING (IS)",
  "admin.volRolePickPreset": "— Velja staðlað hlutverk —",
  "admin.volSlots": "PLÁSS",
  "admin.volLeader": "Ábyrgðarmaður",
  "admin.volLeaderPhone": "Símanúmer",
  "admin.volShowPhone": "Sýna síma á viðburðakorti",
  "admin.volNotes": "Athugasemdir (EN)",
  "admin.volNotesIS": "Athugasemdir (IS)",
  "admin.noVolEvents": "Engir sjálfboðaviðburðir.",
  "admin.confirmDeleteVolEvent": "Eyða þessum sjálfboðaviðburði?",
  "admin.volSignups": "skráningar",
  "admin.noRoles": "Engin hlutverk skilgreind.",
  "admin.roleEndorsement": "Nauðsynleg réttindi",
  "admin.roleNoRestriction": "— Engin takmörkun —",
  "admin.bulkUsesDefaultTimes": "Notar sjálfgefna tíma",
  "admin.bulkSetDefaultTimes": "Stilltu sjálfgefinn byrjunar-/lokatíma hér að ofan til að nota við magnbókun.",
  "admin.volFromActType": "ÚR TEGUND STARFSEMI",
  "admin.volShowPast": "Sýna liðna viðburði ({n})",
  "admin.volHidePast": "Fela liðna viðburði",

  "member.volunteerEvents": "SJÁLFBOÐAVIÐBURÐIR",
  "member.volSignUp": "Skrá mig",
  "member.volWithdraw": "Afskrá",
  "member.volFull": "Fullt",
  "member.volSignedUp": "Skráð/ur",
  "member.volSlotsLeft": "{n} eftir",
  "member.volLeader": "Ábyrgðarmaður",
  "member.volNeedsEndorsement": "Réttindi nauðsynleg",
  "member.noVolEvents": "Engir sjálfboðaviðburðir á næstunni.",
  "member.calendar": "Dagatal",
  "member.calTitle": "DAGATÖL KLÚBBSINS",
  "member.calEmpty": "Engin dagatöl hafa verið sett upp.",
  "member.calOpen": "Opna í Google Dagatali",
  "nav.volunteer": "Sjálfboðaliði",
  "volunteer.title": "Sjálfboðaliði",
  "volunteer.subtitle": "Skráðu þig á sjálfboðaviðburði klúbbsins",
  "volunteer.tabList": "Listi",
  "volunteer.tabCalendar": "Dagatal",
  "volunteer.upcoming": "VIÐBURÐIR FRAMUNDAN",
  "volunteer.inCharge": "Verkstjóri",
  "volunteer.me": "Ég",
  "volunteer.more": "í viðbót",
  "volunteer.youSignedUp": "Þú ert skráð(ur)",
  "volunteer.noEventsThisDay": "Engir viðburðir þennan dag.",
  "volunteer.filterAll": "Allir",
  "volunteer.filterMine": "Mínir viðburðir",
  "volunteer.noMyEvents": "Þú hefur ekki skráð þig á neina komandi viðburði.",
  "volunteer.showMore": "Sýna fleiri ({n})",
  "volunteer.unfilledRoles": "laus pláss í sjálfboðaviðburðum",
  "admin.tabCalendars": "Dagatöl",
  "admin.calDesc": "Bættu við Google Calendar auðkennum sem félagar geta skoðað á félagssvæðinu. Hvert dagatal birtist sem innfellt yfirlit.",
  "admin.calName": "Nafn",
  "admin.calId": "Dagatal ID",
  "admin.calPlaceholder": "t.d. abc123@group.calendar.google.com",
  "admin.calAdd": "+ Bæta við dagatali",
  "admin.calEmpty": "Engin dagatöl skráð.",
  "admin.calRemove": "Fjarlægja",

  "member.notifPending": "í bið",
  "sauma.follow": "★ Fylgjast með",
  "sauma.unfollow": "★ Fylgist með",
  "sauma.followed": "Fylgist með verkefni ★",
  "sauma.unfollowed": "Hætt að fylgjast með"
};
