var _STRINGS_FLAT = {
  "nav.staffHub": "⚓️ Starfsmaenn",
  "nav.memberHub": "⛵ Félagssvæði",
  "nav.admin": "⚙️ Stjórnborð",
  "nav.weather": "⛅️ Veður",
  "nav.logbook": "📖 Siglingabók",
  "nav.back": "← Tilbaka",
  "nav.signOut": "Skrá út",
  "nav.langToggle": "EN",
  "btn.save": "Vista",
  "btn.cancel": "Hætta við",
  "btn.delete": "Eyða",
  "btn.edit": "Breyta",
  "btn.add": "+ Bæta við",
  "btn.close": "Loka",
  "btn.confirm": "Staðfesta",
  "btn.resolve": "Ljúka",
  "btn.saveDraft": "Vista drög",
  "btn.signOff": "Vista & Undirrita",
  "btn.submit": "Senda inn",
  "btn.addComment": "Bæta við athugasemd",
  "btn.viewAll": "Sjá allt →",
  "lbl.loading": "Hleður…",
  "lbl.on": "Kveikt",
  "lbl.off": "Slökkt",
  "lbl.noData": "Engin gögn",
  "lbl.name": "Nafn",
  "lbl.date": "Dagsetning",
  "lbl.time": "Tími",
  "lbl.notes": "Athugasemdir",
  "lbl.status": "Staða",
  "lbl.phone": "Sími",
  "lbl.email": "Netfang",
  "lbl.location": "Staðsetning",
  "lbl.boat": "Bátur",
  "lbl.crew": "Áhöfn",
  "lbl.role": "Hlutverk",
  "lbl.member": "Félagi",
  "lbl.guest": "Gestur",
  "lbl.guardian": "Forráðamaður",
  "lbl.minor": "Ólögráða",
  "lbl.verified": "✓ Staðfest",
  "lbl.pending": "Bíður yfirferðar",
  "lbl.optional": "valfrjálst",
  "lbl.filter": "SÍA:",
  "lbl.active": "Virkt",
  "lbl.inactive": "Óvirkt",
  "lbl.season": "Tímabil",
  "lbl.category": "Flokkur",
  "lbl.description": "Lýsing",
  "lbl.severity": "Alvarleiki",
  "lbl.type": "Tegund",
  "lbl.phase": "Fasi",
  "lbl.sortOrder": "Röðun",
  "lbl.selectDots": "Veldu…",
  "lbl.noneDash": "— ekkert —",
  "toast.saved": "Vistað",
  "toast.saveFailed": "Mistókst að vista",
  "toast.deleted": "Eytt",
  "toast.error": "Eitthvað fór úrskeiðis. Reyndu aftur.",
  "toast.loadFailed": "Hleðsla mistókst",
  "toast.signedOff": "Undirritað ✓",
  "toast.checkedIn": "Skráð inn ✓",
  "toast.noPhone": "Ekkert símanúmer skráð",
  "flag.green.label": "Grænn",
  "flag.green.advice": "Gott veðurlag.",
  "flag.yellow.label": "Gulur",
  "flag.yellow.advice": "Krefjandi — aðeins reyndir siglingamenn.",
  "flag.orange.label": "Appelsínugulur",
  "flag.orange.advice": "Erfitt — takmörkuð siglingar.",
  "flag.red.label": "Rauður",
  "flag.red.advice": "Ekki sigla — Öll siglingar stöðvaðar.",
  "flag.currentLabel": "NÚVERANDI FÁNI",
  "flag.allLevels": "Allar stigur →",
  "flag.conditions": "Siglingaraðstæður",
  "wx.wind": "VINDUR",
  "wx.gusts": "HVIÐA",
  "wx.waves": "BYLGJUR",
  "wx.pressure": "LOFTÞRÝSTINGUR",
  "wx.loading": "Sæki veðurgögn…",
  "wx.unavailable": "⚠️ Veður ekki tiltækt",
  "wx.fullForecast": "Heildarspá →",
  "wx.updated": "Uppfært",
  "login.title": "Siglingafélagið Ýmir",
  "login.subtitle": "Siglingafélagið",
  "login.kennitala": "Kennitala",
  "login.placeholder": "0000000000",
  "login.btn": "Skrá inn",
  "login.loading": "Skrái inn…",
  "login.notFound": "Félagi finnst ekki eða aðgangur er óvirkur.",
  "login.tooShort": "Vinsamlegast sláðu inn 10 stafa kennitölu.",
  "login.error": "Innskráning mistókst. Reyndu aftur.",
  "login.welcome": "Velkomin/n,",
  "login.chooseView": "Hvernig viltu skrá þig inn?",
  "login.back": "← Skrá inn sem annan notandi",
  "login.admin.label": "Stjórnborð",
  "login.admin.desc": "Stjórna félaga, bátum, stöðum, stillingum",
  "login.staff.label": "Starfsmannaþjónusta",
  "login.staff.desc": "Daglegur rekstur, flotinn, tilvik",
  "login.member.label": "Félagssvæði",
  "login.member.desc": "Inn/útskráning, dagbók, mínar ferðir",
  "member.launchBoat": "🚀 Fara á sjó",
  "member.checkIn": "✓ Skrá inn",
  "member.reportIssue": "🔧 Tilkynna vandamál",
  "member.myCheckout": "BÁTAR Á SJÓNUM",
  "member.myCheckoutSub": "smelltu á þinn bát til að skrá inn",
  "member.tabFleet": "Flotinn",
  "member.tabTrips": "Skrá siglingu",
  "member.tabLogbook": "Dagbók",
  "member.tabCerts": "Skírteini",
  "member.fleetAvail": "LAUSIR BÁTAR",
  "member.tripTabHint": "Smelltu á nýlega siglingu til að bæta henni við dagbókina þína sem áhöfn, eða skráðu siglingu handvirkt.",
  "member.statTrips": "SAMTALS SIGLINGAR",
  "member.statHours": "SIGLINGATÍMAR",
  "member.statBoat": "MEST NOTAÐI BÁTUR",
  "member.statSeason": "SIGLINGAR Í TÍMABILI",
  "member.noTrips": "Engar siglingard í dagbókinni þinni enn.",
  "member.noCheckouts": "Engir bátar á sjó.",
  "member.noBoats": "Engir bátar lausir.",
  "member.noCerts": "Engin skírteini skráð.",
  "member.boatOut": "Úti",
  "member.boatOos": "Utan þjónustu",
  "member.boatAvail": "Laus",
  "member.skipper": "skipstjóri",
  "member.crewRole": "áhöfn",
  "member.addAsCrew": "Bæta við sem áhöfn",
  "member.tripsTapHint": "Smelltu á siglingu til að sjá nánar",
  "member.departed": "Lagt af stað",
  "member.returned": "Komið tilbaka",
  "member.duration": "Tímalengd",
  "member.loadFailed": "Hleðsla mistókst",
  "member.logManual": "+ Skrá handvirkt",
  "member.recentTrips": "NÝLEGAR SIGLINGAR",
  "member.noRecent": "Engar nýlegar siglingar",
  "member.myLogbook": "MÍN DAGBÓK",
  "member.myCerts": "MÍN SKÍRTEINI",
  "member.launchTitle": "Fara á sjó",
  "member.nonClubBoat": "Bátur utan félags",
  "member.nonClubHint": "Notaðu þinn eigin bát eða bát frá öðru félagi",
  "member.checkInTitle": "Skrá inn",
  "member.manualTrip": "Skrá siglingu",
  "member.pendingConfirmations": "Beiðnir í bið",
  "member.confirmationsTitle": "Staðfestingar siglinga",
  "member.incoming": "BEIÐNIR TIL ÞÍN",
  "member.outgoing": "ÞÍNAR BEIÐNIR",
  "member.noIncoming": "Engar beiðnir í bið.",
  "member.noOutgoing": "Engar beiðnir sendar.",
  "member.crewAssigned": "skráði þig sem áhöfn",
  "member.crewJoin": "vill taka þátt í siglingu þinni",
  "member.helmReq": "merkti þig sem stýrimann",
  "member.confirmBtn": "Staðfesta",
  "member.rejectBtn": "Hafna",
  "member.statusPending": "í bið",
  "member.statusConfirmed": "staðfest",
  "member.statusRejected": "hafnað",
  "member.rejectReason": "Ástæða höfnunar (valfrjálst):",
  "member.shareRecord": "DEILA SKRÁNINGU",
  "member.shareDesc": "Búðu til hlekk til að deila siglingaskráningunni þinni með leiguaðilum eða öðrum. Hlekkurinn sýnir siglingalotur til og með deginum í dag.",
  "member.btnGenerate": "+ Búa til deilingarhlekk",
  "member.noTokens": "Engir deilingarhlekkir búnir til enn.",
  "member.tokenCreated": "Deilingarhlekkur búinn til.",
  "settings.title": "Stillingar",
  "settings.initials": "Upphafsstafir",
  "settings.initialsHint": "Sjálfvirkt búið til úr nafni. Breyttu hér að neðan.",
  "settings.language": "Tungumál",
  "settings.windUnit": "Vindeining",
  "settings.windUnit.bft": "Beaufort (Force 4)",
  "settings.windUnit.ms": "m/s",
  "settings.windUnit.kts": "Hnútar",
  "settings.windUnit.kmh": "km/klst",
  "settings.windUnit.mph": "mph",
  "settings.windUnitHint": "Stýrir hvernig vindur birtist í dagbókinni þinni.",
  "settings.theme": "Útlit",
  "settings.theme.dark": "Dökkt",
  "settings.theme.light": "Ljóst",
  "settings.theme.auto": "Sjálfvirkt",
  "settings.stats": "Tölfræði sýnileiki",
  "settings.statsHint": "Veldu hvaða tölfræði birtist á dagbókarsíðunni þinni.",
  "settings.stats.ytd": "Siglingar á þessu ári",
  "settings.stats.career": "Samtals siglingar (ferill)",
  "settings.stats.hours": "Siglingatímar",
  "settings.stats.skipper": "Sem skipstjóri",
  "settings.stats.byCategory": "Tímar eftir flokki",
  "settings.stats.distance": "Heildar vegalengd (nm)",
  "settings.stats.longest": "Lengsta sigling",
  "settings.stats.avgWind": "Meðalvindur",
  "settings.stats.streak": "Vikuleg röð",
  "settings.stats.boats": "Einstök bátar sigld",
  "settings.stats.crew": "Siglingar sem áhöfn",
  "settings.stats.heavy": "Hörð veður (F5+)",
  "settings.stats.night": "Nætursiglingar",
  "settings.stats.avgDuration": "Meðal siglingatími",
  "settings.stats.locations": "Staðir sigldir",
  "settings.stats.verified": "Staðfestar siglingar",
  "settings.statsGroup.activity": "Virkni",
  "settings.statsGroup.sailing": "Sigling",
  "settings.statsGroup.roles": "Hlutverk og bátar",
  "settings.statsGroup.conditions": "Aðstæður",
  "settings.statsGroup.other": "Annað",
  "settings.saved": "Stillingar vistaðar",
  "settings.saveFailed": "Mistókst að vista stillingar",
  "nav.settings": "⚙ Stillingar",
  "logbook.shareBtn": "Deila dagbókinni þinni",
  "logbook.sharePhotos": "Taka myndir með",
  "logbook.shareTracks": "Taka GPS-leiðir með",
  "logbook.shareCopy": "Búa til og afrita hlekk",
  "logbook.shareCopied": "Hlekkur afritaður!",
  "logbook.activeTokens": "Virk deilingartóken",
  "logbook.editTrip": "Breyta ferð",
  "logbook.addGps": "Bæta við GPS",
  "logbook.addPhotos": "Bæta við myndum",
  "logbook.shareWithCrew": "Deila með áhöfn",
  "logbook.clubMayUse": "Félagið má nota",
  "logbook.photoSharedHint": "Deildar myndir sjást öðrum í ferðinni. Myndir merktar fyrir félagið má nota í kynningarefni.",
  "logbook.tripUpdated": "Ferð uppfærð",
  "logbook.trackAdded": "GPS-leið bætt við",
  "logbook.photosAdded": "Myndir bættar við",
  "logbook.skipperOnly": "Aðeins skipstj��ri getur breytt ferðinni",
  "staff.dashTitle": "Stjórnborð starfsmanna",
  "staff.fleet": "STAÐA FLOTANS",
  "staff.expandAll": "sýna allt",
  "staff.collapseAll": "fela allt",
  "staff.recentCheckins": "NÝLEGAR INNSKRÁNINGAR (24H)",
  "staff.overdue": "UMFRAM ÁÆTLUN",
  "staff.overdueMinor": "UMFRAM ÁÆTLUN — BARN",
  "staff.maintenance": "OPIN VIÐHALDSMÁL",
  "staff.maintDetail": "Upplýsingar",
  "staff.dailyLog": "Dagbók félagsins",
  "staff.dailyLogDesc": "Flóð, veðurskráning, gátlistar, starfsemi, undirskrift",
  "staff.logbook": "Dagbókarskoðun",
  "staff.logbookDesc": "Staðfesta ferðir félaga og úthluta skírteinum",
  "staff.incidents": "Tilvik",
  "staff.incidentsDesc": "Skrá eða fara yfir öryggistilvik",
  "staff.maintenanceDesc": "Tilkynna og fylgjast með vandamálum á bátum og búnaði",
  "staff.noOverdue": "Engar yfirtíma útskráningar.",
  "staff.noMaint": "Engar opnar beiðnir.",
  "staff.silence": "Þagga",
  "staff.snooze": "Fresta",
  "staff.minsOverdue": "{n} mín yfirtíma",
  "staff.hrsOverdue": "{h}klst {m}mín yfirtíma",
  "staff.expectedReturn": "Áætlaður skilatími",
  "staff.checkIn": "✓ Skrá inn",
  "staff.deleteCheckout": "Eyða",
  "staff.availCount": "{n} tiltækir",
  "staff.activeCheckouts": "VIRKAR ÚTSKRÁNINGAR",
  "staff.boatsOutNow": "BÁTAR Á SJÓNUM",
  "staff.checkOutBtn": "Uthluta bati",
  "staff.groupCheckout": "Hópaúthlutun",
  "staff.newCheckout": "NÝ ÚTSKRÁNING",
  "staff.statBoats": "BÁTAR Á SJÓ",
  "staff.statPeople": "FÓLK Á SJÓ",
  "staff.statOverdue": "YFIRTÍMA",
  "staff.toolsLabel": "VERKFÆRI",
  "staff.fullForecast": "⛅️ Heildarlíkan →",
  "staff.tideHeader": "FLÓÐ · FAXAFLÓI",
  "tide.rising": "Hækkandi",
  "tide.falling": "Lækkandi",
  "tide.high": "Flóð",
  "tide.low": "Fjara",
  "tide.next": "NÆST",
  "tide.autoFill": "↻ Fylla sjálfkrafa",
  "tide.autoFilled": "Sjálfkrafa fyllt úr spá",
  "staff.coForm.departure": "Brottför",
  "staff.coForm.estReturn": "Áætl. heimkoma",
  "staff.coForm.crew": "Áhöfn um borð",
  "staff.coForm.notes": "Athugasemdir (valfrjálst)",
  "staff.coForm.submit": "Útskrá",
  "staff.coForm.memberPlaceholder": "Nafn eða kennitala…",
  "staff.coForm.notesPlaceholder": "Einhverjar athugasemdir…",
  "staff.coForm.errMember": "Veldu félaga.",
  "staff.coForm.errBoat": "Veldu bát.",
  "staff.coForm.errLocation": "Veldu siglingasvæði.",
  "staff.coForm.checkedOut": "Útskráð ✓",
  "staff.coDetail.title": "Upplýsingar um útskráningu",
  "staff.coDetail.tripLabel": "FERÐ",
  "staff.coDetail.out": "FÓRT",
  "staff.coDetail.return": "ÁÆTL. HEIMKOMA",
  "staff.noBoatsOut": "Engir bátar á sjónum.",
  "staff.noRecentCheckins": "Engar innkráningar síðustu 24 klukkustundir.",
  "daily.title": "Dagleg skráning",
  "daily.today": "Í dag",
  "daily.tripsToday": "FERÐIR Í DAG",
  "daily.openingChecklist": "OPNUNARGÁTLISTI",
  "daily.closingChecklist": "LOKUNARGÁTLISTI",
  "daily.activities": "STARFSEMI",
  "daily.addActivity": "+ Bæta við",
  "daily.staffNotes": "ATHUGASEMDIR STARFSMANNA",
  "daily.notesPlaceholder": "Almennar athugasemdir, samantekt á aðstæðum…",
  "daily.incidentReport": "TILVIK",
  "daily.fileIncident": "Senda tilviksskýrslu",
  "daily.incidentSub": "Meiðsli, næstum slys, eignatjón, öryggismál",
  "daily.noIncidents": "Engin tilvik tilkynnt.",
  "daily.wxLog": "VEÐURSKRÁNING",
  "daily.tides": "FLÓÐ OG EBB",
  "daily.signedOff": "Undirritað",
  "daily.readOnly": "Lesaðgangur",
  "daily.noActivities": "Engin starfsemi skráð enn.",
  "daily.noTrips": "Engar ferðir skráðar í dag.",
  "daily.activityModal": "Bæta við starfsemi",
  "daily.actType": "Tegund",
  "daily.actNameLabel": "Nafn / lýsing",
  "daily.actNameHint": "t.d. Unglingakennsla, félagskeppni…",
  "daily.actParticipants": "Þátttakendur",
  "daily.actPartHint": "t.d. 12 unglingar",
  "daily.actNotes": "Athugasemdir",
  "daily.actNotesHint": "valfrjálst",
  "daily.startTime": "Byrjunartími",
  "daily.endTime": "Lokatími",
  "daily.wxLogBtn": "📸 Taka veðurmynd",
  "daily.noWxData": "Engin veðurgögn enn.",
  "daily.signOffConfirm": "PM gátlisti er ekki fullkláraður ({done}/{total}). Undirrita samt?",
  "daily.saveDraftSaving": "Vista…",
  "daily.signOffSaving": "Undirritun…",
  "daily.signedOffBy": "✓ Undirritað af ",
  "incident.title": "Tilvik",
  "incident.viewList": "Skoða tilvik",
  "incident.fileNew": "Skrá nýja skýrslu",
  "incident.typeLabel": "Tegund tilviks",
  "incident.noIncidents": "Engin tilvik skráð.",
  "incident.description": "Lýsing",
  "incident.involved": "Hlutaðeigandi aðilar",
  "incident.witnesses": "Vitni",
  "incident.immediateAction": "Bráðabirgðaaðgerðir",
  "incident.followUp": "Nauðsynleg eftirfylgni",
  "incident.handOff": "Framselt til",
  "incident.staffNotes": "Athugasemdir starfsmanna",
  "incident.addNote": "Bæta við athugasemd",
  "incident.resolved": "Lokið",
  "incident.open": "Opið",
  "incident.markResolved": "Merkja sem lokið",
  "incident.markOpen": "Enduropna",
  "incident.filedBy": "Skráð af",
  "incident.boatLabel": "Bátur (ef við á)",
  "incident.personsInvolved": "Aðilar að máli",
  "incident.witnessHint": "Nöfn / tengiliðaupplýsingar…",
  "incident.actionHint": "Skyndihjálp, rýming, landhelgisgæslan…",
  "incident.followUpHint": "Tilvísun, viðgerð, rannsókn…",
  "incident.handoffSection": "Framsending",
  "incident.handoffTo": "Framselt til",
  "incident.handoffName": "Nafn tengiliðar / tilvísun",
  "incident.handoffNotes": "Athugasemdir um framsendingu",
  "incident.fileBtn": "Skrá skýrslu",
  "incident.descRequired": "Lýsing er skylda.",
  "incident.typeRequired": "Veldu að minnsta kosti eina tegund tilviks.",
  "incident.sevRequired": "Veldu alvarleika.",
  "incident.filed": "Skýrsla skráð ✓",
  "incident.addNoteBtn": "Bæta við athugasemd",
  "incident.notePlaceholder": "Bæta við athugasemd…",
  "incident.type.injury": "🩹 Meiðsli",
  "incident.type.capsize": "⛵ Kæning",
  "incident.type.collision": "💥 Árekstur",
  "incident.type.equipment": "🔧 Búnaðarbilun",
  "incident.type.medical": "🏥 Læknisfræðilegt",
  "incident.type.nearMiss": "⚡️ Nákvæmt miss",
  "incident.type.missing": "🔍 Saknað manneskja",
  "incident.type.propertyDmg": "🏗️ Eignatjón",
  "incident.type.other": "📌 Annað",
  "incident.sev.low": "Lágt",
  "incident.sev.medium": "Miðlungs",
  "incident.sev.high": "Hátt",
  "incident.sev.critical": "Bráðavarsamt",
  "maint.title": "Viðhald",
  "maint.newRequest": "+ Tilkynna vandamál",
  "maint.category": "Flokkur",
  "maint.catBoat": "Bátur",
  "maint.catEquipment": "Búnaður",
  "maint.catFacility": "Aðstaða",
  "maint.part": "Hluti",
  "maint.severity": "Alvarleiki",
  "maint.sevLow": "Lágt — engin haste",
  "maint.sevMedium": "Miðlungs — laga fljótt",
  "maint.sevHigh": "Hátt — hefur áhrif á öryggi",
  "maint.markOos": "Merkja bát utan þjónustu",
  "maint.reportedBy": "Tilkynnt af",
  "maint.noRequests": "Engar opnar viðhaldsbeiðnir.",
  "maint.resolved": "Lokið",
  "maint.open": "Opið",
  "maint.resolveBtn": "Merkja sem lokið",
  "maint.comments": "Athugasemdir",
  "maint.descPlaceholder": "Lýstu vandamálinu…",
  "maint.partPlaceholder": "t.d. stýrið, forskatbylja…",
  "maint.newTitle": "NÝ VIÐHALDSBEIÐNI",
  "maint.filterOpen": "Opið",
  "maint.filterAll": "Allt",
  "maint.filterBoat": "Bátur",
  "maint.filterEquipment": "Búnaður",
  "maint.filterFacility": "Aðstaða",
  "maint.commentPlaceholder": "Bæta við athugasemd…",
  "maint.addCommentBtn": "Bæta við",
  "maint.oosConfirm": "Merkja þennan bát utan þjónustu?",
  "maint.resolveConfirm": "Merkja þessa beiðni sem lokna?",
  "maint.statOpen": "OPIÐ",
  "maint.statHigh": "HÁTT / BRÁÐAVARSAMT",
  "maint.statOos": "BÁTAR UTAN ÞJÓNUSTU",
  "sauma.pageTitle": "🧵 Saumaklúbbur",
  "sauma.pageSubtitle": "Samfélagsverkefni í viðhaldi",
  "sauma.toggle": "Saumaklúbbsverkefni",
  "sauma.toggleHint": "Merkja sem saumaklúbbsverkefni",
  "sauma.verkstjori": "Verkstjóri",
  "sauma.verkstjoriHint": "Ef autt, getur hvaða félagi sem er tekið verkefnið að sér.",
  "sauma.filterOpen": "Opið",
  "sauma.filterMy": "Mín verkefni",
  "sauma.filterUnassigned": "Ótilnefnd",
  "sauma.filterCompleted": "Lokið",
  "sauma.filterResolved": "Lokið",
  "sauma.filterAll": "Allt",
  "sauma.needsVerkstjori": "Þarf verkstjóra",
  "sauma.emptyDefault": "Engin verkefni passa við þessa síu.",
  "sauma.emptyMy": "Engin verkefni sem þú tekur þátt í.",
  "sauma.suggestBtn": "+ Nýtt saumaklúbbsverkefni",
  "sauma.suggestTitle": "🧵 Nýtt saumaklúbbsverkefni",
  "sauma.pendingReview": "Bíður samþykktar",
  "sauma.approve": "Samþykkja",
  "sauma.pendingMsg": "Verkefni sent til samþykktar.",
  "maint.statPending": "BÍÐUR SAMÞYKKTAR",
  "sauma.priority": "Forgangur",
  "sauma.description": "Lýsing",
  "sauma.materials": "Efni sem þarf",
  "sauma.photoLabel": "Mynd (valfrjálst, hámark 5 MB)",
  "sauma.viewList": "Listi",
  "sauma.viewBoard": "Borð",
  "sauma.colPending": "Bíður samþykktar",
  "sauma.colTodo": "Verkefni",
  "sauma.colInProgress": "Í vinnslu",
  "sauma.colOnHold": "Í bið",
  "sauma.colDone": "Lokið",
  "sauma.colEmpty": "Engin verkefni",
  "sauma.myBoardFilter": "Aðeins mín verkefni",
  "sauma.holdBtn": "Setja í bið",
  "sauma.resumeBtn": "Halda áfram",
  "sauma.holdConfirm": "Setja þetta verkefni í bið?",
  "sauma.resumeConfirm": "Halda áfram með þetta verkefni?",
  "sauma.filterOnHold": "Í bið",
  "nav.saumaklubbur": "🧵 Saumaklúbbur",
  "staff.maintAndSauma": "Viðhald & Verkefni",
  "staff.maintAndSaumaDesc": "Viðhaldsbeiðnir & saumaklúbbsverkefni",
  "logrev.title": "Dagbókarskoðun",
  "logrev.subtitle": "Staðfesta ferðir félaga · úthluta skírteinum",
  "logrev.totalTrips": "SAMTALS FERÐIR",
  "logrev.pending": "BÍÐUR SKOÐUNAR",
  "logrev.verified": "STAÐFEST",
  "logrev.verify": "Staðfesta",
  "logrev.unverify": "Afstaðfesta",
  "logrev.staffComment": "Athugasemd starfsmanns (valfrjálst)",
  "logrev.noTrips": "Engar ferðir til skoðunar.",
  "logrev.filterAll": "Allt",
  "logrev.filterPending": "Í bið",
  "logrev.filterVerified": "Staðfest",
  "logrev.filterName": "Sía eftir nafni…",
  "logrev.filterFrom": "Frá",
  "logrev.filterTo": "Til",
  "logrev.assignCert": "ÚTHLUTA SKÍRTEINI",
  "logrev.assignedDate": "Úthlutunardagur",
  "logrev.expires": "Rennur út",
  "logrev.assignBtn": "Úthluta",
  "logrev.certModal": "Skírteini",
  "logrev.noCerts": "Engin skírteini skráð.",
  "logrev.validationRequests": "Beiðnir um staðfestingu",
  "logrev.showAll": "Sýna allar ferðir",
  "logrev.certSearch": "Leitaðu að félaga hér að ofan til að skoða skírteini.",
  "logrev.certSearchPlaceholder": "Leita að nafni félaga...",
  "logrev.certModeByMember": "Eftir félaga",
  "logrev.certModeByType": "Eftir skírteini",
  "logrev.certSelectType": "— Veldu skírteini —",
  "logrev.certNoMatches": "Engir félagar fundust með þetta skírteini.",
  "logrev.verifyRequest": "STAÐFESTINGARBEIÐNI",
  "admin.tabMembers": "Félagar",
  "admin.tabSettings": "Stillingar",
  "admin.tabBoats": "Bátar",
  "admin.tabLocations": "Staðir",
  "admin.tabChecklists": "Gátlistar",
  "admin.tabActTypes": "Tegundir starfsemi",
  "admin.tabCerts": "Skírteini",
  "admin.tabAlerts": "Viðvaranir",
  "admin.tabPayroll": "💰 Launakerfi",
  "admin.tabFlags": "🚩 Fánar",
  "admin.tabReservations": "📅 Leigur",
  "admin.importCsv": "⇪ Flytja inn CSV",
  "admin.searchMembers": "Leita að nafni eða kennitölu…",
  "admin.noMembers": "Engir félagar ennþá.",
  "admin.addMember": "+ Bæta við félaga",
  "admin.addBoat": "+ Bæta við bát",
  "admin.addLocation": "+ Bæta við stað",
  "admin.addItem": "+ Bæta við atriði",
  "admin.addType": "+ Bæta við tegund",
  "admin.importUpdated": "uppfært",
  "admin.importMissing": "ekki í innflutningi",
  "admin.importUnchanged": "óbreytt",
  "admin.saveChanges": "Vista breytingar",
  "admin.alertFirstMins": "Fyrsta viðvörun eftir (mín)",
  "admin.alertRepeatMins": "Endurtaka á (mín)",
  "admin.alertSnoozeMins": "Frestunarlengd (mín)",
  "admin.alertEnabled": "Viðvaranir virkar",
  "admin.flagThresholds": "Mörk fána",
  "admin.windYellow": "Vindur gulur (Bft)",
  "admin.windOrange": "Vindur appelsínugulur (Bft)",
  "admin.windRed": "Vindur rauður (Bft)",
  "admin.waveYellow": "Bylgja gul (m)",
  "admin.waveOrange": "Bylgja appelsínugul (m)",
  "admin.waveRed": "Bylgja rauð (m)",
  "admin.memberModal.add": "Bæta við félaga",
  "admin.memberModal.edit": "Breyta félaga",
  "admin.fullName": "Fullt nafn",
  "admin.birthYear": "Fæðingarár",
  "admin.isMinor": "Barn (undir 18)",
  "admin.guardianSection": "FORRÁÐAMAÐUR / FORELDRI",
  "admin.guardianName": "Nafn forráðamanns",
  "admin.guardianPhone": "Sími forráðamanns",
  "admin.guardianKt": "Kennitala forráðamanns",
  "admin.boatModal.add": "Bæta við bát",
  "admin.boatModal.edit": "Breyta bát",
  "admin.boatName": "Nafn báts",
  "admin.boatCategory": "Flokkur",
  "admin.boatOos": "Utan þjónustu",
  "admin.boatOosReason": "Ástæða OOS",
  "admin.locModal.add": "Bæta við stað",
  "admin.locModal.edit": "Breyta stað",
  "admin.clPhase": "Fasi",
  "admin.clPhaseAm": "AM",
  "admin.clPhasePm": "PM",
  "admin.clTextEN": "Texti (EN)",
  "admin.clTextIS": "Texti (IS)",
  "admin.actTypeEN": "Nafn (EN)",
  "admin.actTypeIS": "Nafn (IS)",
  "admin.certName": "Nafn skírteinis (EN)",
  "admin.certRenewal": "Endurnýjun (dagar, 0 = varanlegt)",
  "admin.certTypes": "TEGUNDIR SKÍRTEINA",
  "admin.certAssign": "ÚTHLUTA SKÍRTEINUM",
  "admin.certAddType": "+ Bæta við tegund skírteinis",
  "admin.certAddModal": "Bæta við tegund skírteinis",
  "admin.certEditModal": "Breyta tegund skírteinis",
  "admin.certDesc": "Lýsing",
  "admin.certDescOptional": "(valfrjálst)",
  "admin.certRenewalPerm": "Varanlegt",
  "admin.certRenewalAnnual": "Árlegt (365 dagar)",
  "admin.certRenewalBiennial": "Annað hvert ár (730 dagar)",
  "admin.certRenewalCustom": "Sérsniðið…",
  "admin.certDaysUntilExpiry": "Dagar þar til rennur út",
  "admin.certSearchMember": "Leita að félaga…",
  "admin.certAllTypes": "Allar tegundir skírteina",
  "admin.noBoats": "Engir bátar.",
  "admin.noLocations": "Engir staðir.",
  "admin.backToList": "← Aftur á lista",
  "admin.importFromCsv": "Flytja inn úr Abler.io CSV",
  "cert.noCerts": "Engin skírteini skráð.",
  "cert.assignedBy": "Úthlutað af",
  "cert.assignedAt": "Úthlutað",
  "cert.expires": "Rennur út",
  "cert.expired": "Útrunnið",
  "cert.permanent": "Varanlegt",
  "cert.level": "Stig / Undirflokkur",
  "cert.assign": "Úthluta",
  "cert.remove": "Fjarlægja",
  "cert.issuingAuthority": "Útgefandi",
  "cert.renewalDays": "Endurnýjun (dagar)",
  "cert.renewalOverride": "Endurnýjun (dagar, hnekkir yfirflokki)",
  "cert.fixedExpiry": "Föst lokadagsetning",
  "cert.fixedExpiryOverride": "Föst lokadagsetning (hnekkir endurnýjun)",
  "cert.subcats": "Undirflokkar",
  "cert.subcatHint": "Bættu við undirflokkum ef skírteinið hefur stig (t.d. Stig 1, 2, 3). Stilltu röð til að framfylgja „hærra kemur í stað lægra\" rök. Útgefandi, endurnýjunardagar eða föst lokadagsetning á undirflokki hnekkir gildum yfirflokksins.",
  "cert.noSubcats": "Engir undirflokkar",
  "cert.subcatLabel": "Merking (t.d. Stig 1)",
  "cert.subcatDesc": "Lýsing",
  "cert.subcatRank": "Röð",
  "cert.rankHint": "Röð (hærra kemur í stað lægra við úthlutun)",
  "cert.cardColour": "Litur korts",
  "cert.colourAuto": "sjálfvirkt ef autt",
  "cert.deleteConfirm": "Eyða þessari tegund skírteinis? Þetta mun ekki fjarlægja fyrirliggjandi úthlutanir.",
  "cert.deleteSubConfirm": "Fjarlægja þennan undirflokk?",
  "cert.saved": "Tegund skírteinis vistuð.",
  "cert.deleted": "Tegund skírteinis eytt.",
  "cert.assigned": "Skírteini úthlutað.",
  "cert.removed": "Skírteini fjarlægt.",
  "cert.nameRequired": "Nafn vantar.",
  "cert.typeRequired": "Veldu tegund skírteinis.",
  "cert.levelRequired": "Veldu stig / undirflokk.",
  "cert.clubEndorsements": "ÁRITANIR KLÚBBSINS",
  "cert.loadError": "Gat ekki hlaðið skírteinum.",
  "payroll.tabTimeReporting": "Tímaskráning",
  "payroll.tabTimesheets": "Launaseðlar",
  "payroll.tabEmployees": "Starfsmenn",
  "payroll.tabLaunamidlar": "Útflutningur",
  "payroll.definePeriod": "Skilgreina launatímabil",
  "payroll.periodFrom": "Frá",
  "payroll.periodTo": "Til",
  "payroll.previewPayslips": "Forskoða launaseðla",
  "payroll.approvePeriod": "Samþykkja og loka tímabili",
  "payroll.approveConfirm": "Samþykkja launaseðla allra starfsmanna og loka þessu tímabili?",
  "payroll.periodClosed": "Tímabili lokað ✓",
  "payroll.exportPdf": "Sækja PDF",
  "payroll.exportXml": "Sækja XML",
  "payroll.noPeriodDefined": "Ekkert launatímabil skilgreint enn.",
  "payroll.noClosedPeriods": "Engin lokuð tímabil enn.",
  "payroll.hoursFromSheets": "Tímar úr tímaskráningu",
  "payroll.hoursConfirm": "Staðfestu tíma áður en samþykkt er",
  "payroll.manualLines": "Handvirðar línur",
  "payroll.addLine": "+ Bæta við línu",
  "payroll.lineDescription": "Lýsing",
  "payroll.lineDescriptionIS": "Lýsing (IS)",
  "payroll.lineAmount": "Upphæð (kr)",
  "payroll.regularHours": "Dagvinna (klst)",
  "payroll.ot1Hours": "Eftirvinna 1,33",
  "payroll.ot2Hours": "Eftirvinna 1,55",
  "payroll.correctedHours": "Leiðréttir tímar",
  "payroll.hoursNote": "Athugasemd / ástæða leiðréttingar",
  "payroll.confirmHours": "Staðfesta tíma",
  "payroll.periodApproved": "Samþykkt",
  "payroll.periodOpen": "Opið",
  "payroll.periodLabel": "Launatímabil",
  "payroll.employeeCount": "{n} starfsmenn",
  "payroll.grossLabel": "Heildarlaun",
  "payroll.netLabel": "Útborgun",
  "payroll.paymentDate": "Greiðsludagur",
  "payroll.slipNumber": "Seðilnúmer",
  "payroll.personuafslattr": "Persónuafsláttur (kr/mán.)",
  "payroll.personuafslattrPct": "% af staðlaðri upphæð hér",
  "payroll.configTitle": "Stillingar launakerfis",
  "payroll.ot1Rate": "Eftirvinna þrep 1 margfaldari",
  "payroll.ot2Rate": "Eftirvinna þrep 2 margfaldari",
  "payroll.orlofsRate": "Orlofslaun hlutfall",
  "payroll.empPensionRate": "Lífeyrissjóður starfsmann %",
  "payroll.emplPensionRate": "Mótframlag lífeyrissjóður %",
  "payroll.taxBracket1": "Skattstigi 1 (upp að 583.854 kr)",
  "payroll.taxBracket2": "Skattstigi 2 (upp að 1.645.733 kr)",
  "payroll.taxBracket3": "Skattstigi 3",
  "payroll.unionDuesRate": "Stéttarfélagsgjald hlutfall",
  "payroll.hoursTotal": "Heildartímar",
  "payroll.editEntry": "Breyta",
  "payroll.notEnabled": "Ekki í launakerfi",
  "payroll.enablePayroll": "Virkja í launakerfi",
  "payroll.calView": "Dagatal",
  "payroll.listView": "Listi",
  "payroll.addEntry": "+ Bæta við færslu",
  "payroll.deleteEntry": "Eyða",
  "payroll.deleteConfirm": "Eyða þessari tímafærslu?",
  "payroll.allStaff": "Allir starfsmenn",
  "payroll.employee": "Starfsmaður",
  "payroll.totalHours": "samtals",
  "payroll.clockInLabel": "Stimpla inn",
  "payroll.clockOutLabel": "Stimpla út",
  "payroll.minsLabel": "Tímalengd (mínútur)",
  "payroll.noteOptional": "Athugasemd (valfrjálst)",
  "payroll.notePlaceholder": "t.d. gleymt innstimpl",
  "payroll.autoCalc": "reiknast sjálft, hnekktu ef þarf",
  "payroll.entryRequired": "Starfsmaður, innstimplun og útstimplun eru nauðsynleg.",
  "payroll.clockOutAfterIn": "Útstimplun verður að vera eftir innstimplun.",
  "payroll.moreEntries": "í viðbót",
  "payroll.pastPeriods": "Fyrri tímabil",
  "payroll.titleField": "Starfsheiti",
  "payroll.bankAccount": "Launareikningur",
  "payroll.orlofsreikningur": "Orlofsreikningur",
  "payroll.union": "Stéttarfélag",
  "payroll.sereignRate": "Séreign %",
  "payroll.pension": "Lífeyrissjóður",
  "lbl.year": "Ár",
  "lbl.duration": "Tímalængd",
  "lbl.edited": "breytt",
  "lbl.view": "Sjá",
  "lbl.admin": "stjórnandi",
  "lbl.staff": "starfsmaður",
  "lbl.monShort": "Mán",
  "lbl.tueShort": "Þri",
  "lbl.wedShort": "Mið",
  "lbl.thuShort": "Fim",
  "lbl.friShort": "Fös",
  "lbl.satShort": "Lau",
  "lbl.sunShort": "Sun",
  "payroll.earningsSection": "Laun",
  "payroll.deductionsSection": "Frádráttur",
  "payroll.accumulatedSection": "Til uppsafnanar",
  "payroll.employerSection": "Framlag launagreiðanda",
  "payroll.ytdSection": "Ár til þa gs",
  "payroll.totalDeductions": "Heildarf rádráttur",
  "payroll.orlofslaun": "Orlof í banka",
  "payroll.payslip": "Launaseðill",
  "payroll.baseRate": "Grunntaxti (kr/klst)",
  "payroll.dagvinna": "Dagvinna",
  "payroll.ot1Label": "Eftirvinna 1,33",
  "payroll.ot2Label": "Eftirvinna 1,55",
  "payroll.units": "Einingar",
  "payroll.rate": "Taxti",
  "payroll.amount": "Upphæð",
  "payroll.ytdUnits": "Einingar (ár)",
  "payroll.taxComputed": "Reiknuð staðgreiðsla",
  "payroll.employerPension": "Mótframlag lífeyriss",
  "payroll.endurhaefingarsjodur": "Endurhæfingarsjóður",
  "payroll.now": "Nú",
  "payroll.config": "Stillingar",
  "payroll.configPayroll": "Launastillingar",
  "payroll.pensionFunds": "Lífeyrissjóðir",
  "payroll.addFund": "Bæta við sjóði",
  "payroll.fundName": "Heiti sjóðs",
  "payroll.fundNameEN": "Heiti sjóðs (EN)",
  "payroll.unions": "Stéttarfélög",
  "payroll.addUnion": "Bæta við félagi",
  "payroll.unionName": "Heiti félags",
  "payroll.deductionLines": "Frádráttsliðir",
  "payroll.lineLabel": "Heiti",
  "payroll.lineLabelEN": "Heiti (EN)",
  "payroll.empRate": "Starfsmaður %",
  "payroll.emprRate": "Launagreiðandi %",
  "payroll.otRules": "Yfirvinnureglur",
  "payroll.otEligible": "Réttindi til yfirvinnu",
  "payroll.otPeriods": "Yfirvinnuterúr",
  "payroll.otDays": "Dagar (0=Sun…6=Lau)",
  "payroll.otFrom": "Frá klukkustund",
  "payroll.otTo": "Að klukkustund",
  "payroll.otMultiplier": "Margfaldari",
  "payroll.personuafslattrUnit": "Persónuafsláttur eining (kr = 1,0)",
  "payroll.personuafslattrFrac": "Hlutfall persónuafsláttar",
  "payroll.pensionFundIds": "Lífeyrissjóður",
  "payroll.unionId": "Stéttarfélag",
  "payroll.none": "Ekkert",
  "payroll.personuafslattrFraction": "Hlutfall persónuafsláttar",
  "payroll.section": "STIMPILKLUKKA",
  "payroll.otTierLabel": "Heiti",
  "payroll.otTierLabelEN": "Heiti (EN)",
  "payroll.addOTTier": "+ Bæta við yfirvinnuþrepi",
  "payroll.deleteOTTier": "Fjarlægja",
  "payroll.taxBrackets": "Skattþrep",
  "payroll.taxBracketUpTo": "Upp að (kr)",
  "payroll.taxBracketRate": "Hlutfall (%)",
  "payroll.taxBracketUnlimited": "∞ (hæsta þrep)",
  "payroll.addTaxBracket": "+ Bæta við þrepi",
  "payroll.tabExportData": "Útflutningur",
  "payroll.exportWithholding": "XML — Staðgreiðsla",
  "payroll.exportPayslipXml": "XML — Launaseðlagögn",
  "payroll.exportPensionCsv": "CSV — Lífeyrissjóðsgögn",
  "payroll.exportLaunamidlar": "XML — Launamiðlar",
  "payroll.exportPlaceholder": "Ekki tilbúið — kemur bráðlega",
  "payroll.selectPeriod": "— Velja tímabil —",
  "payroll.exportCsv": "Sækja CSV",
  "payroll.stadEmployerInfo": "Upplýsingar um launagreiðanda — Staðgreiðsla",
  "payroll.stadKt": "Kennitala launagreiðanda",
  "payroll.stadEmail": "Tölvupóstfang",
  "payroll.stadVeflykill": "Veflykill",
  "payroll.stadForrit": "Kerfisheiti",
  "payroll.stadIsat": "Atvinnuvegaflokkun (ISAT 2008)",
  "payroll.stadKtRequired": "Kennitala launagreiðanda vantar",
  "payroll.starfshlutfall": "Starfshlutfall (%)",
  "payroll.istarf95": "Starfaflokkun",
  "payroll.taxWithheld": "Staðgreiðsla",
  "payroll.clockIn": "Stimpla inn",
  "payroll.clockOut": "Stimpla út",
  "payroll.startBreak": "Fara í hlé",
  "payroll.endBreak": "Ljúka hlé",
  "payroll.currentShift": "Á vakt",
  "payroll.onBreak": "Í hléi síðan",
  "payroll.clockedInAt": "Stimplaðist inn",
  "payroll.recentShifts": "Nýlegar vaktir",
  "payroll.noShifts": "Engar vaktir skráðar",
  "payroll.shiftSummary": "Samantekt vaktar",
  "payroll.totalWorked": "Vann samtals",
  "payroll.totalBreak": "Hlé samtals",
  "payroll.confirmShift": "Loka",
  "payroll.allowBreaks": "Leyfa hléaskráningu",
  "logbook.distanceNm": "Vegalengd (sjómílur)",
  "logbook.departurePort": "Brottfararstaður",
  "logbook.arrivalPort": "Komustaður",
  "logbook.portsOptional": "Höfnar — valfrjálst",
  "logbook.addPort": "+ Bæta „{name}\" við höfnalista",
  "logbook.nonClubToggle": "Ferð utan félags",
  "logbook.nonClubHint": "— skrá ferð utan félagskerfisins",
  "logbook.boatNameLabel": "Nafn báts",
  "logbook.boatNamePh": "t.d. Sunfish, RIB, o.þ.h.",
  "logbook.boatCategory": "Flokkur",
  "logbook.locationNamePh": "t.d. Þingvallavatn",
  "logbook.useMyLocation": "Nota staðsetningu mína",
  "logbook.locating": "Staðsetning…",
  "logbook.locationDenied": "Staðsetningaraðgangur hafnaður",
  "logbook.enterBoatName": "Vinsamlegast sláðu inn nafn báts.",
  "logbook.enterLocation": "Vinsamlegast sláðu inn staðsetningu.",
  "logbook.gpsTrack": "GPS-leið — GPX / KML / KMZ",
  "logbook.photos": "Myndir",
  "logbook.trackReady": "Tilbúið: {name}",
  "logbook.trackAttached": "📍 GPS-leið",
  "logbook.portSame": "⚓️ {port}",
  "logbook.portRoute": "⚓️ {from} → {to}",
  "logbook.noDriveConfig": "Skráarupphal ekki stillt — ferð vistuð án viðhengis.",
  "boat.registrationNo": "Skráningarnúmer",
  "boat.sailNo": "Seglnúmer",
  "boat.loa": "Heildarlengd (fet)",
  "boat.typeModel": "Tegund / gerð",
  "boat.defaultPort": "Heimahöfn",
  "location.type": "Tegund",
  "location.typePort": "Höfn",
  "location.typeLocation": "Siglingasvæði",
  "location.lat": "Breiddargráða",
  "location.lng": "Lengdargráða",
  "fleet.badgeAvail": "LAUST",
  "fleet.badgeOut": "ÚTI",
  "fleet.badgeOverdue": "TÍMABÆRT",
  "fleet.badgeOos": "ÓTÆ.",
  "fleet.badgeYours": "ÞITT",
  "fleet.aboard": "{n} um borð",
  "fleet.outTime": "Út {t}",
  "fleet.checkIn": "Skrá inn",
  "fleet.delete": "Eyða",
  "fleet.badgeChartered": "LEIGÐUR",
  "fleet.badgePrivate": "EINKABÁTUR",
  "fleet.ownedBy": "Eigandi: {name}",
  "fleet.actionCheckout": "Útskrá",
  "fleet.actionMaint": "Beiðni um viðhald",
  "fleet.actionMarkOos": "Merkja ótiltækan",
  "fleet.actionMarkAvail": "Merkja tiltækan",
  "boat.ownership": "Eignarhald",
  "boat.ownershipClub": "Klúbbsbátur",
  "boat.ownershipPrivate": "Einkabátur",
  "boat.owner": "Eigandi",
  "boat.accessMode": "Aðgangshamur",
  "boat.accessFree": "Frjáls aðgangur",
  "boat.accessControlled": "Stýrður aðgangur",
  "boat.gateCert": "Nauðsynleg vottun",
  "boat.gateCertNone": "Ekkert (aðeins listi)",
  "boat.allowlist": "Leyfilegir meðlimir",
  "boat.allowlistAdd": "Bæta við meðlim…",
  "boat.reservations": "Úthluta leigu",
  "boat.addReservation": "Bæta við leigu",
  "boat.removeReservation": "Fjarlægja",
  "boat.reservationSaved": "Leiga vistuð",
  "boat.reservationRemoved": "Leiga fjarlægð",
  "boat.reservedFor": "Leigður til {name}",
  "boat.reservedUntil": "til {date}",
  "boat.reservationNote": "Athugasemd",
  "boat.accessDenied": "Þú hefur ekki aðgang að þessum bát",
  "boat.accessSaved": "Aðgangsstillingar vistaðar",
  "fleet.badgeControlled": "STÝRT",
  "fleet.badgeRestricted": "TAKMARKAÐ",
  "fleet.badgeAuthorized": "HEIMILAÐ",
  "fleet.badgeReserved": "FRÁTEKIÐ",
  "boat.slotScheduling": "Virkja tímabókun",
  "boat.availOutside": "Tiltækt utan áætlaðra tíma",
  "boat.availOutsideHint": "Ef ekki merkt, er báturinn aðeins tiltækur á bókuðum tímum.",
  "day.mon": "Mán",
  "day.tue": "Þri",
  "day.wed": "Mið",
  "day.thu": "Fim",
  "day.fri": "Fös",
  "day.sat": "Lau",
  "day.sun": "Sun",
  "month.jan": "jan",
  "month.feb": "feb",
  "month.mar": "mar",
  "month.apr": "apr",
  "month.may": "maí",
  "month.jun": "jún",
  "month.jul": "júl",
  "month.aug": "ágú",
  "month.sep": "sep",
  "month.oct": "okt",
  "month.nov": "nóv",
  "month.dec": "des",
  "slot.filterBoat": "Bátur",
  "slot.filterCrew": "Áhöfn",
  "slot.allBoats": "Allir bátar",
  "slot.today": "Í dag",
  "slot.addRecurring": "+ Endurtekið",
  "slot.noSlotBoats": "Engir bátar með tímabókun virka",
  "slot.boat": "Bátur",
  "slot.recurTitle": "Búa til endurtekna tíma",
  "slot.editTitle": "Tímabil",
  "slot.newTitle": "Nýr tími",
  "slot.daysOfWeek": "Vikudagar",
  "slot.startTime": "Byrjunartími",
  "slot.endTime": "Lokatími",
  "slot.fromDate": "Frá dagsetningu",
  "slot.toDate": "Til dagsetningar",
  "slot.note": "Athugasemd",
  "slot.preview": "Forskoðun",
  "slot.create": "Búa til",
  "slot.selectDays": "Veldu amk einn dag og tímabil",
  "slot.previewCount": "{count} tímar verða búnir til",
  "slot.created": "{count} tímar búnir til",
  "slot.missingFields": "Dagsetning og tímar eru nauðsynlegir",
  "slot.confirmDelete": "Eyða þessum tíma?",
  "slot.bookedBy": "Bókað af",
  "slot.legendOpen": "Laust",
  "slot.legendYours": "Þitt",
  "slot.legendBooked": "Bókað",
  "slot.booked": "Tími bókaður!",
  "slot.unbooked": "Bókun afturkölluð",
  "slot.confirmUnbook": "Afturkalla þessa bókun?",
  "slot.yours": "ÞITT",
  "slot.clickToBook": "Smelltu á lausan tíma til að bóka.",
  "slot.date": "Dagsetning",
  "slot.bulkBook": "Fjöldabókun",
  "slot.bulkTitle": "Fjöldabókun tíma",
  "slot.bulkPreview": "{open} lausir tímar af {total} verða bókaðir",
  "slot.bulkNoSlots": "Engir lausir tímar passa við valin skilyrði",
  "slot.bulkBooked": "{count} tímar bókaðir!",
  "slot.bulkPartial": "{booked} bókaðir, {skipped} þegar teknir",
  "slot.createAndBook": "+ Ný bókun",
  "slot.createAndBookTitle": "Búa til og bóka tíma",
  "slot.createdAndBooked": "Tími búinn til og bókaður!",
  "cq.reservationsTitle": "LEIGUR",
  "nav.coxswainSeat": "🚣 Róðurdeild",
  "cox.title": "Róðurdeild",
  "cox.noBoats": "Engir stýrðir bátar tiltækir",
  "cox.statsTrips": "FERÐIR",
  "cox.statsHours": "KLST.",
  "cox.statsDist": "VEGALENGD",
  "cox.boatAvailability": "AÐGENGI BÁTA",
  "cox.trips": "FERÐIR",
  "cox.maintenance": "VIÐHALD",
  "cox.readOnly": "Aðeins skoðun — krefst útgefinn róðramaður réttinda",
  "cox.noCrewsShort": "Engir hópar — búðu til einn fyrst",
  "cox.createCrewFirst": "Búðu til hóp fyrst til að bóka tíma",
  "cox.noMaint": "Engar viðhaldsbeiðnir.",
  "cox.reservations": "LEIGUR",
  "cox.addReservation": "Bæta við leigu",
  "cox.resMember": "Meðlimur",
  "cox.resStartDate": "Upphafsdagur",
  "cox.resEndDate": "Lokadagur",
  "cox.resNote": "Athugasemd (valfrjálst)",
  "cox.makeAvailable": "Merkja tiltækan",
  "cox.makeUnavailable": "Merkja ótiltækan",
  "cox.myCrews": "MÍNIR HÓPAR",
  "cox.noCrews": "Engir hópar ennþá. Búðu til einn til að byrja.",
  "cox.createCrew": "+ Búa til hóp",
  "cox.createCrewTitle": "Búa til hóp",
  "cox.crewName": "Nafn hóps",
  "cox.crewNameRequired": "Nafn hóps er nauðsynlegt",
  "cox.numPairs": "Fjöldi para",
  "cox.yourPair": "Þitt par",
  "cox.pair": "Par",
  "cox.empty": "tómt",
  "cox.openSpots": "laus",
  "cox.active": "VIRKT",
  "cox.forming": "Í MÓTUN",
  "cox.inviteMember": "Bjóða meðlim",
  "cox.searchMember": "Meðlimur",
  "cox.pairAssignment": "Par",
  "cox.sendInvite": "Senda boð",
  "cox.selectMember": "Veldu meðlim",
  "cox.selectPair": "Veldu par",
  "cox.inviteSent": "Boð sent!",
  "cox.pendingInvites": "BOÐANIR Í BIÐ",
  "cox.invitedBy": "Boðið af",
  "cox.accept": "Samþykkja",
  "cox.reject": "Hafna",
  "cox.inviteAccepted": "Boð samþykkt!",
  "cox.inviteRejected": "Boði hafnað.",
  "cox.disband": "Leysa upp",
  "cox.confirmDisband": "Leysa upp þennan hóp? Þetta er ekki afturkræft.",
  "cox.crewDisbanded": "Hópur leystur upp.",
  "cox.selectCrew": "Veldu hóp fyrst",
  "cox.crewBoard": "ÁHAFNABORÐ",
  "cox.crewBoardEmpty": "Engir hópar ennþá. Búðu til einn eða bíddu eftir öðrum.",
  "cox.boat": "Bátur",
  "cox.bow": "Framstafn",
  "cox.stern": "Aftarstafn",
  "cox.join": "Ganga í",
  "cox.leave": "Hætta",
  "cox.joined": "Gekk í hóp!",
  "cox.left": "Hætti í hóp.",
  "cox.confirmLeave": "Hætta í þessum hóp?",
  "cox.seatTaken": "Þetta sæti er tekið",
  "cox.description": "Lýsing",
  "cox.descPlaceholder": "t.d., Mán & Mið 7:00, hægur gangur",
  "cox.visibility": "Sýnileiki",
  "cox.visOpen": "Opið — allir geta gengið í",
  "cox.visInvite": "Aðeins boðið",
  "cox.yourSeat": "Þitt sæti",
  "cox.seatBow": "Framstafn",
  "cox.seatStern": "Aftarstafn",
  "cox.numBoats": "Fjöldi báta",
  "cox.needsMore": "vantar {n} í viðbót",
  "cox.crewColor": "Litur",
  "cox.tentative": "BRÁÐABIRGÐA",
  "cox.slotReservations": "BÓKANIR Á TÍMUM",
  "pub.dash.title": "Yfirlit klúbbs",
  "pub.dash.subtitle": "Siglingafélagið Ýmir",
  "pub.dash.season": "Tímabil {year}",
  "pub.dash.ytdTrips": "Siglingar á tímabilinu",
  "pub.dash.totalHours": "Klukkustundir á sjó",
  "pub.dash.byCategory": "Eftir bátategund",
  "pub.dash.locations": "Hvar við siglum",
  "pub.dash.onWater": "Á sjónum núna",
  "pub.dash.boats": "Bátar úti",
  "pub.dash.people": "Fólk",
  "pub.dash.captains": "Skipstjórar okkar",
  "pub.dash.viewRecord": "Skoða siglingaskrá →",
  "pub.dash.noCaptains": "Engir skipstjórar skráðir ennþá.",
  "pub.dash.noActivity": "Engir bátar á sjónum núna.",
  "pub.dash.trips": "siglingar",
  "pub.dash.hrs": "klst",
  "pub.dash.bio": "Skipstjóri hjá Siglingafélaginu Ými. Ævisaga í vinnslu.",
  "pub.dash.loading": "Hleður yfirliti…",
  "pub.dash.error": "Gat ekki hlaðið yfirlitsgögnum.",
  "pub.dash.lastUpdated": "Síðast uppfært",
  "pub.dash.tripCount": "{n} siglingar",
  "pub.dash.hourCount": "{n} klst",
  "pub.dash.conditions": "Aðstæður og staða",
  "pub.dash.weather": "Veður og sjávarföll",
  "pub.dash.boatsOut": "Bátar úti",
  "pub.dash.captainData": "Skipstjóragögn",
  "pub.dash.captainSoon": "Upplýsingar um skipstjóra og tölfræði birtast hér fljótlega.",
  "pub.dash.comingSoon": "Frekari upplýsingar birtast fljótlega.",
  "admin.expectedColumns": "VÆNTIR DÁLKAR",
  "admin.colName": "Fullt nafn (áskilið)",
  "admin.colKt": "10 stafa kennitala (áskilið)",
  "admin.colEmail": "Netfang",
  "admin.colPhone": "Símanúmer",
  "admin.colDob": "Fæðingardagur (ÁÁÁÁ-MM-DD)",
  "admin.colMemberType": "t.d. full, junior, family",
  "admin.csvDrop": "Dragðu CSV hingað eða smelltu",
  "admin.csvEncoding": "UTF-8, kommu- eða semíkommuaðskilið",
  "admin.reviewImport": "Yfirfara innflutning",
  "admin.rolesNeverOverwritten": "Stjórnanda-/starfsmannahlutverk aldrei yfirskrifuð.",
  "admin.confirmImport": "Staðfesta innflutning",
  "admin.importAnother": "Flytja inn annað",
  "admin.viewMembers": "Sjá félaga",
  "admin.addCategory": "+ Bæta við flokki",
  "admin.preLaunchLanding": "SJÓSETNINGAR- OG LENDINGARLISTAR (eftir flokki)",
  "admin.launch": "SJÓSETNING",
  "admin.landing": "LENDING",
  "admin.actTypesTitle": "TEGUNDIR STARFSEMI",
  "admin.credentialsTitle": "SKÍRTEINI",
  "admin.manageCreds": "Skírteini",
  "admin.overdueAlerts": "VIÐVARANIR YFIRTÍMA",
  "admin.notifChannels": "TILKYNNINGALEIÐIR",
  "admin.chanWeb": "Vef (borði í appi)",
  "admin.chanEmail": "Tölvupóstur",
  "admin.chanSms": "SMS",
  "admin.requiresBackend": "krefst bakendauppsetningar",
  "admin.emailRecipients": "Viðtakendur tölvupósts (kommuaðskildir)",
  "admin.smsRecipients": "Viðtakendur SMS (kommuaðskildir)",
  "admin.saveAlertSettings": "Vista viðvörunarstillingar",
  "admin.scoreThresholds": "STIGAMÖRK",
  "admin.scoreThresholdsSub": "heildarstig → fánastig",
  "admin.yellowGte": "Gulur ≥",
  "admin.orangeGte": "Appelsínugulur ≥",
  "admin.redGte": "Rauður ≥",
  "admin.closedGte": "Lokað ≥",
  "admin.windScoring": "VINDASTIG (Force → stig)",
  "admin.windScoringHint": "Hvert bil gildir þegar Force ≤ hámarksForce. Raðað í hækkandi röð.",
  "admin.dirGustMods": "ÁTTIR OG HVÍÐUBREYTINGAR",
  "admin.easterlyMod": "Austanáttarbreyting (stig)",
  "admin.easterlyModHint": "Bætt við þegar vindur er frá austanátt",
  "admin.gustMod1": "Hvíðubreyting +1 Force (stig)",
  "admin.gustMod1Hint": "Bætt við þegar hvíður eru nákvæmlega 1 Force-stigi yfir meðalvindi",
  "admin.gustMod2": "Hvíðubreyting +2 Force (stig)",
  "admin.gustMod2Hint": "Bætt við þegar hvíður eru 2+ Force-stigum yfir meðalvindi",
  "admin.easterlyDirs": "Austanáttir (kommuaðskildar)",
  "admin.waveScoring": "BYLGJUHÆÐARSTIG (metrar → stig)",
  "admin.sstScoring": "SJÁVARHITASTIG (°C → stig)",
  "admin.sstHint": "Fyrsta bil þar sem sjávarhiti ≥ lágmarksC gildir. Raðað hæsta gildi efst.",
  "admin.airTempScoring": "LOFTHITASTIG (°C → stig)",
  "admin.visScoring": "SKYGGNI-STIG",
  "admin.visGood": "Gott (stig)",
  "admin.visReduced": "Skert (stig)",
  "admin.visPoor": "Slæmt <500m (stig)",
  "admin.flagLabelsAdvice": "FÁNATEXTAR OG RÁÐLEGGINGAR",
  "admin.livePreview": "FORSÝNING",
  "admin.saveFlagSettings": "Vista fánastillingar",
  "admin.resetDefaults": "Endurstilla sjálfgefin gildi",
  "admin.addBand": "+ Bæta við bili",
  "admin.memberModal.title": "Bæta við félaga",
  "admin.kennitala": "Kennitala",
  "admin.initials": "Upphafsstafir",
  "admin.initialsPlaceholder": "Sjálfvirkt",
  "admin.dob": "Fæðingardagur",
  "admin.membershipType": "Tegund aðildar",
  "admin.memFull": "Full",
  "admin.memJunior": "Unglingur",
  "admin.memFamily": "Fjölskylda",
  "admin.memStudent": "Nemandi",
  "admin.memHonorary": "Heiðursfélagi",
  "admin.memOther": "Annað",
  "admin.deactivate": "Gera óvirkt",
  "admin.boatCatModal.add": "Bæta við bátaflokki",
  "admin.nameEN": "Nafn (enska)",
  "admin.nameIS": "Nafn (íslenska)",
  "admin.emoji": "Emoji",
  "admin.keyAutoSet": "Lykill (sjálfkrafa)",
  "admin.keyHint": "Lykillinn er notaður innbyrðis til að tengja báta og gátlista. Honum er ekki hægt að breyta eftir að bátum er úthlutað.",
  "admin.locModal.name": "Nafn",
  "admin.clModal.add": "Bæta við gátlistaatriði",
  "admin.clPhaseOpening": "Opnun",
  "admin.clPhaseClosing": "Lokun",
  "admin.clLaunchPhase": "Sjósetning",
  "admin.clLandingPhase": "Lending",
  "admin.actTypeModal.add": "Bæta við tegund starfsemi",
  "admin.subtypes": "UNDIRTEGUNDIR",
  "admin.certDefModal.add": "Bæta við tegund skírteinis",
  "admin.certDescLabel": "Lýsing",
  "admin.certIssuing": "Útgefandi",
  "admin.certClubEndorsement": "Áritun félagsins",
  "admin.certCardColour": "Litur korts",
  "admin.certAutoBlank": "sjálfvirkt ef autt",
  "admin.certExpires": "Þetta skírteini rennur út",
  "admin.certExpiryDate": "LOKADAGSETNING",
  "admin.certHasId": "Þetta skírteini hefur auðkenni / leyfisnúmer",
  "admin.certSubcategories": "UNDIRFLOKKAR",
  "admin.certSubcatHint": "Bættu við undirflokkum ef skírteinið hefur stig (t.d. Stig 1, 2, 3). Stilltu röð til að framfylgja „hærra kemur í stað lægra\" rök. Útgefandi eða lokadagsetning undirflokks hnekkir gildum yfirflokksins.",
  "admin.certCurrent": "NÚVERANDI",
  "admin.certNoneAssigned": "Engin skírteini úthlutað.",
  "admin.certAssignTitle": "ÚTHLUTA SKÍRTEINI",
  "admin.certLicenceNo": "Leyfisnúmer / auðkenni",
  "admin.certExpiryHint": "skildu eftir autt ef varanlegt",
  "admin.certExpiryLabel": "Lokadagsetning",
  "admin.certAssignedDate": "Úthlutunardagur",
  "admin.certCategory": "Flokkur",
  "admin.certCategorySelect": "Veldu flokk…",
  "admin.certAddCategory": "+ Bæta við flokki…",
  "admin.certTitle": "Heiti skírteinis",
  "admin.certIdNumber": "Auðkennisnúmer",
  "admin.certIssuingAuth": "Útgefandi",
  "admin.certIssueDate": "Útgáfudagur",
  "admin.certExpires2": "Rennur þetta skírteini út?",
  "admin.certExpiryDate2": "Lokadagsetning",
  "admin.certDescription": "Viðbótarlýsing",
  "admin.certCustomType": "— Slá inn sérsniðið skírteini —",
  "admin.certTitleRequired": "Heiti vantar.",
  "admin.certAuthorityReq": "Útgefanda vantar.",
  "admin.certExpiryReq": "Lokadagsetning vantar þegar skírteini rennur út.",
  "admin.certCategoryReq": "Flokk vantar.",
  "admin.certDefCategory": "Sjálfgefinn flokkur",
  "admin.certCategoriesTitle": "FLOKKAR SKÍRTEINA",
  "admin.certManageCategories": "Stjórna flokkum",
  "cq.assignCred": "Úthluta skírteini",
  "cq.assignCredTitle": "ÚTHLUTA SKÍRTEINI TIL ÁHAFNAR",
  "cq.searchMember": "Leita að áhafnarmeðlimi…",
  "cq.selectMember": "Veldu félagann",
  "admin.qrScanHint": "Skannaðu → laus: sjósetningarflæði · þinn bátur úti: skilaflæði · annars: sýnir stöðu.",
  "admin.printPdf": "Prenta / PDF",
  "admin.ownerClub": "Klúbbsbátur",
  "admin.ownerPrivate": "Einkabátur",
  "admin.searchMember": "Leita að félaga...",
  "admin.oosReason": "Ástæða",
  "admin.openingChecklist": "OPNUNARGÁTLISTI",
  "admin.closingChecklist": "LOKUNARGÁTLISTI",
  "admin.homePort": "Heimahöfn",
  "admin.loadFailed": "Hleðsla mistókst",
  "admin.nameKtRequired": "Nafn og kennitala vantar.",
  "admin.nameKeyRequired": "Nafn og lykill vantar.",
  "admin.nameRequired": "Nafn vantar.",
  "admin.textENRequired": "Enskan texta vantar.",
  "admin.saveBoatFirst": "Vistaðu bátinn fyrst.",
  "admin.selectMember": "Veldu félaga.",
  "admin.setDatesRequired": "Stilltu upphafs- og lokadagsetningu.",
  "admin.memberDatesRequired": "Félaga og dagsetningar vantar.",
  "admin.categoryExists": "Flokkur er þegar til.",
  "admin.categoryAdded": "Flokki bætt við.",
  "admin.categoryRemoved": "Flokki eytt.",
  "admin.certDefSaved": "Tegund skírteinis vistuð.",
  "admin.parseError": "Þáttunarvilla",
  "admin.importing": "Flytur inn…",
  "admin.importFailed": "Innflutningur mistókst",
  "admin.importComplete": "Innflutningi lokið: {added} bætt við, {updated} uppfært.",
  "admin.importDeactivated": "{count} gert óvirkt.",
  "admin.confirmDeactivateMember": "Gera þennan félaga óvirkan?",
  "admin.confirmRemoveBoatCat": "Eyða þessum flokki? Bátar sem eru í honum verða enn til en geta birst undir 'annað'.",
  "admin.confirmDeleteBoat": "Eyða þessum bát?",
  "admin.confirmDeleteLocation": "Eyða þessum stað?",
  "admin.confirmDeleteItem": "Eyða þessu atriði?",
  "admin.confirmDeleteActType": "Eyða þessari tegund starfsemi?",
  "admin.confirmRemoveCategory": "Eyða þessum flokki?",
  "admin.confirmDeleteCertDef": "Eyða þessari tegund skírteinis? Þetta eyðir ekki núverandi úthlutunum.",
  "admin.confirmResetFlags": "Endurstilla allar fánastillingar á sjálfgefin gildi?",
  "admin.noCategories": "Engir flokkar.",
  "admin.noItems": "Engin atriði.",
  "admin.noActTypes": "Engar tegundir starfsemi.",
  "admin.noCertCategories": "Engir flokkar skilgreindir. Sjálfgefin gildi verða notuð.",
  "admin.noCertDefs": "Engar tegundir skírteina skilgreindar.",
  "admin.noSubcategories": "Engir undirflokkar",
  "admin.noSubtypes": "Engar undirtegundir ennþá.",
  "admin.boatCatModal.edit": "Breyta flokki",
  "admin.clModal.edit": "Breyta atriði",
  "admin.lcModal.add": "Bæta við atriði",
  "admin.lcModal.edit": "Breyta atriði",
  "admin.actTypeModal.edit": "Breyta tegund",
  "admin.optionNone": "— ekkert —",
  "admin.certCategoryNone": "Ekkert",
  "staff.crewMembers": "Áhöfn",
  "staff.crewOptional": "valfrjálst — leita eftir nafni",
  "staff.crewAutoLog": "Nefnd áhöfn fær þessa ferð sjálfkrafa skráða í dagbókina sína.",
  "staff.departurePort": "Brottfararhöfn",
  "staff.recentIn": "Inn",
  "staff.recentMember": "Félagi",
  "staff.recentBoat": "Bátur",
  "staff.recentArea": "Siglingasvæði",
  "staff.recentDuration": "Tímalengd",
  "member.departurePort": "Brottfararhöfn",
  "member.homePort": "Heimahöfn",
  "member.crewMembers": "Áhöfn",
  "member.crewOptional": "valfrjálst — leita eftir nafni",
  "member.crewAutoLog": "Nefnd áhöfn fær þessa ferð sjálfkrafa skráða í dagbókina sína.",
  "member.back": "Til baka",
  "member.continue": "Áfram →",
  "member.preLaunch": "UNDIRBÚNINGUR",
  "member.noChecklist": "Enginn gátlisti stilltur fyrir þennan flokk.",
  "member.confirmAllItems": "Staðfestu alla liði.",
  "daily.ablerRegistered": "Starfsemi skráð í Abler",
  "daily.linkedGroupCo": "Tengdar hópaútskráningar",
  "daily.linkGroupCo": "+ Tengja hópaútskráningu",
  "daily.linkGroupCoTitle": "Tengja hópaútskráningu",
  "daily.noActiveGroups": "Engar virkar hópaútskráningar í dag.",
  "daily.linkSelected": "Tengja valið",
  "daily.groupCheckout": "Hópaútskráning",
  "daily.group": "hópur",
  "daily.groups": "hópar",
  "nav.captainQuarters": "🚢 Skipstjóraherbergi",
  "cq.title": "Skipstjóraherbergi",
  "cq.subtitle": "Yfirlit skipstjóra kjölbáta",
  "cq.ytdHours": "KLUKKUST. Á ÁRI",
  "cq.ytdDistance": "VEGALENGD Á ÁRI",
  "cq.ytdTrips": "FERÐIR Á ÁRI",
  "cq.nm": "sm",
  "cq.hrs": "klst",
  "cq.maintTitle": "VIÐHALD KJÖLBÁTA",
  "cq.maintOpen": "Opin",
  "cq.maintClosed": "Lokað",
  "cq.maintAll": "Allt",
  "cq.noMaint": "Engar viðhaldsbeiðnir.",
  "cq.validationTitle": "STAÐFESTINGARBEIÐNIR",
  "cq.noValidation": "Engar staðfestingarbeiðnir í bið.",
  "cq.crewTitle": "SAMÞYKKI ÁHAFNAR",
  "cq.noCrew": "Engin áhafnarsamþykki í bið.",
  "cq.tripsTitle": "FERÐIR Á KJÖLBÁTUM",
  "cq.myTrips": "Mínar ferðir",
  "cq.allTrips": "Allar kjölbátaferðir",
  "cq.noTrips": "Engar ferðir fundust.",
  "cq.bioTitle": "LÝSING OG PRÓFÍLL",
  "cq.bioPlaceholder": "Skrifaðu stutta lýsingu sem birtist á opinberri skipstjórasíðu þinni…",
  "cq.headshotLabel": "Prófílmynd (hámark 5 MB)",
  "cq.bioSaved": "Lýsing vistuð",
  "cq.headshotUploaded": "Mynd hlaðið upp",
  "cq.boatsTitle": "MÍNIR BÁTAR",
  "cq.noBoats": "Engir einkabátar skráðir.",
  "cq.makeUnavailable": "Merkja ótiltækan",
  "cq.makeAvailable": "Merkja tiltækan",
  "cq.changePort": "Breyta heimahöfn",
  "cq.viewPublicProfile": "Skoða opinbert prófíl →",
  "cq.reservations": "LEIGUR",
  "cq.noReservations": "Engar leigur.",
  "cq.addReservation": "Bæta við leigu",
  "cq.resStartDate": "Upphafsdagur",
  "cq.resEndDate": "Lokadagur",
  "cq.resNote": "Athugasemd (valfrjálst)",
  "cq.resMember": "Meðlimur",
  "tc.skipper": "Skipari",
  "tc.crew": "Áhöfn",
  "tc.helm": "Stýri",
  "tc.student": "Nemi",
  "tc.guest": "Gestur",
  "tc.me": "Ég",
  "tc.nonClub": "Utan félags",
  "tc.pending": "í bið",
  "tc.verificationPending": "Staðfesting í bið",
  "tc.windSpeed": "Vindhraði",
  "tc.direction": "Átt",
  "tc.gusts": "Vindhviður",
  "tc.conditions": "Aðstæður",
  "tc.airTemp": "Hitastig",
  "tc.feelsLike": "Finnst eins og",
  "tc.seaTemp": "Sjávarhiti",
  "tc.waveHeight": "Bylgjuhæð",
  "tc.pressure": "Loftþrýstingur",
  "tc.weatherFlag": "Veðurfáni",
  "tc.departurePort": "Brottfararstaður",
  "tc.arrivalPort": "Komustaður",
  "tc.skipperLabel": "Skipstjóri",
  "tc.crewAboard": "Áhöfn um borð",
  "tc.atTheHelm": "Við stýri",
  "tc.regNo": "Skráningarnúmer",
  "tc.sailNo": "Seglnúmer",
  "tc.typeModel": "Tegund / gerð",
  "tc.loa": "Heildarlengd",
  "tc.distance": "Vegalengd",
  "tc.gpsTrack": "GPS-leið",
  "tc.deleteTrack": "Eyða leið",
  "tc.clickToExpand": "Smelltu til að stækka",
  "tc.downloadFile": "Sækja skrá",
  "tc.viewTrack": "Skoða leið",
  "tc.skipperNote": "Athugasemdir skipstjóra",
  "tc.visibleToCrew": "sýnilegt áhöfn",
  "tc.fromSkipper": "frá skipstjóra",
  "tc.noNoteYet": "Engin skýring",
  "tc.edit": "Breyta",
  "tc.privateNote": "Persónulegar athugasemdir",
  "tc.onlyYou": "aðeins þú sérð",
  "tc.noPrivateNoteYet": "Engin athugasemd",
  "tc.photos": "Myndir",
  "tc.delete": "Eyða",
  "tc.shared": "Deilt",
  "tc.private": "Einka",
  "tc.club": "Félag",
  "tc.editTrip": "✏️ Breyta ferð",
  "tc.addGps": "📍 Bæta við GPS",
  "tc.addPhotos": "📷 Bæta við myndum",
  "tc.boatDetails": "Upplýsingar um bát",
  "tc.tripDetails": "Upplýsingar um ferð",
  "tc.departed": "Brottfarartími",
  "tc.returned": "Komutími",
  "tc.sailingArea": "Siglingasvæði",
  "tc.duration": "Tímalengd",
  "tc.weather": "Veður",
  "tc.notesPhotosTrack": "Athugasemdir og myndir",
  "maint.sevHint.low": "Minniháttar vandamál — engin tafarlaus aðgerð nauðsynleg.",
  "maint.sevHint.medium": "Nothæft vandamál, nothæft með varúð.",
  "maint.sevHint.high": "Verulegt vandamál — meta áður en notað.",
  "maint.sevHint.critical": "Öryggisáhætta — taka úr þjónustu strax.",
  "maint.oosTag": "ÓÞ",
  "maint.inService": "Í þjónustu",
  "maint.confirmBtn": "Staðfesta",
  "maint.cancelBtn": "Hætta við",
  "maint.defaultAuthor": "Starfsmaður",
  "maint.deleteComment": "Eyða athugasemd",
  "maint.addCommentPh": "Bæta við athugasemd…",
  "maint.postBtn": "Birta",
  "maint.postingBtn": "Birti…",
  "maint.approvingBtn": "Samþykki…",
  "maint.approveBtn": "Samþykkja",
  "maint.saumaBadge": "Saumaklúbbur",
  "maint.onHoldBadge": "Í bið",
  "maint.noVerkstjori": "Enginn verkstjóri úthlutaður",
  "maint.adoptProject": "Taka verkefni að mér",
  "maint.reportedByLabel": "Tilkynnt af",
  "maint.pendingReview": "Bíður samþykktar starfsmanna",
  "maint.markCompleted": "Merkja lokið",
  "maint.markResolved2": "Merkja sem lokið",
  "maint.resumeBtn": "Halda áfram",
  "maint.putOnHold": "Setja í bið",
  "maint.deleteBtn": "Eyða",
  "maint.completedStatus": "Lokið",
  "maint.resolvedStatus": "Lokið",
  "maint.severityLabel": "Alvarleiki",
  "maint.priorityLabel": "Forgangur",
  "maint.changeSevConfirm": "Breyta alvarleika í \"{sev}\" án þess að leysa?",
  "maint.adoptConfirm": "Verða verkstjóri þessa verkefnis?",
  "maint.deleteCommentConfirm": "Eyða þessari athugasemd?",
  "maint.holdConfirm": "Setja þetta verkefni í bið?",
  "maint.resumeConfirm": "Halda áfram með þetta verkefni?",
  "maint.completeConfirm": "Merkja þetta verkefni sem lokið?",
  "maint.resolveConfirm2": "Merkja þetta vandamál sem lokið?",
  "maint.deleteConfirm": "Eyða þessu vandamáli? Þetta er ekki afturkræft.",
  "maint.returnToService": "Setja aftur í þjónustu án þess að leysa?",
  "maint.markOosConfirm": "Merkja utan þjónustu án þess að leysa?",
  "maint.maxFileSize": "Hámark 5 MB",
  "maint.materials": "EFNI",
  "maint.addMaterialPh": "t.d. Sandpappír 120…",
  "maint.addMaterialBtn": "+ Bæta við",
  "maint.removeMaterial": "Fjarlægja efni",
  "maint.removeMaterialConfirm": "Fjarlægja þetta efni?",
  "alert.overdueTitle": "BÁTAR YFIRTÍMA",
  "alert.minOverdue": "{n} mín yfirtíma",
  "alert.hrsOverdue": "{h}klst {m}mín yfirtíma",
  "alert.guardian": "Forráðamaður:",
  "alert.snoozedPill": "Frestað — birtist aftur eftir {n} mín",
  "alert.snoozeBtn": "Fresta {n}m",
  "alert.silenceBtn": "Þagga",
  "wx.staffOnDuty": "Starfsmaður á vakt",
  "wx.supportBoatOut": "Björgunarbátur á sjó",
  "wx.poorVisibility": "Slæm sýn",
  "wx.reducedVisibility": "Skert sýn",
  "tc.flagGreen": "Grænn",
  "tc.flagYellow": "Gulur",
  "tc.flagOrange": "Appelsínugulur",
  "tc.flagRed": "Rauður",
  "tc.flagBlack": "Svartur",
  "logbook.deleteTrack": "Ertu viss um að þú viljir eyða GPS-leiðinni?",
  "logbook.deletePhoto": "Eyða þessari mynd?",
  "logbook.revokeLink": "Afturkalla þennan hlekk?",
  "logbook.noFilter": "Engar ferðir passa við þessa síu.",
  "logbook.loadingTrips": "Hleður nýlegum ferðum…",
  "logbook.noClubTrips": "Engar nýlegar félagssiglingar fundust.",
  "logbook.ports": "HÖFNAR",
  "logbook.portsOptional2": "HÖFNAR — VALFRJÁLST",
  "logbook.helmLabel": "Stýri",
  "logbook.studentLabel": "Nemi",
  "logbook.errKtOrPhone": "Vinsamlegast sláðu inn kennitölu/fæðingarár eða símanúmer.",
  "logbook.errSaveFailed": "Vistun mistókst: {msg}",
  "logbook.errFailed": "Mistókst: {msg}",
  "logbook.readingFile": "Lesur skrá…",
  "logbook.fileReady": "Tilbúið: {name}",
  "logbook.readError": "Lestur mistókst",
  "logbook.noTripSelected": "Engin ferð valin",
  "logbook.sendingRequest": "Sendir beiðni…",
  "logbook.requestSent": "Beiðni send til skipstjóra ✓",
  "logbook.addToLogbook": "Bæta við siglingabók",
  "logbook.alreadyInLog": "Þessi ferð er nú þegar í siglingabókinni þinni.",
  "logbook.requestToJoin": "Senda beiðni",
  "logbook.errDepartureTime": "Ógilt brottfarartími (HH:MM).",
  "logbook.errReturnTime": "Ógilt komutími (HH:MM).",
  "logbook.errDate": "Vinsamlegast sláðu inn dagsetningu.",
  "logbook.errBoat": "Vinsamlegast veldu bát.",
  "logbook.errSkipper": "Vinsamlegast veldu skipara.",
  "logbook.errDuplicate": "Þú hefur þegar skráð ferð með þessum bát á þessum degi. Vinsamlegast athugaðu siglingabókina.",
  "logbook.uploading": "Hleður upp…",
  "logbook.uploadNoConfig": "Skráarupphal ekki stillt — ferð vistuð án viðhengis.",
  "logbook.gpsUploadFailed": "GPS upphal mistókst: {msg}",
  "logbook.photoNoConfig": "Skráarupphal ekki stillt",
  "logbook.photoUploadFailed": "Mynda upphal mistókst: {msg}",
  "logbook.saveToLogbook": "Vista í siglingabók",
  "logbook.showLess": "Sýna minna",
  "logbook.showMore": "Sýna meira",
  "logbook.departure": "Brottför",
  "logbook.arrival": "Koma",
  "logbook.trackDeleted": "GPS-leið eytt",
  "logbook.photoDeleted": "Mynd eytt",
  "logbook.upTo": "Til",
  "logbook.views": "skoðanir",
  "logbook.copy": "Afrita",
  "logbook.revoke": "Afturkalla",
  "logbook.linkRevoked": "Hlekkur afturkallaður.",
  "logbook.loadFailed": "Gat ekki hlaðið siglingabók: {msg}",
  "logbook.loadFailed2": "Gat ekki hlaðið: {msg}",
  "logbook.studentBadge": "Nemamerking",
  "logbook.tripVerification": "Staðfesting ferðar",
  "logbook.dismissAllResolved": "Fjarlægja allar afgreiddar",
  "logbook.from": "frá",
  "logbook.dismiss": "Fjarlægja",
  "logbook.confirmed": "Staðfest ✓",
  "logbook.rejected": "Hafnað",
  "logbook.skipperNoteLabel": "Athugasemdir skipstjóra (sýnilegt áhöfn):",
  "logbook.privateNoteLabel": "Persónulegar athugasemdir (aðeins þú sérð):",
  "logbook.noteSaved": "Athugasemd vistuð",
  "logbook.dismissed": "Fjarlægt",
  "logbook.allDismissed": "Allar fjarlægðar",
  "logbook.onlySkipper": "Aðeins skipstjóri getur breytt ferðinni",
  "logbook.selectBoat": "Veldu bát…",
  "logbook.selectLocation": "Veldu staðsetningu…",
  "logbook.editTripTitle": "Breyta ferð",
  "logbook.saveChanges": "Vista breytingar",
  "logbook.saving": "Vista…",
  "logbook.tripUpdated2": "Ferð uppfærð",
  "logbook.uploadingTrack": "Hleð upp GPS-leið…",
  "logbook.uploadFailed": "Upphal mistókst",
  "logbook.trackAdded2": "GPS-leið bætt við",
  "logbook.addPhotosTitle": "Bæta við myndum",
  "logbook.photoHint": "Deildar myndir sjást öðrum í ferðinni. Myndir merktar fyrir félagið má nota í kynningarefni.",
  "logbook.uploadPhotos": "Hlaða upp myndum",
  "logbook.noPhotosSelected": "Engar myndir valdar",
  "logbook.photosAdded2": "Myndir bættar við",
  "logbook.uploadFailed2": "Upphal mistókst: {msg}",
  "logbook.windLabel": "Vindur ({unit})",
  "logbook.gustsLabel": "Hviður ({unit})",
  "logbook.crewSearchPh": "Áhöfn {n} — leita eftir nafni…",
  "logbook.addAsGuest": "+ Bæta við \"{name}\" sem gest",
  "logbook.portAdded": "Höfn bætt við",
  "logbook.verificationReq": "Óskað eftir staðfestingu",
  "logbook.errGeneric": "Villa: {msg}",
  "member.gpsTrackLabel": "GPS-LEIÐ — GPX/KML",
  "member.photosLabel": "MYNDIR",
  "member.distanceLabel": "VEGALENGD (NM)",
  "member.arrivalPortLabel": "KOMUSTAÐUR",
  "member.sameAsDeparture": "Sama og brottfararstaður",
  "member.reportDamage": "Tilkynna skemmdir",
  "member.reportIncident": "Tilkynna atvik",
  "member.helmLabel": "STÝRI",
  "member.youLabel": "(þú)",
  "member.loadingCrew": "Hleður áhöfn…",
  "member.skipperNotes": "ATHUGASEMDIR SKIPSTJÓRA",
  "member.notesVisibleAll": "Sýnileg öllum á ferðinni.",
  "member.notesPlaceholder": "Athugasemd um ferðina (sýnileg áhöfn)",
  "member.personalNotes": "PERSÓNULEGAR ATHUGASEMDIR",
  "member.onlyVisibleYou": "Aðeins sýnilegt þér",
  "member.guestLabel": "Gestur",
  "member.noNamedCrew": "Engin nefnd áhöfn",
  "member.readingFile": "Lesur skrá…",
  "member.fileReady": "Tilbúið: {name}",
  "member.readError": "Lestur mistókst",
  "member.gpsNoConfig": "GPS upphal ekki stillt",
  "member.gpsUploadFailed": "GPS upphal mistókst: {msg}",
  "member.photoNoConfig": "Skráarupphal ekki stillt",
  "member.photoUploadFailed": "Mynda upphal mistókst: {msg}",
  "member.checkInBtn": "Skrá inn",
  "staff.boatNotFound": "Bátur fannst ekki.",
  "staff.groupCheckoutTitle": "Hópaúthlutun",
  "staff.selectBoats": "Veldu báta",
  "staff.participants": "Iðkendur",
  "staff.activityType": "Tegund",
  "staff.errSelectBoat": "Veldu að minnsta kosti einn bát.",
  "staff.errSailingArea": "Veldu siglingasvæði.",
  "staff.errStaffRequired": "Þarf að skrá a.m.k. einn starfsmann.",
  "staff.errStaffFromList": "Vinsamlegast veldu starfsmann af listanum: {names}",
  "staff.groupLaunched": "Hópur sjósettur ✓",
  "staff.searchStaff": "Leita að starfsmanni…",
  "staff.addAsGuest": "+ Bæta við \"{name}\" sem gest",
  "staff.crewSearchPh": "Áhöfn {n} — leita eftir nafni…",
  "staff.errKtOrPhone": "Vinsamlegast sláðu inn kennitölu/fæðingarár eða símanúmer.",
  "staff.guestSaveFailed": "Gat ekki vistað gest: {msg}",
  "staff.checkInClose": "Skrá inn og loka",
  "staff.noActivities": "Engin starfsemi skráð í dagbók dagsins enn.",
  "staff.linkedDailyLog": "Tengt við dagbók ✓",
  "staff.payrollUnavail": "Launakerfi ekki tiltækt — settu upp bakenda fyrst",
  "staff.onWaterTotal": "{n} á sjónum samtals, {b} {boatWord}",
  "staff.boat": "bátur",
  "staff.boats": "bátar",
  "staff.peopleOnWater": "manns á sjó",
  "staff.checkInAll": "Taka inn",
  "staff.noneOption": "— Ekkert —",
  "staff.oosTitle": "Utan þjónustu",
  "staff.alreadyOut": "Nú þegar úti",
  "staff.staffOnDuty": "Starfsmaður á vakt",
  "staff.noStaffOnDuty": "Enginn starfsmaður",
  "staff.supportBoat": "Björunarbátur",
  "staff.noSupportBoat": "Enginn björunarbátur",
  "staff.updatedShort": "Uppf.",
  "staff.guardianLabel": "Sými forráðamanns",
  "staff.phoneLabel": "Sími",
  "staff.expectedBack": "Skilar klukkan",
  "staff.overdueBy": "Seinn um",
  "staff.hrsMin": "{h}klst {m}mín",
  "staff.minOnly": "{m} mín",
  "staff.snoozeBtn": "Fresta ({n} mín)",
  "staff.silenceBtn": "Þagga",
  "maint.noFilterMatch": "Engar beiðnir passa við þessa síu.",
  "maint.loadFailed": "Gat ekki hlaðið: {msg}",
  "maint.errCategory": "Vinsamlegast veldu flokk.",
  "maint.errSeverity": "Vinsamlegast veldu alvarleikastig.",
  "maint.errDescription": "Vinsamlegast lýstu vandamálinu.",
  "maint.errBoat": "Vinsamlegast veldu bát.",
  "maint.errItem": "Vinsamlegast sláðu inn hlut eða staðsetningu.",
  "maint.equipmentItem": "Búnaður",
  "maint.locationArea": "Staðsetning / svæði",
  "maint.imgTooLarge": "Mynd of stór ({size} MB). Hámark er 5 MB.",
  "maint.submitting": "Sendi…",
  "maint.uploadingPhoto": "Hleð upp mynd…",
  "maint.submitBtn": "Senda",
  "maint.submitted": "Beiðni send ✓",
  "maint.resolvedToast": "Lokið ✓",
  "maint.commentAdded": "Athugasemd bætt við.",
  "cert.removeConfirm": "Fjarlægja þetta skírteini?",
  "cq.allBoats": "Allir bátar",
  "cq.allYears": "Öll ár",
  "cq.allCategories": "Allir flokkar",
  "cq.allCaptains": "Allir skipstjórar",
  "cq.allMembers": "Allir félagar",
  "cq.fileTooLarge": "Skrá of stór (hámark 5 MB)",
  "cq.memberDatesRequired": "Meðlimur og dagsetningar eru nauðsynleg.",
  "cq.noTripsMatch": "Engar ferðir passa við þessa síu.",
  "cq.crewJoinRequest": "Biðst til liðs sem áhafnarmeðlimur",
  "cq.crewAssignPending": "Áhafnarúthlutun í bið",
  "cox.memberDatesRequired": "Meðlimur og dagsetningar eru nauðsynleg.",
  "wx.fetching": "Sæki veðurgögn…",
  "wx.updating": "Uppfæri…",
  "wx.checkConnection": "Athugaðu tengingu og reyndu aftur.",
  "wx.failed": "Mistókst",
  "wx.refresh": "Endurhlaða",
  "wx.pressureUnavail": "Þrýstingsgögn ekki tiltæk",
  "logrev.noMemberSelected": "Enginn meðlimur valinn.",
  "logrev.memberNotFound": "Meðlimur fannst ekki.",
  "logrev.credentialRemoved": "Skírteini fjarlægt",
  "sauma.imgTooLarge": "Mynd of stór. Hámark er 5 MB.",
  "sauma.submitting": "Sendi…",
  "sauma.uploadingPhoto": "Hleð upp mynd…",
  "sauma.submitted": "Verkefni sent til samþykktar.",
  "sauma.selectCategory": "Vinsamlegast veldu flokk.",
  "sauma.selectPriority": "Vinsamlegast veldu forgang.",
  "sauma.describeProject": "Vinsamlegast lýstu verkefninu.",
  "sauma.selectBoat": "Vinsamlegast veldu bát.",
  "sauma.enterItem": "Vinsamlegast sláðu inn hlut eða staðsetningu.",
  "sauma.equipmentItem": "Búnaður",
  "sauma.locationArea": "Staðsetning / svæði"
};
