-- Re-imports the 7 certDefs rows previously seeded into app_config
-- (20260921190000_import_cert_boat_categories.sql) into the real table
-- created by 20260922110000. Ids are preserved exactly as-is (see that
-- migration's header for why no remap is needed here, unlike
-- activity_templates).
insert into public.cert_defs (id, name_en, name_is, description_en, description_is, category, issuing_authority, color, expires, has_id_number, club_endorsement, subcats) values
($dq$cert_75585c0f3db745a1$dq$, $dq$Rowing Division$dq$, $dq$Róðrardeild$dq$, '', '', '', '', $dq$#ff0000$dq$, false, false, true, $dq$[{"key": "released_rower", "labelEN": "Released Rower", "labelIS": "", "descriptionEN": "", "descriptionIS": "", "label": "Released Rower", "description": "", "rank": 2, "issuingAuthority": ""}, {"key": "restricted_rower", "labelEN": "Restricted Rower", "labelIS": "", "descriptionEN": "", "descriptionIS": "", "label": "Restricted Rower", "description": "", "rank": 3, "issuingAuthority": ""}]$dq$::jsonb),
($dq$cert_mn9l9294$dq$, $dq$Keelboat Division$dq$, $dq$Kjölbátadeild$dq$, '', '', '', '', $dq$#34783b$dq$, false, false, true, $dq$[{"key": "captain", "labelEN": "Captain", "labelIS": "", "descriptionEN": "", "descriptionIS": "", "label": "Captain", "description": "", "rank": 1, "issuingAuthority": ""}, {"key": "crew", "labelEN": "Crew", "labelIS": "", "descriptionEN": "", "descriptionIS": "", "label": "Crew", "description": "", "rank": 2, "issuingAuthority": ""}]$dq$::jsonb),
($dq$cert_mnuhq6w5$dq$, $dq$Support boat skipper$dq$, $dq$Gæslubátastjóri$dq$, '', '', '', '', $dq$#b5890a$dq$, false, false, true, $dq$[]$dq$::jsonb),
($dq$cert_mo434pwg$dq$, $dq$Courses$dq$, $dq$Námskeið$dq$, $dq$Classes run by Ýmir$dq$, $dq$Námskeið hjá Ými$dq$, '', $dq$Siglingafélagið Ýmir$dq$, $dq$#34783c$dq$, false, false, true, $dq$[{"key": "learn_to_sail", "labelEN": "Learn to Sail", "labelIS": "Lærðu að sigla", "descriptionEN": "Beginner's dinghy sailing class", "descriptionIS": "Kænunámskeið fyrir byrjendur", "label": "Learn to Sail", "description": "Beginner's dinghy sailing class", "rank": null, "issuingAuthority": ""}, {"key": "advanced_sailing", "labelEN": "Advanced Sailing", "labelIS": "Framhaldsnámskeið í siglingum", "descriptionEN": "Continuing education in sailing, encompasses several different projects.", "descriptionIS": "", "label": "Advanced Sailing", "description": "Continuing education in sailing, encompasses several different projects.", "rank": null, "issuingAuthority": ""}, {"key": "keelboat_1", "labelEN": "Keelboat 1", "labelIS": "Kjölbátur 1", "descriptionEN": "", "descriptionIS": "", "label": "Keelboat 1", "description": "", "rank": null, "issuingAuthority": ""}, {"key": "competent_crew", "labelEN": "Competent Crew", "labelIS": "Hæfur Háseti", "descriptionEN": "", "descriptionIS": "", "label": "Competent Crew", "description": "", "rank": null, "issuingAuthority": ""}, {"key": "keelboat_maintenance", "labelEN": "Keelboat Maintenance", "labelIS": "Viðhaldsnámskeið", "descriptionEN": "", "descriptionIS": "", "label": "Keelboat Maintenance", "description": "", "rank": null, "issuingAuthority": ""}]$dq$::jsonb),
($dq$cert_moabuhfs$dq$, $dq$Pleasure boat certificate$dq$, $dq$Skemmtibátaskírteini$dq$, $dq$Non-commercial operator's license for Iceland-registered vessels from 6m to 24m LOA.$dq$, $dq$Skírteini til stjórnunar á íslenskum skráðum bátum í einkanotum, 6–24 m að lengd (LOA)$dq$, $dq$Operator License$dq$, $dq$Samgöngustofnun$dq$, $dq$#b5890a$dq$, true, true, false, $dq$[]$dq$::jsonb),
($dq$cert_mointdv6$dq$, $dq$World Sailing$dq$, $dq$World Sailing$dq$, '', '', $dq$Educational Qualifications$dq$, $dq$World Sailing$dq$, $dq$#b5890a$dq$, false, false, false, $dq$[{"key": "level_1", "labelEN": "Level 1", "labelIS": "Stig 1", "descriptionEN": "", "descriptionIS": "", "label": "Level 1", "description": "", "rank": 3, "issuingAuthority": ""}, {"key": "level_2", "labelEN": "Level 2", "labelIS": "Stig 2", "descriptionEN": "", "descriptionIS": "", "label": "Level 2", "description": "", "rank": 2, "issuingAuthority": ""}, {"key": "level_3", "labelEN": "Level 3", "labelIS": "Stig 3", "descriptionEN": "", "descriptionIS": "", "label": "Level 3", "description": "", "rank": null, "issuingAuthority": ""}]$dq$::jsonb),
($dq$cert_mok1v4ud$dq$, $dq$Dinghy division$dq$, $dq$Kænudeild$dq$, '', '', '', '', $dq$#b5890a$dq$, false, false, true, $dq$[{"key": "training_group", "labelEN": "Training Group", "labelIS": "Æfingahópur", "descriptionEN": "", "descriptionIS": "", "label": "Training Group", "description": "", "rank": null, "issuingAuthority": ""}, {"key": "competition_group", "labelEN": "Competition Group", "labelIS": "Keppnishópur", "descriptionEN": "", "descriptionIS": "", "label": "Competition Group", "description": "", "rank": null, "issuingAuthority": ""}]$dq$::jsonb);

delete from public.app_config where key = 'certDefs';
